-- Flyway Migration V19: Update all 50 Minna no Nihongo lesson titles with exact UTF-8 Vietnamese names and ensure Lesson 1 N5 is properly formatted

-- N5: Minna no Nihongo I (Bài 1 -> Bài 25)
UPDATE lessons SET title = 'Bài 1: Giới thiệu bản thân & Chào hỏi (わたしは～です)', description = 'Giới thiệu tên, quốc tịch, nghề nghiệp, câu chào hỏi ban đầu.', is_sample = TRUE, estimated_minutes = 30, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 1;
UPDATE lessons SET title = 'Bài 2: Đồ vật & Chỉ định từ (これ・それ・あれ)', description = 'Hỏi và trả lời về đồ vật xung quanh, quyền sở hữu đồ đạc.', is_sample = FALSE, estimated_minutes = 30, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 2;
UPDATE lessons SET title = 'Bài 3: Nơi chốn & Phương hướng (ここ・そこ・あそこ)', description = 'Hỏi vị trí địa điểm, tầng lầu, xuất xứ sản phẩm và giá tiền.', is_sample = FALSE, estimated_minutes = 30, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 3;
UPDATE lessons SET title = 'Bài 4: Thời gian & Giờ giấc (今～時です / ～から～まで)', description = 'Hỏi giờ, phút, thứ, ngày tháng và khung thời gian làm việc.', is_sample = FALSE, estimated_minutes = 35, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 4;
UPDATE lessons SET title = 'Bài 5: Đi lại & Phương tiện (～へ行きます / ～で)', description = 'Di chuyển đi đâu, bằng phương tiện gì, đi cùng với ai.', is_sample = FALSE, estimated_minutes = 35, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 5;
UPDATE lessons SET title = 'Bài 6: Hành động & Ngoại động từ (～をします / ～を買います)', description = 'Diễn tả hành động ăn, uống, mua sắm và rủ rê cùng làm.', is_sample = FALSE, estimated_minutes = 35, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 6;
UPDATE lessons SET title = 'Bài 7: Công cụ & Cho nhận quà (～で / あげます・もらいます)', description = 'Sử dụng công cụ/ngôn ngữ làm gì, hành động tặng/nhận quà.', is_sample = FALSE, estimated_minutes = 40, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 7;
UPDATE lessons SET title = 'Bài 8: Tính từ & Miêu tả (い形容詞・な形容詞)', description = 'Miêu tả đặc điểm, tính chất của sự vật, người và nơi chốn.', is_sample = FALSE, estimated_minutes = 40, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 8;
UPDATE lessons SET title = 'Bài 9: Sở thích & Năng lực (～が好きです / 分かります)', description = 'Bày tỏ sở thích, mức độ hiểu biết và lý do (から).', is_sample = FALSE, estimated_minutes = 40, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 9;
UPDATE lessons SET title = 'Bài 10: Tồn tại & Vị trí (～があります / います)', description = 'Sự tồn tại của người, vật, động vật và vị trí không gian.', is_sample = FALSE, estimated_minutes = 40, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 10;
UPDATE lessons SET title = 'Bài 11: Số lượng & Đếm (～つ / ～人 / ～回)', description = 'Cách đếm đồ vật, số người, thời gian và tần suất.', is_sample = FALSE, estimated_minutes = 45, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 11;
UPDATE lessons SET title = 'Bài 12: Quá khứ & So sánh (～でした / ～より～)', description = 'Thì quá khứ của tính từ và các cấu trúc so sánh hơn/nhất.', is_sample = FALSE, estimated_minutes = 45, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 12;
UPDATE lessons SET title = 'Bài 13: Mong muốn & Muốn làm (～が欲しいです / ～たいです)', description = 'Bày tỏ mong muốn có đồ vật hoặc muốn làm hành động gì.', is_sample = FALSE, estimated_minutes = 45, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 13;
UPDATE lessons SET title = 'Bài 14: Thể Te & Nhờ vả (～てください / ～ています)', description = 'Cách chia thể Te, nhờ vả lịch sự và hành động đang diễn ra.', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 14;
UPDATE lessons SET title = 'Bài 15: Cho phép & Cấm đoán (～てもいいです / ～てはいけません)', description = 'Xin phép làm gì và cấu trúc cấm đoán không được làm.', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 15;
UPDATE lessons SET title = 'Bài 16: Trình tự hành động (～てから / ～は～が)', description = 'Nối các động từ theo trình tự và miêu tả đặc điểm chi tiết.', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 16;
UPDATE lessons SET title = 'Bài 17: Thể Nai & Bắt buộc (～ないでください / ～なければなりません)', description = 'Cách chia thể Nai, khuyên không làm và nghĩa vụ bắt buộc.', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 17;
UPDATE lessons SET title = 'Bài 18: Thể Nguyên dạng & Khả năng (～ことができます / 趣味は～です)', description = 'Thể từ điển (Jishokei), nói về khả năng và sở thích.', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 18;
UPDATE lessons SET title = 'Bài 19: Thể Ta & Kinh nghiệm (～たことがあります / ～たり～たり)', description = 'Cách chia thể Ta, nói về kinh nghiệm đã từng làm và liệt kê.', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 19;
UPDATE lessons SET title = 'Bài 20: Thể Thông thường (普通形 - Giao tiếp hàng ngày)', description = 'Chuyển đổi giữa thể Lịch sự (Masu) và thể Thông thường (Futsuu).', is_sample = FALSE, estimated_minutes = 55, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 20;
UPDATE lessons SET title = 'Bài 21: Ý kiến & Trích dẫn (～と思います / ～と言いました)', description = 'Bày tỏ suy nghĩ cá nhân và trích dẫn lời nói người khác.', is_sample = FALSE, estimated_minutes = 55, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 21;
UPDATE lessons SET title = 'Bài 22: Mệnh đề bổ nghĩa danh từ (名詞修飾)', description = 'Dùng mệnh đề động từ để bổ nghĩa chi tiết cho danh từ.', is_sample = FALSE, estimated_minutes = 55, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 22;
UPDATE lessons SET title = 'Bài 23: Khi nào & Điều kiện tự nhiên (～とき / ～と)', description = 'Diễn tả thời điểm xảy ra hành động và kết quả tự nhiên.', is_sample = FALSE, estimated_minutes = 55, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 23;
UPDATE lessons SET title = 'Bài 24: Cho nhận hành động (～てあげます / ～てもらいます)', description = 'Hành động làm giúp ai việc gì hoặc được ai làm giúp.', is_sample = FALSE, estimated_minutes = 60, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 24;
UPDATE lessons SET title = 'Bài 25: Điều kiện Tara & Mặc dù (～たら / ～ても)', description = 'Giả định điều kiện nếu... thì... và quan hệ nhượng bộ mặc dù...', is_sample = FALSE, estimated_minutes = 60, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N5') AND sort_order = 25;

-- N4: Minna no Nihongo II (Bài 26 -> Bài 50)
UPDATE lessons SET title = 'Bài 26: Giải thích lý do & Nhấn mạnh (～んです)', description = 'Dùng Ndesu để giải thích hoàn cảnh, lý do và yêu cầu lời khuyên.', is_sample = TRUE, estimated_minutes = 45, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 1;
UPDATE lessons SET title = 'Bài 27: Động từ Khả năng (可能形)', description = 'Cách chia động từ thể khả năng (có thể làm gì).', is_sample = FALSE, estimated_minutes = 45, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 2;
UPDATE lessons SET title = 'Bài 28: Vừa làm vừa & Thói quen (～ながら / ～し)', description = 'Thực hiện 2 hành động song song và liệt kê lý do tương đồng.', is_sample = FALSE, estimated_minutes = 45, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 3;
UPDATE lessons SET title = 'Bài 29: Trạng thái kết quả & Hoàn thành (～ています / ～てしまいました)', description = 'Diễn tả trạng thái tự động từ và sự nuối tiếc lỡ làm gì.', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 4;
UPDATE lessons SET title = 'Bài 30: Chuẩn bị & Sắp đặt sẵn (～てあります / ～ておきます)', description = 'Trạng thái tha động từ có mục đích và hành động chuẩn bị sẵn.', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 5;
UPDATE lessons SET title = 'Bài 31: Ý định Volitional (意向形 / ～つもりです)', description = 'Cách chia thể Ý định và diễn tả dự định trong tương lai.', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 6;
UPDATE lessons SET title = 'Bài 32: Khuyên bảo & Suy đoán (～ほうがいいです / ～でしょう)', description = 'Đưa ra lời khuyên nên/không nên và phỏng đoán có lẽ.', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 7;
UPDATE lessons SET title = 'Bài 33: Mệnh lệnh & Cấm đoán (命令形 / 禁止形)', description = 'Chia thể Mệnh lệnh và thể Cấm đoán (dùng trong khẩn cấp/biển báo).', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 8;
UPDATE lessons SET title = 'Bài 34: Theo như & Sau khi (～とおりに / ～あとで)', description = 'Làm theo chỉ dẫn và trình tự hành động sau khi làm việc gì.', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 9;
UPDATE lessons SET title = 'Bài 35: Thể Điều kiện Ba (条件形 - ば)', description = 'Cách chia thể điều kiện Ba và mẫu câu càng... càng...', is_sample = FALSE, estimated_minutes = 50, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 10;
UPDATE lessons SET title = 'Bài 36: Cố gắng & Thay đổi trạng thái (～ようにします / ～ようになります)', description = 'Cố gắng tạo thói quen và sự thay đổi khả năng từ không thành có.', is_sample = FALSE, estimated_minutes = 55, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 11;
UPDATE lessons SET title = 'Bài 37: Thể Bị động Passive (受身形)', description = 'Cách chia thể bị động, bị ai đó làm phiền hoặc sự kiện công cộng.', is_sample = FALSE, estimated_minutes = 55, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 12;
UPDATE lessons SET title = 'Bài 38: Danh từ hóa mệnh đề (～のは / ～のが)', description = 'Biến mệnh đề động từ thành danh từ để miêu tả, thích/giỏi.', is_sample = FALSE, estimated_minutes = 55, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 13;
UPDATE lessons SET title = 'Bài 39: Nguyên nhân & Lý do khách quan (～て/で / ～ので)', description = 'Chỉ nguyên nhân kết quả tự nhiên, tai nạn, lý do khách quan.', is_sample = FALSE, estimated_minutes = 55, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 14;
UPDATE lessons SET title = 'Bài 40: Dạng nghi vấn phụ & Thử làm (～かどうか / ～てみます)', description = 'Lồng câu hỏi vào trong câu lớn và thử làm hành động gì.', is_sample = FALSE, estimated_minutes = 55, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 15;
UPDATE lessons SET title = 'Bài 41: Cho nhận kính ngữ (～ていただきます / ～てくださいます)', description = 'Hành động cho/nhận mang tính lịch sự với người trên.', is_sample = FALSE, estimated_minutes = 60, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 16;
UPDATE lessons SET title = 'Bài 42: Mục đích để làm gì (～ために / ～のに)', description = 'Dùng cho mục đích cá nhân và công dụng của đồ vật.', is_sample = FALSE, estimated_minutes = 60, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 17;
UPDATE lessons SET title = 'Bài 43: Sắp sửa & Trông có vẻ (～そうです / ～てきます)', description = 'Phỏng đoán trực quan có vẻ sắp xảy ra và đi rồi về.', is_sample = FALSE, estimated_minutes = 60, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 18;
UPDATE lessons SET title = 'Bài 44: Quá mức & Dễ/Khó làm (～すぎます / ～やすい・にくい)', description = 'Hành động quá đà và mức độ dễ/khó thực hiện.', is_sample = FALSE, estimated_minutes = 60, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 19;
UPDATE lessons SET title = 'Bài 45: Trong trường hợp & Mặc dù (～ばあいは / ～のに)', description = 'Giả định tình huống trường hợp và sự bất ngờ trái kỳ vọng.', is_sample = FALSE, estimated_minutes = 60, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 20;
UPDATE lessons SET title = 'Bài 46: Vừa mới làm xong (～ところです / ～ばかりです)', description = 'Các giai đoạn thời điểm của hành động và vừa mới làm.', is_sample = FALSE, estimated_minutes = 60, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 21;
UPDATE lessons SET title = 'Bài 47: Nghe nói & Hình như (～そうです / ～ようです)', description = 'Truyền đạt thông tin nghe đồn và suy đoán từ căn cứ.', is_sample = FALSE, estimated_minutes = 60, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 22;
UPDATE lessons SET title = 'Bài 48: Thể Sai khiến Causative (使役形 - させる)', description = 'Chia thể sai khiến, cho phép hoặc bắt người khác làm.', is_sample = FALSE, estimated_minutes = 65, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 23;
UPDATE lessons SET title = 'Bài 49: Tôn kính ngữ (尊敬語 - Keigo)', description = 'Kính ngữ dùng khi nói về hành động của cấp trên, khách hàng.', is_sample = FALSE, estimated_minutes = 65, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 24;
UPDATE lessons SET title = 'Bài 50: Khiêm nhường ngữ (謙譲語 - Kenjougo)', description = 'Khiêm nhường ngữ dùng khi nói về hành động của bản thân.', is_sample = FALSE, estimated_minutes = 65, status = 'PUBLISHED' WHERE level_id = (SELECT level_id FROM levels WHERE code = 'N4') AND sort_order = 25;
