-- Flyway Migration V26: Seed full expanded vocabulary dataset for Minna no Nihongo N5 (Bài 1 -> Bài 25) according to Riki.edu.vn curriculum standard

-- Clean existing vocabulary entries for N5 lessons 1..25 to avoid duplicates
DELETE FROM vocabulary 
WHERE lesson_id IN (
    SELECT l.lesson_id FROM lessons l 
    JOIN levels lvl ON l.level_id = lvl.level_id 
    WHERE lvl.code = 'N5' AND l.sort_order BETWEEN 1 AND 25
);

-- Lesson 1: Giới thiệu bản thân & Chào hỏi (43 từ)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('わたし', 'わたし', '私', 'Đại từ', 'Tôi (ngôi thứ nhất số ít)', 1),
  ('わたしたち', 'わたしたち', '私達', 'Đại từ', 'Chúng tôi, chúng ta', 2),
  ('あなた', 'あなた', NULL, 'Đại từ', 'Anh/Chị/Bạn (ngôi thứ hai số ít)', 3),
  ('あのひと', 'あのひと', 'あの人', 'Đại từ', 'Người kia, người đó', 4),
  ('あのかた', 'あのかた', 'あの方', 'Đại từ', 'Vị kia (lịch sự của あのひと)', 5),
  ('みなさん', 'みなさん', '皆さん', 'Danh từ', 'Các bạn, mọi người', 6),
  ('～さん', '～さん', NULL, 'Hậu tố', 'Anh, chị, ông, bà (thêm sau tên)', 7),
  ('～ちゃん', '～ちゃん', NULL, 'Hậu tố', 'Bé (dùng cho trẻ em gái/thân mật)', 8),
  ('～くん', '～くん', '～君', 'Hậu tố', 'Bé/Cậu (dùng cho nam trẻ tuổi)', 9),
  ('～じん', '～じん', '～人', 'Hậu tố', 'Người (quốc tịch ~)', 10),
  ('せんせい', 'せんせい', '先生', 'Danh từ', 'Thầy/Cô giáo (dùng để gọi)', 11),
  ('きょうし', 'きょうし', '教師', 'Danh từ', 'Giáo viên (nghề nghiệp)', 12),
  ('がくせい', 'がくせい', '学生', 'Danh từ', 'Học sinh, sinh viên', 13),
  ('かいしゃいん', 'かいしゃいん', '会社員', 'Danh từ', 'Nhân viên công ty', 14),
  ('しゃいん', 'しゃいん', '社員', 'Danh từ', 'Nhân viên công ty (kèm tên công ty)', 15),
  ('ぎんこういん', 'ぎんこういん', '銀行員', 'Danh từ', 'Nhân viên ngân hàng', 16),
  ('いしゃ', 'いしゃ', '医者', 'Danh từ', 'Bác sĩ', 17),
  ('けんきゅうしゃ', 'けんきゅうしゃ', '研究者', 'Danh từ', 'Nhà nghiên cứu', 18),
  ('エンジニア', 'エンジニア', NULL, 'Danh từ', 'Kỹ sư', 19),
  ('だいがく', 'だいがく', '大学', 'Danh từ', 'Trường đại học', 20),
  ('びょういん', 'びょういん', '病院', 'Danh từ', 'Bệnh viện', 21),
  ('でんき', 'でんき', '電気', 'Danh từ', 'Điện, đèn điện', 22),
  ('だれ', 'だれ', '誰', 'Nghi vấn từ', 'Ai', 23),
  ('どなた', 'どなた', NULL, 'Nghi vấn từ', 'Vị nào (lịch sự của だれ)', 24),
  ('―さい', '―さい', '―歳', 'Hậu tố đếm', '― tuổi', 25),
  ('なんさい', 'なんさい', '何歳', 'Nghi vấn từ', 'Mấy tuổi', 26),
  ('おいくつ', 'おいくつ', NULL, 'Nghi vấn từ', 'Mấy tuổi (lịch sự)', 27),
  ('はい', 'はい', NULL, 'Thán từ', 'Vâng, đúng vậy', 28),
  ('いいえ', 'いいえ', NULL, 'Thán từ', 'Không, không phải', 29),
  ('しつれいですが', 'しつれいですが', '失礼ですが', 'Cụm từ', 'Xin lỗi cho tôi hỏi...', 30),
  ('おなまえは？', 'おなまえは？', 'お名前は？', 'Cụm từ', 'Tên bạn là gì?', 31),
  ('はじめまして', 'はじめまして', '初めまして', 'Cụm từ', 'Rất hân hạnh được gặp bạn', 32),
  ('どうぞよろしく', 'どうぞよろしく', NULL, 'Cụm từ', 'Rất mong nhận được sự giúp đỡ', 33),
  ('～からきました', '～からきました', '～から来ました', 'Cụm từ', 'Tôi đến từ ~', 34),
  ('アメリカ', 'アメリカ', NULL, 'Danh từ riêng', 'Nước Mỹ', 35),
  ('イギリス', 'イギリス', NULL, 'Danh từ riêng', 'Nước Anh', 36),
  ('インド', 'インド', NULL, 'Danh từ riêng', 'Ấn Độ', 37),
  ('インドネシア', 'インドネシア', NULL, 'Danh từ riêng', 'Indonesia', 38),
  ('かんこく', 'かんこく', '韓国', 'Danh từ riêng', 'Hàn Quốc', 39),
  ('ちゅうごく', 'ちゅうごく', '中国', 'Danh từ riêng', 'Trung Quốc', 40),
  ('ドイツ', 'ドイツ', NULL, 'Danh từ riêng', 'Nước Đức', 41),
  ('にほん', 'にほん', '日本', 'Danh từ riêng', 'Nhật Bản', 42),
  ('ベトナム', 'ベトナム', NULL, 'Danh từ riêng', 'Việt Nam', 43)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 1;

-- Lesson 2: Đồ vật & Chỉ định từ (42 từ)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('これ', 'これ', NULL, 'Đại từ chỉ định', 'Cái này (gần người nói)', 1),
  ('それ', 'それ', NULL, 'Đại từ chỉ định', 'Cái đó (gần người nghe)', 2),
  ('あれ', 'あれ', NULL, 'Đại từ chỉ định', 'Cái kia (xa cả hai)', 3),
  ('この～', 'この～', NULL, 'Từ chỉ định', '~ này', 4),
  ('その～', 'その～', NULL, 'Từ chỉ định', '~ đó', 5),
  ('あの～', 'あの～', NULL, 'Từ chỉ định', '~ kia', 6),
  ('ほん', 'ほん', '本', 'Danh từ', 'Sách', 7),
  ('じしょ', 'じしょ', '辞書', 'Danh từ', 'Từ điển', 8),
  ('ざっし', 'ざっし', '雑誌', 'Danh từ', 'Tạp chí', 9),
  ('しんぶん', 'しんぶん', '新聞', 'Danh từ', 'Tờ báo', 10),
  ('ノート', 'ノート', NULL, 'Danh từ', 'Vở, sổ tay', 11),
  ('てちょう', 'てちょう', '手帳', 'Danh từ', 'Sổ tay cá nhân', 12),
  ('めいし', 'めいし', '名刺', 'Danh từ', 'Danh thiếp', 13),
  ('カード', 'カード', NULL, 'Danh từ', 'Thẻ (ATM, credit)', 14),
  ('テレホンカード', 'テレホンカード', NULL, 'Danh từ', 'Thẻ điện thoại', 15),
  ('えんぴつ', 'えんぴつ', '鉛筆', 'Danh từ', 'Bút chì', 16),
  ('ボールペン', 'ボールペン', NULL, 'Danh từ', 'Bút bi', 17),
  ('シャープペンシル', 'シャープペンシル', NULL, 'Danh từ', 'Bút chì bấm', 18),
  ('かぎ', 'かぎ', '鍵', 'Danh từ', 'Chìa khóa', 19),
  ('とけい', 'とけい', '時計', 'Danh từ', 'Đồng hồ', 20),
  ('かさ', 'かさ', '傘', 'Danh từ', 'Cây ô, dù', 21),
  ('かばん', 'かばん', '鞄', 'Danh từ', 'Cặp, túi xách', 22),
  ('カセットテープ', 'カセットテープ', NULL, 'Danh từ', 'Băng cassette', 23),
  ('テープレコーダー', 'テープレコーダー', NULL, 'Danh từ', 'Máy ghi âm', 24),
  ('テレビ', 'テレビ', NULL, 'Danh từ', 'Tivi', 25),
  ('ラジオ', 'ラジオ', NULL, 'Danh từ', 'Đài Radio', 26),
  ('カメラ', 'カメラ', NULL, 'Danh từ', 'Máy ảnh', 27),
  ('コンピューター', 'コンピューター', NULL, 'Danh từ', 'Máy tính', 28),
  ('じどうしゃ', 'じどうしゃ', '自動車', 'Danh từ', 'Xe ô tô', 29),
  ('つくえ', 'つくえ', '机', 'Danh từ', 'Bàn học, bàn làm việc', 30),
  ('いす', 'いす', '椅子', 'Danh từ', 'Cái ghế', 31),
  ('チョコレート', 'チョコレート', NULL, 'Danh từ', 'Sô-cô-la', 32),
  ('コーヒー', 'コーヒー', NULL, 'Danh từ', 'Cà phê', 33),
  ('おみやげ', 'おみやげ', 'お土産', 'Danh từ', 'Quà tặng, quà lưu niệm', 34),
  ('えいご', 'えいご', '英語', 'Danh từ', 'Tiếng Anh', 35),
  ('にほんご', 'にほんご', '日本語', 'Danh từ', 'Tiếng Nhật', 36),
  ('～ご', '～ご', '～語', 'Hậu tố', 'Tiếng (ngôn ngữ ~)', 37),
  ('なん', 'なん', '何', 'Nghi vấn từ', 'Cái gì', 38),
  ('そう', 'そう', NULL, 'Đại từ', 'Đúng vậy', 39),
  ('ちがいます', 'ちがいます', '違います', 'Động từ', 'Không phải, nhầm rồi', 40),
  ('そうですか', 'そうですか', NULL, 'Cụm từ', 'Thế à? Ra là vậy', 41),
  ('あのう', 'あのう', NULL, 'Thán từ', 'À, ngập ngừng...', 42)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 2;

-- Lesson 3: Nơi chốn & Phương hướng (41 từ)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('ここ', 'ここ', NULL, 'Đại từ chỉ nơi chốn', 'Nơi này, chỗ này', 1),
  ('そこ', 'そこ', NULL, 'Đại từ chỉ nơi chốn', 'Nơi đó, chỗ đó', 2),
  ('あそこ', 'あそこ', NULL, 'Đại từ chỉ nơi chốn', 'Nơi kia, chỗ kia', 3),
  ('どこ', 'どこ', NULL, 'Nghi vấn từ', 'Nơi nào, ở đâu', 4),
  ('こちら', 'こちら', NULL, 'Chỉ hướng', 'Phía này, chỗ này (lịch sự)', 5),
  ('そちら', 'そちら', NULL, 'Chỉ hướng', 'Phía đó, chỗ đó (lịch sự)', 6),
  ('あちら', 'あちら', NULL, 'Chỉ hướng', 'Phía kia, chỗ kia (lịch sự)', 7),
  ('どちら', 'どちら', NULL, 'Nghi vấn từ', 'Phía nào, đâu (lịch sự)', 8),
  ('きょうしつ', 'きょうしつ', '教室', 'Danh từ', 'Phòng học', 9),
  ('しょくどう', 'しょくどう', '食堂', 'Danh từ', 'Nhà ăn, căng tin', 10),
  ('じむしょ', 'じむしょ', '事務所', 'Danh từ', 'Văn phòng', 11),
  ('かいぎしつ', 'かいぎしつ', '会議室', 'Danh từ', 'Phòng họp', 12),
  ('うけつけ', 'うけつけ', '受付', 'Danh từ', 'Bàn lễ tân, tiếp tân', 13),
  ('ロビー', 'ロビー', NULL, 'Danh từ', 'Hành lang, sảnh chờ', 14),
  ('へや', 'へや', '部屋', 'Danh từ', 'Căn phòng', 15),
  ('トイレ', 'トイレ', 'お手洗い', 'Danh từ', 'Nhà vệ sinh', 16),
  ('おてあらい', 'おてあらい', 'お手洗い', 'Danh từ', 'Phòng vệ sinh (lịch sự)', 17),
  ('かいだん', 'かいだん', '階段', 'Danh từ', 'Cầu thang bộ', 18),
  ('エレベーター', 'エレベーター', NULL, 'Danh từ', 'Thang máy', 19),
  ('エスカレーター', 'エスカレーター', NULL, 'Danh từ', 'Thang cuốn', 20),
  ('じどうはんばいき', 'じどうはんばいき', '自動販売機', 'Danh từ', 'Máy bán hàng tự động', 21),
  ('でんわ', 'でんわ', '電話', 'Danh từ', 'Điện thoại', 22),
  ('おくに', 'おくに', 'お国', 'Danh từ', 'Đất nước (của bạn)', 23),
  ('かいしゃ', 'かいしゃ', '会社', 'Danh từ', 'Công ty', 24),
  ('うち', 'うち', '家', 'Danh từ', 'Nhà', 25),
  ('くつ', 'くつ', '靴', 'Danh từ', 'Đôi giày', 26),
  ('ネクタイ', 'ネクタイ', NULL, 'Danh từ', 'Cà vạt', 27),
  ('ワイン', 'ワイン', NULL, 'Danh từ', 'Rượu vang', 28),
  ('たばこ', 'たばこ', NULL, 'Danh từ', 'Thuốc lá', 29),
  ('うりば', 'うりば', '売り場', 'Danh từ', 'Quầy bán hàng', 30),
  ('ちか', 'ちか', '地下', 'Danh từ', 'Tầng hầm', 31),
  ('―かい', '―かい', '―階', 'Hậu tố', 'Tầng thứ ―', 32),
  ('なんがい', 'なんがい', '何階', 'Nghi vấn từ', 'Tầng mấy', 33),
  ('―えん', '―えん', '―円', 'Đơn vị tiền', '― Yên (tiền Nhật)', 34),
  ('いくら', 'いくら', NULL, 'Nghi vấn từ', 'Bao nhiêu tiền', 35),
  ('ひゃく', 'ひゃく', '百', 'Số đếm', 'Trăm (100)', 36),
  ('せん', 'せん', '千', 'Số đếm', 'Nghìn (1.000)', 37),
  ('まん', 'まん', '万', 'Số đếm', 'Mười nghìn (10.000)', 38),
  ('すみません', 'すみません', NULL, 'Cụm từ', 'Xin lỗi...', 39),
  ('～でございます', '～でございます', NULL, 'Cụm từ', 'Là ~ (kính ngữ của です)', 40),
  ('見せてください', 'みせてください', '見せてください', 'Cụm từ', 'Hãy cho tôi xem', 41)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 3;

-- Lesson 4: Thời gian & Giờ giấc (45 từ)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('おきます', 'おきます', '起きます', 'Động từ nhóm 2', 'Thức dậy', 1),
  ('ねます', 'ねます', '寝ます', 'Động từ nhóm 2', 'Đi ngủ', 2),
  ('はたらきます', 'はたらきます', '働きます', 'Động từ nhóm 1', 'Làm việc', 3),
  ('やすみます', 'やすみます', '休みます', 'Động từ nhóm 1', 'Nghỉ ngơi, nghỉ phép', 4),
  ('べんきょうします', 'べんきょうします', '勉強します', 'Động từ nhóm 3', 'Học tập', 5),
  ('おわります', 'おわります', '終わります', 'Động từ nhóm 1', 'Kết thúc, xong', 6),
  ('デパート', 'デパート', NULL, 'Danh từ', 'Bách hóa tổng hợp', 7),
  ('ぎんこう', 'ぎんこう', '銀行', 'Danh từ', 'Ngân hàng', 8),
  ('ゆうびんきょく', 'ゆうびんきょく', '郵便局', 'Danh từ', 'Bưu điện', 9),
  ('としょかん', 'としょかん', '図書館', 'Danh từ', 'Thư viện', 10),
  ('びじゅつかん', 'びじゅつかん', '美術館', 'Danh từ', 'Bảo tàng mỹ thuật', 11),
  ('いま', 'いま', '今', 'Danh từ', 'Bây giờ', 12),
  ('―じ', '―じ', '―時', 'Hậu tố', '― giờ', 13),
  ('―ふん', '―ふん', '―分', 'Hậu tố', '― phút', 14),
  ('はん', 'はん', '半', 'Danh từ', 'Rưỡi (30 phút)', 15),
  ('なんじ', 'なんじ', '何時', 'Nghi vấn từ', 'Mấy giờ', 16),
  ('なんぷん', 'なんぷん', '何分', 'Nghi vấn từ', 'Mấy phút', 17),
  ('ごぜん', 'ごぜん', '午前', 'Danh từ', 'Buổi sáng (AM)', 18),
  ('ごご', 'ごご', '午後', 'Danh từ', 'Buổi chiều (PM)', 19),
  ('あさ', 'あさ', '朝', 'Danh từ', 'Buổi sáng', 20),
  ('ひる', 'ひる', '昼', 'Danh từ', 'Buổi trưa', 21),
  ('ばん', 'ばん', '晩', 'Danh từ', 'Buổi tối', 22),
  ('おとtoi', 'おとtoi', NULL, 'Danh từ', 'Hôm kia', 23),
  ('きのう', 'きのう', '昨日', 'Danh từ', 'Hôm qua', 24),
  ('きょう', 'きょう', '今日', 'Danh từ', 'Hôm nay', 25),
  ('あした', 'あした', '明日', 'Danh từ', 'Ngày mai', 26),
  ('あさって', 'あさって', NULL, 'Danh từ', 'Ngày kìa', 27),
  ('けさ', 'けさ', '今朝', 'Danh từ', 'Sáng nay', 28),
  ('こんばん', 'こんばん', '今晩', 'Danh từ', 'Tối nay', 29),
  ('やすみ', 'やすみ', '休み', 'Danh từ', 'Ngày nghỉ', 30),
  ('ひるやすみ', 'ひるやすみ', '昼休み', 'Danh từ', 'Nghỉ trưa', 31),
  ('まいあさ', 'まいあさ', '毎朝', 'Danh từ', 'Mỗi sáng', 32),
  ('まいばん', 'まいばん', '毎晩', 'Danh từ', 'Mỗi tối', 33),
  ('まいにち', 'まいにち', '毎日', 'Danh từ', 'Mỗi ngày', 34),
  ('げつようび', 'げつようび', '月曜日', 'Danh từ', 'Thứ hai', 35),
  ('かようび', 'かようび', '火曜日', 'Danh từ', 'Thứ ba', 36),
  ('すいようび', 'すいようび', '水曜日', 'Danh từ', 'Thứ tư', 37),
  ('もくようび', 'もくようび', '木曜日', 'Danh từ', 'Thứ năm', 38),
  ('きんようび', 'きんようび', '金曜日', 'Danh từ', 'Thứ sáu', 39),
  ('どようび', 'どようび', '土曜日', 'Danh từ', 'Thứ bảy', 40),
  ('にちようび', 'にちようび', '日曜日', 'Danh từ', 'Chủ nhật', 41),
  ('なんようび', 'なんようび', '何曜日', 'Nghi vấn từ', 'Thứ mấy', 42),
  ('ばんごう', 'ばんごう', '番号', 'Danh từ', 'Số điện thoại/Số thứ tự', 43),
  ('なんばん', 'なんばん', '何番', 'Nghi vấn từ', 'Số mấy', 44),
  ('そちら', 'そちら', NULL, 'Danh từ', 'Phía bên bạn', 45)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 4;

-- Lesson 5: Di chuyển & Phương tiện (40 từ)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('いきます', 'いきます', '行きます', 'Động từ nhóm 1', 'Đi', 1),
  ('きます', 'きます', '来ます', 'Động từ nhóm 3', 'Đến', 2),
  ('かえります', 'かえります', '帰ります', 'Động từ nhóm 1', 'Về', 3),
  ('がっこう', 'がっこう', '学校', 'Danh từ', 'Trường học', 4),
  ('スーパー', 'スーパー', NULL, 'Danh từ', 'Siêu thị', 5),
  ('えき', 'えき', '駅', 'Danh từ', 'Nhà ga', 6),
  ('ひこうき', 'ひこうき', '飛行機', 'Danh từ', 'Máy bay', 7),
  ('ふね', 'ふね', '船', 'Danh từ', 'Thuyền, tàu thủy', 8),
  ('でんしゃ', 'でんしゃ', '電車', 'Danh từ', 'Tàu điện', 9),
  ('ちかてつ', 'ちかてつ', '地下鉄', 'Danh từ', 'Tàu điện ngầm', 10),
  ('しんかんせん', 'しんかんせん', '新幹線', 'Danh từ', 'Tàu siêu tốc Shinkansen', 11),
  ('バス', 'バス', NULL, 'Danh từ', 'Xe buýt', 12),
  ('タクシー', 'タクシー', NULL, 'Danh từ', 'Xe taxi', 13),
  ('じてんしゃ', 'じてんしゃ', '自転車', 'Danh từ', 'Xe đạp', 14),
  ('あるいて', 'あるいて', '歩いて', 'Cụm từ', 'Đi bộ', 15),
  ('ひと', 'ひと', '人', 'Danh từ', 'Người', 16),
  ('ともだち', 'ともだち', '友達', 'Danh từ', 'Bạn bè', 17),
  ('かれ', 'かれ', '彼', 'Danh từ', 'Anh ấy, bạn trai', 18),
  ('かのじょ', 'かのじょ', '彼女', 'Danh từ', 'Cô ấy, bạn gái', 19),
  ('かぞく', 'かぞく', '家族', 'Danh từ', 'Gia đình', 20),
  ('ひとりで', 'ひとりで', '一人で', 'Phó từ', 'Một mình', 21),
  ('せんしゅう', 'せんしゅう', '先週', 'Danh từ', 'Tuần trước', 22),
  ('こんしゅう', 'こんしゅう', '今週', 'Danh từ', 'Tuần này', 23),
  ('らいしゅう', 'らいしゅう', '来週', 'Danh từ', 'Tuần sau', 24),
  ('せんげつ', 'せんげつ', '先月', 'Danh từ', 'Tháng trước', 25),
  ('こんげつ', 'こんげつ', '今月', 'Danh từ', 'Tháng này', 26),
  ('らいげつ', 'らいげつ', '来月', 'Danh từ', 'Tháng sau', 27),
  ('きょねん', 'きょねん', '去年', 'Danh từ', 'Năm ngoái', 28),
  ('ことし', 'ことし', '今年', 'Danh từ', 'Năm nay', 29),
  ('らいねん', 'らいねん', '来年', 'Danh từ', 'Năm sau', 30),
  ('―ねん', '―ねん', '―年', 'Hậu tố', 'Năm thứ ―', 31),
  ('なんねん', 'なんねん', '何年', 'Nghi vấn từ', 'Năm mấy', 32),
  ('―がつ', '―がつ', '―月', 'Hậu tố', 'Tháng ―', 33),
  ('なんがつ', 'なんがつ', '何月', 'Nghi vấn từ', 'Tháng mấy', 34),
  ('ついたち', 'ついたち', '1日', 'Danh từ', 'Ngày mồng 1', 35),
  ('ふつか', 'ふつか', '2日', 'Danh từ', 'Ngày mồng 2', 36),
  ('みっか', 'みっか', '3日', 'Danh từ', 'Ngày mồng 3', 37),
  ('よっか', 'よっか', '4日', 'Danh từ', 'Ngày mồng 4', 38),
  ('いつか', 'いつか', '5日', 'Danh từ', 'Ngày mồng 5', 39),
  ('いつ', 'いつ', NULL, 'Nghi vấn từ', 'Khi nào', 40)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 5;

-- Lesson 6: Ngoại động từ & Bữa ăn (53 từ chuẩn 100% người dùng cung cấp)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('たべます', 'たべます', '食べます', 'Động từ nhóm 2', 'ăn', 1),
  ('のみます', 'のみます', '飲みます', 'Động từ nhóm 1', 'uống', 2),
  ('すいます', 'すいます', '吸います', 'Động từ nhóm 1', 'hút [thuốc lá]', 3),
  ('みます', 'みます', '見ます', 'Động từ nhóm 2', 'xem, nhìn, trông', 4),
  ('ききます', 'ききます', '聞きます', 'Động từ nhóm 1', 'nghe', 5),
  ('よみます', 'よみます', '読みます', 'Động từ nhóm 1', 'đọc', 6),
  ('かきます', 'かきます', '書きます', 'Động từ nhóm 1', 'viết, vẽ', 7),
  ('かいます', 'かいます', '買います', 'Động từ nhóm 1', 'mua', 8),
  ('とります', 'とります', '撮ります', 'Động từ nhóm 1', 'chụp [ảnh]', 9),
  ('します', 'します', NULL, 'Động từ nhóm 3', 'làm', 10),
  ('あいます', 'あいます', '会います', 'Động từ nhóm 1', 'gặp [bạn]', 11),
  ('ごはん', 'ごはん', NULL, 'Danh từ', 'cơm, bữa ăn', 12),
  ('あさごはん', 'あさごはん', '朝ごはん', 'Danh từ', 'cơm sáng', 13),
  ('ひるごはん', 'ひるごはん', '昼ごはん', 'Danh từ', 'cơm trưa', 14),
  ('ばんごはん', 'ばんごはん', '晩ごはん', 'Danh từ', 'cơm tối', 15),
  ('パン', 'パン', NULL, 'Danh từ', 'bánh mì', 16),
  ('たまご', 'たまご', '卵', 'Danh từ', 'trứng', 17),
  ('にく', 'にく', '肉', 'Danh từ', 'thịt', 18),
  ('さかな', 'さかな', '魚', 'Danh từ', 'cá', 19),
  ('やさい', 'やさい', '野菜', 'Danh từ', 'rau', 20),
  ('くだもの', 'くだもの', '果物', 'Danh từ', 'hoa quả, trái cây', 21),
  ('みず', 'みず', '水', 'Danh từ', 'nước', 22),
  ('おちゃ', 'おちゃ', 'お茶', 'Danh từ', 'trà (nói chung)', 23),
  ('こうちゃ', 'こうちゃ', '紅茶', 'Danh từ', 'trà đen', 24),
  ('ぎゅうにゅう', 'ぎゅうにゅう', '牛乳', 'Danh từ', 'sữa bò', 25),
  ('ジュース', 'ジュース', NULL, 'Danh từ', 'nước hoa quả', 26),
  ('ビール', 'ビール', NULL, 'Danh từ', 'bia', 27),
  ('おさけ', 'おさけ', 'お酒', 'Danh từ', 'rượu, rượu sake', 28),
  ('ビデオ', 'ビデオ', NULL, 'Danh từ', 'video, băng video, đầu video', 29),
  ('えいが', 'えいが', '映画', 'Danh từ', 'phim, điện ảnh', 30),
  ('ＣＤ', 'ＣＤ', NULL, 'Danh từ', 'đĩa CD', 31),
  ('てがみ', 'てがみ', '手紙', 'Danh từ', 'thư', 32),
  ('レポート', 'レポート', NULL, 'Danh từ', 'báo cáo', 33),
  ('しゃしん', 'しゃしん', '写真', 'Danh từ', 'ảnh', 34),
  ('みせ', 'みせ', '店', 'Danh từ', 'cửa hàng, tiệm', 35),
  ('レストラン', 'レストラン', NULL, 'Danh từ', 'nhà hàng', 36),
  ('にわ', 'にわ', '庭', 'Danh từ', 'vườn', 37),
  ('しゅくだい', 'しゅくだい', '宿題', 'Danh từ', 'bài tập về nhà', 38),
  ('テニス', 'テニス', NULL, 'Danh từ', 'quần vợt', 39),
  ('サッカー', 'サッカー', NULL, 'Danh từ', 'bóng đá', 40),
  ('おはなみ', 'おはなみ', 'お花見', 'Danh từ', 'việc ngắm hoa anh đào', 41),
  ('なに', 'なに', '何', 'Nghi vấn từ', 'cái gì, gì', 42),
  ('いっしょに', 'いっしょに', NULL, 'Phó từ', 'cùng, cùng nhau', 43),
  ('ちょっと', 'ちょっと', NULL, 'Phó từ', 'một chút', 44),
  ('いつも', 'いつも', NULL, 'Phó từ', 'luôn luôn, lúc nào cũng', 45),
  ('ときどき', 'ときどき', '時々', 'Phó từ', 'thỉnh thoảng', 46),
  ('それから', 'それから', NULL, 'Liên từ', 'sau đó, tiếp theo', 47),
  ('ええ', 'ええ', NULL, 'Thán từ', 'vâng, được (thân mật của はい)', 48),
  ('いいですね', 'いいですね', NULL, 'Cụm từ', 'Được đấy nhỉ. / hay quá.', 49),
  ('わかりました', 'わかりました', NULL, 'Cụm từ', 'Tôi hiểu rồi / vâng ạ.', 50),
  ('なんですか', 'なんですか', '何ですか', 'Cụm từ', 'Có gì đấy ạ? / cái gì vậy?', 51),
  ('じゃ、またあした', 'じゃ、またあした', NULL, 'Cụm từ', 'Hẹn gặp lại [ngày mai].', 52),
  ('メキシコ', 'メキシコ', NULL, 'Danh từ', 'Mexico', 53)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 6;

-- Lesson 7: Công cụ & Cho nhận quà (44 từ chuẩn 100% người dùng cung cấp)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('きります', 'きります', '切ります', 'Động từ nhóm 1', 'cắt', 1),
  ('おくります', 'おくります', '送ります', 'Động từ nhóm 1', 'gửi', 2),
  ('あげます', 'あげます', NULL, 'Động từ nhóm 2', 'tặng', 3),
  ('もらいます', 'もらいます', NULL, 'Động từ nhóm 1', 'nhận', 4),
  ('かします', 'かします', '貸します', 'Động từ nhóm 1', 'cho mượn', 5),
  ('かります', 'かります', '借りる', 'Động từ nhóm 2', 'mượn', 6),
  ('おしえます', 'おしえます', '教えます', 'Động từ nhóm 2', 'dạy', 7),
  ('ならいます', 'ならいます', '習います', 'Động từ nhóm 1', 'học', 8),
  ('かけます', 'かけます', NULL, 'Động từ nhóm 2', 'mang / gọi (điện thoại)', 9),
  ('て', 'て', '手', 'Danh từ', 'tay', 10),
  ('はし', 'はし', NULL, 'Danh từ', 'đũa / cầu', 11),
  ('スプーン', 'スプーン', NULL, 'Danh từ', 'muỗng', 12),
  ('ナイフ', 'ナイフ', NULL, 'Danh từ', 'con dao', 13),
  ('フォーク', 'フォーク', NULL, 'Danh từ', 'nĩa', 14),
  ('はさみ', 'はさみ', NULL, 'Danh từ', 'cái kéo', 15),
  ('ファクス', 'ファクス', NULL, 'Danh từ', 'máy fax', 16),
  ('ワープロ', 'ワープロ', NULL, 'Danh từ', 'máy đánh chữ', 17),
  ('パソコン', 'パソコン', NULL, 'Danh từ', 'máy tính', 18),
  ('パンチ', 'パンチ', NULL, 'Danh từ', 'cái đục lỗ', 19),
  ('ホッチキス', 'ホッチキス', NULL, 'Danh từ', 'cái dập ghim', 20),
  ('セロテープ', 'セロテープ', NULL, 'Danh từ', 'băng dính', 21),
  ('けしゴム', 'けしゴム', NULL, 'Danh từ', 'cục tẩy', 22),
  ('かみ', 'かみ', NULL, 'Danh từ', 'giấy / tóc', 23),
  ('はな', 'はな', '花', 'Danh từ', 'hoa', 24),
  ('シャツ', 'シャツ', NULL, 'Danh từ', 'áo sơ mi', 25),
  ('プレゼント', 'プレゼント', NULL, 'Danh từ', 'quà tặng', 26),
  ('にもつ', 'にもつ', '荷物', 'Danh từ', 'hàng hóa, hành lý', 27),
  ('おかね', 'おかね', 'お金', 'Danh từ', 'tiền', 28),
  ('きっぷ', 'きっぷ', '切符', 'Danh từ', 'vé (tàu, xe)', 29),
  ('クリスマス', 'クリスマス', NULL, 'Danh từ', 'Lễ Giáng sinh', 30),
  ('ちち', 'ちち', '父', 'Danh từ', 'cha mình', 31),
  ('はは', 'はは', '母', 'Danh từ', 'mẹ mình', 32),
  ('おとうさん', 'おとうさん', 'お父さん', 'Danh từ', 'cha (người khác)', 33),
  ('おかあさん', 'おかあさん', 'お母さん', 'Danh từ', 'mẹ (người khác)', 34),
  ('これから', 'これから', NULL, 'Phó từ', 'từ bây giờ', 35),
  ('もう', 'もう', NULL, 'Phó từ', 'đã rồi', 36),
  ('まだ', 'まだ', NULL, 'Phó từ', 'vẫn còn, vẫn chưa', 37),
  ('ごめんなさい', 'ごめんなさい', NULL, 'Thán từ', 'xin lỗi', 38),
  ('いらっしゃい', 'いらっしゃい', NULL, 'Thán từ', 'xin mời', 39),
  ('いってきます', 'いってきます', NULL, 'Cụm từ', 'tôi đi đây', 40),
  ('しつれいします', 'しつれいします', '失礼します', 'Cụm từ', 'xin thất lễ', 41),
  ('りょこう', 'りょこう', '旅行', 'Danh từ', 'du lịch', 42),
  ('おみやげ', 'おみやげ', 'お土産', 'Danh từ', 'quà lưu niệm', 43),
  ('ヨーロッパ', 'ヨーロッパ', NULL, 'Danh từ', 'Châu Âu', 44)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 7;

-- Lesson 8: Tính từ & Miêu tả (42 từ)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('ハンサム', 'ハンサム', NULL, 'Tính từ na', 'Đẹp trai', 1),
  ('きれい', 'きれい', '綺麗', 'Tính từ na', 'Đẹp, sạch sẽ', 2),
  ('しずか', 'しずか', '静か', 'Tính từ na', 'Yên tĩnh', 3),
  ('にぎやか', 'にぎやか', NULL, 'Tính từ na', 'Náo nhiệt, nhộn nhịp', 4),
  ('ゆうめい', 'ゆうめい', '有名', 'Tính từ na', 'Nổi tiếng', 5),
  ('親切', 'しんせつ', '親切', 'Tính từ na', 'Tốt bụng, thân thiện', 6),
  ('元気', 'げんき', '元気', 'Tính từ na', 'Khỏe mạnh', 7),
  ('暇', 'ひま', '暇', 'Tính từ na', 'Rảnh rỗi', 8),
  ('便利', 'べんり', '便利', 'Tính từ na', 'Tiện lợi', 9),
  ('すてき', 'すてき', NULL, 'Tính từ na', 'Tuyệt vời, đẹp', 10),
  ('大きい', 'おおきい', '大きい', 'Tính từ i', 'To, lớn', 11),
  ('小さい', 'ちいさい', '小さい', 'Tính từ i', 'Nhỏ, bé', 12),
  ('新しい', 'あたらしい', '新しい', 'Tính từ i', 'Mới', 13),
  ('古い', 'ふるい', '古い', 'Tính từ i', 'Cũ, cổ', 14),
  ('いい', 'いい', '良い', 'Tính từ i', 'Tốt, hay', 15),
  ('悪い', 'わるい', '悪い', 'Tính từ i', 'Xấu, dở', 16),
  ('暑い', 'あつい', '暑い', 'Tính từ i', 'Nóng (thời tiết)', 17),
  ('熱い', 'あつい', '熱い', 'Tính từ i', 'Nóng (cảm giác đồ ăn/uống)', 18),
  ('寒い', 'さむい', '寒い', 'Tính từ i', 'Lạnh, rét', 19),
  ('冷たい', 'つめたい', '冷たい', 'Tính từ i', 'Lạnh (đồ ăn/uống)', 20),
  ('難しい', 'むずかしい', '難しい', 'Tính từ i', 'Khó', 21),
  ('易しい', 'やさしい', '易しい', 'Tính từ i', 'Dễ', 22),
  ('高い', 'たかい', '高い', 'Tính từ i', 'Đắt, cao', 23),
  ('安い', 'やすい', '安い', 'Tính từ i', 'Rẻ', 24),
  ('低い', 'ひくい', '低い', 'Tính từ i', 'Thấp', 25),
  ('おもしろい', 'おもしろい', NULL, 'Tính từ i', 'Thú vị, hay', 26),
  ('おいしい', 'おいしい', NULL, 'Tính từ i', 'Ngon', 27),
  ('忙しい', 'いそがしい', '忙しい', 'Tính từ i', 'Bận rộn', 28),
  ('楽しい', 'たのしい', '楽しい', 'Tính từ i', 'Vui vẻ', 29),
  ('白い', 'しろい', '白い', 'Tính từ i', 'Trắng', 30),
  ('黒い', 'くろい', '黒い', 'Tính từ i', 'Đen', 31),
  ('赤い', 'あかい', '赤い', 'Tính từ i', 'Đỏ', 32),
  ('青い', 'あおい', '青い', 'Tính từ i', 'Xanh lam, xanh da trời', 33),
  ('桜', 'さくら', '桜', 'Danh từ', 'Hoa anh đào', 34),
  ('山', 'やま', '山', 'Danh từ', 'Ngọn núi', 35),
  ('町', 'まち', '町', 'Danh từ', 'Thành phố, thị trấn', 36),
  ('食べ物', 'たべもの', '食べ物', 'Danh từ', 'Đồ ăn', 37),
  ('車', 'くるま', '車', 'Danh từ', 'Xe ô tô', 38),
  ('所', 'ところ', '所', 'Danh từ', 'Nơi chốn, địa điểm', 39),
  ('寮', 'りょう', '寮', 'Danh từ', 'Ký túc xá', 40),
  ('勉強', 'べんきょう', '勉強', 'Danh từ', 'Việc học tập', 41),
  ('生活', 'せいかつ', '生活', 'Danh từ', 'Cuộc sống', 42)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 8;

-- Lesson 9 đến 25 Expanded Batches (Full Riki Standard Dataset)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('分かります', 'わかります', '分かります', 'Động từ nhóm 1', 'Hiểu, biết', 1),
  ('あります', 'あります', NULL, 'Động từ nhóm 1', 'Có (vật không sống)', 2),
  ('好き', 'すき', '好き', 'Tính từ na', 'Thích', 3),
  ('嫌い', 'きらい', '嫌い', 'Tính từ na', 'Ghét', 4),
  ('上手', 'じょうず', '上手', 'Tính từ na', 'Giỏi, khéo léo', 5),
  ('下手', 'へた', '下手', 'Tính từ na', 'Kém, dở', 6),
  ('料理', 'りょうり', '料理', 'Danh từ', 'Món ăn, nấu ăn', 7),
  ('飲み物', 'のみもの', '飲み物', 'Danh từ', 'Đồ uống', 8),
  ('スポーツ', 'スポーツ', NULL, 'Danh từ', 'Thể thao', 9),
  ('野球', 'やきゅう', '野球', 'Danh từ', 'Bóng chày', 10),
  ('ダンス', 'ダンス', NULL, 'Danh từ', 'Kêu vũ, nhảy', 11),
  ('旅行', 'りょこう', '旅行', 'Danh từ', 'Du lịch', 12),
  ('音楽', 'おんがく', '音楽', 'Danh từ', 'Âm nhạc', 13),
  ('歌', 'うた', '歌', 'Danh từ', 'Bài hát', 14),
  ('クラシック', 'クラシック', NULL, 'Danh từ', 'Nhạc cổ điển', 15),
  ('ジャズ', 'ジャズ', NULL, 'Danh từ', 'Nhạc Jazz', 16),
  ('コンサート', 'コンサート', NULL, 'Danh từ', 'Buổi hòa nhạc', 17),
  ('カラオケ', 'カラオケ', NULL, 'Danh từ', 'Karaoke', 18),
  ('歌舞伎', 'かぶき', '歌舞伎', 'Danh từ', 'Kịch Kabuki', 19),
  ('絵', 'え', '絵', 'Danh từ', 'Bức tranh', 20),
  ('字', 'じ', '字', 'Danh từ', 'Chữ cái', 21),
  ('漢字', 'かんじ', '漢字', 'Danh từ', 'Chữ Hán Kanji', 22),
  ('ひらがな', 'ひらがな', NULL, 'Danh từ', 'Chữ Hiragana', 23),
  ('かたかな', 'かたかな', NULL, 'Danh từ', 'Chữ Katakana', 24),
  ('ローマ字', 'ろーまじ', 'ローマ字', 'Danh từ', 'Chữ La-tinh (Romaji)', 25),
  ('細かいお金', 'こまかいおかね', '細かいお金', 'Danh từ', 'Tiền lẻ', 26),
  ('チケット', 'チケット', NULL, 'Danh từ', 'Tấm vé', 27),
  ('時間', 'じかん', '時間', 'Danh từ', 'Thời gian', 28),
  ('用事', 'ようじ', '用事', 'Danh từ', 'Việc bận', 29),
  ('約束', 'やくそく', '約束', 'Danh từ', 'Cuộc hẹn, lời hứa', 30),
  ('アルバイト', 'アルバイト', NULL, 'Danh từ', 'Việc làm thêm', 31),
  ('ご主人', 'ごしゅじん', 'ご主人', 'Danh từ', 'Chồng (người khác)', 32),
  ('夫', 'おっと', '夫', 'Danh từ', 'Chồng (tôi)', 33),
  ('奥さん', 'おくさん', '奥さん', 'Danh từ', 'Vợ (người khác)', 34),
  ('妻', 'つま', '妻', 'Danh từ', 'Vợ (tôi)', 35),
  ('子ども', 'こども', '子ども', 'Danh từ', 'Con cái, trẻ em', 36),
  ('よく', 'よく', NULL, 'Phó từ', 'Rất, thường xuyên', 37),
  ('だいたい', 'だいたい', NULL, 'Phó từ', 'Đại khái, đại thể', 38),
  ('たくさん', 'たくさん', NULL, 'Phó từ', 'Nhiều', 39)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 9;

-- Lesson 10 đến 25 Full Complete Batches
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('います', 'います', NULL, 'Động từ nhóm 2', 'Có, ở (người, động vật)', 1),
  ('あります', 'あります', NULL, 'Động từ nhóm 1', 'Có, ở (đồ vật)', 2),
  ('いろいろ', 'いろいろ', NULL, 'Tính từ na', 'Nhiều loại, đa dạng', 3),
  ('男の人', 'おとこのひと', '男の人', 'Danh từ', 'Người đàn ông', 4),
  ('女の人', 'おんなのひと', '女の人', 'Danh từ', 'Người phụ nữ', 5),
  ('男の子', 'おとこのこ', '男の子', 'Danh từ', 'Cậu bé', 6),
  ('女の子', 'おんなのこ', '女の子', 'Danh từ', 'Cô bé', 7),
  ('犬', 'いぬ', '犬', 'Danh từ', 'Con chó', 8),
  ('猫', 'ねこ', '猫', 'Danh từ', 'Con mèo', 9),
  ('木', 'き', '木', 'Danh từ', 'Cây cối', 10),
  ('物', 'もの', '物', 'Danh từ', 'Đồ vật', 11),
  ('フィルム', 'フィルム', NULL, 'Danh từ', 'Cuộn phim', 12),
  ('電池', 'でんち', '電池', 'Danh từ', 'Cục pin', 13),
  ('箱', 'はこ', '箱', 'Danh từ', 'Cái hộp', 14),
  ('スイッチ', 'スイッチ', NULL, 'Danh từ', 'Công tắc', 15),
  ('冷蔵庫', 'れいぞうこ', '冷蔵庫', 'Danh từ', 'Tủ lạnh', 16),
  ('テーブル', 'テーブル', NULL, 'Danh từ', 'Bàn ăn', 17),
  ('ベッド', 'ベッド', NULL, 'Danh từ', 'Cái giường', 18),
  ('棚', 'たな', '棚', 'Danh từ', 'Giá, kệ', 19),
  ('ドア', 'ドア', NULL, 'Danh từ', 'Cánh cửa', 20),
  ('窓', 'まど', '窓', 'Danh từ', 'Cửa sổ', 21),
  ('ポスト', 'ポスト', NULL, 'Danh từ', 'Hòm thư', 22),
  ('ビル', 'ビル', NULL, 'Danh từ', 'Tòa nhà cao tầng', 23),
  ('公園', 'こうえん', '公園', 'Danh từ', 'Công viên', 24),
  ('喫茶店', 'きっさてん', '喫茶店', 'Danh từ', 'Quán cà phê', 25),
  ('本屋', 'ほんや', '本屋', 'Danh từ', 'Hiệu sách', 26),
  ('乗り場', 'のりば', '乗り場', 'Danh từ', 'Bến xe, điểm đón', 27),
  ('県', 'けん', '県', 'Danh từ', 'Tỉnh', 28),
  ('上', 'うえ', '上', 'Danh từ', 'Trên', 29),
  ('下', 'した', '下', 'Danh từ', 'Dưới', 30),
  ('前', 'まえ', '前', 'Danh từ', 'Trước', 31),
  ('後ろ', 'うしろ', '後ろ', 'Danh từ', 'Sau', 32),
  ('右', 'みぎ', '右', 'Danh từ', 'Phải', 33),
  ('左', 'ひだり', '左', 'Danh từ', 'Trái', 34),
  ('中', 'なか', '中', 'Danh từ', 'Trong', 35),
  ('外', 'そと', '外', 'Danh từ', 'Ngoài', 36),
  ('隣', 'となり', '隣', 'Danh từ', 'Bên cạnh', 37),
  ('近く', 'ちかく', '近く', 'Danh từ', 'Gần', 38),
  ('間', 'あいだ', '間', 'Danh từ', 'Giữa', 39),
  ('～や～など', '～や～など', NULL, 'Cụm từ', '~ và ~ (liệt kê không hoàn toàn)', 40)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 10;

-- Lesson 11: Từ vựng Bài 11 Minna no Nihongo chuẩn 100%
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('います', 'います', NULL, 'Động từ nhóm 2', 'có (động vật, người)', 1),
  ('かかります', 'かかります', NULL, 'Động từ nhóm 1', 'mất, tốn (thời gian, tiền bạc)', 2),
  ('やすみます', 'やすみます', '休みます', 'Động từ nhóm 1', 'nghỉ ngơi, nghỉ làm', 3),
  ('ひとつ', 'ひとつ', '1つ', 'Danh từ đếm', '1 cái (đồ vật)', 4),
  ('ふたつ', 'ふたつ', '2つ', 'Danh từ đếm', '2 cái', 5),
  ('みっつ', 'みっつ', '3つ', 'Danh từ đếm', '3 cái', 6),
  ('よっつ', 'よっつ', '4つ', 'Danh từ đếm', '4 cái', 7),
  ('いつつ', 'いつつ', '5つ', 'Danh từ đếm', '5 cái', 8),
  ('むっつ', 'むっつ', '6つ', 'Danh từ đếm', '6 cái', 9),
  ('ななつ', 'ななつ', '7つ', 'Danh từ đếm', '7 cái', 10),
  ('やっつ', 'やっつ', '8つ', 'Danh từ đếm', '8 cái', 11),
  ('ここのつ', 'ここのつ', '9つ', 'Danh từ đếm', '9 cái', 12),
  ('とお', 'とお', '10', 'Danh từ đếm', '10 cái', 13),
  ('いくつ', 'いくつ', NULL, 'Nghi vấn từ', 'bao nhiêu cái', 14),
  ('ひとり', 'ひとり', '一人', 'Danh từ đếm', '1 người', 15),
  ('ふたり', 'ふたり', '二人', 'Danh từ đếm', '2 người', 16),
  ('～にん', '～にん', '～人', 'Hậu tố đếm', '～người', 17),
  ('～だい', '～だい', '～台', 'Hậu tố đếm', '～cái, chiếc (máy móc, xe)', 18),
  ('～まい', '～まい', '～枚', 'Hậu tố đếm', '～tờ, lá (vật mỏng như giấy, áo)', 19),
  ('～かい', '～かい', '～回', 'Hậu tố đếm', '～lần', 20),
  ('りんご', 'りんご', NULL, 'Danh từ', 'quả táo', 21),
  ('みかん', 'みかん', NULL, 'Danh từ', 'quýt', 22),
  ('サンドイッチ', 'サンドイッチ', NULL, 'Danh từ', 'sandwich', 23),
  ('カレー(ライス)', 'カレー(ライス)', NULL, 'Danh từ', '(cơm) cà ri', 24),
  ('アイスクリーム', 'アイスクリーム', NULL, 'Danh từ', 'kem', 25),
  ('きって', 'きって', '切手', 'Danh từ', 'tem', 26),
  ('はがき', 'はがき', '葉書', 'Danh từ', 'bưu thiếp', 27),
  ('ふうとう', 'ふうとう', '封筒', 'Danh từ', 'phong bì', 28),
  ('そくたつ', 'そくたつ', '速達', 'Danh từ', 'chuyển phát nhanh', 29),
  ('かきとめ', 'かきとめ', '書留', 'Danh từ', 'gửi bảo đảm', 30),
  ('エアメール', 'エアメール', '航空便', 'Danh từ', 'gửi bằng đường hàng không', 31),
  ('ふなびん', 'ふなびん', '船便', 'Danh từ', 'gửi bằng đường biển', 32),
  ('りょうしん', 'りょうしん', '両親', 'Danh từ', 'bố mẹ', 33),
  ('きょうだい', 'きょうだい', '兄弟', 'Danh từ', 'anh chị em', 34),
  ('あに', 'あに', '兄', 'Danh từ', 'anh trai (tôi)', 35),
  ('おにいさん', 'おにいさん', 'お兄さん', 'Danh từ', 'anh trai (người khác)', 36),
  ('あね', 'あね', '姉', 'Danh từ', 'chị gái (tôi)', 37),
  ('おねえさん', 'おねえさん', 'お姉さん', 'Danh từ', 'chị gái (người khác)', 38),
  ('おとうと', 'おとうと', '弟', 'Danh từ', 'em trai (tôi)', 39),
  ('いもうと', 'いもうと', '妹', 'Danh từ', 'em gái (tôi)', 40),
  ('がいこく', 'がいこく', '外国', 'Danh từ', 'nước ngoài', 41),
  ('～じかん', '～じかん', '～時間', 'Hậu tố đếm', '～tiếng, giờ', 42),
  ('～しゅうかん', '～しゅうかん', '～週間', 'Hậu tố đếm', '～tuần', 43),
  ('～かげつ', '～かげつ', '～か月', 'Hậu tố đếm', '～tháng', 44),
  ('～ねん', '～ねん', '～年', 'Hậu tố đếm', '～năm', 45),
  ('～ぐらい', '～ぐらい', NULL, 'Hậu tố', 'khoảng～', 46),
  ('どのくらい', 'どのくらい', NULL, 'Nghi vấn từ', 'bao lâu, bao nhiêu', 47),
  ('ぜんぶで', 'ぜんぶで', '全部で', 'Phó từ', 'tổng cộng', 48),
  ('みんな', 'みんな', NULL, 'Danh từ', 'tất cả', 49),
  ('～だけ', '～だけ', NULL, 'Trợ từ', 'chỉ～', 50),
  ('いらっしゃいませ', 'いらっしゃいませ', NULL, 'Cụm từ', 'xin mời vào / xin chào quý khách', 51)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 11;

-- Lessons 12-25 Mass Populate Pattern (Complete 25 lessons N5)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('簡単', 'かんたん', '簡単', 'Tính từ na', 'Đơn giản, dễ', 1),
  ('近い', 'ちかい', '近い', 'Tính từ i', 'Gần', 2),
  ('遠い', 'とおい', '遠い', 'Tính từ i', 'Xa', 3),
  ('速い', 'はやい', '速い', 'Tính từ i', 'Nhanh', 4),
  ('遅い', 'おそい', '遅い', 'Tính từ i', 'Chậm, trễ', 5),
  ('多い', 'おおい', '多い', 'Tính từ i', 'Nhiều (người)', 6),
  ('少ない', 'すくない', '少ない', 'Tính từ i', 'Ít (người)', 7),
  ('暖かい', 'あたたかい', '暖かい', 'Tính từ i', 'Ấm áp (thời tiết)', 8),
  ('涼しい', 'すずしい', '涼しい', 'Tính từ i', 'Mát mẻ', 9),
  ('甘い', 'あまい', '甘い', 'Tính từ i', 'Ngọt', 10),
  ('辛い', 'からい', '辛い', 'Tính từ i', 'Cay', 11),
  ('重い', 'おもい', '重い', 'Tính từ i', 'Nặng', 12),
  ('軽い', 'かるい', '軽い', 'Tính từ i', 'Nhẹ', 13),
  ('季節', 'きせつ', '季節', 'Danh từ', 'Mùa trong năm', 14),
  ('春', 'はる', '春', 'Danh từ', 'Mùa xuân', 15),
  ('夏', 'なつ', '夏', 'Danh từ', 'Mùa hè', 16),
  ('秋', 'あき', '秋', 'Danh từ', 'Mùa thu', 17),
  ('冬', 'ふゆ', '冬', 'Danh từ', 'Mùa đông', 18),
  ('天気', 'てんき', '天気', 'Danh từ', 'Thời tiết', 19),
  ('雨', 'あめ', '雨', 'Danh từ', 'Mưa', 20),
  ('雪', 'ゆき', '雪', 'Danh từ', 'Tuyết', 21),
  ('曇り', 'くもり', '曇り', 'Danh từ', 'Nhiều mây', 22),
  ('ホテル', 'ホテル', NULL, 'Danh từ', 'Khách sạn', 23),
  ('空港', 'くうこう', '空港', 'Danh từ', 'Sân bay', 24),
  ('海', 'うみ', '海', 'Danh từ', 'Biển, đại dương', 25),
  ('世界', 'せかい', '世界', 'Danh từ', 'Thế giới', 26),
  ('パーティー', 'パーティー', NULL, 'Danh từ', 'Bữa tiệc', 27),
  ('祭り', 'まつり', '祭り', 'Danh từ', 'Lễ hội', 28),
  ('すき焼き', 'すきやき', 'すき焼き', 'Danh từ', 'Món Lẩu Sukiyaki', 29),
  ('刺身', 'さしみ', '刺身', 'Danh từ', 'Món Sashimi', 30),
  ('寿司', 'すし', '寿司', 'Danh từ', 'Món Sushi', 31),
  ('天ぷら', 'てんぷら', '天ぷら', 'Danh từ', 'Món Tempura', 32),
  ('生け花', 'いけばな', '生け花', 'Danh từ', 'Nghệ thuật cắm hoa', 33),
  ('紅葉', 'もみじ', '紅葉', 'Danh từ', 'Lá đỏ Momiji', 34),
  ('どちら', 'どちら', NULL, 'Nghi vấn từ', 'Cái nào, bên nào', 35),
  ('どちらも', 'どちらも', NULL, 'Phó từ', 'Cả hai đều', 36),
  ('ずっと', 'ずっと', NULL, 'Phó từ', 'Hơn hẳn, suốt', 37)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 12;

-- Lessons 13-25 Data Seed Batch
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('遊びます', 'あそびます', '遊びます', 'Động từ nhóm 1', 'Chơi', 1),
  ('泳ぎます', 'およぎます', '泳ぎます', 'Động từ nhóm 1', 'Bơi', 2),
  ('迎えます', 'むかえます', '迎えます', 'Động từ nhóm 2', 'Đón', 3),
  ('疲れます', 'つかれます', '疲れます', 'Động từ nhóm 2', 'Mệt mỏi', 4),
  ('結婚します', 'けっこんします', '結婚します', 'Động từ nhóm 3', 'Kết hôn', 5),
  ('買い物します', 'かいものします', '買い物します', 'Động từ nhóm 3', 'Mua sắm', 6),
  ('食事します', 'しょくじします', '食事します', 'Động từ nhóm 3', 'Dùng bữa, ăn uống', 7),
  ('散歩します', 'さんぽします', '散歩します', 'Động từ nhóm 3', 'Đi dạo', 8),
  ('大変', 'たいへん', '大変', 'Tính từ na', 'Vất vả, kinh khủng', 9),
  ('欲しい', 'ほしい', '欲しい', 'Tính từ i', 'Muốn có', 10),
  ('広い', 'ひろい', '広い', 'Tính từ i', 'Rộng', 11),
  ('狭い', 'せまい', '狭い', 'Tính từ i', 'Hẹp', 12),
  ('プール', 'プール', NULL, 'Danh từ', 'Bể bơi', 13),
  ('川', 'かわ', '川', 'Danh từ', 'Con sông', 14),
  ('美術', 'びじゅつ', '美術', 'Danh từ', 'Mỹ thuật', 15),
  ('釣り', 'つり', '釣り', 'Danh từ', 'Câu cá', 16),
  ('スキー', 'スキー', NULL, 'Danh từ', 'Trượt tuyết', 17),
  ('週末', 'しゅうまつ', '週末', 'Danh từ', 'Cuối tuần', 18),
  ('お正月', 'おしょうがつ', 'お正月', 'Danh từ', 'Tết Nguyên Đán', 19),
  ('～ごろ', '～ごろ', NULL, 'Hậu tố', 'Khoảng (thời gian)', 20),
  ('何か', 'なにか', '何か', 'Phó từ', 'Cái gì đó', 21),
  ('どこか', 'どこか', NULL, 'Phó từ', 'Nơi nào đó', 22),
  ('喉が渇きます', 'のどがかわきます', '喉が渇きます', 'Động từ nhóm 1', 'Khát nước', 23),
  ('お腹が空きます', 'おなかがすきます', 'お腹が空きます', 'Động từ nhóm 1', 'Bụng đói', 24),
  ('そうしましょう', 'そうしましょう', NULL, 'Cụm từ', 'Hãy làm như vậy đi', 25),
  ('ご注文は？', 'ごちゅうもんは？', 'ご注文は？', 'Cụm từ', 'Anh/chị gọi món gì?', 26),
  ('定食', 'ていしょく', '定食', 'Danh từ', 'Suất ăn trọn gói', 27),
  ('牛丼', 'ぎゅうどん', '牛丼', 'Danh từ', 'Cơm thịt bò', 28),
  ('少々お待ちください', 'しょうしょうおまちください', '少々お待ちください', 'Cụm từ', 'Xin chờ một chút', 29),
  ('でございます', 'でございます', NULL, 'Cụm từ', 'Là (kính ngữ)', 30),
  ('別々に', 'べつべつに', '別々に', 'Phó từ', 'Riêng ra, riêng biệt', 31),
  ('つけます', 'つけます', NULL, 'Động từ nhóm 2', 'Bật (đèn, tivi)', 32),
  ('消します', 'けします', '消します', 'Động từ nhóm 1', 'Tắt (đèn, tivi)', 33),
  ('開けます', 'あけます', '開けます', 'Động từ nhóm 2', 'Mở (cửa)', 34),
  ('閉めます', 'しめます', '閉めます', 'Động từ nhóm 2', 'Đóng (cửa)', 35),
  ('急ぎます', 'いそぎます', '急ぎます', 'Động từ nhóm 1', 'Vội vã, gấp', 36)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 13;

-- Lesson 14: Thể Te & Nhờ vả (46 từ)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('つけます', 'つけます', NULL, 'Động từ nhóm 2', 'Bật (điện)', 1),
  ('けします', 'けします', '消します', 'Động từ nhóm 1', 'Tắt (điện)', 2),
  ('あけます', 'あけます', '開けます', 'Động từ nhóm 2', 'Mở (cửa)', 3),
  ('しめます', 'しめます', '閉めます', 'Động từ nhóm 2', 'Đóng (cửa)', 4),
  ('いそぎます', 'いそぎます', '急ぎます', 'Động từ nhóm 1', 'Vội vàng', 5),
  ('まちます', 'まちます', '待ちます', 'Động từ nhóm 1', 'Đợi, chờ', 6),
  ('とめます', 'とめます', '止めます', 'Động từ nhóm 2', 'Dừng, đỗ (xe)', 7),
  ('曲がります', 'まがります', '曲がります', 'Động từ nhóm 1', 'Rẽ, quẹo', 8),
  ('持ちます', 'もちます', '持ちます', 'Động từ nhóm 1', 'Cầm, mang', 9),
  ('取ります', 'とります', '取ります', 'Động từ nhóm 1', 'Lấy', 10),
  ('手伝います', 'てつだいます', '手伝います', 'Động từ nhóm 1', 'Giúp đỡ', 11),
  ('呼びます', 'よびます', '呼びます', 'Động từ nhóm 1', 'Gọi', 12),
  ('話します', 'はなします', '話します', 'Động từ nhóm 1', 'Nói chuyện', 13),
  ('見せます', 'みせます', '見せます', 'Động từ nhóm 2', 'Cho xem', 14),
  ('教えます', 'おしえます', '教えます', 'Động từ nhóm 2', 'Cho biết, dạy', 15),
  ('始めます', 'はじめます', '始めます', 'Động từ nhóm 2', 'Bắt đầu', 16),
  ('降ります', 'ふります', '降ります', 'Động từ nhóm 1', 'Rơi (mưa, tuyết)', 17),
  ('コピーします', 'こぴーします', NULL, 'Động từ nhóm 3', 'Photocopy', 18),
  ('エアコン', 'えあこん', NULL, 'Danh từ', 'Máy điều hòa', 19),
  ('パスポート', 'ぱすぽーと', NULL, 'Danh từ', 'Hộ chiếu', 20),
  ('名前', 'なまえ', '名前', 'Danh từ', 'Họ tên', 21),
  ('住所', 'じゅうしょ', '住所', 'Danh từ', 'Địa chỉ', 22),
  ('地図', 'ちず', '地図', 'Danh từ', 'Bản đồ', 23),
  ('塩', 'しお', '塩', 'Danh từ', 'Muối', 24),
  ('砂糖', 'さとう', '砂糖', 'Danh từ', 'Đường', 25),
  ('読み方', 'よみかた', '読み方', 'Danh từ', 'Cách đọc', 26),
  ('～方', '～かた', '～方', 'Hậu tố', 'Cách (làm ~)', 27),
  ('ゆっくり', 'ゆっくり', NULL, 'Phó từ', 'Chậm rãi, thong thả', 28),
  ('すぐ', 'すぐ', NULL, 'Phó từ', 'Ngay lập tức', 29),
  ('また', 'また', NULL, 'Phó từ', 'Lại, nữa', 30),
  ('あとで', 'あとで', NULL, 'Phó từ', 'Sau đó', 31),
  ('もう少し', 'もうすこし', 'もう少し', 'Phó từ', 'Thêm một chút nữa', 32),
  ('もう～', 'もう～', NULL, 'Phó từ', 'Thêm ~', 33),
  ('いいですよ', 'いいですよ', NULL, 'Cụm từ', 'Được chứ / Đồng ý', 34),
  ('さあ', 'さあ', NULL, 'Thán từ', 'Nào, hãy làm thôi', 35),
  ('あれ？', 'あれ？', NULL, 'Thán từ', 'Ôi, ơ kìa (ngạc nhiên)', 36),
  ('信号を右へ曲がってください', 'しんごうをみぎへまがってください', '信号を右へ曲がってください', 'Cụm từ', 'Hãy rẽ phải ở đèn giao thông', 37),
  ('まっすぐ', 'まっすぐ', NULL, 'Phó từ', 'Đi thẳng', 38),
  ('お釣り', 'おつり', 'お釣り', 'Danh từ', 'Tiền thừa trả lại', 39),
  ('これでおねがいします', 'これでおねがいします', NULL, 'Cụm từ', 'Xin gửi tiền này', 40),
  ('雨が降っています', 'あめがふっています', '雨が降っています', 'Cụm từ', 'Trời đang mưa', 41),
  ('電気を消してください', 'でんきをけしてください', '電気を消してください', 'Cụm từ', 'Hãy tắt đèn đi', 42),
  ('ドアを開けてください', 'どあをあけてください', 'ドアを開けてください', 'Cụm từ', 'Hãy mở cửa ra', 43),
  ('名前を書いてください', 'なまえをかいてください', '名前を書いてください', 'Cụm từ', 'Hãy viết tên vào đây', 44),
  ('ちょっと待ってください', 'ちょっとまってください', 'ちょっと待ってください', 'Cụm từ', 'Xin chờ một chút', 45),
  ('荷物を持ちましょうか', 'にもつを持ちましょうか', '荷物を持ちましょうか', 'Cụm từ', 'Để tôi xách hành lý giúp bạn nhé', 46)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 14;

-- Lessons 15 đến 25 Expanded Batches (Full standard Minna N5 dataset)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('置きます', 'おきます', '置きます', 'Động từ nhóm 1', 'Đặt, để', 1),
  ('作ります', 'つくります', '作ります', 'Động từ nhóm 1', 'Làm, chế tạo', 2),
  ('売ります', 'うります', '売ります', 'Động từ nhóm 1', 'Bán', 3),
  ('知ります', 'しります', '知ります', 'Động từ nhóm 1', 'Biết', 4),
  ('住みます', 'すみます', '住みます', 'Động từ nhóm 1', 'Sống, cư trú', 5),
  ('研究します', 'けんきゅうします', '研究します', 'Động từ nhóm 3', 'Nghiên cứu', 6),
  ('資料', 'しりょう', '資料', 'Danh từ', 'Tài liệu', 7),
  ('カタログ', 'カタログ', NULL, 'Danh từ', 'Catalogue, danh mục', 8),
  ('時刻表', 'じこくひょう', '時刻表', 'Danh từ', 'Bảng giờ tàu xe', 9),
  ('服', 'ふく', '服', 'Danh từ', 'Quần áo', 10),
  ('製品', 'せいひん', '製品', 'Danh từ', 'Sản phẩm', 11),
  ('ソフト', 'ソフト', NULL, 'Danh từ', 'Phần mềm', 12),
  ('電子辞書', 'でんしじしょ', '電子辞書', 'Danh từ', 'Từ điển điện tử', 13),
  ('経済', 'けいざい', '経済', 'Danh từ', 'Kinh tế', 14),
  ('市役所', 'しやくしょ', '市役所', 'Danh từ', 'Tòa thị chính', 15),
  ('高校', 'こうこう', '高校', 'Danh từ', 'Trường cấp 3', 16),
  ('歯医者', 'はいしゃ', '歯医者', 'Danh từ', 'Nha sĩ', 17),
  ('独身', 'どくしん', '独身', 'Danh từ', 'Độc thân', 18),
  ('思い出します', 'おもいだします', '思い出します', 'Động từ nhóm 1', 'Nhớ ra, hồi tưởng', 19),
  ('いらっしゃいます', 'いらっしゃいます', NULL, 'Động từ', 'Đến/ở (kính ngữ)', 20),
  ('座ります', 'すわります', '座ります', 'Động từ nhóm 1', 'Ngồi xuống', 21),
  ('立ちます', 'たちます', '立ちます', 'Động từ nhóm 1', 'Đứng dậy', 22),
  ('使います', 'つかいます', '使います', 'Động từ nhóm 1', 'Sử dụng', 23),
  ('入ります', 'はいります', '入ります', 'Động từ nhóm 1', 'Vào (phòng)', 24),
  ('出ます', 'でます', '出ます', 'Động từ nhóm 2', 'Rời khỏi, ra', 25),
  ('吸ってはいけません', 'すってはいけません', NULL, 'Cụm từ', 'Cấm hút thuốc', 26),
  ('写真を撮ってもいいです', 'しゃしんを撮ってもいいです', NULL, 'Cụm từ', 'Được phép chụp ảnh', 27),
  ('家族は大阪に住んでいます', 'かぞくはおおさかにすんでいます', NULL, 'Cụm từ', 'Gia đình tôi đang sống ở Osaka', 28),
  ('専門', 'せんもん', '専門', 'Danh từ', 'Chuyên ngành', 29),
  ('理髪店', 'りはつてん', '理髪店', 'Danh từ', 'Tiệm cắt tóc', 30),
  ('プレイガイド', 'プレイガイド', NULL, 'Danh từ', 'Quầy bán vé xem kịch', 31),
  ('独身です', 'どくしんです', '独身です', 'Cụm từ', 'Tôi còn độc thân', 32),
  ('特に', 'とくに', '特に', 'Phó từ', 'Đặc biệt là', 33),
  ('みなさん', 'みなさん', '皆さん', 'Danh từ', 'Mọi người', 34),
  ('思い出', 'おもいで', '思い出', 'Danh từ', 'Kỷ niệm', 35),
  ('ご家族', 'ごかぞく', 'ご家族', 'Danh từ', 'Gia đình (người khác)', 36),
  ('いらっしゃい', 'いらっしゃい', NULL, 'Thán từ', 'Chào mừng đến', 37),
  ('おじゃまします', 'おじゃまします', NULL, 'Cụm từ', 'Xin lỗi đã làm phiền', 38)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 15;

-- Lessons 16-25 Continuous Population
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('乗り換えます', 'のりかえます', '乗り換えます', 'Động từ nhóm 2', 'Đổi tàu, đổi xe', 1),
  ('浴びます', 'あびます', '浴びます', 'Động từ nhóm 2', 'Tắm (vòi sen)', 2),
  ('入れます', 'いれます', '入れます', 'Động từ nhóm 2', 'Cho vào, bỏ vào', 3),
  ('出します', 'だします', '出します', 'Động từ nhóm 1', 'Rút (tiền), nộp (bài)', 4),
  ('下ろします', 'おろします', '下ろします', 'Động từ nhóm 1', 'Rút tiền ngân hàng', 5),
  ('入ります', 'はいります', '入ります', 'Động từ nhóm 1', 'Vào (đại học)', 6),
  ('出ます', 'でます', '出ます', 'Động từ nhóm 2', 'Tốt nghiệp (đại học)', 7),
  ('押します', 'おします', '押します', 'Động từ nhóm 1', 'Bấm, ấn (nút)', 8),
  ('若い', 'わかい', '若い', 'Tính từ i', 'Trẻ trung', 9),
  ('長い', 'ながい', '長い', 'Tính từ i', 'Dài', 10),
  ('短い', 'みじかい', '短い', 'Tính từ i', 'Ngắn', 11),
  ('明るい', 'あかるい', '明るい', 'Tính từ i', 'Sáng sủa, vui tính', 12),
  ('暗い', 'くらい', '暗い', 'Tính từ i', 'Tối tăm', 13),
  ('体', 'からだ', '体', 'Danh từ', 'Cơ thể, thân thể', 14),
  ('頭', 'あたま', '頭', 'Danh từ', 'Cái đầu', 15),
  ('髪', 'かみ', '髪', 'Danh từ', 'Mái tóc', 16),
  ('顔', 'かお', '顔', 'Danh từ', 'Khuôn mặt', 17),
  ('目', 'め', '目', 'Danh từ', 'Đôi mắt', 18),
  ('耳', 'みみ', '耳', 'Danh từ', 'Cái tai', 19),
  ('鼻', 'はな', '鼻', 'Danh từ', 'Cái mũi', 20),
  ('口', 'くち', '口', 'Danh từ', 'Cái miệng', 21),
  ('歯', 'は', '歯', 'Danh từ', 'Cái răng', 22),
  ('お腹', 'おなか', 'お腹', 'Danh từ', 'Cái bụng', 23),
  ('足', 'あし', '足', 'Danh từ', 'Bàn chân, đôi chân', 24),
  ('背が高い', 'せがたかい', '背が高い', 'Cụm từ', 'Dáng người cao', 25),
  ('緑', 'みどり', '緑', 'Danh từ', 'Màu xanh lá, cây xanh', 26),
  ('寺', 'てら', '寺', 'Danh từ', 'Ngôi chùa', 27),
  ('神社', 'じんじゃ', '神社', 'Danh từ', 'Đền thờ Shinto', 28),
  ('番', 'ばん', '番', 'Danh từ', 'Số thứ tự', 29),
  ('どうやって', 'どうやって', NULL, 'Nghi vấn từ', 'Làm thế nào, bằng cách nào', 30),
  ('どの～', 'どの～', NULL, 'Từ chỉ định', '~ nào', 31),
  ('どれ', 'どれ', NULL, 'Nghi vấn từ', 'Cái nào (trong nhiều cái)', 32),
  ('まだまだです', 'まだまだです', NULL, 'Cụm từ', 'Tôi vẫn còn kém lắm', 33),
  ('お引き出しですか', 'おひきだしですか', NULL, 'Cụm từ', 'Anh/chị muốn rút tiền ạ?', 34),
  ('まず', 'まず', NULL, 'Phó từ', 'Trước hết, đầu tiên', 35),
  ('次に', 'つぎに', '次に', 'Phó từ', 'Tiếp theo', 36),
  ('キャッシュカード', 'キャッシュカード', NULL, 'Danh từ', 'Thẻ ATM', 37),
  ('暗証番号', 'あんしょうばんごう', '暗証番号', 'Danh từ', 'Mã PIN bảo mật', 38),
  ('金額', 'きんがく', '金額', 'Danh từ', 'Số tiền', 39),
  ('確認', 'かくにん', '確認', 'Danh từ', 'Xác nhận', 40)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 16;

-- Lesson 17: Thể Nai & Xin đừng (38 từ chuẩn người dùng cung cấp)
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('おぼえます', 'おぼえます', '覚えます', 'Động từ nhóm 2', 'nhớ', 1),
  ('わすれます', 'わすれます', '忘れます', 'Động từ nhóm 2', 'quên', 2),
  ('なくします', 'なくします', NULL, 'Động từ nhóm 1', 'mất, đánh mất', 3),
  ('だします', 'だします', '出します', 'Động từ nhóm 1', 'nộp (báo cáo)', 4),
  ('はらいます', 'はらいます', '払います', 'Động từ nhóm 1', 'trả tiền', 5),
  ('かえします', 'かえします', '返します', 'Động từ nhóm 1', 'trả lại', 6),
  ('でかけます', 'でかけます', '出かけます', 'Động từ nhóm 2', 'ra ngoài', 7),
  ('ぬぎます', 'ぬぎます', '脱ぎます', 'Động từ nhóm 1', 'cởi (quần áo, giầy)', 8),
  ('もっていきます', 'もっていきます', '持って行きます', 'Động từ nhóm 1', 'mang đi', 9),
  ('もってきます', 'もってきます', '持って来ます', 'Động từ nhóm 3', 'mang đến', 10),
  ('しんぱいします', 'しんぱいします', '心配します', 'Động từ nhóm 3', 'lo lắng', 11),
  ('ざんぎょうします', 'ざんぎょうします', '残業します', 'Động từ nhóm 3', 'làm thêm giờ', 12),
  ('しゅっちょうします', 'しゅっちょうします', '出張します', 'Động từ nhóm 3', 'đi công tác', 13),
  ('のみます', 'のみます', '飲みます', 'Động từ nhóm 1', 'uống (thuốc)', 14),
  ('はいります', 'はいります', '入ります', 'Động từ nhóm 1', 'tắm bồn', 15),
  ('たいせつ[な]', 'たいせつ', '大切「な」', 'Tính từ na', 'quan trọng', 16),
  ('だいじょうぶ[な]', 'だいじょうぶ', '大丈夫「な」', 'Tính từ na', 'không sao, không có vấn đề gì', 17),
  ('あぶない', 'あぶない', '危ない', 'Tính từ i', 'nguy hiểm', 18),
  ('もんだい', 'もんだい', '問題', 'Danh từ', 'vấn đề', 19),
  ('こたえ', 'こたえ', '答え', 'Danh từ', 'câu trả lời', 20),
  ('きんえん', 'きんえん', '禁煙', 'Danh từ', 'cấm hút thuốc', 21),
  ('ほけんしょう', 'ほけんしょう', '健康保険証', 'Danh từ', 'thẻ bảo hiểm (y tế)', 22),
  ('かぜ', 'かぜ', '風', 'Danh từ', 'cảm, cúm', 23),
  ('ねつ', 'ねつ', '熱', 'Danh từ', 'sốt', 24),
  ('びょうき', 'びょうき', '病気', 'Danh từ', 'ốm, bệnh', 25),
  ('くすり', 'くすり', '薬', 'Danh từ', 'thuốc', 26),
  ('おふろ', 'おふろ', 'お風呂', 'Danh từ', 'bồn tắm', 27),
  ('うわぎ', 'うわぎ', '上着', 'Danh từ', 'áo khoác', 28),
  ('したぎ', 'したぎ', '下着', 'Danh từ', 'quần áo lót', 29),
  ('せんせい', 'せんせい', '先生', 'Danh từ', 'bác sĩ', 30),
  ('２、３にち', 'にさんち', '２、３日', 'Danh từ', 'vài ngày', 31),
  ('２、３～', 'にさん～', NULL, 'Hậu tố đếm', 'vài – ( "–" là hậu tố chỉ cách đếm)', 32),
  ('～までに', '～までに', NULL, 'Hậu tố', 'trước ~ (chỉ thời gian)', 33),
  ('ですから', 'ですから', NULL, 'Phó từ', 'vì thế, vì vậy, do đó', 34),
  ('どうしましたか', 'どうしましたか', NULL, 'Cụm từ', 'Có vấn đề gì? / Anh, Chị bị làm sao?', 35),
  ('いたいです', 'いたいです', NULL, 'Cụm từ', 'Tôi bị đau ~', 36),
  ('のど', 'のど', '喉', 'Danh từ', 'họng', 37),
  ('おだいじに', 'おだいじに', NULL, 'Cụm từ', 'Anh, chị nhớ giữ gìn sức khỏe (nói với người bị ốm)', 38)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 17;

-- Lessons 18-25 Remaining Batch Population
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('できます', 'できます', NULL, 'Động từ nhóm 2', 'Có thể làm được', 1),
  ('洗います', 'あ洗います', '洗います', 'Động từ nhóm 1', 'Rửa, giặt', 2),
  ('弾きます', 'ひきます', '弾きます', 'Động từ nhóm 1', 'Chơi (đàn piano, guitar)', 3),
  ('歌います', 'うたいます', '歌います', 'Động từ nhóm 1', 'Hát', 4),
  ('集めます', 'あつめます', '集めます', 'Động từ nhóm 2', 'Sưu tầm, thu thập', 5),
  ('捨てます', 'すてます', '捨てます', 'Động từ nhóm 2', 'Vứt, bỏ đi', 6),
  ('換えます', 'かえます', '換えます', 'Động từ nhóm 2', 'Đổi, trao đổi', 7),
  ('運転します', 'うんてんします', '運転します', 'Động từ nhóm 3', 'Lái xe', 8),
  ('予約します', 'よやくします', '予約します', 'Động từ nhóm 3', 'Đặt trước (chỗ/vé)', 9),
  ('ピアノ', 'ピアノ', NULL, 'Danh từ', 'Đàn Piano', 10),
  ('メートル', 'メートル', NULL, 'Danh từ', 'Mét (đơn vị đo)', 11),
  ('現金', 'げんきん', '現金', 'Danh từ', 'Tiền mặt', 12),
  ('趣味', 'しゅみ', '趣味', 'Danh từ', 'Sở thích', 13),
  ('日記', 'にっき', '日記', 'Danh từ', 'Nhật ký', 14),
  ('お祈り', 'おいのり', 'お祈り', 'Danh từ', 'Lời cầu nguyện', 15),
  ('課長', 'かちょう', '課長', 'Danh từ', 'Trưởng phòng', 16),
  ('部長', 'ぶちょう', '部長', 'Danh từ', 'Trưởng khoa, giám đốc', 17),
  ('社長', 'しゃちょう', '社長', 'Danh từ', 'Giám đốc công ty', 18),
  ('動物', 'どうぶつ', '動物', 'Danh từ', 'Động vật', 19),
  ('馬', 'うま', '馬', 'Danh từ', 'Con ngựa', 20),
  ('インターネット', 'インターネット', NULL, 'Danh từ', 'Mạng Internet', 21),
  ('特に', 'とくに', '特に', 'Phó từ', 'Đặc biệt', 22),
  ('へえ', 'へえ', NULL, 'Thán từ', 'Ồ! (ngạc nhiên)', 23),
  ('それはおもしろいですね', 'それはおもしろいですね', NULL, 'Cụm từ', 'Điều đó thú vị nhỉ', 24),
  ('なかなか', 'なかなか', NULL, 'Phó từ', 'Khó mà..., hiếm khi', 25),
  ('本当ですか', 'ほんとうですか', '本当ですか', 'Cụm từ', 'Có thật vậy không?', 26),
  ('ぜひ', 'ぜひ', NULL, 'Phó từ', 'Nhất định', 27),
  ('日本語を話すことができます', 'はなすことができます', NULL, 'Cụm từ', 'Có thể nói được tiếng Nhật', 28),
  ('趣味は写真をとることです', 'しゅみはしゃしんをとることです', NULL, 'Cụm từ', 'Sở thích là chụp ảnh', 29),
  ('寝る前に日記を書きます', 'ねるまえににっきをかきます', NULL, 'Cụm từ', 'Trước khi đi ngủ tôi viết nhật ký', 30),
  ('カードで払うことができます', 'はらうことができます', NULL, 'Cụm từ', 'Có thể thanh toán bằng thẻ', 31),
  ('スキーができます', 'すきーができます', NULL, 'Cụm từ', 'Biết trượt tuyết', 32),
  ('歌を歌うことができます', 'うたをうたうことができます', NULL, 'Cụm từ', 'Có thể hát bài hát', 33),
  ('車を運転することができます', 'うんてんすることができます', NULL, 'Cụm từ', 'Có thể lái xe ô tô', 34),
  ('食料品', 'しょくりょうひん', '食料品', 'Danh từ', 'Thực phẩm', 35),
  ('カンフー', 'カンフー', NULL, 'Danh từ', 'Võ thuật Kungfu', 36),
  ('水泳', 'すいえい', '水泳', 'Danh từ', 'Môn bơi lội', 37),
  ('国際', 'こくさい', '国際', 'Danh từ', 'Quốc tế', 38)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 18;

-- Lessons 19-25 Continuous Batches
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('登ります', 'のぼります', '登ります', 'Động từ nhóm 1', 'Leo, trèo (núi)', 1),
  ('泊まります', 'とまります', '泊まります', 'Động từ nhóm 1', 'Trọ lại, ở lại (khách sạn)', 2),
  ('掃除します', 'そうじします', '掃除します', 'Động từ nhóm 3', 'Dọn dẹp vệ sinh', 3),
  ('洗濯します', 'せんたくします', '洗濯します', 'Động từ nhóm 3', 'Giặt giũ quần áo', 4),
  ('なります', 'なります', NULL, 'Động từ nhóm 1', 'Trở thành, trở nên', 5),
  ('眠い', 'ねむい', '眠い', 'Tính từ i', 'Buồn ngủ', 6),
  ('強い', 'つよい', '強い', 'Tính từ i', 'Mạnh mẽ', 7),
  ('弱い', 'よわい', '弱い', 'Tính từ i', 'Yếu ớt', 8),
  ('練習', 'れんしゅう', '練習', 'Danh từ', 'Luyện tập', 9),
  ('ゴルフ', 'ゴルフ', NULL, 'Danh từ', 'Môn Golf', 10),
  ('相撲', 'すもう', '相撲', 'Danh từ', 'Võ Sumo', 11),
  ('お茶', 'おちゃ', 'お茶', 'Danh từ', 'Trà đạo', 12),
  ('日', 'ひ', '日', 'Danh từ', 'Ngày, mặt trời', 13),
  ('調子', 'ちょうし', '調子', 'Danh từ', 'Tình trạng (sức khỏe/máy)', 14),
  ('一度', 'いちど', '一度', 'Phó từ', 'Một lần', 15),
  ('一度も', 'いちども', NULL, 'Phó từ', 'Chưa một lần nào (đi với phủ định)', 16),
  ('だんだん', 'だんだん', NULL, 'Phó từ', 'Dần dần, từng chút một', 17),
  ('もうすぐ', 'もうすぐ', NULL, 'Phó từ', 'Sắp sửa', 18),
  ('おかげさまで', 'おかげさまで', NULL, 'Cụm từ', 'Nhờ có bạn / Ơn trời', 19),
  ('富士山に登ったことがあります', 'ふじさんにのぼったことがあります', NULL, 'Cụm từ', 'Tôi đã từng leo núi Phú Sĩ', 20),
  ('日曜日掃除したり洗濯したりします', 'そうじしたりせんたくしたりします', NULL, 'Cụm từ', 'Chủ nhật tôi dọn dẹp rồi giặt giũ', 21),
  ('これから暑くなります', 'あつくなります', NULL, 'Cụm từ', 'Thời tiết sắp trở nên nóng', 22),
  ('乾杯', 'かんぱい', '乾杯', 'Cụm từ', 'Cạn ly! (zô)', 23),
  ('ダイエット', 'ダイエット', NULL, 'Danh từ', 'Ăn kiêng giảm cân', 24),
  ('無理', 'むり', '無理', 'Tính từ na', 'Quá sức, không thể', 25),
  ('体にいい', 'からだにいい', NULL, 'Cụm từ', 'Tốt cho cơ thể', 26),
  ('東京タワー', 'とうきょうたわー', NULL, 'Danh từ', 'Tháp Tokyo', 27),
  ('パチンコ', 'パチンコ', NULL, 'Danh từ', 'Trò chơi Pachinko', 28),
  ('温泉', 'おんせん', '温泉', 'Danh từ', 'Suối nước nóng', 29),
  ('歌舞伎を見たことがありますか', 'かぶきをみたことがありますか', NULL, 'Cụm từ', 'Bạn đã từng xem kịch Kabuki chưa?', 30),
  ('泊まったホテル', 'とまったほてる', NULL, 'Cụm từ', 'Khách sạn đã ở trọ', 31),
  ('だんだん寒くなります', 'さむくなります', NULL, 'Cụm từ', 'Trời dần trở nên lạnh', 32),
  ('元気になります', 'げんきになります', NULL, 'Cụm từ', 'Trở nên khỏe mạnh', 33),
  ('綺麗になります', 'きれいになります', NULL, 'Cụm từ', 'Trở nên đẹp hơn', 34),
  ('お祝い', 'おいわい', 'お祝い', 'Danh từ', 'Quà chúc mừng', 35),
  ('何回も', 'なんかいも', '何回も', 'Phó từ', 'Rất nhiều lần', 36),
  ('しかし', 'しかし', NULL, 'Phó từ', 'Tuy nhiên', 37)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 19;

-- Lessons 20-25 Final Batches
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('要ります', 'いります', '要ります', 'Động từ nhóm 1', 'Cần (vĩ dụ: vi-za)', 1),
  ('調べます', 'しらべます', '調べます', 'Động từ nhóm 2', 'Điều tra, tìm hiểu', 2),
  ('修理します', 'しゅうりします', '修理します', 'Động từ nhóm 3', 'Sửa chữa', 3),
  ('僕', 'ぼく', '僕', 'Đại từ', 'Tôi (xưng hô nam thân mật)', 4),
  ('君', 'きみ', '君', 'Đại từ', 'Cậu, bạn (gọi thân mật)', 5),
  ('～君', '～くん', '～君', 'Hậu tố', 'Cậu (gọi nam trẻ tuổi)', 6),
  ('うん', 'うん', NULL, 'Thán từ', 'Ừ (thân mật của はい)', 7),
  ('うーん', 'うーん', NULL, 'Thán từ', 'Không (thân mật của いいえ)', 8),
  ('言葉', 'ことば', '言葉', 'Danh từ', 'Từ vựng, ngôn ngữ', 9),
  ('着物', 'きもの', '着物', 'Danh từ', 'Trang phục Kimono', 10),
  ('ビザ', 'ビザ', NULL, 'Danh từ', 'Thị thực Visa', 11),
  ('初め', 'はじめ', '初め', 'Danh từ', 'Ban đầu, lúc đầu', 12),
  ('終わり', 'おわり', '終わり', 'Danh từ', 'Kết thúc', 13),
  ('こっち', 'こっち', NULL, 'Chỉ hướng', 'Phía này (thân mật)', 14),
  ('そっち', 'そっち', NULL, 'Chỉ hướng', 'Phía đó (thân mật)', 15),
  ('あっち', 'あっち', NULL, 'Chỉ hướng', 'Phía kia (thân mật)', 16),
  ('どっち', 'どっち', NULL, 'Nghi vấn từ', 'Phía nào (thân mật)', 17),
  ('みんなで', 'みんなで', NULL, 'Phó từ', 'Tất cả mọi người cùng', 18),
  ('～けど', '～けど', NULL, 'Liên từ', '~ nhưng (thân mật)', 19),
  ('お腹がいっぱいです', 'おなかがいっぱいです', NULL, 'Cụm từ', 'No bụng rồi', 20),
  ('よかったら', 'よかったら', NULL, 'Cụm từ', 'Nếu được thì...', 21),
  ('いろいろ', 'いろいろ', NULL, 'Phó từ', 'Nhiều thứ khác nhau', 22),
  ('明日京都へ行く？', 'あしたきょうとへいく？', NULL, 'Cụm từ', 'Ngày mai cậu đi Kyoto không?', 23),
  ('うん、行く。', 'うん、いく。', NULL, 'Cụm từ', 'Ừ, tớ đi.', 24),
  ('ううん、行かない。', 'ううん、いかない。', NULL, 'Cụm từ', 'Không, tớ không đi.', 25),
  ('毎日忙しい？', 'まいにちいそがしい？', NULL, 'Cụm từ', 'Cậu bận mỗi ngày à?', 26),
  ('うん、忙しい。', 'うん、いそがしい。', NULL, 'Cụm từ', 'Ừ, bận lắm.', 27),
  ('暇？', 'ひま？', NULL, 'Cụm từ', 'Rảnh không?', 28),
  ('ううん、暇じゃない。', 'ううん、ひまじゃない。', NULL, 'Cụm từ', 'Không, tớ không rảnh.', 29),
  ('富士山はどうだった？', 'ふじさんはどうだった？', NULL, 'Cụm từ', 'Núi Phú Sĩ thế nào?', 30),
  ('綺麗だった。', 'きれいだった。', NULL, 'Cụm từ', 'Rất đẹp.', 31),
  ('チケットがあるけど、一緒に行かない？', 'いっしょにいかない？', NULL, 'Cụm từ', 'Tớ có vé nè, đi cùng không?', 32),
  ('いいね。', 'いいね。', NULL, 'Cụm từ', 'Hay đấy!', 33),
  ('残念だけど、行けない。', 'ざんねんだけど、いけない。', NULL, 'Cụm từ', 'Tiếc quá tớ không đi được.', 34),
  ('また今度お願い。', 'またこんどおねがい。', NULL, 'Cụm từ', 'Hẹn cậu lần khác nhé.', 35)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 20;

-- Lessons 21-25 Remaining Batch Population
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('思います', 'おもいます', '思います', 'Động từ nhóm 1', 'Nghĩ rằng, cho rằng', 1),
  ('言います', 'いいま', '言います', 'Động từ nhóm 1', 'Nói rằng', 2),
  ('勝ちます', 'かちます', '勝ちます', 'Động từ nhóm 1', 'Thắng, chiến thắng', 3),
  ('負けます', 'まけます', '負けます', 'Động từ nhóm 2', 'Thua, thất bại', 4),
  ('役に立ちます', 'やくにたちます', '役に立ちます', 'Động từ nhóm 1', 'Có ích, giúp ích', 5),
  ('動きます', 'うごきます', '動きます', 'Động từ nhóm 1', 'Chuyển động, hoạt động', 6),
  ('やめます', 'やめます', '辞めます', 'Động từ nhóm 2', 'Nghỉ việc, từ bỏ', 7),
  ('気をつけます', 'きをつけます', '気をつけます', 'Động từ nhóm 2', 'Chú ý, cẩn thận', 8),
  ('留学します', 'りゅうがくします', '留学します', 'Động từ nhóm 3', 'Du học', 9),
  ('無駄', 'むだ', '無駄', 'Tính từ na', 'Lãng phí, vô ích', 10),
  ('不便', 'ふべん', '不便', 'Tính từ na', 'Bất tiện', 11),
  ('同じ', 'おなじ', '同じ', 'Tính từ na', 'Giống nhau', 12),
  ('すごい', 'すごい', NULL, 'Tính từ i', 'Tuyệt vời, giỏi quá', 13),
  ('首相', 'しゅしょう', '首相', 'Danh từ', 'Thủ tướng', 14),
  ('大統領', 'だいとうりょう', '大統領', 'Danh từ', 'Tổng thống', 15),
  ('政治', 'せいじ', '政治', 'Danh từ', 'Chính trị', 16),
  ('ニュース', 'ニュース', NULL, 'Danh từ', 'Tin tức', 17),
  ('スピーチ', 'スピーチ', NULL, 'Danh từ', 'Bài phát biểu', 18),
  ('試合', 'しあい', '試合', 'Danh từ', 'Trận đấu thể thao', 19),
  ('アルバイト', 'アルバイト', NULL, 'Danh từ', 'Việc làm thêm', 20),
  ('意見', 'いけん', '意見', 'Danh từ', 'Ý kiến', 21),
  ('話', 'はなし', '話', 'Danh từ', 'Câu chuyện, cuộc nói chuyện', 22),
  ('ユーモア', 'ユーモア', NULL, 'Danh từ', 'Hài hước, hóm hỉnh', 23),
  ('無駄', 'むだ', '無駄', 'Danh từ', 'Sự lãng phí', 24),
  ('デザイン', 'デザイン', NULL, 'Danh từ', 'Thiết kế', 25),
  ('交通', 'こうつう', '交通', 'Danh từ', 'Giao thông', 26),
  ('ラッシュ', 'ラッシュ', NULL, 'Danh từ', 'Giờ cao điểm', 27),
  ('最近', 'さいきん', '最近', 'Phó từ', 'Gần đây', 28),
  ('たぶん', 'たぶん', NULL, 'Phó từ', 'Có lẽ, chắc là', 29),
  ('きっと', 'きっと', NULL, 'Phó từ', 'Chắc chắn', 30),
  ('ほんとうに', 'ほんとうに', NULL, 'Phó từ', 'Thật sự', 31),
  ('そんなに', 'そんなに', NULL, 'Phó từ', 'Không đến mức như thế', 32),
  ('～について', '～について', NULL, 'Cụm từ', 'Về vấn đề ~', 33),
  ('日本は物価が高いと思います', 'ぶっかがたかいとおもいます', NULL, 'Cụm từ', 'Tôi nghĩ Nhật Bản có giá cả đắt đỏ', 34),
  ('明日雨が降ると思います', 'あしたあめがふるとおもいます', NULL, 'Cụm từ', 'Tôi nghĩ ngày mai trời sẽ mưa', 35),
  ('田中さんは来月結婚すると言いました', 'けっこんするといいました', NULL, 'Cụm từ', 'Anh Tanaka nói tháng sau sẽ kết hôn', 36)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 21;

-- Lessons 22-25 Continuous Batches
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('着ます', 'きます', '着ます', 'Động từ nhóm 2', 'Mặc (áo sơ mi, áo khoác)', 1),
  ('はきます', 'はきます', NULL, 'Động từ nhóm 1', 'Đi, mặc (quần, giày, tất)', 2),
  ('かぶります', 'かぶります', NULL, 'Động từ nhóm 1', 'Đội (nón, mũ)', 3),
  (' megane をかけます', 'かけます', '眼鏡をかけます', 'Động từ nhóm 2', 'Đeo (kính)', 4),
  ('生まれます', 'うまれます', '生まれます', 'Động từ nhóm 2', 'Sinh ra', 5),
  ('コート', 'コート', NULL, 'Danh từ', 'Áo khoác dáng dài', 6),
  ('スーツ', 'スーツ', NULL, 'Danh từ', 'Bộ vest', 7),
  ('セーター', 'セーター', NULL, 'Danh từ', 'Áo len', 8),
  ('帽子', 'ぼうし', '帽子', 'Danh từ', 'Mũ, nón', 9),
  ('眼鏡', 'めがね', '眼鏡', 'Danh từ', 'Kính mắt', 10),
  ('よく', 'よく', NULL, 'Phó từ', 'Thường xuyên', 11),
  ('おめでとうございます', 'おめでとうございます', NULL, 'Cụm từ', 'Xin chúc mừng!', 12),
  ('家', 'うち', '家', 'Danh từ', 'Căn nhà', 13),
  ('家賃', 'やちん', '家賃', 'Danh từ', 'Tiền thuê nhà', 14),
  ('和室', 'わしつ', '和室', 'Danh từ', 'Phòng kiểu Nhật (chiếu Tatami)', 15),
  ('押し入れ', 'おしいれ', '押し入れ', 'Danh từ', 'Tủ âm tường', 16),
  ('布団', 'ふとん', '布団', 'Danh từ', 'Bộ chăn đệm Nhật', 17),
  ('アパート', 'アパート', NULL, 'Danh từ', 'Căn hộ chung cư nhỏ', 18),
  ('パリ', 'パリ', NULL, 'Danh từ', 'Kinh đô Paris', 19),
  ('万里の長城', 'ばんりのちょうじょう', '万里の長城', 'Danh từ', 'Vạn Lý Trường Thành', 20),
  ('余暇開発センター', 'よかかいはつせんたー', NULL, 'Danh từ', 'Trung tâm phát triển giải trí', 21),
  ('あちら', 'あちら', NULL, 'Chỉ hướng', 'Phía kia', 22),
  ('こちら', 'こちら', NULL, 'Chỉ hướng', 'Phía này', 23),
  ('そちら', 'そちら', NULL, 'Chỉ hướng', 'Phía đó', 24),
  ('メガネをかけた人', 'めがねをかけたひと', NULL, 'Cụm từ', 'Người đeo kính', 25),
  ('黒い帽子をかぶっている人', 'くろいぼうしをかぶっているひと', NULL, 'Cụm từ', 'Người đang đội chiếc mũ màu đen', 26),
  ('私が昨日買った本', 'わたしがきのうかったほん', NULL, 'Cụm từ', 'Cuốn sách tôi đã mua hôm qua', 27),
  ('彼が住んでいる家', 'かれがすんでいるうち', NULL, 'Cụm từ', 'Căn nhà anh ấy đang sống', 28),
  ('青いシャツを着ている人', 'あおいしゃつをきているひと', NULL, 'Cụm từ', 'Người đang mặc chiếc áo màu xanh', 29),
  ('背が高くて髪が長い人', 'せが高くてかみがながいひと', NULL, 'Cụm từ', 'Người dáng cao và tóc dài', 30),
  ('約束の時間', 'やくそくのじかん', '約束の時間', 'Danh từ', 'Thời gian cuộc hẹn', 31),
  ('用事がある日', 'ようじがあるひ', NULL, 'Danh từ', 'Ngày có việc bận', 32),
  ('朝ご飯を食べる時間がない', 'あさごはんをたべるじかんがない', NULL, 'Cụm từ', 'Không có thời gian ăn sáng', 33),
  ('今度一緒に行きませんか', 'こんどいっしょにいきませんか', NULL, 'Cụm từ', 'Lần tới cùng đi nhé?', 34),
  ('いいですね', 'いいですね', NULL, 'Cụm từ', 'Hay quá nhỉ!', 35)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 22;

-- Lessons 23-25 Final Completion
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('聞きます', 'ききます', '聞きます', 'Động từ nhóm 1', 'Hỏi (giáo viên)', 1),
  ('回します', 'まわします', '回します', 'Động từ nhóm 1', 'Vặn, xoay (núm vặn)', 2),
  ('引きます', 'ひきます', '引きます', 'Động từ nhóm 1', 'Kéo (cửa)', 3),
  ('変えます', 'かえます', '変えます', 'Động từ nhóm 2', 'Đổi, thay đổi', 4),
  ('触ります', 'さわります', '触ります', 'Động từ nhóm 1', 'Chạm vào, sờ vào', 5),
  ('出ます', 'でます', '出ます', 'Động từ nhóm 2', 'Tiền thừa đi ra', 6),
  ('動きます', 'うごきます', '動きます', 'Động từ nhóm 1', 'Chạy, hoạt động (đồng hồ)', 7),
  ('歩きます', 'あるきます', '歩きます', 'Động từ nhóm 1', 'Đi bộ (trên đường)', 8),
  ('渡ります', 'わたります', '渡ります', 'Động từ nhóm 1', 'Băng qua (cầu, đường)', 9),
  ('曲がります', 'まがります', '曲がります', 'Động từ nhóm 1', 'Rẽ (sang phải)', 10),
  ('寂しい', 'さびしい', '寂しい', 'Tính từ i', 'Buồn bã, cô đơn', 11),
  ('湯', 'おゆ', 'お湯', 'Danh từ', 'Nước nóng', 12),
  ('音', 'おと', '音', 'Danh từ', 'Âm thanh', 13),
  ('サイズ', 'サイズ', NULL, 'Danh từ', 'Kích cỡ, size', 14),
  ('故障', 'こしょう', '故障', 'Danh từ', 'Hỏng hóc, sự cố', 15),
  ('道', 'みち', '道', 'Danh từ', 'Con đường', 16),
  ('交差点', 'こうさてん', '交差点', 'Danh từ', 'Ngã tư giao thông', 17),
  ('信号', 'しんごう', '信号', 'Danh từ', 'Đèn tín hiệu giao thông', 18),
  ('角', 'かど', '角', 'Danh từ', 'Góc đường', 19),
  ('橋', 'はし', '橋', 'Danh từ', 'Cây cầu', 20),
  ('駐車場', 'ちゅうしゃじょう', '駐車場', 'Danh từ', 'Bãi đỗ xe', 21),
  ('建物', 'たてもの', '建物', 'Danh từ', 'Tòa nhà', 22),
  ('何回も', 'なんかいも', '何回も', 'Phó từ', 'Nhiều lần', 23),
  ('～目', '～め', '～目', 'Hậu tố', 'Thứ ~ (số thứ tự)', 24),
  ('これに触ると水が出ます', 'これにさわるとみずがでます', NULL, 'Cụm từ', 'Chạm vào cái này nước sẽ chảy ra', 25),
  ('右へ曲がると銀行があります', 'みぎへまがるとぎんこうがあります', NULL, 'Cụm từ', 'Rẽ phải sẽ thấy ngân hàng', 26),
  ('図書館へ行くとき本を借ります', 'としょかんへいくときほんをかります', NULL, 'Cụm từ', 'Khi đi thư viện tôi mượn sách', 27),
  ('家に帰ったときただいまと言います', 'うちにかえったとき', NULL, 'Cụm từ', 'Khi về đến nhà tôi nói Tadaima', 28),
  ('お釣りが出ます', 'おつりがでます', 'お釣りが出ます', 'Cụm từ', 'Tiền thừa thối ra', 29),
  ('ボタンを押すと動きます', 'ぼたんをおすとうごきます', NULL, 'Cụm từ', 'Ấn nút thì máy sẽ hoạt động', 30),
  ('つまみを右へ回すと音が大きくなります', 'みぎへまわすと', NULL, 'Cụm từ', 'Vặn núm sang phải âm thanh to lên', 31),
  ('橋を渡ります', 'はしをわたります', '橋を渡ります', 'Cụm từ', 'Đi qua cầu', 32),
  ('交差点を左へ曲がります', 'こうさてんをひだりへまがります', NULL, 'Cụm từ', 'Rẽ trái ở ngã tư', 33),
  ('一つ目の角を右へ曲がってください', 'ひとつめのかどをみぎへまがってください', NULL, 'Cụm từ', 'Hãy rẽ phải ở góc đường thứ nhất', 34),
  ('聖徳太子', 'しょうとくたいし', '聖徳太子', 'Danh từ riêng', 'Thái tử Shotoku', 35),
  ('法隆寺', 'ほうりゅうじ', '法隆寺', 'Danh từ riêng', 'Chùa Horyuji', 36),
  ('元気ですか', 'げんきですか', '元気ですか', 'Cụm từ', 'Bạn khỏe không?', 37),
  ('気をつけてください', 'きをつけてください', NULL, 'Cụm từ', 'Hãy đi cẩn thận nhé', 38)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 23;

-- Lesson 24 & 25 Completion
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('くれます', 'くれます', NULL, 'Động từ nhóm 2', 'Cho, tặng (tôi / người thân)', 1),
  ('直します', 'なおします', '直します', 'Động từ nhóm 1', 'Sửa chữa, đính chính', 2),
  ('連れて行きます', 'つれていきます', '連れて行きます', 'Động từ nhóm 1', 'Dẫn đi', 3),
  ('連れて来ます', 'つれてきます', '連れて来ます', 'Động từ nhóm 3', 'Dẫn đến', 4),
  ('送ります', 'おくります', '送ります', 'Động từ nhóm 1', 'Tiễn (người)', 5),
  ('紹介します', 'しょうかいします', '紹介します', 'Động từ nhóm 3', 'Giới thiệu', 6),
  ('案内します', 'あんないします', '案内します', 'Động từ nhóm 3', 'Hướng dẫn, dẫn đường', 7),
  ('説明します', 'せつめいします', '説明します', 'Động từ nhóm 3', 'Giải thích, thuyết minh', 8),
  ('おじいさん', 'おじいさん', NULL, 'Danh từ', 'Ông (nói chung / người khác)', 9),
  ('おばあさん', 'おばあさん', NULL, 'Danh từ', 'Bà (nói chung / người khác)', 10),
  ('準備', 'じゅんび', '準備', 'Danh từ', 'Chuẩn bị', 11),
  ('引っ越し', 'ひっこし', '引っ越し', 'Danh từ', 'Chuyển nhà', 12),
  ('お菓子', 'おかし', 'お菓子', 'Danh từ', 'Bánh kẹo', 13),
  ('ホームステイ', 'ホームステイ', NULL, 'Danh từ', 'Homestay ở nhà bản xứ', 14),
  ('全部', 'ぜんぶ', '全部', 'Danh từ', 'Tất cả, toàn bộ', 15),
  ('自分で', 'じぶんで', '自分で', 'Phó từ', 'Tự mình làm', 16),
  ('ほかに', 'ほかに', NULL, 'Phó từ', 'Ngoài ra', 17),
  ('母の日', 'ははのひ', '母の日', 'Danh từ', 'Ngày của Mẹ', 18),
  ('佐藤さんは傘を貸してくれました', 'かさをかしてくれました', NULL, 'Cụm từ', 'Anh Sato đã cho tôi mượn cây ô', 19),
  ('私は山田さんに写真を送ってあげました', 'おくってあげました', NULL, 'Cụm từ', 'Tôi đã gửi ảnh giúp anh Yamada', 20),
  ('私はミラーさんに日本語を教えてもらいました', 'おしえてもらいました', NULL, 'Cụm từ', 'Tôi được anh Miller dạy tiếng Nhật', 21),
  ('車で送ってあげます', 'くるまでおくってあげます', NULL, 'Cụm từ', 'Tôi sẽ chở bạn đi bằng xe ô tô', 22),
  ('道案内をしてくれました', 'みちあんないをしてくれました', NULL, 'Cụm từ', 'Đã chỉ đường cho tôi', 23),
  ('おじいちゃん', 'おじいちゃん', NULL, 'Danh từ', 'Ông ơi (thân mật)', 24),
  ('おばあちゃん', 'おばあちゃん', NULL, 'Danh từ', 'Bà ơi (thân mật)', 25),
  ('引っ越しを手伝いましょうか', 'ひっこしをてつだいましょうか', NULL, 'Cụm từ', 'Để tôi giúp bạn chuyển nhà nhé', 26),
  ('自分で作りました', 'じぶんでつくりました', NULL, 'Cụm từ', 'Tự tay tôi làm đấy', 27),
  ('素晴らしい', 'すばらしい', '素晴らしい', 'Tính từ i', 'Tuyệt vời', 28),
  ('感謝します', 'かんしゃします', '感謝します', 'Động từ nhóm 3', 'Cảm ơn, biết ơn', 29),
  ('お礼', 'おれい', 'お礼', 'Danh từ', 'Lời cảm ơn, quà đáp lễ', 30),
  ('本当にありがとうございました', 'ほんとうにありがとうございました', NULL, 'Cụm từ', 'Chân thành cảm ơn bạn rất nhiều', 31),
  ('言葉を教えてくれました', 'ことばをおしえてくれました', NULL, 'Cụm từ', 'Đã dạy từ vựng cho tôi', 32),
  ('駅まで送ります', 'えくまでおくります', NULL, 'Cụm từ', 'Tiễn ra tận nhà ga', 33),
  ('荷物を持ってくれました', 'にもつをもってくれました', NULL, 'Cụm từ', 'Đã mang giúp tôi hành lý', 34),
  ('親切にしてくれました', 'しんせつにしてくれました', NULL, 'Cụm từ', 'Đã đối xử rất tốt với tôi', 35)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 24;

-- Lesson 25 Completion
INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
SELECT l.lesson_id, v.word, v.kana, v.kanji_form, v.meaning_vi, v.part_of_speech, v.sort_order, 'PUBLISHED'
FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id CROSS JOIN (VALUES
  ('考えます', 'かんがえます', '考えます', 'Động từ nhóm 2', 'Suy nghĩ, suy xét', 1),
  ('着きます', 'つきます', '着きます', 'Động từ nhóm 1', 'Đến nơi (nhà ga, sân bay)', 2),
  ('留学します', 'りゅうがくします', '留学します', 'Động từ nhóm 3', 'Du học', 3),
  ('取ります', 'とります', '取ります', 'Động từ nhóm 1', 'Thêm tuổi, già đi', 4),
  ('田舎', 'いなか', '田舎', 'Danh từ', 'Quê hương, nông thôn', 5),
  ('大使館', 'たいしかん', '大使館', 'Danh từ', 'Đại sứ quán', 6),
  ('グループ', 'グループ', NULL, 'Danh từ', 'Nhóm, tập đoàn', 7),
  ('チャンス', 'チャンス', NULL, 'Danh từ', 'Cơ hội', 8),
  ('億', 'おく', '億', 'Số đếm', 'Một trăm triệu (100.000.000)', 9),
  ('もし～たら', 'もし～たら', NULL, 'Cụm từ', 'Nếu ~ thì', 10),
  ('いくら～ても', 'いくら～ても', NULL, 'Cụm từ', 'Cho dù ~ đi chăng nữa', 11),
  ('転勤', 'てんきん', '転勤', 'Danh từ', 'Chuyển công tác', 12),
  ('こと', 'こと', NULL, 'Danh từ', 'Việc, chuyện', 13),
  ('一杯飲みましょう', 'いっぱいのみましょう', NULL, 'Cụm từ', 'Cùng uống một ly nhé', 14),
  ('いろいろお世話になりました', 'おせわになりました', NULL, 'Cụm từ', 'Cảm ơn đã giúp đỡ tôi', 15),
  ('頑張ります', 'がんばります', '頑張ります', 'Động từ nhóm 1', 'Cố gắng hết sức', 16),
  ('どうぞお元気で', 'どうぞおげんきで', NULL, 'Cụm từ', 'Chúc bạn luôn giữ gìn sức khỏe', 17),
  ('雨が降ったら出かけません', 'あめがふったらでかけません', NULL, 'Cụm từ', 'Nếu trời mưa tôi sẽ không ra ngoài', 18),
  ('安かったら買います', 'やすかったらかいます', NULL, 'Cụm từ', 'Nếu rẻ tôi sẽ mua', 19),
  ('暇だったら遊びに来てください', 'ひまだたらあそびにきてください', NULL, 'Cụm từ', 'Nếu rảnh hãy đến chơi nhé', 20),
  ('いい天気だったら散歩します', 'いいてんきだったらさんぽします', NULL, 'Cụm từ', 'Nếu thời tiết đẹp tôi sẽ đi dạo', 21),
  ('高くても買います', 'たかくてもかいます', NULL, 'Cụm từ', 'Cho dù đắt tôi vẫn mua', 22),
  ('静かでも寝られません', 'しずかでもねられません', NULL, 'Cụm từ', 'Cho dù yên tĩnh vẫn không ngủ được', 23),
  ('日曜日でも働きます', 'にちようびでもはたらきます', NULL, 'Cụm từ', 'Cho dù là chủ nhật vẫn làm việc', 24),
  ('１億円あったら何をしたいですか', '1おくえんあったらなにをしたいですか', NULL, 'Cụm từ', 'Nếu có 100 triệu Yên bạn muốn làm gì?', 25),
  ('世界中を旅行したいです', 'せかいじゅうをりょこうしたいです', NULL, 'Cụm từ', 'Tôi muốn đi du lịch vòng quanh thế giới', 26),
  ('着いたら電話をください', 'ついたらでんわをください', NULL, 'Cụm từ', 'Khi đến nơi hãy gọi điện cho tôi nhé', 27),
  ('年を取ったら田舎に住みたいです', 'としをとったらいなかにつみたいです', NULL, 'Cụm từ', 'Khi về già tôi muốn sống ở quê', 28),
  ('考えても分かりません', 'かんがえてもわかりません', NULL, 'Cụm từ', 'Cho dù suy nghĩ kỹ vẫn không hiểu', 29),
  ('いくら考えても分かりません', 'いくらかんがえてもわかりません', NULL, 'Cụm từ', 'Dù có nghĩ thế nào đi nữa cũng không hiểu', 30),
  ('転勤します', 'てんきんします', '転勤します', 'Động từ nhóm 3', 'Chuyển vùng làm việc', 31),
  ('東京へ行っても私を忘れないでください', 'わたしをわすれないでください', NULL, 'Cụm từ', 'Dù có đi Tokyo xin đừng quên tôi', 32),
  ('お世話になりました', 'おせわになりました', NULL, 'Cụm từ', 'Cảm ơn vì đã chiếu cố giúp đỡ', 33),
  ('お体に気をつけてください', 'おからだにきをつけてください', NULL, 'Cụm từ', 'Hãy giữ gìn sức khỏe nhé', 34),
  ('乾杯', 'かんぱい', '乾杯', 'Thán từ', 'Cạn ly! Chúc mừng!', 35),
  ('また会いましょう', 'またあいましょう', NULL, 'Cụm từ', 'Hẹn sớm gặp lại nhé', 36)
) AS v(word, kana, kanji_form, part_of_speech, meaning_vi, sort_order)
WHERE lvl.code = 'N5' AND l.sort_order = 25;
