-- Flyway Migration V28: Enterprise Question Bank & Quiz Configuration Tables

-- 1. Create Question Bank table for reusable questions linked to lessons
CREATE TABLE IF NOT EXISTS question_bank (
    question_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id             BIGINT NOT NULL REFERENCES lessons(lesson_id) ON DELETE CASCADE,
    question_type         VARCHAR(30) NOT NULL,
    difficulty            VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    prompt                TEXT NOT NULL,
    japanese_text         TEXT,
    audio_url             TEXT,
    audio_text            TEXT,
    transcript            TEXT,
    valid_answers         JSONB,
    explanation           TEXT,
    weight                NUMERIC(8,2) NOT NULL DEFAULT 1.00,
    status                VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by            BIGINT REFERENCES users(user_id),
    updated_by            BIGINT REFERENCES users(user_id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at            TIMESTAMPTZ,
    CONSTRAINT ck_qb_type CHECK (question_type IN ('MULTIPLE_CHOICE', 'LISTENING', 'TYPING')),
    CONSTRAINT ck_qb_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT ck_qb_status CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE'))
);

CREATE INDEX IF NOT EXISTS ix_qb_lesson_status ON question_bank(lesson_id, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_qb_lesson_type ON question_bank(lesson_id, question_type) WHERE deleted_at IS NULL;

-- 2. Create Options table for Multiple Choice & Listening questions
CREATE TABLE IF NOT EXISTS question_bank_options (
    option_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id           BIGINT NOT NULL REFERENCES question_bank(question_id) ON DELETE CASCADE,
    option_text           TEXT NOT NULL,
    is_correct            BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order            INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT ck_qbo_sort CHECK (sort_order > 0)
);

CREATE INDEX IF NOT EXISTS ix_qbo_question ON question_bank_options(question_id);

-- 3. Enhance Quizzes table for Quiz modes, publishing lifecycle, and difficulty distribution
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS quiz_mode VARCHAR(30) DEFAULT 'MULTIPLE_CHOICE';
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS difficulty_distribution JSONB DEFAULT '{"easy": 40, "medium": 40, "hard": 20}'::jsonb;

-- Drop legacy status check constraint if exists and add updated status constraint
ALTER TABLE quizzes DROP CONSTRAINT IF EXISTS ck_quizzes_status;
ALTER TABLE quizzes ADD CONSTRAINT ck_quizzes_status CHECK (status IN ('DRAFT', 'READY', 'PUBLISHED', 'ARCHIVED'));
