-- Flyway Migration V60: Seed Authentic 2000 JLPT N3 Essential Vocabulary from JTest.net

DO $$
DECLARE
    lvl_n3_id BIGINT;
    les_id BIGINT;
BEGIN
    SELECT level_id INTO lvl_n3_id FROM levels WHERE code = 'N3';

    -- Delete existing N3 vocabulary to avoid duplicate seed conflicts
    DELETE FROM vocabulary WHERE lesson_id IN (SELECT lesson_id FROM lessons WHERE level_id = lvl_n3_id);

    -- Chapter 1: Bài 51: Quan hệ giữa người với người (人と人との関係) (89 từ)
    SELECT lesson_id INTO les_id FROM lessons WHERE level_id = lvl_n3_id AND sort_order = 1;
    IF les_id IS NULL THEN
        INSERT INTO lessons (level_id, title, description, sort_order, is_sample, estimated_minutes, status, version)
        VALUES (lvl_n3_id, 'Bài 51: Quan hệ giữa người với người (人と人との関係)', '2000 Từ vựng JLPT N3 cốt lõi từ JTest.net', 1, FALSE, 60, 'PUBLISHED', 0)
        RETURNING lesson_id INTO les_id;
    END IF;

    INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
    VALUES
      (les_id, '父親', 'ちちおや', '父親', 'bố, người cha', 'Danh từ', 1, 'PUBLISHED'),
      (les_id, '母親', 'ははおや', '母親', 'mẹ, người mẹ', 'Danh từ', 2, 'PUBLISHED'),
      (les_id, '長女', 'ちょうじょ', '長女', 'trưởng nữ, con gái cả, con gái đầu lòng', 'Danh từ', 3, 'PUBLISHED'),
      (les_id, '長男', 'ちょうなん', '長男', 'trưởng nam, con trai cả, con trai đầu lòng', 'Danh từ', 4, 'PUBLISHED'),
      (les_id, '次女', 'じじょ', '次女', 'con gái thứ hai', 'Danh từ', 5, 'PUBLISHED'),
      (les_id, '次男', 'じなん', '次男', 'con trai thứ hai', 'Danh từ', 6, 'PUBLISHED'),
      (les_id, '三女', 'さんじょ', '三女', 'con gái thứ ba', 'Danh từ', 7, 'PUBLISHED'),
      (les_id, '三男', 'さんなん', '三男', 'con trai thứ ba', 'Danh từ', 8, 'PUBLISHED'),
      (les_id, '末っ子', 'すえっこ', '末っ子', 'con út', 'Danh từ', 9, 'PUBLISHED'),
      (les_id, '一人っ子', 'ひとりっこ', '一人っ子', 'con một', 'Danh từ', 10, 'PUBLISHED'),
      (les_id, '姉妹', 'しまい', '姉妹', 'chị em gái', 'Danh từ', 11, 'PUBLISHED'),
      (les_id, '一人娘', 'ひとりむすめ', '一人娘', 'con gái độc nhất, con gái duy nhất', 'Danh từ', 12, 'PUBLISHED'),
      (les_id, '親子', 'おやこ', '親子', 'cha mẹ và con cái', 'Danh từ', 13, 'PUBLISHED'),
      (les_id, '夫婦', 'ふうふ', '夫婦', 'vợ chồng', 'Danh từ', 14, 'PUBLISHED'),
      (les_id, '［ご］夫妻', '［ご］ふさい', '［ご］夫妻', 'vợ chồng (kính ngữ)', 'Danh từ', 15, 'PUBLISHED'),
      (les_id, '親類', 'しんるい', '親類', 'họ hàng', 'Danh từ', 16, 'PUBLISHED'),
      (les_id, '先祖', 'せんぞ', '先祖', 'tổ tiên', 'Danh từ', 17, 'PUBLISHED'),
      (les_id, '尊敬（する）', 'そんけい（する）', '尊敬（する）', 'kính trọng, tôn kính', 'Danh từ', 18, 'PUBLISHED'),
      (les_id, '連れる', 'つれる', '連れる', 'dẫn đi, dắt đi', 'Danh từ', 19, 'PUBLISHED'),
      (les_id, '似る', 'にる', '似る', 'giống, giống nhau', 'Danh từ', 20, 'PUBLISHED'),
      (les_id, '親友', 'しんゆう', '親友', 'bạn thân', 'Danh từ', 21, 'PUBLISHED'),
      (les_id, '仲間', 'なかま', '仲間', 'đồng đội, bạn bè, người cùng nhóm', 'Danh từ', 22, 'PUBLISHED'),
      (les_id, '仲良し', 'なかよし', '仲良し', 'thân, thân thiết, quan hệ tốt', 'Danh từ', 23, 'PUBLISHED'),
      (les_id, '幼なじみ', 'おさななじみ', '幼なじみ', 'bạn thuở bé', 'Danh từ', 24, 'PUBLISHED'),
      (les_id, '友情', 'ゆうじょう', '友情', 'tình bạn', 'Danh từ', 25, 'PUBLISHED'),
      (les_id, '親しい', 'したしい', '親しい', 'thân thiết, thân mật', 'Danh từ', 26, 'PUBLISHED'),
      (les_id, '知人', 'ちじん', '知人', 'người quen', 'Danh từ', 27, 'PUBLISHED'),
      (les_id, '当時', 'とうじ', '当時', 'lúc đó, thời đó', 'Danh từ', 28, 'PUBLISHED'),
      (les_id, '祝う', 'いわう', '祝う', 'mừng, chúc mừng', 'Danh từ', 29, 'PUBLISHED'),
      (les_id, '遠慮（する）', 'えんりょ（する）', '遠慮（する）', 'sự làm khách, e ngại, giữ kẽ', 'Danh từ', 30, 'PUBLISHED'),
      (les_id, '別々（な）', 'べつべつ（な）', '別々（な）', 'sự khác nhau, riêng biệt', 'Danh từ', 31, 'PUBLISHED'),
      (les_id, '彼女', 'かのじょ', '彼女', 'cô ấy, bạn gái', 'Danh từ', 32, 'PUBLISHED'),
      (les_id, '彼', 'かれ', '彼', 'anh ấy, bạn trai', 'Danh từ', 33, 'PUBLISHED'),
      (les_id, '愛情', 'あいじょう', '愛情', 'tình yêu, tình cảm', 'Danh từ', 34, 'PUBLISHED'),
      (les_id, '出会い', 'であい', '出会い', 'cuộc gặp gỡ', 'Danh từ', 35, 'PUBLISHED'),
      (les_id, '出会う', 'であう', '出会う', 'gặp, gặp gỡ', 'Danh từ', 36, 'PUBLISHED'),
      (les_id, '付き合う', 'つきあう', '付き合う', 'hẹn hò, giao lưu, đi cùng', 'Danh từ', 37, 'PUBLISHED'),
      (les_id, '交際（する）', 'こうさい（する）', '交際（する）', 'sự giao thiệp, mối quan hệ, hẹn hò', 'Danh từ', 38, 'PUBLISHED'),
      (les_id, '記念（する）', 'きねん（する）', '記念（する）', 'sự kỷ niệm', 'Danh từ', 39, 'PUBLISHED'),
      (les_id, '記念日', 'きねんび', '記念日', 'ngày kỷ niệm', 'Danh từ', 40, 'PUBLISHED'),
      (les_id, '言い返す', 'いいかえす', '言い返す', 'nói lại, bắt bẻ, bốp chát', 'Danh từ', 41, 'PUBLISHED'),
      (les_id, '謝る', 'あやまる', '謝る', 'xin lỗi', 'Danh từ', 42, 'PUBLISHED'),
      (les_id, '仲直り（する）', 'なかなおり（する）', '仲直り（する）', 'sự làm lành', 'Danh từ', 43, 'PUBLISHED'),
      (les_id, '連れて行く', 'つれていく', '連れて行く', 'dẫn đi, dắt đi', 'Danh từ', 44, 'PUBLISHED'),
      (les_id, '連れて来る', 'つれてくる', '連れて来る', 'dẫn đến, dẫn về', 'Danh từ', 45, 'PUBLISHED'),
      (les_id, '秘密', 'ひみつ', '秘密', 'bí mật', 'Danh từ', 46, 'PUBLISHED'),
      (les_id, '内緒', 'ないしょ', '内緒', 'bí mật, chuyện nội bộ, biết với nhau', 'Danh từ', 47, 'PUBLISHED'),
      (les_id, '好かれる', 'すかれる', '好かれる', 'được thích, được yêu mến', 'Danh từ', 48, 'PUBLISHED'),
      (les_id, '（人を）ふる', '（ひとを）ふる', '（人を）ふる', 'bỏ (người yêu), từ chối (ai đó)', 'Danh từ', 49, 'PUBLISHED'),
      (les_id, '［ぉ］見合い（する）', '［ぉ］みあい（する）', '［ぉ］見合い（する）', 'xem mặt, mai mối', 'Danh từ', 50, 'PUBLISHED'),
      (les_id, '恋愛（する）', 'れんあい（する）', '恋愛（する）', 'chuyện yêu đương, tình yêu', 'Danh từ', 51, 'PUBLISHED'),
      (les_id, '存在（する）', 'そんざい（する）', '存在（する）', 'sự tồn tại, người, thứ', 'Danh từ', 52, 'PUBLISHED'),
      (les_id, '相手', 'あいて', '相手', 'đối phương, đối tác, người đối diện', 'Danh từ', 53, 'PUBLISHED'),
      (les_id, '助ける', 'たすける', '助ける', 'giúp đỡ, cứu', 'Danh từ', 54, 'PUBLISHED'),
      (les_id, '助かる', 'たすかる', '助かる', 'được cứu, được giúp đỡ, nhờ có... mà đỡ', 'Danh từ', 55, 'PUBLISHED'),
      (les_id, '支える', 'ささえる', '支える', 'hỗ trợ, nâng đỡ, làm chỗ dựa', 'Danh từ', 56, 'PUBLISHED'),
      (les_id, '誘う', 'さそう', '誘う', 'rủ, mời', 'Danh từ', 57, 'PUBLISHED'),
      (les_id, '待ち合わせる', 'まちあわせる', '待ち合わせる', 'hẹn gặp nhau', 'Danh từ', 58, 'PUBLISHED'),
      (les_id, '交換（する）', 'こうかん（する）', '交換（する）', 'sự trao đổi', 'Danh từ', 59, 'PUBLISHED'),
      (les_id, '交流（する）', 'こうりゅう（する）', '交流（する）', 'sự giao lưu', 'Danh từ', 60, 'PUBLISHED'),
      (les_id, '断る', 'ことわる', '断る', 'từ chối', 'Danh từ', 61, 'PUBLISHED'),
      (les_id, '預ける', 'あずける', '預ける', 'gửi, giao cho ai trông hộ', 'Danh từ', 62, 'PUBLISHED'),
      (les_id, '預かる', 'あずかる', '預かる', 'trông hộ, giữ hộ, được giao phó', 'Danh từ', 63, 'PUBLISHED'),
      (les_id, '甘やかす', 'あまやかす', '甘やかす', 'chiều, chiều chuộng, nuông chiều', 'Danh từ', 64, 'PUBLISHED'),
      (les_id, 'ついて来る', 'ついてくる', 'ついて来る', 'đi theo, bám theo', 'Danh từ', 65, 'PUBLISHED'),
      (les_id, '抱く', 'だく', '抱く', 'ôm, bế', 'Danh từ', 66, 'PUBLISHED'),
      (les_id, '話しかける', 'はなしかける', '話しかける', 'bắt chuyện, lên tiếng nói với', 'Danh từ', 67, 'PUBLISHED'),
      (les_id, '無視（する）', 'むし（する）', '無視（する）', 'sự phớt lờ, làm ngơ, bỏ qua', 'Danh từ', 68, 'PUBLISHED'),
      (les_id, '振り向く', 'ふりむく', '振り向く', 'quay đầu lại, ngoảnh lại', 'Danh từ', 69, 'PUBLISHED'),
      (les_id, '差し上げる', 'さしあげる', '差し上げる', 'tặng, biếu (kính ngữ khiêm nhường)', 'Danh từ', 70, 'PUBLISHED'),
      (les_id, '与える', 'あたえる', '与える', 'cho, ban cho, mang lại', 'Danh từ', 71, 'PUBLISHED'),
      (les_id, '味方（する）', 'みかた（する）', '味方（する）', 'đồng minh, người cùng phe, đứng về phía', 'Danh từ', 72, 'PUBLISHED'),
      (les_id, '悪口', 'わるぐち', '悪口', 'nói xấu, lời nói xấu', 'Danh từ', 73, 'PUBLISHED'),
      (les_id, '我々', 'われわれ', '我々', 'chúng tôi, chúng ta (trang trọng)', 'Danh từ', 74, 'PUBLISHED'),
      (les_id, '名字', 'みょうじ', '名字', 'họ (tên)', 'Danh từ', 75, 'PUBLISHED'),
      (les_id, '性別', 'せいべつ', '性別', 'giới tính', 'Danh từ', 76, 'PUBLISHED'),
      (les_id, '年齢', 'ねんれい', '年齢', 'tuổi, tuổi tác', 'Danh từ', 77, 'PUBLISHED'),
      (les_id, '高齢', 'こうれい', '高齢', 'cao tuổi, nhiều tuổi', 'Danh từ', 78, 'PUBLISHED'),
      (les_id, '老人', 'ろうじん', '老人', 'người già', 'Danh từ', 79, 'PUBLISHED'),
      (les_id, '幼児', 'ようじ', '幼児', 'trẻ ấu nhi (trẻ từ 1-5 tuổi)', 'Danh từ', 80, 'PUBLISHED'),
      (les_id, '出身', 'しゅっしん', '出身', 'xuất thân, quê quán', 'Danh từ', 81, 'PUBLISHED'),
      (les_id, '生まれ', 'うまれ', '生まれ', '(sự) sinh ra, nơi sinh', 'Danh từ', 82, 'PUBLISHED'),
      (les_id, '育ち', 'そだち', '育ち', '(sự) lớn lên, trưởng thành', 'Danh từ', 83, 'PUBLISHED'),
      (les_id, '行儀', 'ぎょうぎ', '行儀', 'cách cư xử, phép tắc', 'Danh từ', 84, 'PUBLISHED'),
      (les_id, '個人', 'こじん', '個人', 'cá nhân', 'Danh từ', 85, 'PUBLISHED'),
      (les_id, '本人', 'ほんにん', '本人', 'bản thân, đương sự', 'Danh từ', 86, 'PUBLISHED'),
      (les_id, '独身', 'どくしん', '独身', 'độc thân', 'Danh từ', 87, 'PUBLISHED'),
      (les_id, '主婦', 'しゅふ', '主婦', 'nội trợ', 'Danh từ', 88, 'PUBLISHED'),
      (les_id, '無職', 'むしょく', '無職', 'thất nghiệp, không có việc làm', 'Danh từ', 89, 'PUBLISHED');

    -- Chapter 2: Bài 52: Cuộc sống hàng ngày ① (毎日の暮らし①) (83 từ)
    SELECT lesson_id INTO les_id FROM lessons WHERE level_id = lvl_n3_id AND sort_order = 2;
    IF les_id IS NULL THEN
        INSERT INTO lessons (level_id, title, description, sort_order, is_sample, estimated_minutes, status, version)
        VALUES (lvl_n3_id, 'Bài 52: Cuộc sống hàng ngày ① (毎日の暮らし①)', '2000 Từ vựng JLPT N3 cốt lõi từ JTest.net', 2, FALSE, 60, 'PUBLISHED', 0)
        RETURNING lesson_id INTO les_id;
    END IF;

    INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
    VALUES
      (les_id, '本日', 'ほんじつ', '本日', 'hôm nay', 'Danh từ', 1, 'PUBLISHED'),
      (les_id, '明日', 'あす', '明日', 'ngày mai', 'Danh từ', 2, 'PUBLISHED'),
      (les_id, '前日', 'ぜんじつ', '前日', 'ngày hôm trước', 'Danh từ', 3, 'PUBLISHED'),
      (les_id, '翌日', 'よくじつ', '翌日', 'ngày hôm sau', 'Danh từ', 4, 'PUBLISHED'),
      (les_id, '先おととい', 'さきおととい', '先おととい', 'hôm kìa', 'Danh từ', 5, 'PUBLISHED'),
      (les_id, '昨日', 'さくじつ', '昨日', 'hôm qua', 'Danh từ', 6, 'PUBLISHED'),
      (les_id, '昨年', 'さくねん', '昨年', 'năm ngoái', 'Danh từ', 7, 'PUBLISHED'),
      (les_id, '先日', 'せんじつ', '先日', 'hôm nọ, hôm trước', 'Danh từ', 8, 'PUBLISHED'),
      (les_id, '再来週', 'さらいしゅう', '再来週', 'tuần tới nữa', 'Danh từ', 9, 'PUBLISHED'),
      (les_id, '先々週', 'せんせんしゅう', '先々週', 'tuần trước nữa', 'Danh từ', 10, 'PUBLISHED'),
      (les_id, '上旬', 'じょうじゅん', '上旬', 'thượng tuần, đầu tháng', 'Danh từ', 11, 'PUBLISHED'),
      (les_id, '中旬', 'ちゅうじゅん', '中旬', 'trung tuần, giữa tháng', 'Danh từ', 12, 'PUBLISHED'),
      (les_id, '下旬', 'げじゅん', '下旬', 'hạ tuần, cuối tháng', 'Danh từ', 13, 'PUBLISHED'),
      (les_id, '深夜', 'しんや', '深夜', 'đêm khuya', 'Danh từ', 14, 'PUBLISHED'),
      (les_id, '未来', 'みらい', '未来', 'tương lai', 'Danh từ', 15, 'PUBLISHED'),
      (les_id, '数日', 'すうじつ', '数日', 'vài ngày, mấy ngày', 'Danh từ', 16, 'PUBLISHED'),
      (les_id, '以降', 'いこう', '以降', 'từ sau, kể từ sau', 'Danh từ', 17, 'PUBLISHED'),
      (les_id, '朝食', 'ちょうしょく', '朝食', 'bữa sáng', 'Danh từ', 18, 'PUBLISHED'),
      (les_id, '昼食', 'ちゅうしょく', '昼食', 'bữa trưa', 'Danh từ', 19, 'PUBLISHED'),
      (les_id, '夕食', 'ゆうしょく', '夕食', 'bữa tối', 'Danh từ', 20, 'PUBLISHED'),
      (les_id, '[お]弁当', '[お]べんとう', '[お]弁当', 'cơm hộp', 'Danh từ', 21, 'PUBLISHED'),
      (les_id, '自炊（する）', 'じすい（する）', '自炊（する）', 'việc tự nấu ăn', 'Danh từ', 22, 'PUBLISHED'),
      (les_id, '外食（する）', 'がいしょく（する）', '外食（する）', 'việc ăn ngoài', 'Danh từ', 23, 'PUBLISHED'),
      (les_id, '食欲', 'しょくよく', '食欲', '(sự) thèm ăn, hứng ăn', 'Danh từ', 24, 'PUBLISHED'),
      (les_id, '注文（する）', 'ちゅうもん（する）', '注文（する）', 'sự đặt hàng, gọi món', 'Danh từ', 25, 'PUBLISHED'),
      (les_id, '乾杯（する）', 'かんぱい（する）', '乾杯（する）', 'sự cạn chén, nâng cốc, cụng ly', 'Danh từ', 26, 'PUBLISHED'),
      (les_id, '味わう', 'あじわう', '味わう', 'thưởng thức, nếm', 'Danh từ', 27, 'PUBLISHED'),
      (les_id, 'お代わり（する）', 'おかわり（する）', 'お代わり（する）', 'sự ăn thêm, uống thêm', 'Danh từ', 28, 'PUBLISHED'),
      (les_id, '残す', 'のこす', '残す', 'để thừa, để lại', 'Danh từ', 29, 'PUBLISHED'),
      (les_id, '残り物', 'のこりもの', '残り物', 'đồ (ăn) thừa', 'Danh từ', 30, 'PUBLISHED'),
      (les_id, '済ませる', 'すませる', '済ませる', 'làm xong, dùng ... cho đơn giản', 'Danh từ', 31, 'PUBLISHED'),
      (les_id, '済む', 'すむ', '済む', 'xong, xong xuôi; giải quyết xong', 'Danh từ', 32, 'PUBLISHED'),
      (les_id, '量', 'りょう', '量', 'lượng, số lượng', 'Danh từ', 33, 'PUBLISHED'),
      (les_id, '包丁', 'ほうちょう', '包丁', 'dao nhà bếp', 'Danh từ', 34, 'PUBLISHED'),
      (les_id, 'まな板', 'まないた', 'まな板', 'thớt', 'Danh từ', 35, 'PUBLISHED'),
      (les_id, '大さじ', 'おおさじ', '大さじ', 'thìa to, muỗng to', 'Danh từ', 36, 'PUBLISHED'),
      (les_id, '炊飯器', 'すいはんき', '炊飯器', 'nồi cơm điện', 'Danh từ', 37, 'PUBLISHED'),
      (les_id, '流し台', 'ながしだい', '流し台', 'bồn rửa', 'Danh từ', 38, 'PUBLISHED'),
      (les_id, '電子レンジ', 'でんしレンジ', '電子レンジ', 'lò vi sóng', 'Danh từ', 39, 'PUBLISHED'),
      (les_id, '調味料', 'ちょうみりょう', '調味料', 'gia vị', 'Danh từ', 40, 'PUBLISHED'),
      (les_id, 'サラダ油', 'サラダあぶら', 'サラダ油', 'dầu ăn', 'Danh từ', 41, 'PUBLISHED'),
      (les_id, '食品', 'しょくひん', '食品', 'thực phẩm, đồ ăn', 'Danh từ', 42, 'PUBLISHED'),
      (les_id, '切らす', 'きらす', '切らす', 'dùng hết, để hết', 'Danh từ', 43, 'PUBLISHED'),
      (les_id, '刻む', 'きざむ', '刻む', 'băm nhỏ, thái nhỏ; khắc, chạm trổ', 'Danh từ', 44, 'PUBLISHED'),
      (les_id, '（卵を）割る', '（たまごを）わる', '（卵を）割る', 'đập (trứng), làm bể', 'Danh từ', 45, 'PUBLISHED'),
      (les_id, '加える', 'くわえる', '加える', 'thêm vào', 'Danh từ', 46, 'PUBLISHED'),
      (les_id, '少々', 'しょうしょう', '少々', 'một chút, một ít', 'Danh từ', 47, 'PUBLISHED'),
      (les_id, '揚げる', 'あげる', '揚げる', 'rán, chiên', 'Danh từ', 48, 'PUBLISHED'),
      (les_id, '煮る', 'にる', '煮る', 'nấu, ninh', 'Danh từ', 49, 'PUBLISHED'),
      (les_id, '蒸す', 'むす', '蒸す', 'hấp', 'Danh từ', 50, 'PUBLISHED'),
      (les_id, '熱する', 'ねっする', '熱する', 'làm nóng, đun nóng', 'Danh từ', 51, 'PUBLISHED'),
      (les_id, '取り出す', 'とりだす', '取り出す', 'lấy ra', 'Danh từ', 52, 'PUBLISHED'),
      (les_id, '塗る', 'ぬる', '塗る', 'phết, bôi, sơn', 'Danh từ', 53, 'PUBLISHED'),
      (les_id, '温める', 'あたためる', '温める', 'làm nóng, hâm nóng', 'Danh từ', 54, 'PUBLISHED'),
      (les_id, '冷やす', 'ひやす', '冷やす', 'làm lạnh, ướp lạnh', 'Danh từ', 55, 'PUBLISHED'),
      (les_id, '水分', 'すいぶん', '水分', 'thành phần nước, độ ẩm', 'Danh từ', 56, 'PUBLISHED'),
      (les_id, '沸かす', 'わかす', '沸かす', 'đun sôi', 'Danh từ', 57, 'PUBLISHED'),
      (les_id, '注ぐ', 'そそぐ', '注ぐ', 'rót, đổ', 'Danh từ', 58, 'PUBLISHED'),
      (les_id, '味見（する）', 'あじみ（する）', '味見（する）', 'nếm thử', 'Danh từ', 59, 'PUBLISHED'),
      (les_id, '手間', 'てま', '手間', 'thời gian và công sức', 'Danh từ', 60, 'PUBLISHED'),
      (les_id, '手軽な', 'てがるな', '手軽な', 'dễ dàng, đơn giản', 'Danh từ', 61, 'PUBLISHED'),
      (les_id, 'でき上がり', 'できあがり', 'でき上がり', 'hoàn thành, thành phẩm', 'Danh từ', 62, 'PUBLISHED'),
      (les_id, '分ける', 'わける', '分ける', 'chia, phân chia', 'Danh từ', 63, 'PUBLISHED'),
      (les_id, '塩辛い', 'しおからい', '塩辛い', 'mặn', 'Danh từ', 64, 'PUBLISHED'),
      (les_id, '冷凍（する）', 'れいとう（する）', '冷凍（する）', 'đông lạnh', 'Danh từ', 65, 'PUBLISHED'),
      (les_id, '片付ける', 'かたづける', '片付ける', 'dọn, dọn dẹp', 'Danh từ', 66, 'PUBLISHED'),
      (les_id, '清潔な', 'せいけつな', '清潔な', 'sạch sẽ', 'Danh từ', 67, 'PUBLISHED'),
      (les_id, '掃く', 'はく', '掃く', 'quét, quét dọn', 'Danh từ', 68, 'PUBLISHED'),
      (les_id, '掃除機', 'そうじき', '掃除機', 'máy hút bụi', 'Danh từ', 69, 'PUBLISHED'),
      (les_id, '洗剤', 'せんざい', '洗剤', 'bột giặt, nước rửa, chất tẩy rửa', 'Danh từ', 70, 'PUBLISHED'),
      (les_id, '臭う', 'におう', '臭う', 'bốc mùi, có mùi', 'Danh từ', 71, 'PUBLISHED'),
      (les_id, '洗濯物', 'せんたくもの', '洗濯物', 'đồ giặt', 'Danh từ', 72, 'PUBLISHED'),
      (les_id, '汚れ', 'よごれ', '汚れ', 'bẩn, vết bẩn', 'Danh từ', 73, 'PUBLISHED'),
      (les_id, '干す', 'ほす', '干す', 'phơi, hong', 'Danh từ', 74, 'PUBLISHED'),
      (les_id, '乾燥（する）', 'かんそう（する）', '乾燥（する）', 'sự sấy khô', 'Danh từ', 75, 'PUBLISHED'),
      (les_id, '敷く', 'しく', '敷く', 'trải', 'Danh từ', 76, 'PUBLISHED'),
      (les_id, '育児', 'いくじ', '育児', 'nuôi con', 'Danh từ', 77, 'PUBLISHED'),
      (les_id, '（人を）起こす', '（ひとを）おこす', '（人を）起こす', 'đánh thức', 'Danh từ', 78, 'PUBLISHED'),
      (les_id, '糸', 'いと', '糸', 'sợi chỉ', 'Danh từ', 79, 'PUBLISHED'),
      (les_id, '針', 'はり', '針', 'kim', 'Danh từ', 80, 'PUBLISHED'),
      (les_id, '生ごみ', 'なまごみ', '生ごみ', 'rác hữu cơ', 'Danh từ', 81, 'PUBLISHED'),
      (les_id, '空き缶', 'あきかん', '空き缶', 'vỏ lon', 'Danh từ', 82, 'PUBLISHED'),
      (les_id, '（ごみを）出す', '（ごみを）だす', '（ごみを）出す', 'vứt (rác)', 'Danh từ', 83, 'PUBLISHED');

    -- Chapter 3: Bài 53: Cuộc sống hàng ngày ② (毎日の暮らし②) (80 từ)
    SELECT lesson_id INTO les_id FROM lessons WHERE level_id = lvl_n3_id AND sort_order = 3;
    IF les_id IS NULL THEN
        INSERT INTO lessons (level_id, title, description, sort_order, is_sample, estimated_minutes, status, version)
        VALUES (lvl_n3_id, 'Bài 53: Cuộc sống hàng ngày ② (毎日の暮らし②)', '2000 Từ vựng JLPT N3 cốt lõi từ JTest.net', 3, FALSE, 60, 'PUBLISHED', 0)
        RETURNING lesson_id INTO les_id;
    END IF;

    INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
    VALUES
      (les_id, '住まい', 'すまい', '住まい', 'chỗ ở, nơi ở', 'Danh từ', 1, 'PUBLISHED'),
      (les_id, '居間', 'いま', '居間', 'phòng khách (kiểu Nhật)', 'Danh từ', 2, 'PUBLISHED'),
      (les_id, '家電', 'かでん', '家電', 'đồ điện gia dụng', 'Danh từ', 3, 'PUBLISHED'),
      (les_id, '暖める', 'あたためる', '暖める', 'làm ấm, sưởi ấm', 'Danh từ', 4, 'PUBLISHED'),
      (les_id, '天井', 'てんじょう', '天井', 'trần nhà', 'Danh từ', 5, 'PUBLISHED'),
      (les_id, '床', 'ゆか', '床', 'sàn nhà', 'Danh từ', 6, 'PUBLISHED'),
      (les_id, '蛇口', 'じゃぐち', '蛇口', 'vòi nước', 'Danh từ', 7, 'PUBLISHED'),
      (les_id, '実家', 'じっか', '実家', 'nhà bố mẹ đẻ', 'Danh từ', 8, 'PUBLISHED'),
      (les_id, '家賃', 'やちん', '家賃', 'tiền thuê nhà', 'Danh từ', 9, 'PUBLISHED'),
      (les_id, '物置', 'ものおき', '物置', 'nhà kho, nơi để đồ', 'Danh từ', 10, 'PUBLISHED'),
      (les_id, '日当たり', 'ひあたり', '日当たり', 'ánh nắng, hướng nắng', 'Danh từ', 11, 'PUBLISHED'),
      (les_id, '内側', 'うちがわ', '内側', 'bên trong, mặt trong', 'Danh từ', 12, 'PUBLISHED'),
      (les_id, '［お］札', '［お］さつ', '［お］札', 'tiền giấy', 'Danh từ', 13, 'PUBLISHED'),
      (les_id, '小銭', 'こぜに', '小銭', 'tiền lẻ, xu lẻ', 'Danh từ', 14, 'PUBLISHED'),
      (les_id, '生活費', 'せいかつひ', '生活費', 'chi phí sinh hoạt', 'Danh từ', 15, 'PUBLISHED'),
      (les_id, '食費', 'しょくひ', '食費', 'chi phí ăn uống, tiền ăn', 'Danh từ', 16, 'PUBLISHED'),
      (les_id, '光熱費', 'こうねつひ', '光熱費', 'chi phí điện nước ga', 'Danh từ', 17, 'PUBLISHED'),
      (les_id, '交際費', 'こうさいひ', '交際費', 'chi phí giao tiếp, tiền tiếp khách', 'Danh từ', 18, 'PUBLISHED'),
      (les_id, '公共料金', 'こうきょうりょうきん', '公共料金', 'phí dịch vụ công cộng', 'Danh từ', 19, 'PUBLISHED'),
      (les_id, '節約（する）', 'せつやく（する）', '節約（する）', 'sự tiết kiệm', 'Danh từ', 20, 'PUBLISHED'),
      (les_id, '割り勘', 'わりかん', '割り勘', 'chia nhau trả tiền', 'Danh từ', 21, 'PUBLISHED'),
      (les_id, '支払う', 'しはらう', '支払う', 'trả tiền, thanh toán', 'Danh từ', 22, 'PUBLISHED'),
      (les_id, '支払い', 'しはらい', '支払い', 'sự chi trả, thanh toán', 'Danh từ', 23, 'PUBLISHED'),
      (les_id, '勘定（する）', 'かんじょう（する）', '勘定（する）', 'sự tính tiền, thanh toán', 'Danh từ', 24, 'PUBLISHED'),
      (les_id, '口座', 'こうざ', '口座', 'tài khoản ngân hàng', 'Danh từ', 25, 'PUBLISHED'),
      (les_id, '暗証番号', 'あんしょうばんごう', '暗証番号', 'mã PIN, mã số cá nhân', 'Danh từ', 26, 'PUBLISHED'),
      (les_id, '預金（する）', 'よきん（する）', '預金（する）', 'tiền gửi ngân hàng, sự gửi tiền', 'Danh từ', 27, 'PUBLISHED'),
      (les_id, '引き出す', 'ひきだす', '引き出す', 'rút (tiền)', 'Danh từ', 28, 'PUBLISHED'),
      (les_id, '振り込む', 'ふりこむ', '振り込む', 'chuyển khoản', 'Danh từ', 29, 'PUBLISHED'),
      (les_id, '送金（する）', 'そうきん（する）', '送金（する）', 'sự gửi tiền, chuyển tiền (cho ai đó)', 'Danh từ', 30, 'PUBLISHED'),
      (les_id, '通帳記入', 'つうちょうきにゅう', '通帳記入', 'cập nhật sổ ngân hàng', 'Danh từ', 31, 'PUBLISHED'),
      (les_id, '品物', 'しなもの', '品物', 'hàng, hàng hóa', 'Danh từ', 32, 'PUBLISHED'),
      (les_id, '現金', 'げんきん', '現金', 'tiền mặt', 'Danh từ', 33, 'PUBLISHED'),
      (les_id, '一回払い', 'いっかいばらい', '一回払い', 'thanh toán một lần', 'Danh từ', 34, 'PUBLISHED'),
      (les_id, '合計（する）', 'ごうけい（する）', '合計（する）', 'tổng cộng', 'Danh từ', 35, 'PUBLISHED'),
      (les_id, '代金', 'だいきん', '代金', 'tiền mua hàng', 'Danh từ', 36, 'PUBLISHED'),
      (les_id, '税込', 'ぜいこみ', '税込', 'bao gồm thuế', 'Danh từ', 37, 'PUBLISHED'),
      (les_id, '請求書', 'せいきゅうしょ', '請求書', 'phiếu yêu cầu thanh toán', 'Danh từ', 38, 'PUBLISHED'),
      (les_id, '領収書', 'りょうしゅうしょ', '領収書', 'biên lai, hóa đơn', 'Danh từ', 39, 'PUBLISHED'),
      (les_id, '売り切れ', 'うりきれ', '売り切れ', 'sự bán hết', 'Danh từ', 40, 'PUBLISHED'),
      (les_id, '品切れ', 'しなぎれ', '品切れ', 'sự hết hàng', 'Danh từ', 41, 'PUBLISHED'),
      (les_id, '日替わり', 'ひがわり', '日替わり', 'thay đổi theo ngày', 'Danh từ', 42, 'PUBLISHED'),
      (les_id, '割引', 'わりびき', '割引', 'giảm giá', 'Danh từ', 43, 'PUBLISHED'),
      (les_id, '半額', 'はんがく', '半額', 'nửa giá tiền', 'Danh từ', 44, 'PUBLISHED'),
      (les_id, '特売日', 'とくばいび', '特売日', 'ngày hạ giá đặc biệt', 'Danh từ', 45, 'PUBLISHED'),
      (les_id, '得（な）', 'とく（な）', '得（な）', 'món hời (hời, lời)', 'Danh từ', 46, 'PUBLISHED'),
      (les_id, '損（な）', 'そん（な）', '損（な）', 'tổn thất, thiệt (bị thiệt)', 'Danh từ', 47, 'PUBLISHED'),
      (les_id, '寄る', 'よる', '寄る', 'rẽ qua, ghé qua', 'Danh từ', 48, 'PUBLISHED'),
      (les_id, 'レジ袋', 'レジぶくろ', 'レジ袋', 'túi ni lông, túi bóng', 'Danh từ', 49, 'PUBLISHED'),
      (les_id, '定休日', 'ていきゅうび', '定休日', 'ngày nghỉ quy định', 'Danh từ', 50, 'PUBLISHED'),
      (les_id, '覚ます', 'さます', '覚ます', 'tỉnh dậy, thức dậy', 'Danh từ', 51, 'PUBLISHED'),
      (les_id, '覚める', 'さめる', '覚める', 'tỉnh giấc, thức dậy', 'Danh từ', 52, 'PUBLISHED'),
      (les_id, '（夜が）明ける', '（よが）あける', '（夜が）明ける', 'trời sáng', 'Danh từ', 53, 'PUBLISHED'),
      (les_id, '支度（する）', 'したく（する）', '支度（する）', 'sự chuẩn bị, sửa soạn', 'Danh từ', 54, 'PUBLISHED'),
      (les_id, '合わせる', 'あわせる', '合わせる', 'ghép lại, chắp lại, kết hợp', 'Danh từ', 55, 'PUBLISHED'),
      (les_id, '（髪を）とかす', '（かみを）とかす', '（髪を）とかす', 'chải (tóc)', 'Danh từ', 56, 'PUBLISHED'),
      (les_id, '昼寝（する）', 'ひるね（する）', '昼寝（する）', 'việc ngủ trưa', 'Danh từ', 57, 'PUBLISHED'),
      (les_id, '腰かける', 'こしかける', '腰かける', 'ngồi xuống', 'Danh từ', 58, 'PUBLISHED'),
      (les_id, '暮れる', 'くれる', '暮れる', 'tối dần, (mặt trời) lặn', 'Danh từ', 59, 'PUBLISHED'),
      (les_id, 'ふだん着', 'ふだんぎ', 'ふだん着', 'quần áo thường ngày, quần áo ở nhà', 'Danh từ', 60, 'PUBLISHED'),
      (les_id, '相変わらず', 'あいかわらず', '相変わらず', 'vẫn như cũ, vẫn như thường', 'Danh từ', 61, 'PUBLISHED'),
      (les_id, '夜ふかし（する）', 'よふかし（する）', '夜ふかし（する）', 'sự thức khuya', 'Danh từ', 62, 'PUBLISHED'),
      (les_id, '電源', 'でんげん', '電源', 'nguồn điện, ổ cắm điện', 'Danh từ', 63, 'PUBLISHED'),
      (les_id, '充電（する）', 'じゅうでん（する）', '充電（する）', 'việc sạc pin, nạp điện', 'Danh từ', 64, 'PUBLISHED'),
      (les_id, '運', 'うん', '運', 'vận, vận may', 'Danh từ', 65, 'PUBLISHED'),
      (les_id, '日常', 'にちじょう', '日常', 'thường nhật, hằng ngày', 'Danh từ', 66, 'PUBLISHED'),
      (les_id, '常に', 'つねに', '常に', 'luôn luôn, lúc nào cũng', 'Danh từ', 67, 'PUBLISHED'),
      (les_id, '出迎え', 'でむかえ', '出迎え', '(sự) đón tiếp', 'Danh từ', 68, 'PUBLISHED'),
      (les_id, '出迎える', 'でむかえる', '出迎える', 'đón, đón tiếp', 'Danh từ', 69, 'PUBLISHED'),
      (les_id, '見送り', 'みおくり', '見送り', '(sự) tiễn', 'Danh từ', 70, 'PUBLISHED'),
      (les_id, '見送る', 'みおくる', '見送る', 'tiễn', 'Danh từ', 71, 'PUBLISHED'),
      (les_id, '郵送（する）', 'ゆうそう（する）', '郵送（する）', 'gửi qua bưu điện', 'Danh từ', 72, 'PUBLISHED'),
      (les_id, '小包', 'こづつみ', '小包', 'gói hàng, bưu kiện', 'Danh từ', 73, 'PUBLISHED'),
      (les_id, '送料', 'そうりょう', '送料', 'phí gửi hàng, cước vận chuyển', 'Danh từ', 74, 'PUBLISHED'),
      (les_id, 'あて先', 'あてさき', 'あて先', 'địa chỉ người nhận', 'Danh từ', 75, 'PUBLISHED'),
      (les_id, 'あて名', 'あてな', 'あて名', 'tên người nhận', 'Danh từ', 76, 'PUBLISHED'),
      (les_id, '差出人', 'さしだしにん', '差出人', 'người gửi', 'Danh từ', 77, 'PUBLISHED'),
      (les_id, '出前', 'でまえ', '出前', 'giao đồ ăn tận nhà', 'Danh từ', 78, 'PUBLISHED'),
      (les_id, '留守番電話', 'るすばんでんわ', '留守番電話', 'máy trả lời tự động, hộp thư thoại', 'Danh từ', 79, 'PUBLISHED'),
      (les_id, '早め（な）', 'はやめ（な）', '早め（な）', 'sớm, sớm hơn bình thường', 'Danh từ', 80, 'PUBLISHED');

    -- Chapter 4: Bài 54: Thành phố của chúng tôi (私たちの町) (103 từ)
    SELECT lesson_id INTO les_id FROM lessons WHERE level_id = lvl_n3_id AND sort_order = 4;
    IF les_id IS NULL THEN
        INSERT INTO lessons (level_id, title, description, sort_order, is_sample, estimated_minutes, status, version)
        VALUES (lvl_n3_id, 'Bài 54: Thành phố của chúng tôi (私たちの町)', '2000 Từ vựng JLPT N3 cốt lõi từ JTest.net', 4, FALSE, 60, 'PUBLISHED', 0)
        RETURNING lesson_id INTO les_id;
    END IF;

    INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
    VALUES
      (les_id, '商店街', 'しょうてんがい', '商店街', 'Phố thương mại', 'Danh từ', 1, 'PUBLISHED'),
      (les_id, '高層ビル', 'こうそうビル', '高層ビル', 'Tòa nhà cao tầng', 'Danh từ', 2, 'PUBLISHED'),
      (les_id, '建つ', 'たつ', '建つ', 'Được xây dựng', 'Danh từ', 3, 'PUBLISHED'),
      (les_id, '水族館', 'すいぞくかん', '水族館', 'Thủy cung', 'Danh từ', 4, 'PUBLISHED'),
      (les_id, '博物館', 'はくぶつかん', '博物館', 'Bảo tàng', 'Danh từ', 5, 'PUBLISHED'),
      (les_id, '出入り口（出入口）', 'でいりぐち（でいりぐち）', '出入り口（出入口）', 'Lối / cửa ra vào', 'Danh từ', 6, 'PUBLISHED'),
      (les_id, '自動ドア', 'じどうドア', '自動ドア', 'Cửa tự động', 'Danh từ', 7, 'PUBLISHED'),
      (les_id, '入館料', 'にゅうかんりょう', '入館料', 'Phí vào cửa', 'Danh từ', 8, 'PUBLISHED'),
      (les_id, '混雑（する）', 'こんざつ（する）', '混雑（する）', 'Sự đông đúc, đông nghịt', 'Danh từ', 9, 'PUBLISHED'),
      (les_id, '行列', 'ぎょうれつ', '行列', 'Hàng người', 'Danh từ', 10, 'PUBLISHED'),
      (les_id, '休館日', 'きゅうかんび', '休館日', 'Ngày đóng cửa', 'Danh từ', 11, 'PUBLISHED'),
      (les_id, '使用料', 'しようりょう', '使用料', 'Phí sử dụng', 'Danh từ', 12, 'PUBLISHED'),
      (les_id, '無料', 'むりょう', '無料', 'Miễn phí', 'Danh từ', 13, 'PUBLISHED'),
      (les_id, '老人ホーム', 'ろうじんホーム', '老人ホーム', 'Nhà dưỡng lão', 'Danh từ', 14, 'PUBLISHED'),
      (les_id, '目印', 'めじるし', '目印', 'Dấu hiệu nhận biết', 'Danh từ', 15, 'PUBLISHED'),
      (les_id, '歩道橋', 'ほどうきょう', '歩道橋', 'Cầu vượt đi bộ', 'Danh từ', 16, 'PUBLISHED'),
      (les_id, '居酒屋', 'いざかや', '居酒屋', 'Quán nhậu', 'Danh từ', 17, 'PUBLISHED'),
      (les_id, '八百屋', 'やおや', '八百屋', 'Cửa hàng rau quả', 'Danh từ', 18, 'PUBLISHED'),
      (les_id, '正面', 'しょうめん', '正面', 'Chính diện, mặt trước', 'Danh từ', 19, 'PUBLISHED'),
      (les_id, '地方', 'ちほう', '地方', 'Địa phương', 'Danh từ', 20, 'PUBLISHED'),
      (les_id, '地域', 'ちいき', '地域', 'Khu vực', 'Danh từ', 21, 'PUBLISHED'),
      (les_id, '郊外', 'こうがい', '郊外', 'Ngoại ô', 'Danh từ', 22, 'PUBLISHED'),
      (les_id, '中心', 'ちゅうしん', '中心', 'Trung tâm, giữa', 'Danh từ', 23, 'PUBLISHED'),
      (les_id, '移転（する）', 'いてん（する）', '移転（する）', 'Sự di dời, di chuyển', 'Danh từ', 24, 'PUBLISHED'),
      (les_id, '工事（する）', 'こうじ（する）', '工事（する）', 'Thi công, công trình xây dựng', 'Danh từ', 25, 'PUBLISHED'),
      (les_id, '空き地', 'あきち', '空き地', 'Khu đất trống', 'Danh từ', 26, 'PUBLISHED'),
      (les_id, '人ごみ', 'ひとごみ', '人ごみ', 'Đám đông', 'Danh từ', 27, 'PUBLISHED'),
      (les_id, '都会', 'とかい', '都会', 'Đô thị', 'Danh từ', 28, 'PUBLISHED'),
      (les_id, '通りかかる', 'とおりかかる', '通りかかる', 'Tình cờ đi ngang qua', 'Danh từ', 29, 'PUBLISHED'),
      (les_id, '通り過ぎる', 'とおりすぎる', '通り過ぎる', 'Đi quá, đi lướt qua', 'Danh từ', 30, 'PUBLISHED'),
      (les_id, '徒歩', 'とほ', '徒歩', 'Đi bộ', 'Danh từ', 31, 'PUBLISHED'),
      (les_id, '方向', 'ほうこう', '方向', 'Hướng, phương hướng', 'Danh từ', 32, 'PUBLISHED'),
      (les_id, '遠回り（する）', 'とおまわり（する）', '遠回り（する）', 'Sự đi vòng, đường vòng', 'Danh từ', 33, 'PUBLISHED'),
      (les_id, '近道（する）', 'ちかみち（する）', '近道（する）', 'Sự đi tắt, đường tắt', 'Danh từ', 34, 'PUBLISHED'),
      (les_id, '距離', 'きょり', '距離', 'Cự ly, khoảng cách', 'Danh từ', 35, 'PUBLISHED'),
      (les_id, '追いかける', 'おいかける', '追いかける', 'Đuổi theo', 'Danh từ', 36, 'PUBLISHED'),
      (les_id, '追いつく', 'おいつく', '追いつく', 'Đuổi kịp', 'Danh từ', 37, 'PUBLISHED'),
      (les_id, '追い越す', 'おいこす', '追い越す', 'Vượt, vượt qua', 'Danh từ', 38, 'PUBLISHED'),
      (les_id, '突き当たり', 'つきあたり', '突き当たり', 'Cuối đường, ngõ cụt', 'Danh từ', 39, 'PUBLISHED'),
      (les_id, '立ち止まる', 'たちどまる', '立ち止まる', 'Dừng lại', 'Danh từ', 40, 'PUBLISHED'),
      (les_id, '横切る', 'よこぎる', '横切る', 'Băng qua', 'Danh từ', 41, 'PUBLISHED'),
      (les_id, '見かける', 'みかける', '見かける', 'Trông thấy, bắt gặp', 'Danh từ', 42, 'PUBLISHED'),
      (les_id, '行き先', 'いきさき / ゆきさき', '行き先', 'Nơi đến, điểm đến', 'Danh từ', 43, 'PUBLISHED'),
      (les_id, '往復（する）', 'おうふく（する）', '往復（する）', 'Sự đi và về, khứ hồi', 'Danh từ', 44, 'PUBLISHED'),
      (les_id, '片道', 'かたみち', '片道', 'Một chiều', 'Danh từ', 45, 'PUBLISHED'),
      (les_id, '各駅停車', 'かくえきていしゃ', '各駅停車', 'Tàu chậm (đỗ lại tất cả các ga)', 'Danh từ', 46, 'PUBLISHED'),
      (les_id, '急行', 'きゅうこう', '急行', 'Tàu tốc hành', 'Danh từ', 47, 'PUBLISHED'),
      (les_id, '始発', 'しはつ', '始発', 'Chuyến đầu tiên, ga đầu', 'Danh từ', 48, 'PUBLISHED'),
      (les_id, '終電', 'しゅうでん', '終電', 'Chuyến tàu cuối cùng', 'Danh từ', 49, 'PUBLISHED'),
      (les_id, '終点', 'しゅうてん', '終点', 'Ga cuối, trạm cuối', 'Danh từ', 50, 'PUBLISHED'),
      (les_id, '上り', 'のぼり', '上り', 'Lên thành phố, tàu đi về hướng trung tâm', 'Danh từ', 51, 'PUBLISHED'),
      (les_id, '下り', 'くだり', '下り', 'Đi về địa phương, tàu đi ra ngoại thành', 'Danh từ', 52, 'PUBLISHED'),
      (les_id, 'ＪＲ', 'ジェイアール', NULL, 'JR (Công ty đường sắt Nhật Bản)', 'Danh từ', 53, 'PUBLISHED'),
      (les_id, '私鉄', 'してつ', '私鉄', 'Tuyến đường sắt tư nhân', 'Danh từ', 54, 'PUBLISHED'),
      (les_id, '経由（する）', 'けいゆ（する）', '経由（する）', 'Sự đi qua, quá cảnh', 'Danh từ', 55, 'PUBLISHED'),
      (les_id, '定期券', 'ていきけん', '定期券', 'Vé tháng', 'Danh từ', 56, 'PUBLISHED'),
      (les_id, '有効期限', 'ゆうこうきげん', '有効期限', 'Thời hạn có hiệu lực, hạn sử dụng', 'Danh từ', 57, 'PUBLISHED'),
      (les_id, '窓口', 'まどぐち', '窓口', 'Quầy giao dịch', 'Danh từ', 58, 'PUBLISHED'),
      (les_id, '販売（する）', 'はんばい（する）', '販売（する）', 'Sự bán, việc bán hàng', 'Danh từ', 59, 'PUBLISHED'),
      (les_id, '通路側', 'つうろがわ', '通路側', 'Phía lối đi', 'Danh từ', 60, 'PUBLISHED'),
      (les_id, '改札', 'かいさつ', '改札', 'Cửa soát vé', 'Danh từ', 61, 'PUBLISHED'),
      (les_id, '指定席', 'していせき', '指定席', 'Ghế chỉ định', 'Danh từ', 62, 'PUBLISHED'),
      (les_id, '車内アナウンス', 'しゃないアナウンス', '車内アナウンス', 'Phát thanh trên tàu', 'Danh từ', 63, 'PUBLISHED'),
      (les_id, '車掌', 'しゃしょう', '車掌', 'Người soát vé, nhân viên phụ trách trên tàu', 'Danh từ', 64, 'PUBLISHED'),
      (les_id, '線路', 'せんろ', '線路', 'Đường ray, đường tàu', 'Danh từ', 65, 'PUBLISHED'),
      (les_id, '踏切', 'ふみきり', '踏切', 'Đường ngang (chỗ đường bộ giao với đường sắt)', 'Danh từ', 66, 'PUBLISHED'),
      (les_id, '乗り遅れる', 'のりおくれる', '乗り遅れる', 'Trễ tàu xe, lỡ tàu xe', 'Danh từ', 67, 'PUBLISHED'),
      (les_id, '乗り換える', 'のりかえる', '乗り換える', 'Chuyển tàu xe, đổi tàu xe', 'Danh từ', 68, 'PUBLISHED'),
      (les_id, '乗り越す', 'のりこす', '乗り越す', 'Đi quá (phạm vi vé đã mua)', 'Danh từ', 69, 'PUBLISHED'),
      (les_id, '乗り過ごす', 'のりすごす', '乗り過ごす', 'Đi quá trạm, lỡ trạm', 'Danh từ', 70, 'PUBLISHED'),
      (les_id, '踏む', 'ふむ', '踏む', 'Giẫm, dẫm', 'Danh từ', 71, 'PUBLISHED'),
      (les_id, 'バス停', 'バスてい', 'バス停', 'Bến đỗ xe buýt', 'Danh từ', 72, 'PUBLISHED'),
      (les_id, '乗車口', 'じょうしゃぐち', '乗車口', 'Cửa lên xe', 'Danh từ', 73, 'PUBLISHED'),
      (les_id, '乗客', 'じょうきゃく', '乗客', 'Hành khách', 'Danh từ', 74, 'PUBLISHED'),
      (les_id, '乗車（する）', 'じょうしゃ（する）', '乗車（する）', 'Đi tàu, đi xe', 'Danh từ', 75, 'PUBLISHED'),
      (les_id, '発車（する）', 'はっしゃ（する）', '発車（する）', 'Sự xuất phát', 'Danh từ', 76, 'PUBLISHED'),
      (les_id, '通過（する）', 'つうか（する）', '通過（する）', 'Sự đi qua', 'Danh từ', 77, 'PUBLISHED'),
      (les_id, '停車（する）', 'ていしゃ（する）', '停車（する）', 'Sự dừng xe', 'Danh từ', 78, 'PUBLISHED'),
      (les_id, '下車（する）', 'げしゃ（する）', '下車（する）', 'Sự xuống xe', 'Danh từ', 79, 'PUBLISHED'),
      (les_id, '交通費', 'こうつうひ', '交通費', 'Tiền đi lại', 'Danh từ', 80, 'PUBLISHED'),
      (les_id, 'バス代', 'バスだい', 'バス代', 'Tiền xe buýt', 'Danh từ', 81, 'PUBLISHED'),
      (les_id, '払い戻す', 'はらいもどす', '払い戻す', 'Hoàn trả, lấy lại', 'Danh từ', 82, 'PUBLISHED'),
      (les_id, '定員', 'ていいん', '定員', 'Số người chở tối đa', 'Danh từ', 83, 'PUBLISHED'),
      (les_id, '満員', 'まんいん', '満員', 'Đầy chỗ, hết chỗ, chật', 'Danh từ', 84, 'PUBLISHED'),
      (les_id, '時刻', 'じこく', '時刻', 'Giờ giấc', 'Danh từ', 85, 'PUBLISHED'),
      (les_id, '優先席', 'ゆうせんせき', '優先席', 'Ghế ưu tiên', 'Danh từ', 86, 'PUBLISHED'),
      (les_id, '立ち上がる', 'たちあがる', '立ち上がる', 'Đứng dậy', 'Danh từ', 87, 'PUBLISHED'),
      (les_id, '乗せる', 'のせる', '乗せる', 'Chở, cho lên xe', 'Danh từ', 88, 'PUBLISHED'),
      (les_id, '助手席', 'じょしゅせき', '助手席', 'Ghế phụ', 'Danh từ', 89, 'PUBLISHED'),
      (les_id, '道路', 'どうろ', '道路', 'Đường, đường bộ', 'Danh từ', 90, 'PUBLISHED'),
      (les_id, '渋滞（する）', 'じゅうたい（する）', '渋滞（する）', 'Sự kẹt xe, tắc đường', 'Danh từ', 91, 'PUBLISHED'),
      (les_id, '速度', 'そくど', '速度', 'Tốc độ', 'Danh từ', 92, 'PUBLISHED'),
      (les_id, '高速道路', 'こうそくどうろ', '高速道路', 'Đường cao tốc', 'Danh từ', 93, 'PUBLISHED'),
      (les_id, '安全（な）', 'あんぜん（な）', '安全（な）', 'Sự an toàn (an toàn)', 'Danh từ', 94, 'PUBLISHED'),
      (les_id, '列', 'れつ', '列', 'Hàng, dãy', 'Danh từ', 95, 'PUBLISHED'),
      (les_id, '割り込む', 'わりこむ', '割り込む', 'Chen ngang, chen vào', 'Danh từ', 96, 'PUBLISHED'),
      (les_id, '駐車違反', 'ちゅうしゃいはん', '駐車違反', 'Vi phạm quy định đỗ xe', 'Danh từ', 97, 'PUBLISHED'),
      (les_id, 'スピード違反', 'スピードいはん', 'スピード違反', 'Vi phạm tốc độ', 'Danh từ', 98, 'PUBLISHED'),
      (les_id, '飲酒運転', 'いんしゅうんてん', '飲酒運転', 'Lái xe khi đã uống rượu bia', 'Danh từ', 99, 'PUBLISHED'),
      (les_id, '一方通行', 'いっぽうつうこう', '一方通行', 'Đường một chiều', 'Danh từ', 100, 'PUBLISHED'),
      (les_id, '通行止め', 'つうこうどめ', '通行止め', 'Cấm lưu thông, đường bị chặn', 'Danh từ', 101, 'PUBLISHED'),
      (les_id, '運転免許証', 'うんてんめんきょしょう', '運転免許証', 'Bằng lái xe', 'Danh từ', 102, 'PUBLISHED'),
      (les_id, '中古車', 'ちゅうこしゃ', '中古車', 'Xe ô tô cũ', 'Danh từ', 103, 'PUBLISHED');

    -- Chapter 5: Bài 55: Học tập & Thi cử (勉強しよう！) (103 từ)
    SELECT lesson_id INTO les_id FROM lessons WHERE level_id = lvl_n3_id AND sort_order = 5;
    IF les_id IS NULL THEN
        INSERT INTO lessons (level_id, title, description, sort_order, is_sample, estimated_minutes, status, version)
        VALUES (lvl_n3_id, 'Bài 55: Học tập & Thi cử (勉強しよう！)', '2000 Từ vựng JLPT N3 cốt lõi từ JTest.net', 5, FALSE, 60, 'PUBLISHED', 0)
        RETURNING lesson_id INTO les_id;
    END IF;

    INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
    VALUES
      (les_id, '入学式', 'にゅうがくしき', '入学式', 'Lễ nhập học', 'Danh từ', 1, 'PUBLISHED'),
      (les_id, '卒業式', 'そつぎょうしき', '卒業式', 'Lễ tốt nghiệp', 'Danh từ', 2, 'PUBLISHED'),
      (les_id, '通学（する）', 'つうがく（する）', '通学（する）', 'Sự đi học', 'Danh từ', 3, 'PUBLISHED'),
      (les_id, '学年', 'がくねん', '学年', 'Năm học, khối lớp', 'Danh từ', 4, 'PUBLISHED'),
      (les_id, '学期', 'がっき', '学期', 'Học kỳ', 'Danh từ', 5, 'PUBLISHED'),
      (les_id, '欠席（する）', 'けっせき（する）', '欠席（する）', 'Vắng mặt, nghỉ', 'Danh từ', 6, 'PUBLISHED'),
      (les_id, '遅れる', 'おくれる', '遅れる', 'Đến trễ, đến muộn', 'Danh từ', 7, 'PUBLISHED'),
      (les_id, '遅刻（する）', 'ちこく（する）', '遅刻（する）', 'Sự đi trễ, đi muộn', 'Danh từ', 8, 'PUBLISHED'),
      (les_id, '集中（する）', 'しゅうちゅう（する）', '集中（する）', 'Sự tập trung', 'Danh từ', 9, 'PUBLISHED'),
      (les_id, '居眠り（する）', 'いねむり（する）', '居眠り（する）', 'Sự ngủ gật', 'Danh từ', 10, 'PUBLISHED'),
      (les_id, '寝不足（な）', 'ねぶそく（な）', '寝不足（な）', 'Sự thiếu ngủ (thiếu ngủ)', 'Danh từ', 11, 'PUBLISHED'),
      (les_id, '期間', 'きかん', '期間', 'Thời gian, thời kỳ', 'Danh từ', 12, 'PUBLISHED'),
      (les_id, '期限', 'きげん', '期限', 'Thời hạn', 'Danh từ', 13, 'PUBLISHED'),
      (les_id, '時間割', 'じかんわり', '時間割', 'Thời khóa biểu', 'Danh từ', 14, 'PUBLISHED'),
      (les_id, '項目', 'こうもく', '項目', 'Mục, khoản', 'Danh từ', 15, 'PUBLISHED'),
      (les_id, '座席', 'ざせき', '座席', 'Chỗ ngồi', 'Danh từ', 16, 'PUBLISHED'),
      (les_id, '締め切り', 'しめきり', '締め切り', 'Hạn chót', 'Danh từ', 17, 'PUBLISHED'),
      (les_id, '開く', 'ひらく', '開く', 'Mở', 'Danh từ', 18, 'PUBLISHED'),
      (les_id, '一応', 'いちおう', '一応', 'Tạm thời, cứ thử, cho chắc', 'Danh từ', 19, 'PUBLISHED'),
      (les_id, '貸し出し', 'かしだし', '貸し出し', '(Sự) cho mượn', 'Danh từ', 20, 'PUBLISHED'),
      (les_id, '返却（する）', 'へんきゃく（する）', '返却（する）', 'Sự trả lại', 'Danh từ', 21, 'PUBLISHED'),
      (les_id, '名札', 'なふだ', '名札', 'Thẻ tên, bảng tên', 'Danh từ', 22, 'PUBLISHED'),
      (les_id, '給食', 'きゅうしょく', '給食', 'Bữa ăn trưa ở trường', 'Danh từ', 23, 'PUBLISHED'),
      (les_id, '体育', 'たいいく', '体育', 'Môn thể dục', 'Danh từ', 24, 'PUBLISHED'),
      (les_id, '単語', 'たんご', '単語', 'Từ vựng', 'Danh từ', 25, 'PUBLISHED'),
      (les_id, '暗記（する）', 'あんき（する）', '暗記（する）', 'Học thuộc lòng', 'Danh từ', 26, 'PUBLISHED'),
      (les_id, '記憶（する）', 'きおく（する）', '記憶（する）', 'Trí nhớ, ghi nhớ', 'Danh từ', 27, 'PUBLISHED'),
      (les_id, 'くり返す', 'くりかえす', 'くり返す', 'Lặp lại', 'Danh từ', 28, 'PUBLISHED'),
      (les_id, '聞き取る', 'ききとる', '聞き取る', 'Nghe hiểu, nghe lấy', 'Danh từ', 29, 'PUBLISHED'),
      (les_id, '聞き返す', 'ききかえす', '聞き返す', 'Hỏi lại', 'Danh từ', 30, 'PUBLISHED'),
      (les_id, '聞き直す', 'ききなおす', '聞き直す', 'Nghe lại', 'Danh từ', 31, 'PUBLISHED'),
      (les_id, '言い直す', 'いいなおす', '言い直す', 'Nói lại, sửa lại lời nói', 'Danh từ', 32, 'PUBLISHED'),
      (les_id, '英会話', 'えいかいわ', '英会話', 'Hội thoại tiếng Anh', 'Danh từ', 33, 'PUBLISHED'),
      (les_id, '入門', 'にゅうもん', '入門', 'Nhập môn', 'Danh từ', 34, 'PUBLISHED'),
      (les_id, '下書き（する）', 'したがき（する）', '下書き（する）', 'Bản nháp, viết nháp', 'Danh từ', 35, 'PUBLISHED'),
      (les_id, '清書（する）', 'せいしょ（する）', '清書（する）', 'Viết chính thức, viết sạch', 'Danh từ', 36, 'PUBLISHED'),
      (les_id, '表れる', 'あらわれる', '表れる', 'Thể hiện, biểu hiện', 'Danh từ', 37, 'PUBLISHED'),
      (les_id, '物語', 'ものがたり', '物語', 'Câu chuyện, truyện kể', 'Danh từ', 38, 'PUBLISHED'),
      (les_id, '教科', 'きょうか', '教科', 'Môn học', 'Danh từ', 39, 'PUBLISHED'),
      (les_id, '科目', 'かもく', '科目', 'Môn học', 'Danh từ', 40, 'PUBLISHED'),
      (les_id, '足し算', 'たしざん', '足し算', 'Phép cộng', 'Danh từ', 41, 'PUBLISHED'),
      (les_id, '三角形', 'さんかっけい', '三角形', 'Hình tam giác', 'Danh từ', 42, 'PUBLISHED'),
      (les_id, '定規', 'じょうぎ', '定規', 'Thước kẻ', 'Danh từ', 43, 'PUBLISHED'),
      (les_id, '自習（する）', 'じしゅう（する）', '自習（する）', 'Tự học', 'Danh từ', 44, 'PUBLISHED'),
      (les_id, 'ローマ字', 'ローマじ', 'ローマ字', 'Chữ cái La-tinh', 'Danh từ', 45, 'PUBLISHED'),
      (les_id, '補講（する）', 'ほこう（する）', '補講（する）', 'Học bù, giờ học bổ sung', 'Danh từ', 46, 'PUBLISHED'),
      (les_id, '学部', 'がくぶ', '学部', 'Khoa', 'Danh từ', 47, 'PUBLISHED'),
      (les_id, '文系', 'ぶんけい', '文系', 'Khối ngành xã hội', 'Danh từ', 48, 'PUBLISHED'),
      (les_id, '理系', 'りけい', '理系', 'Khối ngành tự nhiên', 'Danh từ', 49, 'PUBLISHED'),
      (les_id, '学科', 'がっか', '学科', 'Bộ môn', 'Danh từ', 50, 'PUBLISHED'),
      (les_id, '専攻（する）', 'せんこう（する）', '専攻（する）', 'Chuyên môn, chuyên ngành', 'Danh từ', 51, 'PUBLISHED'),
      (les_id, '前期', 'ぜんき', '前期', 'Học kỳ đầu', 'Danh từ', 52, 'PUBLISHED'),
      (les_id, '学費', 'がくひ', '学費', 'Học phí', 'Danh từ', 53, 'PUBLISHED'),
      (les_id, '奨学金', 'しょうがくきん', '奨学金', 'Học bổng', 'Danh từ', 54, 'PUBLISHED'),
      (les_id, '公立', 'こうりつ', '公立', 'Công lập', 'Danh từ', 55, 'PUBLISHED'),
      (les_id, '私立', 'しりつ', '私立', 'Tư lập', 'Danh từ', 56, 'PUBLISHED'),
      (les_id, '教授', 'きょうじゅ', '教授', 'Giáo sư', 'Danh từ', 57, 'PUBLISHED'),
      (les_id, '講義（する）', 'こうぎ（する）', '講義（する）', 'Bài giảng', 'Danh từ', 58, 'PUBLISHED'),
      (les_id, '手続き（する）', 'てつづき（する）', '手続き（する）', 'Thủ tục', 'Danh từ', 59, 'PUBLISHED'),
      (les_id, '日付', 'ひづけ', '日付', 'Ngày tháng', 'Danh từ', 60, 'PUBLISHED'),
      (les_id, '筆者', 'ひっしゃ', '筆者', 'Tác giả', 'Danh từ', 61, 'PUBLISHED'),
      (les_id, '内容', 'ないよう', '内容', 'Nội dung', 'Danh từ', 62, 'PUBLISHED'),
      (les_id, '仕上げる', 'しあげる', '仕上げる', 'Làm xong, hoàn thành', 'Danh từ', 63, 'PUBLISHED'),
      (les_id, '提出（する）', 'ていしゅつ（する）', '提出（する）', 'Sự nộp, xuất trình', 'Danh từ', 64, 'PUBLISHED'),
      (les_id, '進路', 'しんろ', '進路', 'Lựa chọn trong tương lai', 'Danh từ', 65, 'PUBLISHED'),
      (les_id, '大学院', 'だいがくいん', '大学院', 'Cao học', 'Danh từ', 66, 'PUBLISHED'),
      (les_id, '進学（する）', 'しんがく（する）', '進学（する）', 'Sự học lên', 'Danh từ', 67, 'PUBLISHED'),
      (les_id, '一人暮らし', 'ひとりぐらし', '一人暮らし', 'Sống một mình', 'Danh từ', 68, 'PUBLISHED'),
      (les_id, '時給', 'じきゅう', '時給', 'Lương theo giờ', 'Danh từ', 69, 'PUBLISHED'),
      (les_id, '寮', 'りょう', '寮', 'Ký túc xá', 'Danh từ', 70, 'PUBLISHED'),
      (les_id, '休学（する）', 'きゅうがく（する）', '休学（する）', 'Sự nghỉ học', 'Danh từ', 71, 'PUBLISHED'),
      (les_id, '退学（する）', 'たいがく（する）', '退学（する）', 'Sự thôi học, bỏ học', 'Danh từ', 72, 'PUBLISHED'),
      (les_id, '受験（する）', 'じゅけん（する）', '受験（する）', 'Sự dự thi (thường chỉ việc thi vào các lớp đầu cấp, thi vào đại học)', 'Danh từ', 73, 'PUBLISHED'),
      (les_id, '受験生', 'じゅけんせい', '受験生', 'Thí sinh', 'Danh từ', 74, 'PUBLISHED'),
      (les_id, '合格（する）', 'ごうかく（する）', '合格（する）', 'Sự thi đỗ, thi đậu', 'Danh từ', 75, 'PUBLISHED'),
      (les_id, '配る', 'くばる', '配る', 'Phát', 'Danh từ', 76, 'PUBLISHED'),
      (les_id, '氏名', 'しめい', '氏名', 'Họ tên', 'Danh từ', 77, 'PUBLISHED'),
      (les_id, '裏返す', 'うらがえす', '裏返す', 'Lật, úp', 'Danh từ', 78, 'PUBLISHED'),
      (les_id, '問い', 'とい', '問い', 'Câu hỏi', 'Danh từ', 79, 'PUBLISHED'),
      (les_id, '解く', 'とく', '解く', 'Giải', 'Danh từ', 80, 'PUBLISHED'),
      (les_id, '正解（する）', 'せいかい（する）', '正解（する）', 'Câu trả lời đúng, sự trả lời đúng', 'Danh từ', 81, 'PUBLISHED'),
      (les_id, '正確（な）', 'せいかく（な）', '正確（な）', 'Sự chính xác (chính xác)', 'Danh từ', 82, 'PUBLISHED'),
      (les_id, '余る', 'あまる', '余る', 'Thừa', 'Danh từ', 83, 'PUBLISHED'),
      (les_id, '適当な', 'てきとうな', '適当な', 'Phù hợp, đại khái', 'Danh từ', 84, 'PUBLISHED'),
      (les_id, '間違い', 'まちがい', '間違い', 'Chỗ nhầm, chỗ sai', 'Danh từ', 85, 'PUBLISHED'),
      (les_id, '優れる', 'すぐれる', '優れる', 'Giỏi, xuất sắc', 'Danh từ', 86, 'PUBLISHED'),
      (les_id, '実力', 'じつりょく', '実力', 'Thực lực', 'Danh từ', 87, 'PUBLISHED'),
      (les_id, '結果', 'けっか', '結果', 'Kết quả', 'Danh từ', 88, 'PUBLISHED'),
      (les_id, '少数', 'しょうすう', '少数', 'Số ít', 'Danh từ', 89, 'PUBLISHED'),
      (les_id, '可能性', 'かのうせい', '可能性', 'Khả năng', 'Danh từ', 90, 'PUBLISHED'),
      (les_id, '掲示板', 'けいじばん', '掲示板', 'Bảng thông báo', 'Danh từ', 91, 'PUBLISHED'),
      (les_id, '知識', 'ちしき', '知識', 'Kiến thức', 'Danh từ', 92, 'PUBLISHED'),
      (les_id, '理解（する）', 'りかい（する）', '理解（する）', 'Sự lý giải, hiểu', 'Danh từ', 93, 'PUBLISHED'),
      (les_id, '目指す', 'めざす', '目指す', 'Nhắm tới, lấy mục tiêu', 'Danh từ', 94, 'PUBLISHED'),
      (les_id, '試す', 'ためす', '試す', 'Thử', 'Danh từ', 95, 'PUBLISHED'),
      (les_id, '自信', 'じしん', '自信', 'Tự tin', 'Danh từ', 96, 'PUBLISHED'),
      (les_id, 'やる気', 'やるき', 'やる気', 'Động lực, sự hăng hái', 'Danh từ', 97, 'PUBLISHED'),
      (les_id, '利口（な）', 'りこう（な）', '利口（な）', 'Khôn ngoan, lanh lợi', 'Danh từ', 98, 'PUBLISHED'),
      (les_id, '相当（な）', 'そうとう（な）', '相当（な）', 'Khá, rất, tương đương', 'Danh từ', 99, 'PUBLISHED'),
      (les_id, '努力（する）', 'どりょく（する）', '努力（する）', 'Sự nỗ lực, cố gắng', 'Danh từ', 100, 'PUBLISHED'),
      (les_id, '得意な', 'とくいな', '得意な', 'Giỏi, sở trường', 'Danh từ', 101, 'PUBLISHED'),
      (les_id, '苦手な', 'にがてな', '苦手な', 'Yếu, không giỏi', 'Danh từ', 102, 'PUBLISHED'),
      (les_id, '問い合わせる', 'といあわせる', '問い合わせる', 'Hỏi, liên hệ hỏi', 'Danh từ', 103, 'PUBLISHED');

    -- Chapter 6: Bài 56: Công việc & Công ty (仕事) (89 từ)
    SELECT lesson_id INTO les_id FROM lessons WHERE level_id = lvl_n3_id AND sort_order = 6;
    IF les_id IS NULL THEN
        INSERT INTO lessons (level_id, title, description, sort_order, is_sample, estimated_minutes, status, version)
        VALUES (lvl_n3_id, 'Bài 56: Công việc & Công ty (仕事)', '2000 Từ vựng JLPT N3 cốt lõi từ JTest.net', 6, FALSE, 60, 'PUBLISHED', 0)
        RETURNING lesson_id INTO les_id;
    END IF;

    INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
    VALUES
      (les_id, '企業', 'きぎょう', '企業', 'Doanh nghiệp, công ty', 'Danh từ', 1, 'PUBLISHED'),
      (les_id, '条件', 'じょうけん', '条件', 'Điều kiện', 'Danh từ', 2, 'PUBLISHED'),
      (les_id, '募集（する）', 'ぼしゅう（する）', '募集（する）', 'Sự tuyển mộ, chiêu mộ', 'Danh từ', 3, 'PUBLISHED'),
      (les_id, '応募（する）', 'おうぼ（する）', '応募（する）', 'Sự ứng tuyển', 'Danh từ', 4, 'PUBLISHED'),
      (les_id, '登録（する）', 'とうろく（する）', '登録（する）', 'Sự đăng ký', 'Danh từ', 5, 'PUBLISHED'),
      (les_id, '面接（する）', 'めんせつ（する）', '面接（する）', 'Sự phỏng vấn', 'Danh từ', 6, 'PUBLISHED'),
      (les_id, '履歴書', 'りれきしょ', '履歴書', 'Sơ yếu lý lịch', 'Danh từ', 7, 'PUBLISHED'),
      (les_id, '記入（する）', 'きにゅう（する）', '記入（する）', 'Việc ghi, điền vào', 'Danh từ', 8, 'PUBLISHED'),
      (les_id, '資格', 'しかく', '資格', 'Chứng chỉ, tư cách', 'Danh từ', 9, 'PUBLISHED'),
      (les_id, '服装', 'ふくそう', '服装', 'Trang phục', 'Danh từ', 10, 'PUBLISHED'),
      (les_id, '長所', 'ちょうしょ', '長所', 'Sở trường, điểm mạnh', 'Danh từ', 11, 'PUBLISHED'),
      (les_id, '短所', 'たんしょ', '短所', 'Sở đoản, điểm yếu', 'Danh từ', 12, 'PUBLISHED'),
      (les_id, '全て', 'すべて', '全て', 'Tất cả', 'Danh từ', 13, 'PUBLISHED'),
      (les_id, '採用（する）', 'さいよう（する）', '採用（する）', 'Sự tuyển dụng', 'Danh từ', 14, 'PUBLISHED'),
      (les_id, '受け取る', 'うけとる', '受け取る', 'Nhận', 'Danh từ', 15, 'PUBLISHED'),
      (les_id, '正社員', 'せいしゃいん', '正社員', 'Nhân viên chính thức', 'Danh từ', 16, 'PUBLISHED'),
      (les_id, '研修（する）', 'けんしゅう（する）', '研修（する）', 'Sự đào tạo, tập huấn', 'Danh từ', 17, 'PUBLISHED'),
      (les_id, '実習（する）', 'じっしゅう（する）', '実習（する）', 'Sự thực tập, tập sự', 'Danh từ', 18, 'PUBLISHED'),
      (les_id, '職場', 'しょくば', '職場', 'Nơi làm việc', 'Danh từ', 19, 'PUBLISHED'),
      (les_id, '得る', 'える', '得る', 'Đạt được, có được', 'Danh từ', 20, 'PUBLISHED'),
      (les_id, '受付', 'うけつけ', '受付', 'Quầy lễ tân', 'Danh từ', 21, 'PUBLISHED'),
      (les_id, '話し合う', 'はなしあう', '話し合う', 'Thảo luận, bàn bạc', 'Danh từ', 22, 'PUBLISHED'),
      (les_id, '調整（する）', 'ちょうせい（する）', '調整（する）', 'Sự điều chỉnh, điều phối, sắp xếp', 'Danh từ', 23, 'PUBLISHED'),
      (les_id, '能力', 'のうりょく', '能力', 'Năng lực', 'Danh từ', 24, 'PUBLISHED'),
      (les_id, '役割', 'やくわり', '役割', 'Vai trò', 'Danh từ', 25, 'PUBLISHED'),
      (les_id, '通勤（する）', 'つうきん（する）', '通勤（する）', 'Sự đi làm (chỉ việc đi và về)', 'Danh từ', 26, 'PUBLISHED'),
      (les_id, '早退（する）', 'そうたい（する）', '早退（する）', 'Sự về sớm', 'Danh từ', 27, 'PUBLISHED'),
      (les_id, '無断', 'むだん', '無断', 'Không xin phép', 'Danh từ', 28, 'PUBLISHED'),
      (les_id, '社会人', 'しゃかいじん', '社会人', 'Người đi làm', 'Danh từ', 29, 'PUBLISHED'),
      (les_id, '一人ひとり', 'ひとりひとり', '一人ひとり', 'Từng người từng người', 'Danh từ', 30, 'PUBLISHED'),
      (les_id, '印鑑', 'いんかん', '印鑑', 'Con dấu', 'Danh từ', 31, 'PUBLISHED'),
      (les_id, '回答（する）', 'かいとう（する）', '回答（する）', 'Sự trả lời, hồi đáp', 'Danh từ', 32, 'PUBLISHED'),
      (les_id, '月末', 'げつまつ', '月末', 'Cuối tháng', 'Danh từ', 33, 'PUBLISHED'),
      (les_id, '確かめる', 'たしかめる', '確かめる', 'Kiểm tra lại, xác nhận', 'Danh từ', 34, 'PUBLISHED'),
      (les_id, '確かに', 'たしかに', '確かに', 'Quả thật, đúng là, chắc chắn là', 'Danh từ', 35, 'PUBLISHED'),
      (les_id, '失業（する）', 'しつぎょう（する）', '失業（する）', 'Sự thất nghiệp', 'Danh từ', 36, 'PUBLISHED'),
      (les_id, '上司', 'じょうし', '上司', 'Cấp trên, sếp', 'Danh từ', 37, 'PUBLISHED'),
      (les_id, '部下', 'ぶか', '部下', 'Cấp dưới, nhân viên dưới quyền', 'Danh từ', 38, 'PUBLISHED'),
      (les_id, '先輩', 'せんぱい', '先輩', 'Bậc đàn anh, người đi trước', 'Danh từ', 39, 'PUBLISHED'),
      (les_id, '肩書き', 'かたがき', '肩書き', 'Chức danh, chức vụ', 'Danh từ', 40, 'PUBLISHED'),
      (les_id, '同僚', 'どうりょう', '同僚', 'Đồng nghiệp', 'Danh từ', 41, 'PUBLISHED'),
      (les_id, '同期', 'どうき', '同期', 'Cùng đợt, cùng khóa', 'Danh từ', 42, 'PUBLISHED'),
      (les_id, '休暇', 'きゅうか', '休暇', 'Nghỉ phép, kỳ nghỉ', 'Danh từ', 43, 'PUBLISHED'),
      (les_id, '責任', 'せきにん', '責任', 'Trách nhiệm', 'Danh từ', 44, 'PUBLISHED'),
      (les_id, '不満（な）', 'ふまん（な）', '不満（な）', 'Bất mãn, không hài lòng', 'Danh từ', 45, 'PUBLISHED'),
      (les_id, '命令（する）', 'めいれい（する）', '命令（する）', 'Lệnh, mệnh lệnh', 'Danh từ', 46, 'PUBLISHED'),
      (les_id, '指示（する）', 'しじ（する）', '指示（する）', 'Chỉ thị, chỉ dẫn', 'Danh từ', 47, 'PUBLISHED'),
      (les_id, '苦労（する）', 'くろう（する）', '苦労（する）', 'Sự vất vả, gian khổ', 'Danh từ', 48, 'PUBLISHED'),
      (les_id, '報告（する）', 'ほうこく（する）', '報告（する）', 'Báo cáo', 'Danh từ', 49, 'PUBLISHED'),
      (les_id, '飲み会', 'のみかい', '飲み会', 'Buổi nhậu, tiệc rượu', 'Danh từ', 50, 'PUBLISHED'),
      (les_id, '歓迎会', 'かんげいかい', '歓迎会', 'Tiệc chào mừng, tiệc đón chào', 'Danh từ', 51, 'PUBLISHED'),
      (les_id, '飲み放題', 'のみほうだい', '飲み放題', 'Uống không giới hạn, uống thoải mái', 'Danh từ', 52, 'PUBLISHED'),
      (les_id, '勤務（する）', 'きんむ（する）', '勤務（する）', 'Sự làm việc', 'Danh từ', 53, 'PUBLISHED'),
      (les_id, '事務', 'じむ', '事務', 'Việc văn phòng', 'Danh từ', 54, 'PUBLISHED'),
      (les_id, '担当（する）', 'たんとう（する）', '担当（する）', 'Sự phụ trách', 'Danh từ', 55, 'PUBLISHED'),
      (les_id, '営業（する）', 'えいぎょう（する）', '営業（する）', 'Kinh doanh (thường chỉ hoạt động mua bán của doanh nghiệp)', 'Danh từ', 56, 'PUBLISHED'),
      (les_id, '経営（する）', 'けいえい（する）', '経営（する）', 'Sự quản lý, điều hành (doanh nghiệp)', 'Danh từ', 57, 'PUBLISHED'),
      (les_id, '広告（する）', 'こうこく（する）', '広告（する）', 'Việc quảng cáo', 'Danh từ', 58, 'PUBLISHED'),
      (les_id, '出版（する）', 'しゅっぱん（する）', '出版（する）', 'Sự xuất bản', 'Danh từ', 59, 'PUBLISHED'),
      (les_id, '制作（する）', 'せいさく（する）', '制作（する）', 'Việc sản xuất, làm, chế tác', 'Danh từ', 60, 'PUBLISHED'),
      (les_id, '通訳（する）', 'つうやく（する）', '通訳（する）', 'Sự phiên dịch, thông dịch', 'Danh từ', 61, 'PUBLISHED'),
      (les_id, '精算（する）', 'せいさん（する）', '精算（する）', 'Sự quyết toán, thanh toán', 'Danh từ', 62, 'PUBLISHED'),
      (les_id, '（予定を）立てる', '（よていを）たてる', '（予定を）立てる', 'Lên, lập (dự định)', 'Danh từ', 63, 'PUBLISHED'),
      (les_id, '長期', 'ちょうき', '長期', 'Trường kỳ, dài hạn', 'Danh từ', 64, 'PUBLISHED'),
      (les_id, '日程', 'にってい', '日程', 'Lịch trình', 'Danh từ', 65, 'PUBLISHED'),
      (les_id, '延期（する）', 'えんき（する）', '延期（する）', 'Sự hoãn, hoãn lại', 'Danh từ', 66, 'PUBLISHED'),
      (les_id, '携帯（する）', 'けいたい（する）', '携帯（する）', 'Sự mang theo, cầm theo', 'Danh từ', 67, 'PUBLISHED'),
      (les_id, '協力（する）', 'きょうりょく（する）', '協力（する）', 'Sự hợp tác', 'Danh từ', 68, 'PUBLISHED'),
      (les_id, '省略（する）', 'しょうりゃく（する）', '省略（する）', 'Sự lược bỏ, bỏ qua', 'Danh từ', 69, 'PUBLISHED'),
      (les_id, '積む', 'つむ', '積む', 'Tích lũy, chồng chất', 'Danh từ', 70, 'PUBLISHED'),
      (les_id, '成長（する）', 'せいちょう（する）', '成長（する）', 'Sự trưởng thành', 'Danh từ', 71, 'PUBLISHED'),
      (les_id, '画面', 'がめん', '画面', 'Màn hình', 'Danh từ', 72, 'PUBLISHED'),
      (les_id, '件名', 'けんめい', '件名', 'Tiêu đề (email)', 'Danh từ', 73, 'PUBLISHED'),
      (les_id, '受信（する）', 'じゅしん（する）', '受信（する）', 'Việc nhận (thư, e-mail)', 'Danh từ', 74, 'PUBLISHED'),
      (les_id, '送信（する）', 'そうしん（する）', '送信（する）', 'Việc gửi (thư, e-mail)', 'Danh từ', 75, 'PUBLISHED'),
      (les_id, '返信（する）', 'へんしん（する）', '返信（する）', 'Việc trả lời (thư, e-mail)', 'Danh từ', 76, 'PUBLISHED'),
      (les_id, 'やり取り（する）', 'やりとり（する）', 'やり取り（する）', 'Sự trao đổi qua lại', 'Danh từ', 77, 'PUBLISHED'),
      (les_id, '入力（する）', 'にゅうりょく（する）', '入力（する）', 'Sự đánh máy, gõ, nhập', 'Danh từ', 78, 'PUBLISHED'),
      (les_id, '変換（する）', 'へんかん（する）', '変換（する）', 'Sự chuyển đổi', 'Danh từ', 79, 'PUBLISHED'),
      (les_id, '改行（する）', 'かいぎょう（する）', '改行（する）', 'Sự xuống dòng', 'Danh từ', 80, 'PUBLISHED'),
      (les_id, '見直す', 'みなおす', '見直す', 'Xem lại', 'Danh từ', 81, 'PUBLISHED'),
      (les_id, '変更（する）', 'へんこう（する）', '変更（する）', 'Sự thay đổi', 'Danh từ', 82, 'PUBLISHED'),
      (les_id, '画像', 'がぞう', '画像', 'Hình ảnh, ảnh', 'Danh từ', 83, 'PUBLISHED'),
      (les_id, '挿入（する）', 'そうにゅう（する）', '挿入（する）', 'Sự chèn', 'Danh từ', 84, 'PUBLISHED'),
      (les_id, '添付（する）', 'てんぷ（する）', '添付（する）', 'Sự đính kèm', 'Danh từ', 85, 'PUBLISHED'),
      (les_id, '削除（する）', 'さくじょ（する）', '削除（する）', 'Sự xóa bỏ', 'Danh từ', 86, 'PUBLISHED'),
      (les_id, '保存（する）', 'ほぞん（する）', '保存（する）', 'Sự lưu trữ, lưu', 'Danh từ', 87, 'PUBLISHED'),
      (les_id, '新規作成（する）', 'しんきさくせい（する）', '新規作成（する）', 'Sự tạo mới', 'Danh từ', 88, 'PUBLISHED'),
      (les_id, '完了（する）', 'かんりょう（する）', '完了（する）', 'Sự hoàn thành, hoàn tất', 'Danh từ', 89, 'PUBLISHED');

    -- Chapter 7: Bài 57: Những điều giải trí (楽しいこと) (76 từ)
    SELECT lesson_id INTO les_id FROM lessons WHERE level_id = lvl_n3_id AND sort_order = 7;
    IF les_id IS NULL THEN
        INSERT INTO lessons (level_id, title, description, sort_order, is_sample, estimated_minutes, status, version)
        VALUES (lvl_n3_id, 'Bài 57: Những điều giải trí (楽しいこと)', '2000 Từ vựng JLPT N3 cốt lõi từ JTest.net', 7, FALSE, 60, 'PUBLISHED', 0)
        RETURNING lesson_id INTO les_id;
    END IF;

    INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
    VALUES
      (les_id, '日にち', 'ひにち', '日にち', 'Ngày, số ngày', 'Danh từ', 1, 'PUBLISHED'),
      (les_id, '日帰り', 'ひがえり', '日帰り', 'Đi về trong ngày', 'Danh từ', 2, 'PUBLISHED'),
      (les_id, '泊まり', 'とまり', '泊まり', 'Nghỉ qua đêm', 'Danh từ', 3, 'PUBLISHED'),
      (les_id, '宿泊（する）', 'しゅくはく（する）', '宿泊（する）', 'Sự lưu trú, nghỉ trọ', 'Danh từ', 4, 'PUBLISHED'),
      (les_id, '滞在（する）', 'たいざい（する）', '滞在（する）', 'Ở, lưu trú', 'Danh từ', 5, 'PUBLISHED'),
      (les_id, '団体', 'だんたい', '団体', 'Đoàn, đoàn thể', 'Danh từ', 6, 'PUBLISHED'),
      (les_id, '観光（する）', 'かんこう（する）', '観光（する）', 'Sự du lịch, tham quan', 'Danh từ', 7, 'PUBLISHED'),
      (les_id, '費用', 'ひよう', '費用', 'Phí, chi phí', 'Danh từ', 8, 'PUBLISHED'),
      (les_id, '予算', 'よさん', '予算', 'Kinh phí, ngân sách', 'Danh từ', 9, 'PUBLISHED'),
      (les_id, '集合（する）', 'しゅうごう（する）', '集合（する）', 'Sự tập trung, tập hợp', 'Danh từ', 10, 'PUBLISHED'),
      (les_id, '解散（する）', 'かいさん（する）', '解散（する）', 'Sự giải tán', 'Danh từ', 11, 'PUBLISHED'),
      (les_id, '旅館', 'りょかん', '旅館', 'Lữ quán (nhà trọ kiểu Nhật)', 'Danh từ', 12, 'PUBLISHED'),
      (les_id, '五つ星ホテル', 'いつつぼしホテル', '五つ星ホテル', 'Khách sạn 5 sao', 'Danh từ', 13, 'PUBLISHED'),
      (les_id, '満室', 'まんしつ', '満室', 'Hết phòng', 'Danh từ', 14, 'PUBLISHED'),
      (les_id, '近づく', 'ちかづく', '近づく', 'Đến gần', 'Danh từ', 15, 'PUBLISHED'),
      (les_id, '取り消す', 'とりけす', '取り消す', 'Hủy, hủy bỏ', 'Danh từ', 16, 'PUBLISHED'),
      (les_id, '追加（する）', 'ついか（する）', '追加（する）', 'Sự bổ sung, thêm', 'Danh từ', 17, 'PUBLISHED'),
      (les_id, '持ち物', 'もちもの', '持ち物', 'Đồ mang đi, đồ đạc cá nhân', 'Danh từ', 18, 'PUBLISHED'),
      (les_id, '足りる', 'たりる', '足りる', 'Đủ', 'Danh từ', 19, 'PUBLISHED'),
      (les_id, '使用（する）', 'しよう（する）', '使用（する）', 'Việc sử dụng', 'Danh từ', 20, 'PUBLISHED'),
      (les_id, '船旅', 'ふなたび', '船旅', 'Du lịch tàu thủy', 'Danh từ', 21, 'PUBLISHED'),
      (les_id, '時差', 'じさ', '時差', 'Chênh lệch múi giờ', 'Danh từ', 22, 'PUBLISHED'),
      (les_id, '両替（する）', 'りょうがえ（する）', '両替（する）', 'Sự đổi tiền', 'Danh từ', 23, 'PUBLISHED'),
      (les_id, '来日（する）', 'らいにち（する）', '来日（する）', 'Đến Nhật Bản', 'Danh từ', 24, 'PUBLISHED'),
      (les_id, '競争（する）', 'きょうそう（する）', '競争（する）', 'Sự cạnh tranh', 'Danh từ', 25, 'PUBLISHED'),
      (les_id, '活躍（する）', 'かつやく（する）', '活躍（する）', 'Hoạt động tích cực', 'Danh từ', 26, 'PUBLISHED'),
      (les_id, '打つ', 'うつ', '打つ', 'Đánh', 'Danh từ', 27, 'PUBLISHED'),
      (les_id, '前半', 'ぜんはん', '前半', 'Hiệp đầu, nửa đầu', 'Danh từ', 28, 'PUBLISHED'),
      (les_id, '引き分け', 'ひきわけ', '引き分け', 'Hòa', 'Danh từ', 29, 'PUBLISHED'),
      (les_id, '運動会', 'うんどうかい', '運動会', 'Ngày hội thể thao', 'Danh từ', 30, 'PUBLISHED'),
      (les_id, '大声', 'おおごえ', '大声', 'Tiếng to, hô to, hò hét', 'Danh từ', 31, 'PUBLISHED'),
      (les_id, '思い切り', 'おもいきり', '思い切り', 'Hết sức, hết mình', 'Danh từ', 32, 'PUBLISHED'),
      (les_id, '拍手（する）', 'はくしゅ（する）', '拍手（する）', 'Vỗ tay', 'Danh từ', 33, 'PUBLISHED'),
      (les_id, '握手（する）', 'あくしゅ（する）', '握手（する）', 'Bắt tay', 'Danh từ', 34, 'PUBLISHED'),
      (les_id, '惜しい', 'おしい', '惜しい', 'Tiếc, đáng tiếc', 'Danh từ', 35, 'PUBLISHED'),
      (les_id, '体操（する）', 'たいそう（する）', '体操（する）', 'Thể dục', 'Danh từ', 36, 'PUBLISHED'),
      (les_id, '日課', 'にっか', '日課', 'Việc thường làm hàng ngày', 'Danh từ', 37, 'PUBLISHED'),
      (les_id, '引退（する）', 'いんたい（する）', '引退（する）', 'Sự giải nghệ, rút lui', 'Danh từ', 38, 'PUBLISHED'),
      (les_id, '水着', 'みずぎ', '水着', 'Quần áo tắm, quần áo bơi', 'Danh từ', 39, 'PUBLISHED'),
      (les_id, '好む', 'このむ', '好む', 'Thích, chuộng', 'Danh từ', 40, 'PUBLISHED'),
      (les_id, '好み', 'このみ', '好み', 'Sở thích, gu', 'Danh từ', 41, 'PUBLISHED'),
      (les_id, '流行（する）', 'りゅうこう（する）', '流行（する）', 'Sự thịnh hành, lưu hành, mốt', 'Danh từ', 42, 'PUBLISHED'),
      (les_id, '探す', 'さがす', '探す', 'Tìm, tìm kiếm', 'Danh từ', 43, 'PUBLISHED'),
      (les_id, '似合う', 'にあう', '似合う', 'Hợp, phù hợp', 'Danh từ', 44, 'PUBLISHED'),
      (les_id, '高級（な）', 'こうきゅう（な）', '高級（な）', 'Sự cao cấp (cao cấp)', 'Danh từ', 45, 'PUBLISHED'),
      (les_id, '本物', 'ほんもの', '本物', 'Đồ thật, hàng thật', 'Danh từ', 46, 'PUBLISHED'),
      (les_id, 'にせ物', 'にせもの', 'にせ物', 'Hàng giả', 'Danh từ', 47, 'PUBLISHED'),
      (les_id, '保証（する）', 'ほしょう（する）', '保証（する）', 'Sự bảo đảm, bảo hành', 'Danh từ', 48, 'PUBLISHED'),
      (les_id, '取り替える', 'とりかえる', '取り替える', 'Thay, đổi', 'Danh từ', 49, 'PUBLISHED'),
      (les_id, '外す', 'はずす', '外す', 'Tháo, rời', 'Danh từ', 50, 'PUBLISHED'),
      (les_id, '染める', 'そめる', '染める', 'Nhuộm', 'Danh từ', 51, 'PUBLISHED'),
      (les_id, '夏物', 'なつもの', '夏物', 'Đồ mùa hè', 'Danh từ', 52, 'PUBLISHED'),
      (les_id, '冬物', 'ふゆもの', '冬物', 'Đồ mùa đông', 'Danh từ', 53, 'PUBLISHED'),
      (les_id, '上着', 'うわぎ', '上着', 'Áo khoác', 'Danh từ', 54, 'PUBLISHED'),
      (les_id, '婦人服', 'ふじんふく', '婦人服', 'Quần áo nữ', 'Danh từ', 55, 'PUBLISHED'),
      (les_id, '紳士服', 'しんしふく', '紳士服', 'Quần áo nam', 'Danh từ', 56, 'PUBLISHED'),
      (les_id, '宝石', 'ほうせき', '宝石', 'Đá quý', 'Danh từ', 57, 'PUBLISHED'),
      (les_id, '手袋', 'てぶくろ', '手袋', 'Găng tay', 'Danh từ', 58, 'PUBLISHED'),
      (les_id, '[お]化粧（する）', '[お]けしょう（する）', '[お]化粧（する）', 'Trang điểm', 'Danh từ', 59, 'PUBLISHED'),
      (les_id, '口紅', 'くちべに', '口紅', 'Son môi', 'Danh từ', 60, 'PUBLISHED'),
      (les_id, 'まつ毛', 'まつげ', 'まつ毛', 'Lông mi', 'Danh từ', 61, 'PUBLISHED'),
      (les_id, '香水', 'こうすい', '香水', 'Nước hoa', 'Danh từ', 62, 'PUBLISHED'),
      (les_id, '古着', 'ふるぎ', '古着', 'Quần áo cũ', 'Danh từ', 63, 'PUBLISHED'),
      (les_id, '革', 'かわ', '革', 'Da (thuộc da)', 'Danh từ', 64, 'PUBLISHED'),
      (les_id, '気に入る', 'きにいる', '気に入る', 'Thích, ưa thích', 'Danh từ', 65, 'PUBLISHED'),
      (les_id, 'お気に入り', 'おきにいり', 'お気に入り', 'Đồ yêu thích, người yêu thích', 'Danh từ', 66, 'PUBLISHED'),
      (les_id, '芸術', 'げいじゅつ', '芸術', 'Nghệ thuật', 'Danh từ', 67, 'PUBLISHED'),
      (les_id, '絵画', 'かいが', '絵画', 'Hội họa, tranh vẽ', 'Danh từ', 68, 'PUBLISHED'),
      (les_id, '才能', 'さいのう', '才能', 'Tài năng, năng khiếu', 'Danh từ', 69, 'PUBLISHED'),
      (les_id, '読書（する）', 'どくしょ（する）', '読書（する）', 'Việc đọc sách', 'Danh từ', 70, 'PUBLISHED'),
      (les_id, '名作', 'めいさく', '名作', 'Tác phẩm nổi tiếng, kiệt tác', 'Danh từ', 71, 'PUBLISHED'),
      (les_id, '登場（する）', 'とうじょう（する）', '登場（する）', 'Sự xuất hiện, sự ra mắt', 'Danh từ', 72, 'PUBLISHED'),
      (les_id, '好奇心', 'こうきしん', '好奇心', 'Sự tò mò, lòng hiếu kỳ', 'Danh từ', 73, 'PUBLISHED'),
      (les_id, '出品（する）', 'しゅっぴん（する）', '出品（する）', 'Đưa tác phẩm đi dự thi, trưng bày', 'Danh từ', 74, 'PUBLISHED'),
      (les_id, '演奏（する）', 'えんそう（する）', '演奏（する）', 'Sự biểu diễn âm nhạc, sự trình tấu', 'Danh từ', 75, 'PUBLISHED'),
      (les_id, '講演会', 'こうえんかい', '講演会', 'Buổi diễn thuyết, buổi thuyết trình', 'Danh từ', 76, 'PUBLISHED');

    -- Chapter 8: Bài 58: Sức khỏe & Bệnh viện (健康のために) (66 từ)
    SELECT lesson_id INTO les_id FROM lessons WHERE level_id = lvl_n3_id AND sort_order = 8;
    IF les_id IS NULL THEN
        INSERT INTO lessons (level_id, title, description, sort_order, is_sample, estimated_minutes, status, version)
        VALUES (lvl_n3_id, 'Bài 58: Sức khỏe & Bệnh viện (健康のために)', '2000 Từ vựng JLPT N3 cốt lõi từ JTest.net', 8, FALSE, 60, 'PUBLISHED', 0)
        RETURNING lesson_id INTO les_id;
    END IF;

    INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
    VALUES
      (les_id, '身長', 'しんちょう', '身長', 'Chiều cao', 'Danh từ', 1, 'PUBLISHED'),
      (les_id, '伸びる', 'のびる', '伸びる', 'Dài ra, tăng lên', 'Danh từ', 2, 'PUBLISHED'),
      (les_id, '測る', 'はかる', '測る', 'Đo', 'Danh từ', 3, 'PUBLISHED'),
      (les_id, '体重', 'たいじゅう', '体重', 'Cân nặng, thể trọng', 'Danh từ', 4, 'PUBLISHED'),
      (les_id, '体重計', 'たいじゅうけい', '体重計', 'Cân, cân sức khỏe', 'Danh từ', 5, 'PUBLISHED'),
      (les_id, '体温', 'たいおん', '体温', 'Thân nhiệt', 'Danh từ', 6, 'PUBLISHED'),
      (les_id, '額', 'ひたい', '額', 'Trán', 'Danh từ', 7, 'PUBLISHED'),
      (les_id, '血液', 'けつえき', '血液', 'Máu', 'Danh từ', 8, 'PUBLISHED'),
      (les_id, '血液型', 'けつえきがた', '血液型', 'Nhóm máu', 'Danh từ', 9, 'PUBLISHED'),
      (les_id, '心臓', 'しんぞう', '心臓', 'Tim', 'Danh từ', 10, 'PUBLISHED'),
      (les_id, '汗', 'あせ', '汗', 'Mồ hôi', 'Danh từ', 11, 'PUBLISHED'),
      (les_id, '息', 'いき', '息', 'Hơi thở', 'Danh từ', 12, 'PUBLISHED'),
      (les_id, 'ため息', 'ためいき', 'ため息', 'Thở dài', 'Danh từ', 13, 'PUBLISHED'),
      (les_id, '皮ふ', 'ひふ', '皮ふ', 'Da', 'Danh từ', 14, 'PUBLISHED'),
      (les_id, '顔色', 'かおいろ', '顔色', 'Sắc mặt', 'Danh từ', 15, 'PUBLISHED'),
      (les_id, '睡眠', 'すいみん', '睡眠', 'Giấc ngủ', 'Danh từ', 16, 'PUBLISHED'),
      (les_id, '丈夫な', 'じょうぶな', '丈夫な', 'Khỏe mạnh, bền chắc', 'Danh từ', 17, 'PUBLISHED'),
      (les_id, '歯科医', 'しかい', '歯科医', 'Nha sĩ', 'Danh từ', 18, 'PUBLISHED'),
      (les_id, '虫歯', 'むしば', '虫歯', 'Răng sâu', 'Danh từ', 19, 'PUBLISHED'),
      (les_id, '裸', 'はだか', '裸', 'Trần truồng, khỏa thân', 'Danh từ', 20, 'PUBLISHED'),
      (les_id, '裸足', 'はだし', '裸足', 'Chân trần, chân đất', 'Danh từ', 21, 'PUBLISHED'),
      (les_id, '調子', 'ちょうし', '調子', 'Tình trạng, cảm giác', 'Danh từ', 22, 'PUBLISHED'),
      (les_id, '気になる', 'きになる', '気になる', 'Bận tâm', 'Danh từ', 23, 'PUBLISHED'),
      (les_id, '気にする', 'きにする', '気にする', 'Bận tâm, lo lắng', 'Danh từ', 24, 'PUBLISHED'),
      (les_id, '白髪', 'しらが', '白髪', 'Tóc bạc', 'Danh từ', 25, 'PUBLISHED'),
      (les_id, '抜く', 'ぬく', '抜く', 'Nhổ', 'Danh từ', 26, 'PUBLISHED'),
      (les_id, '生える', 'はえる', '生える', 'Mọc', 'Danh từ', 27, 'PUBLISHED'),
      (les_id, '日焼け（する）', 'ひやけ（する）', '日焼け（する）', 'Cháy nắng', 'Danh từ', 28, 'PUBLISHED'),
      (les_id, '傷', 'きず', '傷', 'Vết thương', 'Danh từ', 29, 'PUBLISHED'),
      (les_id, '酔っぱらう', 'よっぱらう', '酔っぱらう', 'Say, say rượu', 'Danh từ', 30, 'PUBLISHED'),
      (les_id, '酔っぱらい', 'よっぱらい', '酔っぱらい', 'Kẻ say rượu', 'Danh từ', 31, 'PUBLISHED'),
      (les_id, '控える', 'ひかえる', '控える', 'Hạn chế, kiêng', 'Danh từ', 32, 'PUBLISHED'),
      (les_id, '花粉症', 'かふんしょう', '花粉症', 'Dị ứng phấn hoa', 'Danh từ', 33, 'PUBLISHED'),
      (les_id, '手洗い', 'てあらい', '手洗い', 'Rửa tay', 'Danh từ', 34, 'PUBLISHED'),
      (les_id, '鼻水', 'はなみず', '鼻水', 'Nước mũi', 'Danh từ', 35, 'PUBLISHED'),
      (les_id, '（肩が）こる', '（かたが）こる', '（肩が）こる', '(Vai) đau mỏi', 'Danh từ', 36, 'PUBLISHED'),
      (les_id, '肩こり', 'かたこり', '肩こり', 'Chứng đau mỏi vai', 'Danh từ', 37, 'PUBLISHED'),
      (les_id, '痛み', 'いたみ', '痛み', 'Cơn đau, sự đau đớn', 'Danh từ', 38, 'PUBLISHED'),
      (les_id, '頭痛', 'ずつう', '頭痛', 'Đau đầu', 'Danh từ', 39, 'PUBLISHED'),
      (les_id, '腹痛', 'ふくつう', '腹痛', 'Đau bụng', 'Danh từ', 40, 'PUBLISHED'),
      (les_id, '異常（な）', 'いじょう（な）', '異常（な）', 'Sự bất thường (bất thường)', 'Danh từ', 41, 'PUBLISHED'),
      (les_id, '吐く', 'はく', '吐く', 'Nôn', 'Danh từ', 42, 'PUBLISHED'),
      (les_id, '吐き気', 'はきけ', '吐き気', 'Buồn nôn', 'Danh từ', 43, 'PUBLISHED'),
      (les_id, '（痛みが）とれる', '（いたみが）とれる', '（痛みが）とれる', 'Hết (đau)', 'Danh từ', 44, 'PUBLISHED'),
      (les_id, '苦しむ', 'くるしむ', '苦しむ', 'Khổ sở, chịu đựng', 'Danh từ', 45, 'PUBLISHED'),
      (les_id, '部分', 'ぶぶん', '部分', 'Bộ phận, phần', 'Danh từ', 46, 'PUBLISHED'),
      (les_id, '骨折（する）', 'こっせつ（する）', '骨折（する）', 'Gãy xương', 'Danh từ', 47, 'PUBLISHED'),
      (les_id, '患者', 'かんじゃ', '患者', 'Bệnh nhân', 'Danh từ', 48, 'PUBLISHED'),
      (les_id, '診察（する）', 'しんさつ（する）', '診察（する）', 'Khám', 'Danh từ', 49, 'PUBLISHED'),
      (les_id, '検査（する）', 'けんさ（する）', '検査（する）', 'Xét nghiệm, kiểm tra', 'Danh từ', 50, 'PUBLISHED'),
      (les_id, '治療（する）', 'ちりょう（する）', '治療（する）', 'Điều trị, chữa', 'Danh từ', 51, 'PUBLISHED'),
      (les_id, '健康診断', 'けんこうしんだん', '健康診断', 'Khám sức khỏe', 'Danh từ', 52, 'PUBLISHED'),
      (les_id, '内科', 'ないか', '内科', 'Khoa nội, nội khoa', 'Danh từ', 53, 'PUBLISHED'),
      (les_id, '外科', 'げか', '外科', 'Khoa ngoại, ngoại khoa', 'Danh từ', 54, 'PUBLISHED'),
      (les_id, '小児科', 'しょうにか', '小児科', 'Khoa nhi, nhi khoa', 'Danh từ', 55, 'PUBLISHED'),
      (les_id, '保険', 'ほけん', '保険', 'Bảo hiểm', 'Danh từ', 56, 'PUBLISHED'),
      (les_id, '保険証', 'ほけんしょう', '保険証', 'Thẻ bảo hiểm', 'Danh từ', 57, 'PUBLISHED'),
      (les_id, '効く', 'きく', '効く', 'Có tác dụng, có hiệu quả', 'Danh từ', 58, 'PUBLISHED'),
      (les_id, '注射（する）', 'ちゅうしゃ（する）', '注射（する）', 'Tiêm', 'Danh từ', 59, 'PUBLISHED'),
      (les_id, '栄養', 'えいよう', '栄養', 'Dinh dưỡng, bổ dưỡng', 'Danh từ', 60, 'PUBLISHED'),
      (les_id, '回復（する）', 'かいふく（する）', '回復（する）', 'Hồi phục', 'Danh từ', 61, 'PUBLISHED'),
      (les_id, '証明（する）', 'しょうめい（する）', '証明（する）', 'Sự chứng minh', 'Danh từ', 62, 'PUBLISHED'),
      (les_id, '手術（する）', 'しゅじゅつ（する）', '手術（する）', 'Phẫu thuật, mổ', 'Danh từ', 63, 'PUBLISHED'),
      (les_id, '包帯', 'ほうたい', '包帯', 'Băng bó', 'Danh từ', 64, 'PUBLISHED'),
      (les_id, '巻く', 'まく', '巻く', 'Quấn', 'Danh từ', 65, 'PUBLISHED'),
      (les_id, '長生き（する）', 'ながいき（する）', '長生き（する）', 'Sự sống lâu', 'Danh từ', 66, 'PUBLISHED');

    -- Chapter 9: Bài 59: Tự nhiên & Cuộc sống (自然と暮らし) (75 từ)
    SELECT lesson_id INTO les_id FROM lessons WHERE level_id = lvl_n3_id AND sort_order = 9;
    IF les_id IS NULL THEN
        INSERT INTO lessons (level_id, title, description, sort_order, is_sample, estimated_minutes, status, version)
        VALUES (lvl_n3_id, 'Bài 59: Tự nhiên & Cuộc sống (自然と暮らし)', '2000 Từ vựng JLPT N3 cốt lõi từ JTest.net', 9, FALSE, 60, 'PUBLISHED', 0)
        RETURNING lesson_id INTO les_id;
    END IF;

    INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
    VALUES
      (les_id, '豊かな', 'ゆたかな', '豊かな', 'Phong phú, giàu có', 'Danh từ', 1, 'PUBLISHED'),
      (les_id, '資源', 'しげん', '資源', 'Nguồn tài nguyên', 'Danh từ', 2, 'PUBLISHED'),
      (les_id, '種類', 'しゅるい', '種類', 'Loại, chủng loại', 'Danh từ', 3, 'PUBLISHED'),
      (les_id, '枯れる', 'かれる', '枯れる', 'Héo, tàn', 'Danh từ', 4, 'PUBLISHED'),
      (les_id, '散る', 'ちる', '散る', 'Rơi, rụng', 'Danh từ', 5, 'PUBLISHED'),
      (les_id, '草', 'くさ', '草', 'Cỏ', 'Danh từ', 6, 'PUBLISHED'),
      (les_id, '種', 'たね', '種', 'Hạt, hạt giống', 'Danh từ', 7, 'PUBLISHED'),
      (les_id, '浮かぶ', 'うかぶ', '浮かぶ', 'Nổi, trôi; nảy ra (trong đầu)', 'Danh từ', 8, 'PUBLISHED'),
      (les_id, '太陽', 'たいよう', '太陽', 'Mặt trời', 'Danh từ', 9, 'PUBLISHED'),
      (les_id, '現れる', 'あらわれる', '現れる', 'Xuất hiện', 'Danh từ', 10, 'PUBLISHED'),
      (les_id, '沈む', 'しずむ', '沈む', 'Chìm, lặn', 'Danh từ', 11, 'PUBLISHED'),
      (les_id, '薄暗い', 'うすぐらい', '薄暗い', 'Tối mờ, nhập nhoạng tối', 'Danh từ', 12, 'PUBLISHED'),
      (les_id, '穴', 'あな', '穴', 'Lỗ, hang, hố', 'Danh từ', 13, 'PUBLISHED'),
      (les_id, '土', 'つち', '土', 'Đất', 'Danh từ', 14, 'PUBLISHED'),
      (les_id, '岩', 'いわ', '岩', 'Tảng đá, đá', 'Danh từ', 15, 'PUBLISHED'),
      (les_id, '丘', 'おか', '丘', 'Đồi', 'Danh từ', 16, 'PUBLISHED'),
      (les_id, '火山', 'かざん', '火山', 'Núi lửa', 'Danh từ', 17, 'PUBLISHED'),
      (les_id, '想像（する）', 'そうぞう（する）', '想像（する）', 'Sự tưởng tượng, tưởng tượng', 'Danh từ', 18, 'PUBLISHED'),
      (les_id, '見上げる', 'みあげる', '見上げる', 'Ngước nhìn lên', 'Danh từ', 19, 'PUBLISHED'),
      (les_id, '見下ろす', 'みおろす', '見下ろす', 'Nhìn xuống', 'Danh từ', 20, 'PUBLISHED'),
      (les_id, '予想（する）', 'よそう（する）', '予想（する）', 'Dự đoán', 'Danh từ', 21, 'PUBLISHED'),
      (les_id, '予報（する）', 'よほう（する）', '予報（する）', 'Dự báo', 'Danh từ', 22, 'PUBLISHED'),
      (les_id, '湿度', 'しつど', '湿度', 'Độ ẩm', 'Danh từ', 23, 'PUBLISHED'),
      (les_id, '湿気', 'しっけ', '湿気', 'Hơi ẩm, độ ẩm, ẩm ướt', 'Danh từ', 24, 'PUBLISHED'),
      (les_id, '嵐', 'あらし', '嵐', 'Bão, giông tố', 'Danh từ', 25, 'PUBLISHED'),
      (les_id, '強風', 'きょうふう', '強風', 'Gió to, gió mạnh', 'Danh từ', 26, 'PUBLISHED'),
      (les_id, '大雨', 'おおあめ', '大雨', 'Mưa to', 'Danh từ', 27, 'PUBLISHED'),
      (les_id, '折りたたみ傘', 'おりたたみがさ', '折りたたみ傘', 'O gấp, dù xếp', 'Danh từ', 28, 'PUBLISHED'),
      (les_id, '（傘を）さす', '（かさを）さす', '（傘を）さす', 'Che (ô), giương (ô)', 'Danh từ', 29, 'PUBLISHED'),
      (les_id, 'にわか雨', 'にわかあめ', 'にわか雨', 'Mưa rào', 'Danh từ', 30, 'PUBLISHED'),
      (les_id, '突然', 'とつぜん', '突然', 'Bỗng nhiên, đột nhiên', 'Danh từ', 31, 'PUBLISHED'),
      (les_id, 'あっという間', 'あっというま', 'あっという間', 'Chẳng mấy chốc, loáng một cái', 'Danh từ', 32, 'PUBLISHED'),
      (les_id, '止む', 'やむ', '止む', 'Tạnh, ngớt', 'Danh từ', 33, 'PUBLISHED'),
      (les_id, '積もる', 'つもる', '積もる', 'Tích tụ, chất đống, phủ', 'Danh từ', 34, 'PUBLISHED'),
      (les_id, '快晴', 'かいせい', '快晴', 'Trời trong xanh', 'Danh từ', 35, 'PUBLISHED'),
      (les_id, '当たる', 'あたる', '当たる', 'Trúng, đúng', 'Danh từ', 36, 'PUBLISHED'),
      (les_id, '蒸し暑い', 'むしあつい', '蒸し暑い', 'Nóng ẩm, oi bức', 'Danh từ', 37, 'PUBLISHED'),
      (les_id, '温度計', 'おんどけい', '温度計', 'Nhiệt kế', 'Danh từ', 38, 'PUBLISHED'),
      (les_id, '凍る', 'こおる', '凍る', 'Đóng băng', 'Danh từ', 39, 'PUBLISHED'),
      (les_id, '氷', 'こおり', '氷', 'Băng, đá', 'Danh từ', 40, 'PUBLISHED'),
      (les_id, '冷える', 'ひえる', '冷える', 'Lạnh, cóng', 'Danh từ', 41, 'PUBLISHED'),
      (les_id, '非常な', 'ひじょうな', '非常な', 'Phi thường, rất, cực kỳ', 'Danh từ', 42, 'PUBLISHED'),
      (les_id, '夏日', 'なつび', '夏日', 'Ngày hè nhiệt độ trên 25 độ', 'Danh từ', 43, 'PUBLISHED'),
      (les_id, '真夏日', 'まなつび', '真夏日', 'Ngày hè nóng trên 30 độ', 'Danh từ', 44, 'PUBLISHED'),
      (les_id, '猛暑日', 'もうしょび', '猛暑日', 'Ngày hè cực nóng trên 35 độ', 'Danh từ', 45, 'PUBLISHED'),
      (les_id, '冬日', 'ふゆび', '冬日', 'Ngày đông nhiệt độ thấp nhất dưới 0 độ', 'Danh từ', 46, 'PUBLISHED'),
      (les_id, '真冬日', 'まふゆび', '真冬日', 'Ngày đông hàn nhiệt độ cao nhất dưới 0 độ', 'Danh từ', 47, 'PUBLISHED'),
      (les_id, '暖冬', 'だんとう', '暖冬', 'Mùa đông ấm', 'Danh từ', 48, 'PUBLISHED'),
      (les_id, '冷夏', 'れいか', '冷夏', 'Mùa hè mát', 'Danh từ', 49, 'PUBLISHED'),
      (les_id, '状態', 'じょうたい', '状態', 'Trạng thái, tình trạng', 'Danh từ', 50, 'PUBLISHED'),
      (les_id, '変化（する）', 'へんか（する）', '変化（する）', 'Sự thay đổi, sự biến đổi', 'Danh từ', 51, 'PUBLISHED'),
      (les_id, '一定（する）', 'いってい（する）', '一定（する）', 'Cố định, nhất định, ổn định', 'Danh từ', 52, 'PUBLISHED'),
      (les_id, '観察（する）', 'かんさつ（する）', '観察（する）', 'Sự quan sát', 'Danh từ', 53, 'PUBLISHED'),
      (les_id, '次第に', 'しだいに', '次第に', 'Dần dần', 'Danh từ', 54, 'PUBLISHED'),
      (les_id, '一気に', 'いっきに', '一気に', 'Một mạch, một lèo', 'Danh từ', 55, 'PUBLISHED'),
      (les_id, '一度に', 'いちどに', '一度に', 'Cùng một lúc, đồng loạt', 'Danh từ', 56, 'PUBLISHED'),
      (les_id, 'いつの間にか', 'いつのまにか', 'いつの間にか', 'Lúc nào không hay', 'Danh từ', 57, 'PUBLISHED'),
      (les_id, '温暖化', 'おんだんか', '温暖化', 'Sự nóng lên toàn cầu, hiện tượng ấm dần', 'Danh từ', 58, 'PUBLISHED'),
      (les_id, '変な', 'へんな', '変な', 'Lạ, kỳ lạ, bất thường', 'Danh từ', 59, 'PUBLISHED'),
      (les_id, '祝日', 'しゅくじつ', '祝日', 'Ngày nghỉ lễ', 'Danh từ', 60, 'PUBLISHED'),
      (les_id, '年末年始', 'ねんまつねんし', '年末年始', 'Cuối năm đầu năm', 'Danh từ', 61, 'PUBLISHED'),
      (les_id, '元日', 'がんじつ', '元日', 'Ngày mùng một Tết', 'Danh từ', 62, 'PUBLISHED'),
      (les_id, '迎える', 'むかえる', '迎える', 'Đón, chào đón', 'Danh từ', 63, 'PUBLISHED'),
      (les_id, '年賀状', 'ねんがじょう', '年賀状', 'Thiếp chúc mừng năm mới', 'Danh từ', 64, 'PUBLISHED'),
      (les_id, 'お年玉', 'おとしだま', 'お年玉', 'Tiền mừng tuổi', 'Danh từ', 65, 'PUBLISHED'),
      (les_id, '成人の日', 'せいじんのひ', '成人の日', 'Ngày lễ Thành nhân', 'Danh từ', 66, 'PUBLISHED'),
      (les_id, 'ひな祭り', 'ひなまつり', 'ひな祭り', 'Lễ hội búp bê Hina', 'Danh từ', 67, 'PUBLISHED'),
      (les_id, '子どもの日', 'こどものひ', '子どもの日', 'Ngày Trẻ em', 'Danh từ', 68, 'PUBLISHED'),
      (les_id, '母の日', 'ははのひ', '母の日', 'Ngày của Mẹ', 'Danh từ', 69, 'PUBLISHED'),
      (les_id, '父の日', 'ちちのひ', '父の日', 'Ngày của Bố', 'Danh từ', 70, 'PUBLISHED'),
      (les_id, '海の日', 'うみのひ', '海の日', 'Ngày của Biển', 'Danh từ', 71, 'PUBLISHED'),
      (les_id, '敬老の日', 'けいろうのひ', '敬老の日', 'Ngày Kính lão', 'Danh từ', 72, 'PUBLISHED'),
      (les_id, '体育の日', 'たいいくのひ', '体育の日', 'Ngày Thể dục thể thao', 'Danh từ', 73, 'PUBLISHED'),
      (les_id, '七五三', 'しちごさん', '七五三', 'Lễ Thất Ngũ Tam (lễ mừng trẻ 3, 5, 7 tuổi)', 'Danh từ', 74, 'PUBLISHED'),
      (les_id, '大みそか', 'おおみそか', '大みそか', 'Đêm giao thừa', 'Danh từ', 75, 'PUBLISHED');

    -- Chapter 10: Bài 60: Tin tức thời sự (ニュースで学ぼう！) (74 từ)
    SELECT lesson_id INTO les_id FROM lessons WHERE level_id = lvl_n3_id AND sort_order = 10;
    IF les_id IS NULL THEN
        INSERT INTO lessons (level_id, title, description, sort_order, is_sample, estimated_minutes, status, version)
        VALUES (lvl_n3_id, 'Bài 60: Tin tức thời sự (ニュースで学ぼう！)', '2000 Từ vựng JLPT N3 cốt lõi từ JTest.net', 10, FALSE, 60, 'PUBLISHED', 0)
        RETURNING lesson_id INTO les_id;
    END IF;

    INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
    VALUES
      (les_id, '伝わる', 'つたわる', '伝わる', 'Được truyền đi', 'Danh từ', 1, 'PUBLISHED'),
      (les_id, '記事', 'きじ', '記事', 'Bài, bài báo', 'Danh từ', 2, 'PUBLISHED'),
      (les_id, '週刊誌', 'しゅうかんし', '週刊誌', 'Tuần báo', 'Danh từ', 3, 'PUBLISHED'),
      (les_id, '政治家', 'せいじか', '政治家', 'Chính trị gia', 'Danh từ', 4, 'PUBLISHED'),
      (les_id, '政府', 'せいふ', '政府', 'Chính phủ', 'Danh từ', 5, 'PUBLISHED'),
      (les_id, '市民', 'しみん', '市民', 'Người dân, công dân', 'Danh từ', 6, 'PUBLISHED'),
      (les_id, '立場', 'たちば', '立場', 'Lập trường, vị trí', 'Danh từ', 7, 'PUBLISHED'),
      (les_id, '世の中', 'よのなか', '世の中', 'Thế gian, xã hội', 'Danh từ', 8, 'PUBLISHED'),
      (les_id, '重大な', 'じゅうだいな', '重大な', 'Rất quan trọng, trọng đại', 'Danh từ', 9, 'PUBLISHED'),
      (les_id, '重要な', 'じゅうような', '重要な', 'Quan trọng', 'Danh từ', 10, 'PUBLISHED'),
      (les_id, '大して', 'たいして', '大して', 'Không ... lắm, không ... mấy', 'Danh từ', 11, 'PUBLISHED'),
      (les_id, '司会者', 'しかいしゃ', '司会者', 'Người dẫn chương trình, MC', 'Danh từ', 12, 'PUBLISHED'),
      (les_id, '生放送', 'なまほうそう', '生放送', 'Truyền hình trực tiếp, phát sóng trực tiếp', 'Danh từ', 13, 'PUBLISHED'),
      (les_id, '商品', 'しょうひん', '商品', 'Sản phẩm, hàng hóa', 'Danh từ', 14, 'PUBLISHED'),
      (les_id, '発売（する）', 'はつばい（する）', '発売（する）', 'Bán ra, bắt đầu bán, phát hành', 'Danh từ', 15, 'PUBLISHED'),
      (les_id, '評判', 'ひょうばん', '評判', 'Danh tiếng, tiếng tăm', 'Danh từ', 16, 'PUBLISHED'),
      (les_id, '注目（する）', 'ちゅうもく（する）', '注目（する）', 'Chú ý, dồn sự chú ý', 'Danh từ', 17, 'PUBLISHED'),
      (les_id, '結局', 'けっきょく', '結局', 'Kết cục, cuối cùng', 'Danh từ', 18, 'PUBLISHED'),
      (les_id, '怪しい', 'あやしい', '怪しい', 'Khả nghi, đáng ngờ', 'Danh từ', 19, 'PUBLISHED'),
      (les_id, '恐ろしい', 'おそろしい', '恐ろしい', 'Đáng sợ, khủng khiếp', 'Danh từ', 20, 'PUBLISHED'),
      (les_id, '暴れる', 'あばれる', '暴れる', 'Đập phá, quậy phá', 'Danh từ', 21, 'PUBLISHED'),
      (les_id, '争う', 'あらそう', '争う', 'Tranh cãi, đấu tranh, tranh giành', 'Danh từ', 22, 'PUBLISHED'),
      (les_id, '犯罪', 'はんざい', '犯罪', 'Tội phạm, tội ác', 'Danh từ', 23, 'PUBLISHED'),
      (les_id, '発見者', 'はっけんしゃ', '発見者', 'Người phát hiện', 'Danh từ', 24, 'PUBLISHED'),
      (les_id, '疑う', 'うたがう', '疑う', 'Nghi ngờ, hoài nghi', 'Danh từ', 25, 'PUBLISHED'),
      (les_id, '犯人', 'はんにん', '犯人', 'Phạm nhân, thủ phạm', 'Danh từ', 26, 'PUBLISHED'),
      (les_id, '盗む', 'ぬすむ', '盗む', 'Ăn trộm, ăn cắp', 'Danh từ', 27, 'PUBLISHED'),
      (les_id, '捜す', 'さがす', '捜す', 'Tìm kiếm, lùng tìm', 'Danh từ', 28, 'PUBLISHED'),
      (les_id, '追う', 'おう', '追う', 'Đuổi theo, truy đuổi', 'Danh từ', 29, 'PUBLISHED'),
      (les_id, '捕まえる', 'つかまえる', '捕まえる', 'Bắt, tóm', 'Danh từ', 30, 'PUBLISHED'),
      (les_id, '捕まる', 'つかまる', '捕まる', 'Bị bắt', 'Danh từ', 31, 'PUBLISHED'),
      (les_id, '逮捕（する）', 'たいほ（する）', '逮捕（する）', 'Bắt giữ, bắt giam', 'Danh từ', 32, 'PUBLISHED'),
      (les_id, '気味が悪い', 'きみがわるい', '気味が悪い', 'Rùng rợn, cảm thấy ghê ghê', 'Danh từ', 33, 'PUBLISHED'),
      (les_id, '（事故に）あう', '（じこに）あう', '（事故に）あう', 'Gặp (tai nạn)', 'Danh từ', 34, 'PUBLISHED'),
      (les_id, '発生（する）', 'はっせい（する）', '発生（する）', 'Phát sinh, xảy ra', 'Danh từ', 35, 'PUBLISHED'),
      (les_id, '命', 'いのち', '命', 'Mạng sống, tính mạng', 'Danh từ', 36, 'PUBLISHED'),
      (les_id, '救う', 'すくう', '救う', 'Cứu, cứu giúp', 'Danh từ', 37, 'PUBLISHED'),
      (les_id, '現場', 'げんば', '現場', 'Hiện trường, công trường', 'Danh từ', 38, 'PUBLISHED'),
      (les_id, '混乱（する）', 'こんらん（する）', '混乱（する）', 'Sự hỗn loạn, náo loạn', 'Danh từ', 39, 'PUBLISHED'),
      (les_id, '無事（な）', 'ぶじ（な）', '無事（な）', 'Sự an toàn, bình an vô sự (an toàn, bình an)', 'Danh từ', 40, 'PUBLISHED'),
      (les_id, '防ぐ', 'ふせぐ', '防ぐ', 'Ngăn chặn, phòng ngừa', 'Danh từ', 41, 'PUBLISHED'),
      (les_id, '再び', 'ふたたび', '再び', 'Lại, một lần nữa', 'Danh từ', 42, 'PUBLISHED'),
      (les_id, '被害者', 'ひがいしゃ', '被害者', 'Nạn nhân, người bị hại', 'Danh từ', 43, 'PUBLISHED'),
      (les_id, '[お]互いに', '[お]たがいに', '[お]互いに', 'Lẫn nhau, với nhau', 'Danh từ', 44, 'PUBLISHED'),
      (les_id, '疑問', 'ぎもん', '疑問', 'Nghi vấn, thắc mắc', 'Danh từ', 45, 'PUBLISHED'),
      (les_id, '飛び込む', 'とびこむ', '飛び込む', 'Nhảy vào, lao vào', 'Danh từ', 46, 'PUBLISHED'),
      (les_id, '飛び出す', 'とびだす', '飛び出す', 'Lao ra, nhảy ra', 'Danh từ', 47, 'PUBLISHED'),
      (les_id, '行方不明', 'ゆくえふめい', '行方不明', 'Mất tích', 'Danh từ', 48, 'PUBLISHED'),
      (les_id, '亡くなる', 'なくなる', '亡くなる', 'Qua đời, mất', 'Danh từ', 49, 'PUBLISHED'),
      (les_id, '偶然', 'ぐうぜん', '偶然', 'Ngẫu nhiên, tình cờ', 'Danh từ', 50, 'PUBLISHED'),
      (les_id, '苦情', 'くじょう', '苦情', 'Kêu ca, phàn nàn', 'Danh từ', 51, 'PUBLISHED'),
      (les_id, '迷子', 'まいご', '迷子', 'Trẻ lạc, sự đi lạc', 'Danh từ', 52, 'PUBLISHED'),
      (les_id, '場合', 'ばあい', '場合', 'Trường hợp', 'Danh từ', 53, 'PUBLISHED'),
      (les_id, '落とす', 'おとす', '落とす', 'Đánh rơi', 'Danh từ', 54, 'PUBLISHED'),
      (les_id, '借金（する）', 'しゃっきん（する）', '借金（する）', 'Sự vay tiền, tiền nợ', 'Danh từ', 55, 'PUBLISHED'),
      (les_id, '倒れる', 'たおれる', '倒れる', 'Đổ, ngã quỵ, đổ bệnh', 'Danh từ', 56, 'PUBLISHED'),
      (les_id, '転ぶ', 'ころぶ', '転ぶ', 'Bị ngã, vấp ngã', 'Danh từ', 57, 'PUBLISHED'),
      (les_id, '（会社が）つぶれる', '（かいしゃが）つぶれる', '（会社が）つぶれる', 'Bị dập nát; (công ty) bị phá sản', 'Danh từ', 58, 'PUBLISHED'),
      (les_id, '次々[と]', 'つぎつぎ [と]', '次々[と]', 'Liên tiếp, lần lượt', 'Danh từ', 59, 'PUBLISHED'),
      (les_id, '停電（する）', 'ていでん（する）', '停電（する）', 'Sự mất điện, cúp điện', 'Danh từ', 60, 'PUBLISHED'),
      (les_id, '断水（する）', 'だんすい（する）', '断水（する）', 'Sự mất nước, cúp nước', 'Danh từ', 61, 'PUBLISHED'),
      (les_id, '非常口', 'ひじょうぐち', '非常口', 'Lối thoát hiểm', 'Danh từ', 62, 'PUBLISHED'),
      (les_id, '増加（する）', 'ぞうか（する）', '増加（する）', 'Sự gia tăng, tăng lên', 'Danh từ', 63, 'PUBLISHED'),
      (les_id, '減少（する）', 'げんしょう（する）', '減少（する）', 'Sự giảm sút, giảm đi', 'Danh từ', 64, 'PUBLISHED'),
      (les_id, '超える', 'こえる', '超える', 'Vượt qua, vượt quá', 'Danh từ', 65, 'PUBLISHED'),
      (les_id, '越える', 'こえる', '越える', 'Vượt qua, đi qua', 'Danh từ', 66, 'PUBLISHED'),
      (les_id, '全体', 'ぜんたい', '全体', 'Toàn bộ, toàn thể', 'Danh từ', 67, 'PUBLISHED'),
      (les_id, '信用（する）', 'しんよう（する）', '信用（する）', 'Sự tin tưởng, tin dùng', 'Danh từ', 68, 'PUBLISHED'),
      (les_id, '失う', 'うしなう', '失う', 'Đánh mất, mất đi', 'Danh từ', 69, 'PUBLISHED'),
      (les_id, '正常（な）', 'せいじょう（な）', '正常（な）', 'Bình thường, chính thường', 'Danh từ', 70, 'PUBLISHED'),
      (les_id, '不景気（な）', 'ふけいき（な）', '不景気（な）', 'Tình trạng kinh tế suy thoái, ế ẩm', 'Danh từ', 71, 'PUBLISHED'),
      (les_id, '円高', 'えんだか', '円高', 'Đồng yên tăng giá', 'Danh từ', 72, 'PUBLISHED'),
      (les_id, '平均（する）', 'へいきん（する）', '平均（する）', 'Trung bình, bình quân', 'Danh từ', 73, 'PUBLISHED'),
      (les_id, '最も', 'もっとも', '最も', 'Nhất, nhiều nhất', 'Danh từ', 74, 'PUBLISHED');

    -- Chapter 11: Bài 61: Cảm xúc & Tâm trạng (気持ちを伝えよう！) (64 từ)
    SELECT lesson_id INTO les_id FROM lessons WHERE level_id = lvl_n3_id AND sort_order = 11;
    IF les_id IS NULL THEN
        INSERT INTO lessons (level_id, title, description, sort_order, is_sample, estimated_minutes, status, version)
        VALUES (lvl_n3_id, 'Bài 61: Cảm xúc & Tâm trạng (気持ちを伝えよう！)', '2000 Từ vựng JLPT N3 cốt lõi từ JTest.net', 11, FALSE, 60, 'PUBLISHED', 0)
        RETURNING lesson_id INTO les_id;
    END IF;

    INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
    VALUES
      (les_id, '個性', 'こせい', '個性', 'Cá tính', 'Danh từ', 1, 'PUBLISHED'),
      (les_id, '働き者', 'はたらきもの', '働き者', 'Người chăm làm, người hay lam hay làm', 'Danh từ', 2, 'PUBLISHED'),
      (les_id, '正直（な）', 'しょうじき（な）', '正直（な）', 'Thật thà, trung thực', 'Danh từ', 3, 'PUBLISHED'),
      (les_id, '素直な', 'すなおな', '素直な', 'Ngoan ngoãn, dễ bảo, thật thà', 'Danh từ', 4, 'PUBLISHED'),
      (les_id, '積極的な', 'せっきょくてきな', '積極的な', 'Tích cực, chủ động', 'Danh từ', 5, 'PUBLISHED'),
      (les_id, '消極的な', 'しょうきょくてきな', '消極的な', 'Thụ động, tiêu cực', 'Danh từ', 6, 'PUBLISHED'),
      (les_id, '人なつこい', 'ひとなつこい', '人なつこい', 'Dễ làm thân, dễ mến, thân thiện', 'Danh từ', 7, 'PUBLISHED'),
      (les_id, 'のん気な', 'のんきな', 'のん気な', 'Ung dung, vô tư, đủng đỉnh', 'Danh từ', 8, 'PUBLISHED'),
      (les_id, '意地悪（な）', 'いじわる（な）', '意地悪（な）', 'Ác ý, xấu tính, ý địa xấu', 'Danh từ', 9, 'PUBLISHED'),
      (les_id, '勝手（な）', 'かって（な）', '勝手（な）', 'Tự tiện, tùy tiện', 'Danh từ', 10, 'PUBLISHED'),
      (les_id, '図々しい', 'ずうずうしい', '図々しい', 'Trơ trẽn, dày mặt, trâng tráo', 'Danh từ', 11, 'PUBLISHED'),
      (les_id, '生意気（な）', 'なまいき（な）', '生意気（な）', 'Xấc láo, hỗn láo, hỗn xược', 'Danh từ', 12, 'PUBLISHED'),
      (les_id, '鋭い', 'するどい', '鋭い', 'Sắc, nhạy bén, tinh tường', 'Danh từ', 13, 'PUBLISHED'),
      (les_id, '鈍い', 'にぶい', '鈍い', 'Cùn, chậm chạp, đần độn', 'Danh từ', 14, 'PUBLISHED'),
      (les_id, '単純（な）', 'たんじゅん（な）', '単純（な）', 'Đơn giản, chất phác', 'Danh từ', 15, 'PUBLISHED'),
      (les_id, '欠点', 'けってん', '欠点', 'Khuyết điểm', 'Danh từ', 16, 'PUBLISHED'),
      (les_id, '器用な', 'きような', '器用な', 'Khéo léo, khéo tay', 'Danh từ', 17, 'PUBLISHED'),
      (les_id, '感情', 'かんじょう', '感情', 'Cảm xúc', 'Danh từ', 18, 'PUBLISHED'),
      (les_id, '落ち着く', 'おちつく', '落ち着く', 'Bình tĩnh, bình yên', 'Danh từ', 19, 'PUBLISHED'),
      (les_id, '感激（する）', 'かんげき（する）', '感激（する）', 'Sự cảm kích, xúc động sâu sắc', 'Danh từ', 20, 'PUBLISHED'),
      (les_id, '感動（する）', 'かんどう（する）', '感動（する）', 'Sự cảm động', 'Danh từ', 21, 'PUBLISHED'),
      (les_id, '感心（する）', 'かんしん（する）', '感心（する）', 'Sự cảm phục, khâm phục', 'Danh từ', 22, 'PUBLISHED'),
      (les_id, '気軽な', 'きがるな', '気軽な', 'Thoải mái, không dè dặt', 'Danh từ', 23, 'PUBLISHED'),
      (les_id, '気楽な', 'きらくな', '気楽な', 'Thoải mái, thanh thản', 'Danh từ', 24, 'PUBLISHED'),
      (les_id, '幸せ（な）', 'しあわせ（な）', '幸せ（な）', 'Hạnh phúc', 'Danh từ', 25, 'PUBLISHED'),
      (les_id, '冗談', 'じょうだん', '冗談', 'Đùa, nói đùa', 'Danh từ', 26, 'PUBLISHED'),
      (les_id, '愛する', 'あいする', '愛する', 'Yêu, yêu thương', 'Danh từ', 27, 'PUBLISHED'),
      (les_id, '真剣な', 'しんけんな', '真剣な', 'Nghiêm túc, chân thành', 'Danh từ', 28, 'PUBLISHED'),
      (les_id, '夢中（な）', 'むちゅう（な）', '夢中（な）', 'Say mê, say sưa, mải mê', 'Danh từ', 29, 'PUBLISHED'),
      (les_id, '勇気', 'ゆうき', '勇気', 'Lòng dũng cảm, can đảm', 'Danh từ', 30, 'PUBLISHED'),
      (les_id, '嫌がる', 'いやがる', '嫌がる', 'Tỏ ra ghét, miễn cưỡng', 'Danh từ', 31, 'PUBLISHED'),
      (les_id, '落ち込む', 'おちこむ', '落ち込む', 'Buồn, thất vọng', 'Danh từ', 32, 'PUBLISHED'),
      (les_id, '悲しむ', 'かなしむ', '悲しむ', 'Đau buồn', 'Danh từ', 33, 'PUBLISHED'),
      (les_id, '気の毒な', 'きのどくな', '気の毒な', 'Tội nghiệp, đáng thương', 'Danh từ', 34, 'PUBLISHED'),
      (les_id, '恐怖', 'きょうふ', '恐怖', 'Nỗi sợ hãi', 'Danh từ', 35, 'PUBLISHED'),
      (les_id, '後悔（する）', 'こうかい（する）', '後悔（する）', 'Sự hối hận, ân hận', 'Danh từ', 36, 'PUBLISHED'),
      (les_id, '悩む', 'なやむ', '悩む', 'Trăn trở, phiền muộn', 'Danh từ', 37, 'PUBLISHED'),
      (les_id, '悩み', 'なやみ', '悩み', 'Điều trăn trở, nỗi lo', 'Danh từ', 38, 'PUBLISHED'),
      (les_id, '不安（な）', 'ふあん（な）', '不安（な）', 'Sự bất an (bất an, lo lắng)', 'Danh từ', 39, 'PUBLISHED'),
      (les_id, '迷惑（な/する）', 'めいわく（な/する）', '迷惑（な/する）', 'Sự phiền phức, phiền toái', 'Danh từ', 40, 'PUBLISHED'),
      (les_id, '面倒（な）', 'めんどう（な）', '面倒（な）', 'Sự chăm sóc, trông nom, sự phiền phức, khó khăn (phiền)', 'Danh từ', 41, 'PUBLISHED'),
      (les_id, '面倒くさい', 'めんどうくさい', '面倒くさい', 'Phiền phức, ngại', 'Danh từ', 42, 'PUBLISHED'),
      (les_id, '心から', 'こころから', '心から', 'Tự đáy lòng, chân thành', 'Danh từ', 43, 'PUBLISHED'),
      (les_id, '祈る', 'いのる', '祈る', 'Cầu nguyện, cầu mong', 'Danh từ', 44, 'PUBLISHED'),
      (les_id, '希望（する）', 'きぼう（する）', '希望（する）', 'Hy vọng, mong muốn', 'Danh từ', 45, 'PUBLISHED'),
      (les_id, '願う', 'ねがう', '願う', 'Cầu mong, cầu nguyện', 'Danh từ', 46, 'PUBLISHED'),
      (les_id, '願い', 'ねがい', '願い', 'Lời cầu nguyện, điều ước', 'Danh từ', 47, 'PUBLISHED'),
      (les_id, '感じる', 'かんじる', '感じる', 'Cảm nhận, cảm thấy', 'Danh từ', 48, 'PUBLISHED'),
      (les_id, '案外', 'あんがい', '案外', 'Không ngờ, ngoài dự đoán', 'Danh từ', 49, 'PUBLISHED'),
      (les_id, '表現（する）', 'ひょうげん（する）', '表現（する）', 'Sự diễn đạt, thể hiện, cách nói; diễn đạt', 'Danh từ', 50, 'PUBLISHED'),
      (les_id, '表現（する）', 'ひょうげん（する）', '表現（する）', 'Sự diễn đạt, thể hiện, cách nói; diễn đạt', 'Danh từ', 51, 'PUBLISHED'),
      (les_id, '我慢（する）', 'がまん（する）', '我慢（する）', 'Sự chịu đựng, kiên nhẫn; chịu đựng, nhẫn nhịn', 'Danh từ', 52, 'PUBLISHED'),
      (les_id, '自慢（する）', 'じまん（する）', '自慢（する）', 'Sự tự hào, hãnh diện; khoe khoang', 'Danh từ', 53, 'PUBLISHED'),
      (les_id, '関心', 'かんしん', '関心', 'Sự quan tâm, mối quan tâm', 'Danh từ', 54, 'PUBLISHED'),
      (les_id, '機嫌', 'きげん', '機嫌', 'Tâm trạng, tính khí', 'Danh từ', 55, 'PUBLISHED'),
      (les_id, '平気（な）', 'へいき（な）', '平気（な）', 'Bình thản, không sao, không ngại', 'Danh từ', 56, 'PUBLISHED'),
      (les_id, '本気（な）', 'ほんき（な）', '本気（な）', 'Sự nghiêm túc, thật lòng; nghiêm túc, thật sự', 'Danh từ', 57, 'PUBLISHED'),
      (les_id, '迷う', 'まよう', '迷う', 'Lạc (đường); phân vân, do dự, lưỡng lự', 'Danh từ', 58, 'PUBLISHED'),
      (les_id, '迷い', 'まよい', '迷い', 'Sự phân vân, do dự, lưỡng lự', 'Danh từ', 59, 'PUBLISHED'),
      (les_id, '微妙な', 'びみょうな', '微妙な', 'Tế nhị, khó nói, mơ hồ, khó tả', 'Danh từ', 60, 'PUBLISHED'),
      (les_id, '魅力', 'みりょく', '魅力', 'Sức hấp dẫn, sức quyến rũ, vẻ thu hút', 'Danh từ', 61, 'PUBLISHED'),
      (les_id, '本音', 'ほんね', '本音', 'Suy nghĩ thực, lòng thật, tâm tư thật', 'Danh từ', 62, 'PUBLISHED'),
      (les_id, '涙', 'なみだ', '涙', 'Nước mắt', 'Danh từ', 63, 'PUBLISHED'),
      (les_id, '憎む', 'にくむ', '憎む', 'Hận, căm ghét, thù ghét', 'Danh từ', 64, 'PUBLISHED');

    -- Chapter 12: Bài 62: Ấn tượng & Xã hội (イメージを伝えよう！) (78 từ)
    SELECT lesson_id INTO les_id FROM lessons WHERE level_id = lvl_n3_id AND sort_order = 12;
    IF les_id IS NULL THEN
        INSERT INTO lessons (level_id, title, description, sort_order, is_sample, estimated_minutes, status, version)
        VALUES (lvl_n3_id, 'Bài 62: Ấn tượng & Xã hội (イメージを伝えよう！)', '2000 Từ vựng JLPT N3 cốt lõi từ JTest.net', 12, FALSE, 60, 'PUBLISHED', 0)
        RETURNING lesson_id INTO les_id;
    END IF;

    INSERT INTO vocabulary (lesson_id, word, kana, kanji_form, meaning_vi, part_of_speech, sort_order, status)
    VALUES
      (les_id, '模様', 'もよう', '模様', 'Hoa văn, họa tiết', 'Danh từ', 1, 'PUBLISHED'),
      (les_id, '特徴', 'とくちょう', '特徴', 'Đặc điểm, đặc trưng', 'Danh từ', 2, 'PUBLISHED'),
      (les_id, '特色', 'とくしょく', '特色', 'Điểm đặc sắc, nét riêng', 'Danh từ', 3, 'PUBLISHED'),
      (les_id, '柄', 'がら', '柄', 'Hoa văn, họa tiết', 'Danh từ', 4, 'PUBLISHED'),
      (les_id, '花柄', 'はながら', '花柄', 'Họa tiết hoa', 'Danh từ', 5, 'PUBLISHED'),
      (les_id, '水玉', 'みずたま', '水玉', 'Chấm bi', 'Danh từ', 6, 'PUBLISHED'),
      (les_id, '横', 'よこ', '横', 'Chiều ngang, bên cạnh', 'Danh từ', 7, 'PUBLISHED'),
      (les_id, '幅', 'はば', '幅', 'Bề ngang, chiều rộng', 'Danh từ', 8, 'PUBLISHED'),
      (les_id, '無地', 'むじ', '無地', 'Trơn, không có họa tiết', 'Danh từ', 9, 'PUBLISHED'),
      (les_id, '真っ赤な', 'まっかな', '真っ赤な', 'Đỏ rực, đỏ chót', 'Danh từ', 10, 'PUBLISHED'),
      (les_id, '素敵な', 'すてきな', '素敵な', 'Tuyệt vời, đẹp, tuyệt', 'Danh từ', 11, 'PUBLISHED'),
      (les_id, '印象', 'いんしょう', '印象', 'Ấn tượng', 'Danh từ', 12, 'PUBLISHED'),
      (les_id, '外見', 'がいけん', '外見', 'Ngoại hình, vẻ bề ngoài', 'Danh từ', 13, 'PUBLISHED'),
      (les_id, '様子', 'ようす', '様子', 'Tình hình, dáng vẻ, bộ dạng', 'Danh từ', 14, 'PUBLISHED'),
      (les_id, '表情', 'ひょうじょう', '表情', 'Biểu cảm, nét mặt', 'Danh từ', 15, 'PUBLISHED'),
      (les_id, '姿', 'すがた', '姿', 'Dáng, bóng dáng', 'Danh từ', 16, 'PUBLISHED'),
      (les_id, '雰囲気', 'ふんいき', '雰囲気', 'Bầu không khí, phong thái', 'Danh từ', 17, 'PUBLISHED'),
      (les_id, '幼い', 'おさない', '幼い', 'Thơ ấu, ngây thơ, trẻ con', 'Danh từ', 18, 'PUBLISHED'),
      (les_id, '言葉づかい', 'ことばづかい', '言葉づかい', 'Cách ăn nói, cách dùng từ ngữ', 'Danh từ', 19, 'PUBLISHED'),
      (les_id, '上品な', 'じょうひんな', '上品な', 'Thanh lịch, nhã nhặn', 'Danh từ', 20, 'PUBLISHED'),
      (les_id, '下品な', 'げひんな', '下品な', 'Thô tục, hạ lưu', 'Danh từ', 21, 'PUBLISHED'),
      (les_id, '地味な', 'じみな', '地味な', 'Giản dị, mộc mạc', 'Danh từ', 22, 'PUBLISHED'),
      (les_id, '派手な', 'はでな', '派手な', 'Lòe loẹt, sặc sỡ', 'Danh từ', 23, 'PUBLISHED'),
      (les_id, '美人', 'びじん', '美人', 'Người đẹp, mỹ nhân', 'Danh từ', 24, 'PUBLISHED'),
      (les_id, '不思議（な）', 'ふしぎ（な）', '不思議（な）', 'Kỳ lạ, huyền bí', 'Danh từ', 25, 'PUBLISHED'),
      (les_id, '普通（な）', 'ふつう（な）', '普通（な）', 'Bình thường, phổ thông', 'Danh từ', 26, 'PUBLISHED'),
      (les_id, '表面', 'ひょうめん', '表面', 'Bề mặt, bề ngoài', 'Danh từ', 27, 'PUBLISHED'),
      (les_id, '立派な', 'りっぱな', '立派な', 'Hoành tráng, xuất sắc', 'Danh từ', 28, 'PUBLISHED'),
      (les_id, '目立つ', 'めだつ', '目立つ', 'Nổi bật', 'Danh từ', 29, 'PUBLISHED'),
      (les_id, '異なる', 'ことなる', '異なる', 'Khác, khác nhau', 'Danh từ', 30, 'PUBLISHED'),
      (les_id, '大型', 'おおがた', '大型', 'Cỡ lớn', 'Danh từ', 31, 'PUBLISHED'),
      (les_id, '多め（な）', 'おおめ（な）', '多め（な）', 'Hơi nhiều (một chút)', 'Danh từ', 32, 'PUBLISHED'),
      (les_id, '大きめ（な）', 'おおきめ（な）', '大きめ（な）', 'Hơi to, hơi lớn (một chút)', 'Danh từ', 33, 'PUBLISHED'),
      (les_id, '太め（な）', 'ふとめ（な）', '太め（な）', 'Hơi dày, hơi rộng (một chút)', 'Danh từ', 34, 'PUBLISHED'),
      (les_id, '完ぺき（な）', 'かんぺき（な）', '完ぺき（な）', 'Hoàn hảo, không thể chê vào đâu được', 'Danh từ', 35, 'PUBLISHED'),
      (les_id, '多少', 'たしょう', '多少', 'Ít nhiều, đôi chút', 'Danh từ', 36, 'PUBLISHED'),
      (les_id, '縮む', 'ちぢむ', '縮む', 'Bị co rút, co lại', 'Danh từ', 37, 'PUBLISHED'),
      (les_id, '現代', 'げんだい', '現代', 'Hiện đại', 'Danh từ', 38, 'PUBLISHED'),
      (les_id, '現実', 'げんじつ', '現実', 'Hiện thực', 'Danh từ', 39, 'PUBLISHED'),
      (les_id, '理想', 'りそう', '理想', 'Lý tưởng', 'Danh từ', 40, 'PUBLISHED'),
      (les_id, '偉大な', 'いだいな', '偉大な', 'Vĩ đại', 'Danh từ', 41, 'PUBLISHED'),
      (les_id, '当然（な）', 'とうぜん（な）', '当然（な）', 'Đương nhiên', 'Danh từ', 42, 'PUBLISHED'),
      (les_id, '当たり前（な）', 'あたりまえ（な）', '当たり前（な）', 'Sự đương nhiên (đương nhiên)', 'Danh từ', 43, 'PUBLISHED'),
      (les_id, '[お]金持ち', '[お]かねもち', '[お]金持ち', 'Người giàu, giàu', 'Danh từ', 44, 'PUBLISHED'),
      (les_id, '貧しい', 'まずしい', '貧しい', 'Nghèo', 'Danh từ', 45, 'PUBLISHED'),
      (les_id, '貧乏（な/する）', 'びんぼう（な/する）', '貧乏（な/する）', 'Sự nghèo khổ (nghèo)', 'Danh từ', 46, 'PUBLISHED'),
      (les_id, '発展（する）', 'はってん（する）', '発展（する）', 'Sự phát triển', 'Danh từ', 47, 'PUBLISHED'),
      (les_id, '進歩（する）', 'しんぽ（する）', '進歩（する）', 'Sự tiến bộ', 'Danh từ', 48, 'PUBLISHED'),
      (les_id, '強力な', 'きょうりょくな', '強力な', 'Mạnh mẽ', 'Danh từ', 49, 'PUBLISHED'),
      (les_id, '経つ', 'たつ', '経つ', 'Trôi qua', 'Danh từ', 50, 'PUBLISHED'),
      (les_id, '前後', 'ぜんご', '前後', 'Trước sau, khoảng', 'Danh từ', 51, 'PUBLISHED'),
      (les_id, '盛んな', 'さかんな', '盛んな', 'Rầm rộ, thịnh vượng, phát triển', 'Danh từ', 52, 'PUBLISHED'),
      (les_id, '産業', 'さんぎょう', '産業', 'Ngành sản xuất, công nghiệp', 'Danh từ', 53, 'PUBLISHED'),
      (les_id, '工業', 'こうぎょう', '工業', 'Công nghiệp', 'Danh từ', 54, 'PUBLISHED'),
      (les_id, '商業', 'しょうぎょう', '商業', 'Thương nghiệp, thương mại', 'Danh từ', 55, 'PUBLISHED'),
      (les_id, '農業', 'のうぎょう', '農業', 'Nông nghiệp', 'Danh từ', 56, 'PUBLISHED'),
      (les_id, '語る', 'かたる', '語る', 'Kể, thuật lại', 'Danh từ', 57, 'PUBLISHED'),
      (les_id, '解消（する）', 'かいしょう（する）', '解消（する）', 'Sự giải quyết, giải tỏa', 'Danh từ', 58, 'PUBLISHED'),
      (les_id, '片方', 'かたほう', '片方', 'Một bên, một phía', 'Danh từ', 59, 'PUBLISHED'),
      (les_id, '囲む', 'かこむ', '囲む', 'Vây quanh, bao bọc', 'Danh từ', 60, 'PUBLISHED'),
      (les_id, '代わり', 'かわり', '代わり', 'Thay cho, thay thế', 'Danh từ', 61, 'PUBLISHED'),
      (les_id, '友好', 'ゆうこう', '友好', 'Tình hữu nghị', 'Danh từ', 62, 'PUBLISHED'),
      (les_id, '期待（する）', 'きたい（する）', '期待（する）', 'Kỳ vọng, mong đợi', 'Danh từ', 63, 'PUBLISHED'),
      (les_id, '区別（する）', 'くべつ（する）', '区別（する）', 'Sự phân biệt, tách biệt', 'Danh từ', 64, 'PUBLISHED'),
      (les_id, '差別（する）', 'さべつ（する）', '差別（する）', 'Sự phân biệt đối xử', 'Danh từ', 65, 'PUBLISHED'),
      (les_id, '限界', 'げんかい', '限界', 'Giới hạn', 'Danh từ', 66, 'PUBLISHED'),
      (les_id, '通じる', 'つうじる', '通じる', 'Thông hiểu, giao tiếp được', 'Danh từ', 67, 'PUBLISHED'),
      (les_id, '首都', 'しゅと', '首都', 'Thủ đô', 'Danh từ', 68, 'PUBLISHED'),
      (les_id, '順調な', 'じゅんちょうな', '順調な', 'Thuận lợi, suôn sẻ', 'Danh từ', 69, 'PUBLISHED'),
      (les_id, '対象', 'たいしょう', '対象', 'Đối tượng', 'Danh từ', 70, 'PUBLISHED'),
      (les_id, '通知（する）', 'つうち（する）', '通知（する）', 'Thông báo', 'Danh từ', 71, 'PUBLISHED'),
      (les_id, '態度', 'たいど', '態度', 'Thái độ', 'Danh từ', 72, 'PUBLISHED'),
      (les_id, '求める', 'もとめる', '求める', 'Yêu cầu, đòi hỏi, mong muốn', 'Danh từ', 73, 'PUBLISHED'),
      (les_id, '結論', 'けつろん', '結論', 'Kết luận', 'Danh từ', 74, 'PUBLISHED'),
      (les_id, 'ひっくり返す', 'ひっくりかえす', 'ひっくり返す', 'Lật ngược, đảo ngược', 'Danh từ', 75, 'PUBLISHED'),
      (les_id, '広がる', 'ひろがる', '広がる', 'Lan rộng, mở rộng', 'Danh từ', 76, 'PUBLISHED'),
      (les_id, '広げる', 'ひろげる', '広げる', 'Mở rộng, mở mang', 'Danh từ', 77, 'PUBLISHED'),
      (les_id, '活動（する）', 'かつどう（する）', '活動（する）', 'Hoạt động', 'Danh từ', 78, 'PUBLISHED');

END $$;
