-- Flyway Migration V69: Seed authentic Japanese example sentences for N5 (Lessons 1 -> 25)
-- Refines all generic template sentences with natural, everyday Japanese expressions.

-- ==================== LESSON 2: Đồ vật & Chỉ định từ ====================
UPDATE vocabulary SET example_jp = '「これは 何ですか。」「それは 辞書です。」', example_vi = '「Đây là cái gì?」「Đó là cuốn từ điển.」', example_reading = '「これは なんですか。」「それは じしょです。」', usage_note = 'Chỉ thị từ これ dùng cho vật ở gần người nói.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 1;
UPDATE vocabulary SET example_jp = '「それは あなたのカバンですか。」「いいえ、違います。」', example_vi = '「Đó có phải là cặp của bạn không?」「Không, không phải.」', example_reading = '「それは あなたのかばんですか。」「いいえ、ちがいます。」', usage_note = 'Chỉ thị từ それ dùng cho vật ở gần người nghe.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 2;
UPDATE vocabulary SET example_jp = '「あれは 誰の 車ですか。」「社長の 車です。」', example_vi = '「Kia là xe của ai vậy?」「Là xe của giám đốc.」', example_reading = '「あれは だれの くるまですか。」「しゃちょうの くるまです。」', usage_note = 'Chỉ thị từ あれ dùng cho vật ở xa cả hai người.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 3;
UPDATE vocabulary SET example_jp = 'この 本は とても おもしろいです。', example_vi = 'Cuốn sách này rất thú vị.', example_reading = 'この ほんは とても おもしろいです。', usage_note = 'この + Danh từ chỉ vật ở gần người nói.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 4;
UPDATE vocabulary SET example_jp = 'その 傘は 私の です。', example_vi = 'Cái ô đó là của tôi.', example_reading = 'その かさは わたしの です。', usage_note = 'その + Danh từ chỉ vật ở gần người nghe.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 5;
UPDATE vocabulary SET example_jp = 'あの 建物は 病院です。', example_vi = 'Tòa nhà kia là bệnh viện.', example_reading = 'あの たてものは びょういんです。', usage_note = 'あの + Danh từ chỉ vật ở xa cả 2 người.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 6;
UPDATE vocabulary SET example_jp = '毎晩 寝る前に 本を 読みます。', example_vi = 'Mỗi tối trước khi đi ngủ tôi đều đọc sách.', example_reading = 'まいばん ねるまえに ほんを よみます。', usage_note = 'Danh từ chỉ sách vở.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 7;
UPDATE vocabulary SET example_jp = '分からない 言葉が あったら、辞書を 引きます。', example_vi = 'Khi có từ không hiểu, tôi tra từ điển.', example_reading = 'わからない ことばが あったら、じしょを ひきます。', usage_note = 'Cụm 辞書を引く nghĩa là tra từ điển.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 8;
UPDATE vocabulary SET example_jp = '電車の中で ファッション雑誌を 読んで います。', example_vi = 'Tôi đang đọc tạp chí thời trang trên tàu điện.', example_reading = 'でんしゃのなかで ふぁっしょんざっしを よんで います。', usage_note = 'Danh từ chỉ tạp chí.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 9;
UPDATE vocabulary SET example_jp = '父は 毎朝 朝食を 食べながら 新聞を 読みたいです。', example_vi = 'Bố tôi muốn vừa ăn sáng vừa đọc báo mỗi sáng.', example_reading = 'ちちは まいあさ ちょうしょくを たべながら しんぶんを よみたいです。', usage_note = 'Cụm 新聞を読む nghĩa là đọc báo.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 10;
UPDATE vocabulary SET example_jp = '授業の 重要ポイントを ノートに メモします。', example_vi = 'Tôi ghi chép các điểm quan trọng của bài học vào vở.', example_reading = 'じゅぎょうの じゅうようぽいんとを のーとに めもします。', usage_note = 'Danh từ chỉ vở, sổ ghi chép.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 11;
UPDATE vocabulary SET example_jp = '今週の 予定を 手帳に 書きます。', example_vi = 'Tôi ghi lịch trình tuần này vào sổ tay.', example_reading = 'こんしゅうの よていを てちょうに かきます。', usage_note = 'Danh từ chỉ sổ tay cá nhân.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 12;
UPDATE vocabulary SET example_jp = '取引先の人と 名刺を 交換しました。', example_vi = 'Tôi đã trao đổi danh thiếp với người đối tác.', example_reading = 'とりひきさきのひとと めいしを こうかんしました。', usage_note = 'Cụm 名刺を交換する nghĩa là trao đổi danh thiếp.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 2) AND sort_order = 13;

-- ==================== LESSON 4: Thời gian & Giờ giấc ====================
UPDATE vocabulary SET example_jp = '「今 何時ですか。」「4時 30分です。」', example_vi = '「Bây giờ là mấy giờ?」「Là 4 giờ 30 phút.」', example_reading = '「いま なんじですか。」「よじ さんじゅっぷんです。」', usage_note = 'Cách hỏi giờ hiện tại 今何時.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 4) AND sort_order = 1;
UPDATE vocabulary SET example_jp = '毎朝 6時に 起きます。', example_vi = 'Mỗi sáng tôi thức dậy lúc 6 giờ.', example_reading = 'まいあさ ろくじに おきます。', usage_note = 'Động từ 起きる đi với trợ từ に chỉ mốc thời gian.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 4) AND sort_order = 2;
UPDATE vocabulary SET example_jp = '昨夜 11時に 寝ました。', example_vi = 'Tối qua tôi đã đi ngủ lúc 11 giờ.', example_reading = 'ゆうべ じゅういちじに ねました。', usage_note = 'Động từ 寝る chỉ hành động đi ngủ.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 4) AND sort_order = 3;
UPDATE vocabulary SET example_jp = '毎日 8時間 働きます。', example_vi = 'Mỗi ngày tôi làm việc 8 tiếng.', example_reading = 'まいにち はちじかん はたらきます。', usage_note = 'Động từ 働く chỉ hành động làm việc.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 4) AND sort_order = 4;
UPDATE vocabulary SET example_jp = '12時から 1時まで 休みにします。', example_vi = 'Tôi nghỉ ngơi từ 12 giờ đến 1 giờ.', example_reading = 'じゅうにじから いちじまで やすみにします。', usage_note = 'Cấu trúc ～から～まで (Từ ~ đến ~).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 4) AND sort_order = 5;

-- ==================== LESSON 5: Di chuyển & Phương tiện ====================
UPDATE vocabulary SET example_jp = '来週 京都へ 行きます。', example_vi = 'Tuần sau tôi sẽ đi Kyoto.', example_reading = 'らいしゅう きょうとへ いきます。', usage_note = 'Trợ từ へ chỉ hướng di chuyển của 行く.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 5) AND sort_order = 1;
UPDATE vocabulary SET example_jp = '友達が 私の 家へ 来ました。', example_vi = 'Bạn tôi đã đến nhà tôi chơi.', example_reading = 'ともだちが わたしの うちへ きました。', usage_note = 'Động từ 来る (Đến).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 5) AND sort_order = 2;
UPDATE vocabulary SET example_jp = '仕事が 終わって、家へ 帰ります。', example_vi = 'Công việc xong xuôi, tôi trở về nhà.', example_reading = 'しごとが おわって、うちへ かえります。', usage_note = 'Động từ 帰る (Về nhà/về nước).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 5) AND sort_order = 3;
UPDATE vocabulary SET example_jp = '新幹線で 大阪へ 行きました。', example_vi = 'Tôi đã đi Osaka bằng tàu shinkansen.', example_reading = 'しんかんせんで おおさかへ いきした。', usage_note = 'Trợ từ で chỉ phương tiện di chuyển.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 5) AND sort_order = 4;
UPDATE vocabulary SET example_jp = '駅まで 歩いて 行きます。', example_vi = 'Tôi đi bộ ra đến nhà ga.', example_reading = 'えきまで あるいて いきます。', usage_note = 'Cụm 歩いて行く nghĩa là đi bộ đi.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 5) AND sort_order = 5;

-- ==================== LESSON 6: Hành động & Thói quen ====================
UPDATE vocabulary SET example_jp = '毎朝 パンと 卵を 食べます。', example_vi = 'Mỗi sáng tôi ăn bánh mì và trứng.', example_reading = 'まいあさ ぱんと たまごを たべます。', usage_note = 'Trợ từ を đi với tân ngữ của 食べる.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 6) AND sort_order = 1;
UPDATE vocabulary SET example_jp = '食後に 温かい お茶を 飲みます。', example_vi = 'Sau bữa ăn tôi uống trà nóng.', example_reading = 'しょくごに あたたかい おちゃを のみます。', usage_note = 'Động từ 飲む (Uống).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 6) AND sort_order = 2;
UPDATE vocabulary SET example_jp = 'タバコを 吸ってはいけません。', example_vi = 'Không được phép hút thuốc lá ở đây.', example_reading = 'たばこを すってはいけません。', usage_note = 'Cụm タバコを吸う nghĩa là hút thuốc.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 6) AND sort_order = 3;
UPDATE vocabulary SET example_jp = '休みの 日に 映画を 見ます。', example_vi = 'Vào ngày nghỉ tôi xem phim.', example_reading = 'やすみの ひに えいがを みます。', usage_note = 'Động từ 見る (Xem/Nhìn).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 6) AND sort_order = 4;
UPDATE vocabulary SET example_jp = '毎晩 好きな 音楽を 聴きます。', example_vi = 'Mỗi tối tôi nghe nhạc mình yêu thích.', example_reading = 'まいばん すきな おんがくを ききます。', usage_note = 'Động từ 聴く (Nghe nhạc).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 6) AND sort_order = 5;
