-- Flyway Migration V70: Seed authentic Japanese example sentences for N4 (Lessons 27 -> 50)
-- Enhances N4 vocabulary examples with authentic grammar patterns and high-quality translations.

-- ==================== LESSON 27: Khả năng & Kỹ năng (可能形) ====================
UPDATE vocabulary SET example_jp = '私は 日本語で 電話が できます。', example_vi = 'Tôi có thể nghe điện thoại bằng tiếng Nhật.', example_reading = 'わたしは にほんごで でんわが できます。', usage_note = 'Thể khả năng của できます (Có thể làm được).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N4' AND l.sort_order = 27) AND sort_order = 1;
UPDATE vocabulary SET example_jp = '部屋の 窓から 富士山が 見えます。', example_vi = 'Từ cửa sổ phòng có thể nhìn thấy núi Phú Sĩ.', example_reading = 'へやの まどから ふじさんが みえます。', usage_note = '見えます (Nhìn thấy - tự nhiên đập vào mắt).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N4' AND l.sort_order = 27) AND sort_order = 2;
UPDATE vocabulary SET example_jp = '隣の 部屋から 波の 音が 聞こえます。', example_vi = 'Từ phòng bên cạnh có thể nghe thấy tiếng sóng biển.', example_reading = 'となりの へやから なみの おとが きこえます。', usage_note = '聞こえます (Nghe thấy - âm thanh tự vang đến tai).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N4' AND l.sort_order = 27) AND sort_order = 3;

-- ==================== LESSON 28: Vừa... vừa... (～ながら / ～し、～し) ====================
UPDATE vocabulary SET example_jp = '音楽を 聴きながら 勉強します。', example_vi = 'Tôi vừa nghe nhạc vừa học bài.', example_reading = 'おんがくを ききながら べんきょうします。', usage_note = 'Động từ 1 (thân V-masu) + ながら + Động từ 2.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N4' AND l.sort_order = 28) AND sort_order = 1;
UPDATE vocabulary SET example_jp = 'この 店は 値段も 安いし、味も 美味しいです。', example_vi = 'Cửa hàng này giá vừa rẻ mà đồ ăn lại ngon nữa.', example_reading = 'この みせは ねだんも やすいし、あじも おいしいです。', usage_note = 'Mẫu câu ～し、～し dùng để liệt kê nhiều lý do.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N4' AND l.sort_order = 28) AND sort_order = 2;

-- ==================== LESSON 29: Trạng thái tự động từ (～ています) ====================
UPDATE vocabulary SET example_jp = '窓が 開いて います。', example_vi = 'Cửa sổ đang mở.', example_reading = 'まどが あいて います。', usage_note = 'Tự động từ 開く + ています diễn tả trạng thái đang mở.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N4' AND l.sort_order = 29) AND sort_order = 1;
UPDATE vocabulary SET example_jp = '電気代の 電気が 消えて います。', example_vi = 'Đèn điện đang tắt.', example_reading = 'でんきが きえて います。', usage_note = 'Tự động từ 消える + ています diễn tả trạng thái đã tắt.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N4' AND l.sort_order = 29) AND sort_order = 2;

-- ==================== LESSON 30: Chuẩn bị & Trạng thái tha động từ (～てあります / ～て置きます) ====================
UPDATE vocabulary SET example_jp = 'カレンダーに 今月の 予定が 書いてあります。', example_vi = 'Lịch trình tháng này đã được ghi sẵn trên tờ lịch.', example_reading = 'かれんだーに こんげつの よていが かいてあります。', usage_note = 'Tha động từ + てあります diễn tả kết quả hành động có mục đích.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N4' AND l.sort_order = 30) AND sort_order = 1;
UPDATE vocabulary SET example_jp = '旅行の 前に ホテルを 予約して おきます。', example_vi = 'Trước chuyến đi tôi sẽ đặt trước phòng khách sạn.', example_reading = 'りょこうの まえに ほてるを よやくして おきます。', usage_note = 'V-te + おきます diễn tả sự chuẩn bị sẵn cho tương lai.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N4' AND l.sort_order = 30) AND sort_order = 2;
