-- Flyway Migration V71: Seed authentic Japanese example sentences for N5 (Lessons 15 -> 19)
-- Synchronized with V66 authentic examples

-- ==================== LESSON 15 ====================
UPDATE vocabulary SET example_jp = 'ここに 荷物を 置いてください。', example_vi = 'Xin hãy đặt hành lý ở đây.', example_reading = 'ここに にもつを おいてください。', usage_note = 'Động từ 置きます (đặt, để).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 15) AND sort_order = 1;
UPDATE vocabulary SET example_jp = '母は 毎晩 美味しい 料理を 作ります。', example_vi = 'Mỗi tối mẹ tôi đều nấu thức ăn ngon.', example_reading = 'ははは まいばん おいしい りょうりを つくります。', usage_note = 'Động từ 作ります (nấu, chế tạo).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 15) AND sort_order = 2;
UPDATE vocabulary SET example_jp = 'この スーパーで 新鮮な 果物を 売っています。', example_vi = 'Siêu thị này đang bán trái cây tươi.', example_reading = 'この すーぱーで しんせんな くだものを うっています。', usage_note = 'Động từ 売ります (bán).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 15) AND sort_order = 3;
UPDATE vocabulary SET example_jp = '「田中さんの 電話番号を 知っていますか。」「いいえ、知りません。」', example_vi = '「Bạn có biết số điện thoại của anh Tanaka không?」「Không, tôi không biết.」', example_reading = '「たなかさんの でんわばんごうを しっていますか。」「いいえ、しりません。」', usage_note = 'Động từ 知ります (biết).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 15) AND sort_order = 4;
UPDATE vocabulary SET example_jp = '私は 家族と 一緒に 東京に 住んでいます。', example_vi = 'Tôi đang sống cùng gia đình ở Tokyo.', example_reading = 'わたしは かぞくと いっしょに とうきょうに すんでいます。', usage_note = 'Động từ 住みます (sống, cư trú).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 15) AND sort_order = 5;
UPDATE vocabulary SET example_jp = 'どうぞ こちらの 椅子に 座ってください。', example_vi = 'Mời bạn ngồi xuống chiếc ghế này.', example_reading = 'どうぞ こちらの いすに すわってください。', usage_note = 'Động từ 座ります (ngồi xuống).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 15) AND sort_order = 21;
UPDATE vocabulary SET example_jp = '電車で お年寄りに 席を 譲るため、立ちました。', example_vi = 'Tôi đã đứng dậy nhường chỗ cho người cao tuổi trên tàu điện.', example_reading = 'でんしゃで おとしよりに せきを ゆずるため、たちました。', usage_note = 'Động từ 立ちます (đứng dậy).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 15) AND sort_order = 22;
UPDATE vocabulary SET example_jp = '辞書を 使って、日本語の 手紙を 書きます。', example_vi = 'Tôi dùng từ điển để viết thư bằng tiếng Nhật.', example_reading = 'じしょを つかって、にほんごの てがみを かきます。', usage_note = 'Động từ 使います (sử dụng).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 15) AND sort_order = 23;
UPDATE vocabulary SET example_jp = '寒いので、暖かい お風呂に 入ります。', example_vi = 'Vì trời lạnh nên tôi vào tắm bồn nước nóng.', example_reading = 'さむいので、あたたかい おふろに はいります。', usage_note = 'Động từ 入ります (vào, tắm bồn).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 15) AND sort_order = 24;
UPDATE vocabulary SET example_jp = '毎朝 7時に 家を 出て、会社へ 行きます。', example_vi = 'Mỗi sáng tôi rời khỏi nhà lúc 7 giờ để đến công ty.', example_reading = 'まいあさ 7じに いえを でて、かいしゃへ いきます。', usage_note = 'Động từ 出ます chỉ việc ra khỏi nhà.' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 15) AND sort_order = 25;
UPDATE vocabulary SET example_jp = 'ここでは タバコを 吸ってはいけません。', example_vi = 'Ở đây cấm hút thuốc.', example_reading = 'ここでは たばこを すってはいけません。', usage_note = 'Mẫu câu ~てはいけません (cấm làm gì).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 15) AND sort_order = 26;
UPDATE vocabulary SET example_jp = 'この 公園では 写真を 撮っても いいです。', example_vi = 'Ở công viên này được phép chụp ảnh.', example_reading = 'この こうえんは しゃしんを とっても いいです。', usage_note = 'Mẫu câu ~てもいいです (được phép làm gì).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 15) AND sort_order = 27;

-- ==================== LESSON 16 ====================
UPDATE vocabulary SET example_jp = '新宿駅で JR線から 地下鉄に 乗り換えます。', example_vi = 'Tôi đổi từ tuyến JR sang tàu điện ngầm ở ga Shinjuku.', example_reading = 'しんじゅくえきで じぇーあーるせんから ちかてつに のりかえます。', usage_note = 'Động từ 乗り換えます (đổi tàu, xe).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 16) AND sort_order = 1;
UPDATE vocabulary SET example_jp = '毎朝 起きてから シャワーを 浴びます。', example_vi = 'Mỗi sáng sau khi thức dậy tôi đều tắm vòi sen.', example_reading = 'まいあさ おきてから しゃわーを あびます。', usage_note = 'Cụm シャワーを浴びます (tắm vòi sen).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 16) AND sort_order = 2;
UPDATE vocabulary SET example_jp = 'お客様に 美味しい コーヒーを 淹れました。', example_vi = 'Tôi đã pha cà phê ngon dành tặng cho khách hàng.', example_reading = 'おきゃくさまに おいしい こーひーを いれました。', usage_note = 'Động từ 淹れます (pha trà/cà phê).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 16) AND sort_order = 3;

-- ==================== LESSON 17 ====================
UPDATE vocabulary SET example_jp = '毎日 新しい 漢字を 5つ 覚えます。', example_vi = 'Mỗi ngày tôi học thuộc 5 chữ Kanji mới.', example_reading = 'まいにち あたらしい かんじを ごつ おぼえます。', usage_note = 'Động từ 覚えます (ghi nhớ, học thuộc).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 17) AND sort_order = 1;
UPDATE vocabulary SET example_jp = '電車に 傘を 忘れてしまいました。', example_vi = 'Tôi lỡ quên chiếc ô trên tàu điện mất rồi.', example_reading = 'でんしゃに かさを わすれてしまいました。', usage_note = 'Động từ 忘れます (quên).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 17) AND sort_order = 2;

-- ==================== LESSON 18 ====================
UPDATE vocabulary SET example_jp = 'ミラーさんは 日本語で 会話が できます。', example_vi = 'Anh Miller có thể hội thoại bằng tiếng Nhật.', example_reading = 'みらーさんは にほんごで かいわが できます。', usage_note = 'Động từ できます (có thể).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 18) AND sort_order = 1;
UPDATE vocabulary SET example_jp = 'お風呂で シャンプーを使って 髪を 洗います。', example_vi = 'Trong phòng tắm tôi dùng dầu gội để gội đầu.', example_reading = 'おふろで しゃんぷーをつかって かみを あらいます。', usage_note = 'Động từ 洗います (giặt, rửa, gội).' WHERE lesson_id = (SELECT l.lesson_id FROM lessons l JOIN levels lvl ON l.level_id = lvl.level_id WHERE lvl.code = 'N5' AND l.sort_order = 18) AND sort_order = 2;
