-- Flyway Migration V8: Recreate import_errors table to guarantee column import_error_id exists

DROP TABLE IF EXISTS import_errors CASCADE;

CREATE TABLE import_errors (
    import_error_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_job_id         BIGINT NOT NULL REFERENCES import_jobs(import_job_id) ON DELETE CASCADE,
    row_number            INTEGER NOT NULL,
    sheet_name            VARCHAR(100) NOT NULL DEFAULT 'Sheet1',
    column_name           VARCHAR(100),
    field_name            VARCHAR(100),
    reason_code           VARCHAR(50) NOT NULL,
    message               TEXT NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_import_errors_job ON import_errors(import_job_id);
