-- Flyway Migration V9: Recreate import_jobs and import_errors tables to guarantee all columns exist

DROP TABLE IF EXISTS import_errors CASCADE;
DROP TABLE IF EXISTS import_jobs CASCADE;

CREATE TABLE import_jobs (
    import_job_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id              BIGINT NOT NULL REFERENCES users(user_id),
    file_name             VARCHAR(255) NOT NULL,
    file_path             TEXT NOT NULL,
    file_type             VARCHAR(50) NOT NULL,
    template_version      VARCHAR(20) NOT NULL DEFAULT 'v1.0',
    target_level_id       BIGINT NOT NULL REFERENCES levels(level_id),
    target_lesson_id      BIGINT NOT NULL REFERENCES lessons(lesson_id),
    duplicate_mode        VARCHAR(20) NOT NULL DEFAULT 'SKIP',
    status                VARCHAR(30) NOT NULL DEFAULT 'UPLOADED',
    total_rows            INTEGER NOT NULL DEFAULT 0,
    valid_rows            INTEGER NOT NULL DEFAULT 0,
    invalid_rows          INTEGER NOT NULL DEFAULT 0,
    skipped_rows          INTEGER NOT NULL DEFAULT 0,
    version               BIGINT NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_import_job_type CHECK (file_type IN ('VOCABULARY', 'KANJI', 'GRAMMAR', 'GRAMMAR_EXAMPLE')),
    CONSTRAINT ck_import_job_mode CHECK (duplicate_mode IN ('SKIP', 'UPDATE')),
    CONSTRAINT ck_import_job_status CHECK (status IN ('UPLOADED', 'VALIDATING', 'VALIDATION_FAILED', 'READY_TO_COMMIT', 'COMMITTING', 'COMPLETED', 'FAILED_TECHNICAL', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS ix_import_jobs_admin ON import_jobs(admin_id);
CREATE INDEX IF NOT EXISTS ix_import_jobs_status ON import_jobs(status);
CREATE INDEX IF NOT EXISTS ix_import_jobs_created ON import_jobs(created_at);

CREATE TABLE import_errors (
    import_error_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_job_id         BIGINT NOT NULL REFERENCES import_jobs(import_job_id) ON DELETE CASCADE,
    row_number            INTEGER NOT NULL,
    sheet_name            VARCHAR(100) NOT NULL DEFAULT 'Sheet1',
    column_name           VARCHAR(100),
    field_name            VARCHAR(100),
    reason_code           VARCHAR(50) NOT NULL,
    message               TEXT NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_import_errors_job ON import_errors(import_job_id);
