-- ANH SENSEI - PostgreSQL/Supabase database schema
-- Based on SRS version 2.0 (20/08/2026)
-- Run this file once in Supabase Dashboard -> SQL Editor -> New query -> Run.

BEGIN;

-- pgvector is used by the AI/RAG module (Version 1.2).
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

-- ============================================================
-- 1. IDENTITY AND ACCESS MANAGEMENT
-- ============================================================

CREATE TABLE IF NOT EXISTS roles (
    role_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name            VARCHAR(30) NOT NULL UNIQUE,
    description          VARCHAR(255),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_roles_name CHECK (role_name IN ('LEARNER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS users (
    user_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id              BIGINT NOT NULL REFERENCES roles(role_id),
    email                VARCHAR(320) NOT NULL,
    password_hash        VARCHAR(255) NOT NULL,
    full_name            VARCHAR(150) NOT NULL,
    avatar_url           TEXT,
    target_level         VARCHAR(10),
    timezone             VARCHAR(100) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    status               VARCHAR(30) NOT NULL DEFAULT 'PENDING_VERIFICATION',
    email_verified_at    TIMESTAMPTZ,
    failed_login_count   INTEGER NOT NULL DEFAULT 0,
    lock_until           TIMESTAMPTZ,
    last_login_at        TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at           TIMESTAMPTZ,
    CONSTRAINT ck_users_email_lower CHECK (email = LOWER(BTRIM(email))),
    CONSTRAINT ck_users_target_level CHECK (target_level IS NULL OR target_level IN ('N5','N4','N3','N2','N1')),
    CONSTRAINT ck_users_status CHECK (status IN ('PENDING_VERIFICATION','ACTIVE','LOCKED','DISABLED','ARCHIVED')),
    CONSTRAINT ck_users_failed_login CHECK (failed_login_count >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email_active
    ON users (LOWER(email)) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_users_role ON users(role_id);
CREATE INDEX IF NOT EXISTS ix_users_status ON users(status);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    token_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash           VARCHAR(255) NOT NULL UNIQUE,
    token_family         UUID NOT NULL,
    expires_at           TIMESTAMPTZ NOT NULL,
    revoked_at           TIMESTAMPTZ,
    replaced_by_token_id BIGINT REFERENCES refresh_tokens(token_id),
    device_info          VARCHAR(500),
    ip_address           INET,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_refresh_token_expiry CHECK (expires_at > created_at)
);

CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_active
    ON refresh_tokens(user_id, expires_at) WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS email_verification_tokens (
    verification_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash             VARCHAR(255) NOT NULL UNIQUE,
    expires_at             TIMESTAMPTZ NOT NULL,
    used_at                TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    reset_token_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash            VARCHAR(255) NOT NULL UNIQUE,
    expires_at            TIMESTAMPTZ NOT NULL,
    used_at               TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- 2. CURRICULUM AND LEARNING CONTENT
-- ============================================================

CREATE TABLE IF NOT EXISTS levels (
    level_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                  VARCHAR(10) NOT NULL UNIQUE,
    name                  VARCHAR(100) NOT NULL,
    description           TEXT,
    sort_order            INTEGER NOT NULL,
    status                VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by            BIGINT REFERENCES users(user_id),
    updated_by            BIGINT REFERENCES users(user_id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at          TIMESTAMPTZ,
    deleted_at            TIMESTAMPTZ,
    CONSTRAINT ck_levels_code CHECK (code IN ('N5','N4','N3','N2','N1')),
    CONSTRAINT ck_levels_sort CHECK (sort_order > 0),
    CONSTRAINT ck_levels_status CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_levels_sort_active
    ON levels(sort_order) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS lessons (
    lesson_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_id              BIGINT NOT NULL REFERENCES levels(level_id),
    title                 VARCHAR(200) NOT NULL,
    description           TEXT,
    sort_order            INTEGER NOT NULL,
    completion_criteria   JSONB NOT NULL DEFAULT '{"requireAllItems":true,"requireRequiredQuizzes":true}'::jsonb,
    is_sample             BOOLEAN NOT NULL DEFAULT FALSE,
    estimated_minutes     INTEGER,
    status                VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by            BIGINT REFERENCES users(user_id),
    updated_by            BIGINT REFERENCES users(user_id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at          TIMESTAMPTZ,
    deleted_at            TIMESTAMPTZ,
    CONSTRAINT ck_lessons_sort CHECK (sort_order > 0),
    CONSTRAINT ck_lessons_minutes CHECK (estimated_minutes IS NULL OR estimated_minutes > 0),
    CONSTRAINT ck_lessons_status CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_lessons_level_sort_active
    ON lessons(level_id, sort_order) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_lessons_level_status ON lessons(level_id, status);

CREATE TABLE IF NOT EXISTS vocabulary (
    vocabulary_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id            BIGINT NOT NULL REFERENCES lessons(lesson_id),
    word                  VARCHAR(150) NOT NULL,
    kana                  VARCHAR(150) NOT NULL,
    kanji_form            VARCHAR(150),
    meaning_vi            TEXT NOT NULL,
    part_of_speech        VARCHAR(80),
    audio_url             TEXT,
    notes                 TEXT,
    sort_order            INTEGER NOT NULL DEFAULT 1,
    is_required           BOOLEAN NOT NULL DEFAULT TRUE,
    status                VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by            BIGINT REFERENCES users(user_id),
    updated_by            BIGINT REFERENCES users(user_id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at          TIMESTAMPTZ,
    deleted_at            TIMESTAMPTZ,
    CONSTRAINT ck_vocabulary_sort CHECK (sort_order > 0),
    CONSTRAINT ck_vocabulary_status CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED'))
);

CREATE INDEX IF NOT EXISTS ix_vocabulary_lesson_status ON vocabulary(lesson_id, status);
CREATE INDEX IF NOT EXISTS ix_vocabulary_word ON vocabulary(word);

CREATE TABLE IF NOT EXISTS kanji (
    kanji_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character             VARCHAR(10) NOT NULL UNIQUE,
    onyomi                VARCHAR(255),
    kunyomi               VARCHAR(255),
    meaning_vi            TEXT NOT NULL,
    stroke_count          INTEGER,
    radical               VARCHAR(50),
    image_url             TEXT,
    jlpt_level            VARCHAR(10),
    status                VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by            BIGINT REFERENCES users(user_id),
    updated_by            BIGINT REFERENCES users(user_id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at          TIMESTAMPTZ,
    deleted_at            TIMESTAMPTZ,
    CONSTRAINT ck_kanji_strokes CHECK (stroke_count IS NULL OR stroke_count > 0),
    CONSTRAINT ck_kanji_level CHECK (jlpt_level IS NULL OR jlpt_level IN ('N5','N4','N3','N2','N1')),
    CONSTRAINT ck_kanji_status CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED'))
);

CREATE TABLE IF NOT EXISTS lesson_kanji (
    lesson_id             BIGINT NOT NULL REFERENCES lessons(lesson_id) ON DELETE CASCADE,
    kanji_id              BIGINT NOT NULL REFERENCES kanji(kanji_id),
    sort_order            INTEGER NOT NULL DEFAULT 1,
    notes                 TEXT,
    is_required           BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (lesson_id, kanji_id),
    CONSTRAINT ck_lesson_kanji_sort CHECK (sort_order > 0)
);

CREATE TABLE IF NOT EXISTS grammar_points (
    grammar_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id             BIGINT NOT NULL REFERENCES lessons(lesson_id),
    pattern               VARCHAR(255) NOT NULL,
    meaning               TEXT NOT NULL,
    explanation           TEXT NOT NULL,
    structure             TEXT,
    jlpt_level            VARCHAR(10) NOT NULL,
    sort_order            INTEGER NOT NULL DEFAULT 1,
    is_required           BOOLEAN NOT NULL DEFAULT TRUE,
    status                VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by            BIGINT REFERENCES users(user_id),
    updated_by            BIGINT REFERENCES users(user_id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at          TIMESTAMPTZ,
    deleted_at            TIMESTAMPTZ,
    CONSTRAINT ck_grammar_level CHECK (jlpt_level IN ('N5','N4','N3','N2','N1')),
    CONSTRAINT ck_grammar_sort CHECK (sort_order > 0),
    CONSTRAINT ck_grammar_status CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED'))
);

CREATE INDEX IF NOT EXISTS ix_grammar_lesson_status ON grammar_points(lesson_id, status);

-- Polymorphic relation. Spring Boot must validate that content_id exists
-- in the table represented by content_type in the same transaction.
CREATE TABLE IF NOT EXISTS examples (
    example_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type          VARCHAR(30) NOT NULL,
    content_id            BIGINT NOT NULL,
    japanese_text         TEXT NOT NULL,
    furigana              TEXT,
    translation_vi        TEXT NOT NULL,
    notes                 TEXT,
    sort_order            INTEGER NOT NULL DEFAULT 1,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_examples_type CHECK (content_type IN ('VOCABULARY','KANJI','GRAMMAR')),
    CONSTRAINT ck_examples_sort CHECK (sort_order > 0)
);

CREATE INDEX IF NOT EXISTS ix_examples_target ON examples(content_type, content_id);

-- ============================================================
-- 3. QUIZZES AND MEDIA
-- ============================================================

CREATE TABLE IF NOT EXISTS quizzes (
    quiz_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id             BIGINT REFERENCES lessons(lesson_id),
    title                 VARCHAR(200) NOT NULL,
    description           TEXT,
    quiz_type             VARCHAR(30) NOT NULL DEFAULT 'LESSON',
    pass_score            NUMERIC(5,2) NOT NULL DEFAULT 70.00,
    time_limit_minutes    INTEGER,
    review_mode           VARCHAR(30) NOT NULL DEFAULT 'IMMEDIATE',
    review_at             TIMESTAMPTZ,
    max_attempts          INTEGER,
    is_required           BOOLEAN NOT NULL DEFAULT TRUE,
    status                VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by            BIGINT REFERENCES users(user_id),
    updated_by            BIGINT REFERENCES users(user_id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at          TIMESTAMPTZ,
    deleted_at            TIMESTAMPTZ,
    CONSTRAINT ck_quizzes_type CHECK (quiz_type IN ('LESSON','READING','LISTENING','PRACTICE')),
    CONSTRAINT ck_quizzes_pass_score CHECK (pass_score BETWEEN 0 AND 100),
    CONSTRAINT ck_quizzes_time_limit CHECK (time_limit_minutes IS NULL OR time_limit_minutes > 0),
    CONSTRAINT ck_quizzes_review_mode CHECK (review_mode IN ('IMMEDIATE','AFTER_DEADLINE','AFTER_MAX_ATTEMPTS','NEVER')),
    CONSTRAINT ck_quizzes_max_attempts CHECK (max_attempts IS NULL OR max_attempts > 0),
    CONSTRAINT ck_quizzes_review_at CHECK (review_mode <> 'AFTER_DEADLINE' OR review_at IS NOT NULL),
    CONSTRAINT ck_quizzes_attempt_rule CHECK (review_mode <> 'AFTER_MAX_ATTEMPTS' OR max_attempts IS NOT NULL),
    CONSTRAINT ck_quizzes_status CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED'))
);

CREATE INDEX IF NOT EXISTS ix_quizzes_lesson_status ON quizzes(lesson_id, status);

CREATE TABLE IF NOT EXISTS reading_contents (
    reading_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id             BIGINT NOT NULL REFERENCES lessons(lesson_id),
    quiz_id               BIGINT UNIQUE REFERENCES quizzes(quiz_id),
    title                 VARCHAR(200) NOT NULL,
    passage               TEXT NOT NULL,
    difficulty            VARCHAR(10),
    sort_order            INTEGER NOT NULL DEFAULT 1,
    is_required           BOOLEAN NOT NULL DEFAULT TRUE,
    status                VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at          TIMESTAMPTZ,
    deleted_at            TIMESTAMPTZ,
    CONSTRAINT ck_reading_difficulty CHECK (difficulty IS NULL OR difficulty IN ('N5','N4','N3','N2','N1')),
    CONSTRAINT ck_reading_sort CHECK (sort_order > 0),
    CONSTRAINT ck_reading_status CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED'))
);

CREATE TABLE IF NOT EXISTS listening_contents (
    listening_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id             BIGINT NOT NULL REFERENCES lessons(lesson_id),
    quiz_id               BIGINT UNIQUE REFERENCES quizzes(quiz_id),
    title                 VARCHAR(200) NOT NULL,
    audio_url             TEXT NOT NULL,
    transcript            TEXT,
    difficulty            VARCHAR(10),
    sort_order            INTEGER NOT NULL DEFAULT 1,
    is_required           BOOLEAN NOT NULL DEFAULT TRUE,
    status                VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at          TIMESTAMPTZ,
    deleted_at            TIMESTAMPTZ,
    CONSTRAINT ck_listening_difficulty CHECK (difficulty IS NULL OR difficulty IN ('N5','N4','N3','N2','N1')),
    CONSTRAINT ck_listening_sort CHECK (sort_order > 0),
    CONSTRAINT ck_listening_status CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED'))
);

-- A quiz can belong to only one owner: a lesson directly, reading, or listening.
CREATE OR REPLACE FUNCTION check_quiz_exclusive_owner(p_quiz_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    SELECT
        (CASE WHEN EXISTS (SELECT 1 FROM quizzes q WHERE q.quiz_id = p_quiz_id AND q.lesson_id IS NOT NULL) THEN 1 ELSE 0 END) +
        (CASE WHEN EXISTS (SELECT 1 FROM reading_contents r WHERE r.quiz_id = p_quiz_id) THEN 1 ELSE 0 END) +
        (CASE WHEN EXISTS (SELECT 1 FROM listening_contents l WHERE l.quiz_id = p_quiz_id) THEN 1 ELSE 0 END)
        <= 1;
$$;

CREATE OR REPLACE FUNCTION enforce_quiz_exclusive_owner()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_quiz_id BIGINT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_quiz_id := OLD.quiz_id;
    ELSE
        v_quiz_id := NEW.quiz_id;
    END IF;

    IF v_quiz_id IS NOT NULL AND NOT check_quiz_exclusive_owner(v_quiz_id) THEN
        RAISE EXCEPTION 'Quiz % may belong to only one owner', v_quiz_id;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_quiz_owner_on_quiz ON quizzes;
CREATE CONSTRAINT TRIGGER trg_quiz_owner_on_quiz
AFTER INSERT OR UPDATE OR DELETE ON quizzes
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION enforce_quiz_exclusive_owner();

DROP TRIGGER IF EXISTS trg_quiz_owner_on_reading ON reading_contents;
CREATE CONSTRAINT TRIGGER trg_quiz_owner_on_reading
AFTER INSERT OR UPDATE OR DELETE ON reading_contents
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION enforce_quiz_exclusive_owner();

DROP TRIGGER IF EXISTS trg_quiz_owner_on_listening ON listening_contents;
CREATE CONSTRAINT TRIGGER trg_quiz_owner_on_listening
AFTER INSERT OR UPDATE OR DELETE ON listening_contents
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION enforce_quiz_exclusive_owner();

CREATE TABLE IF NOT EXISTS questions (
    question_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id               BIGINT NOT NULL REFERENCES quizzes(quiz_id) ON DELETE CASCADE,
    question_type         VARCHAR(30) NOT NULL,
    prompt                TEXT NOT NULL,
    correct_answer        JSONB NOT NULL,
    explanation           TEXT,
    weight                NUMERIC(8,2) NOT NULL DEFAULT 1.00,
    audio_url             TEXT,
    sort_order            INTEGER NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_questions_type CHECK (question_type IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE','TEXT','FILL_BLANK','MATCHING')),
    CONSTRAINT ck_questions_weight CHECK (weight > 0),
    CONSTRAINT ck_questions_sort CHECK (sort_order > 0),
    UNIQUE (quiz_id, sort_order)
);

CREATE TABLE IF NOT EXISTS question_options (
    option_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id           BIGINT NOT NULL REFERENCES questions(question_id) ON DELETE CASCADE,
    option_text           TEXT NOT NULL,
    is_correct            BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order            INTEGER NOT NULL,
    CONSTRAINT ck_question_options_sort CHECK (sort_order > 0),
    UNIQUE (question_id, sort_order)
);

CREATE TABLE IF NOT EXISTS quiz_attempts (
    attempt_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL REFERENCES users(user_id),
    quiz_id               BIGINT NOT NULL REFERENCES quizzes(quiz_id),
    attempt_number        INTEGER NOT NULL,
    score                 NUMERIC(5,2),
    correct_count         INTEGER NOT NULL DEFAULT 0,
    total_count           INTEGER NOT NULL DEFAULT 0,
    started_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    submitted_at          TIMESTAMPTZ,
    status                VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    submission_key        UUID NOT NULL DEFAULT gen_random_uuid(),
    CONSTRAINT ck_attempt_number CHECK (attempt_number > 0),
    CONSTRAINT ck_attempt_score CHECK (score IS NULL OR score BETWEEN 0 AND 100),
    CONSTRAINT ck_attempt_counts CHECK (correct_count >= 0 AND total_count >= 0 AND correct_count <= total_count),
    CONSTRAINT ck_attempt_status CHECK (status IN ('IN_PROGRESS','SUBMITTED','EXPIRED','ABANDONED')),
    CONSTRAINT ck_attempt_submission CHECK ((status = 'SUBMITTED' AND submitted_at IS NOT NULL AND score IS NOT NULL) OR status <> 'SUBMITTED'),
    UNIQUE (user_id, quiz_id, attempt_number),
    UNIQUE (submission_key)
);

CREATE INDEX IF NOT EXISTS ix_attempts_user_quiz ON quiz_attempts(user_id, quiz_id, started_at DESC);

CREATE TABLE IF NOT EXISTS quiz_attempt_answers (
    attempt_answer_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id                       BIGINT NOT NULL REFERENCES quiz_attempts(attempt_id) ON DELETE CASCADE,
    question_id                      BIGINT NOT NULL REFERENCES questions(question_id),
    selected_option_id               BIGINT REFERENCES question_options(option_id),
    text_answer                      TEXT,
    is_correct                       BOOLEAN NOT NULL DEFAULT FALSE,
    earned_score                     NUMERIC(8,2) NOT NULL DEFAULT 0,
    question_prompt_snapshot         TEXT NOT NULL,
    user_answer_snapshot             JSONB NOT NULL,
    correct_answer_snapshot          JSONB NOT NULL,
    explanation_snapshot             TEXT,
    answered_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_attempt_answer_score CHECK (earned_score >= 0),
    UNIQUE (attempt_id, question_id)
);

-- ============================================================
-- 4. LEARNING PROGRESS, STREAK AND FAVORITES
-- ============================================================

CREATE TABLE IF NOT EXISTS learning_progress (
    learning_progress_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    lesson_id            BIGINT NOT NULL REFERENCES lessons(lesson_id),
    completion_percent   NUMERIC(5,2) NOT NULL DEFAULT 0,
    status               VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
    completed_at         TIMESTAMPTZ,
    last_accessed_at     TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_learning_percent CHECK (completion_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_learning_status CHECK (status IN ('NOT_STARTED','IN_PROGRESS','COMPLETED')),
    CONSTRAINT ck_learning_completed CHECK ((status = 'COMPLETED' AND completed_at IS NOT NULL AND completion_percent = 100) OR status <> 'COMPLETED'),
    UNIQUE (user_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS learning_activities (
    activity_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    activity_type        VARCHAR(40) NOT NULL,
    reference_type       VARCHAR(30) NOT NULL,
    reference_id         BIGINT NOT NULL,
    duration_seconds     INTEGER NOT NULL DEFAULT 0,
    activity_date        DATE NOT NULL,
    user_timezone        VARCHAR(100) NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_learning_activity_type CHECK (activity_type IN ('CONTENT_COMPLETED','QUIZ_SUBMITTED','FLASHCARD_REVIEWED')),
    CONSTRAINT ck_learning_reference_type CHECK (reference_type IN ('VOCABULARY','KANJI','GRAMMAR','READING','LISTENING','QUIZ','FLASHCARD','LESSON')),
    CONSTRAINT ck_learning_duration CHECK (duration_seconds >= 0)
);

CREATE INDEX IF NOT EXISTS ix_learning_activities_streak ON learning_activities(user_id, activity_date);

CREATE TABLE IF NOT EXISTS user_streaks (
    user_id              BIGINT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
    current_streak       INTEGER NOT NULL DEFAULT 0,
    best_streak          INTEGER NOT NULL DEFAULT 0,
    last_activity_date   DATE,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_streak_values CHECK (current_streak >= 0 AND best_streak >= current_streak)
);

CREATE TABLE IF NOT EXISTS favorites (
    favorite_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    content_type         VARCHAR(30) NOT NULL,
    content_id           BIGINT NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_favorites_type CHECK (content_type IN ('LESSON','VOCABULARY','KANJI','GRAMMAR','READING','LISTENING')),
    UNIQUE (user_id, content_type, content_id)
);

-- ============================================================
-- 5. FLASHCARD / SPACED REPETITION
-- ============================================================

CREATE TABLE IF NOT EXISTS flashcard_progress (
    progress_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    content_type         VARCHAR(30) NOT NULL,
    content_id           BIGINT NOT NULL,
    state                 VARCHAR(20) NOT NULL DEFAULT 'NEW',
    ease_factor           NUMERIC(5,2) NOT NULL DEFAULT 2.50,
    interval_days         INTEGER NOT NULL DEFAULT 0,
    next_review_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    review_count          INTEGER NOT NULL DEFAULT 0,
    lapse_count           INTEGER NOT NULL DEFAULT 0,
    algorithm_version     VARCHAR(30) NOT NULL DEFAULT 'SM2_V1',
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_flashcard_type CHECK (content_type IN ('VOCABULARY','KANJI','GRAMMAR')),
    CONSTRAINT ck_flashcard_state CHECK (state IN ('NEW','LEARNING','REVIEW','RELEARNING','SUSPENDED')),
    CONSTRAINT ck_flashcard_ease CHECK (ease_factor >= 1.30),
    CONSTRAINT ck_flashcard_values CHECK (interval_days >= 0 AND review_count >= 0 AND lapse_count >= 0),
    UNIQUE (user_id, content_type, content_id)
);

CREATE INDEX IF NOT EXISTS ix_flashcard_due ON flashcard_progress(user_id, next_review_at)
    WHERE state <> 'SUSPENDED';

CREATE TABLE IF NOT EXISTS flashcard_review_logs (
    review_log_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    progress_id          BIGINT REFERENCES flashcard_progress(progress_id),
    user_id              BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    content_type         VARCHAR(30) NOT NULL,
    content_id           BIGINT NOT NULL,
    rating                VARCHAR(10) NOT NULL,
    previous_interval    INTEGER NOT NULL,
    new_interval         INTEGER NOT NULL,
    previous_ease_factor NUMERIC(5,2),
    new_ease_factor      NUMERIC(5,2),
    algorithm_version    VARCHAR(30) NOT NULL,
    reviewed_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_review_log_type CHECK (content_type IN ('VOCABULARY','KANJI','GRAMMAR')),
    CONSTRAINT ck_review_rating CHECK (rating IN ('AGAIN','HARD','GOOD','EASY')),
    CONSTRAINT ck_review_intervals CHECK (previous_interval >= 0 AND new_interval >= 0)
);

CREATE INDEX IF NOT EXISTS ix_flashcard_logs_user_date ON flashcard_review_logs(user_id, reviewed_at DESC);

-- ============================================================
-- 6. STRICT EXCEL IMPORT
-- ============================================================

CREATE TABLE IF NOT EXISTS import_jobs (
    import_job_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id             BIGINT NOT NULL REFERENCES users(user_id),
    file_url             TEXT NOT NULL,
    file_name            VARCHAR(255) NOT NULL,
    file_type            VARCHAR(20) NOT NULL,
    file_size_bytes      BIGINT NOT NULL,
    file_checksum        VARCHAR(128),
    template_version     VARCHAR(30) NOT NULL,
    target_level_id      BIGINT REFERENCES levels(level_id),
    target_lesson_id     BIGINT REFERENCES lessons(lesson_id),
    target_entity        VARCHAR(30) NOT NULL,
    duplicate_mode       VARCHAR(10) NOT NULL,
    status                VARCHAR(30) NOT NULL DEFAULT 'UPLOADED',
    total_rows           INTEGER NOT NULL DEFAULT 0,
    valid_rows           INTEGER NOT NULL DEFAULT 0,
    invalid_rows         INTEGER NOT NULL DEFAULT 0,
    skipped_rows         INTEGER NOT NULL DEFAULT 0,
    committed_rows       INTEGER NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at         TIMESTAMPTZ,
    cancelled_at         TIMESTAMPTZ,
    CONSTRAINT ck_import_file_type CHECK (file_type = 'XLSX'),
    CONSTRAINT ck_import_file_size CHECK (file_size_bytes > 0 AND file_size_bytes <= 10485760),
    CONSTRAINT ck_import_target CHECK (target_entity IN ('VOCABULARY','KANJI','GRAMMAR')),
    CONSTRAINT ck_import_mode CHECK (duplicate_mode IN ('SKIP','UPDATE')),
    CONSTRAINT ck_import_status CHECK (status IN ('UPLOADED','VALIDATING','VALIDATION_FAILED','READY_TO_COMMIT','COMMITTING','COMPLETED','FAILED_TECHNICAL','CANCELLED')),
    CONSTRAINT ck_import_rows CHECK (total_rows BETWEEN 0 AND 1000 AND valid_rows >= 0 AND invalid_rows >= 0 AND skipped_rows >= 0 AND committed_rows >= 0)
);

CREATE INDEX IF NOT EXISTS ix_import_jobs_admin_date ON import_jobs(admin_id, created_at DESC);

CREATE TABLE IF NOT EXISTS import_errors (
    error_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_job_id        BIGINT NOT NULL REFERENCES import_jobs(import_job_id) ON DELETE CASCADE,
    row_number           INTEGER NOT NULL,
    column_name          VARCHAR(100) NOT NULL,
    field_name           VARCHAR(100) NOT NULL,
    reason_code          VARCHAR(80) NOT NULL,
    error_reason         TEXT NOT NULL,
    raw_data             JSONB,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_import_error_row CHECK (row_number > 0)
);

CREATE INDEX IF NOT EXISTS ix_import_errors_job_row ON import_errors(import_job_id, row_number);

CREATE TABLE IF NOT EXISTS import_processing_attempts (
    processing_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_job_id          BIGINT NOT NULL REFERENCES import_jobs(import_job_id) ON DELETE CASCADE,
    attempt_number         INTEGER NOT NULL,
    operation              VARCHAR(20) NOT NULL,
    status                 VARCHAR(20) NOT NULL,
    technical_error        TEXT,
    started_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at            TIMESTAMPTZ,
    CONSTRAINT ck_processing_operation CHECK (operation IN ('VALIDATE','COMMIT')),
    CONSTRAINT ck_processing_status CHECK (status IN ('PROCESSING','SUCCEEDED','FAILED')),
    UNIQUE (import_job_id, attempt_number, operation)
);

-- ============================================================
-- 7. AI TUTOR AND KNOWLEDGE BASE (VERSION 1.2)
-- ============================================================

CREATE TABLE IF NOT EXISTS knowledge_documents (
    document_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id             BIGINT NOT NULL REFERENCES users(user_id),
    title                VARCHAR(255) NOT NULL,
    file_url             TEXT NOT NULL,
    file_name            VARCHAR(255),
    mime_type            VARCHAR(120),
    approval_status      VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    index_status         VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_by          BIGINT REFERENCES users(user_id),
    approved_at          TIMESTAMPTZ,
    rejection_reason     TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_knowledge_approval CHECK (approval_status IN ('DRAFT','APPROVED','REJECTED')),
    CONSTRAINT ck_knowledge_index CHECK (index_status IN ('PENDING','PROCESSING','INDEXED','FAILED')),
    CONSTRAINT ck_knowledge_approved CHECK ((approval_status = 'APPROVED' AND approved_by IS NOT NULL AND approved_at IS NOT NULL) OR approval_status <> 'APPROVED'),
    CONSTRAINT ck_knowledge_retrievable CHECK (index_status <> 'INDEXED' OR approval_status = 'APPROVED')
);

CREATE TABLE IF NOT EXISTS knowledge_chunks (
    chunk_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id          BIGINT NOT NULL REFERENCES knowledge_documents(document_id) ON DELETE CASCADE,
    chunk_text           TEXT NOT NULL,
    embedding            extensions.vector(1536),
    chunk_order          INTEGER NOT NULL,
    token_count          INTEGER NOT NULL DEFAULT 0,
    metadata             JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_chunk_order CHECK (chunk_order >= 0),
    CONSTRAINT ck_chunk_tokens CHECK (token_count >= 0),
    UNIQUE (document_id, chunk_order)
);

-- Add the vector index after data is loaded if the table is very small.
CREATE INDEX IF NOT EXISTS ix_knowledge_chunks_embedding
    ON knowledge_chunks USING hnsw (embedding extensions.vector_cosine_ops);

CREATE TABLE IF NOT EXISTS chat_sessions (
    session_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    title                 VARCHAR(200),
    status                VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    message_count         INTEGER NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    closed_at             TIMESTAMPTZ,
    CONSTRAINT ck_chat_session_status CHECK (status IN ('ACTIVE','CLOSED','ARCHIVED')),
    CONSTRAINT ck_chat_message_count CHECK (message_count >= 0)
);

CREATE INDEX IF NOT EXISTS ix_chat_sessions_user ON chat_sessions(user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS chat_messages (
    message_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id           BIGINT NOT NULL REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
    message_role         VARCHAR(20) NOT NULL,
    content              TEXT NOT NULL,
    model_name           VARCHAR(100),
    response_time_ms     INTEGER,
    token_count          INTEGER,
    status                VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    reported_at          TIMESTAMPTZ,
    report_reason        TEXT,
    reviewed_by          BIGINT REFERENCES users(user_id),
    reviewed_at          TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_chat_role CHECK (message_role IN ('USER','ASSISTANT','SYSTEM')),
    CONSTRAINT ck_chat_message_status CHECK (status IN ('PROCESSING','COMPLETED','FAILED','FALLBACK')),
    CONSTRAINT ck_chat_response_time CHECK (response_time_ms IS NULL OR response_time_ms >= 0),
    CONSTRAINT ck_chat_tokens CHECK (token_count IS NULL OR token_count >= 0),
    CONSTRAINT ck_chat_report CHECK (reported_at IS NULL OR report_reason IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS message_retrieval_sources (
    message_id           BIGINT NOT NULL REFERENCES chat_messages(message_id) ON DELETE CASCADE,
    chunk_id             BIGINT NOT NULL REFERENCES knowledge_chunks(chunk_id),
    similarity_score     NUMERIC(8,6),
    rank_order           INTEGER NOT NULL,
    PRIMARY KEY (message_id, chunk_id),
    CONSTRAINT ck_retrieval_score CHECK (similarity_score IS NULL OR similarity_score BETWEEN -1 AND 1),
    CONSTRAINT ck_retrieval_rank CHECK (rank_order > 0)
);

-- ============================================================
-- 8. NOTIFICATIONS AND STUDY REMINDERS (VERSION 1.1)
-- ============================================================

CREATE TABLE IF NOT EXISTS notifications (
    notification_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    notification_type    VARCHAR(40) NOT NULL,
    title                 VARCHAR(200) NOT NULL,
    message               TEXT NOT NULL,
    action_url            TEXT,
    is_read               BOOLEAN NOT NULL DEFAULT FALSE,
    read_at               TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at            TIMESTAMPTZ,
    CONSTRAINT ck_notification_read CHECK ((is_read = TRUE AND read_at IS NOT NULL) OR is_read = FALSE)
);

CREATE INDEX IF NOT EXISTS ix_notifications_unread ON notifications(user_id, created_at DESC)
    WHERE is_read = FALSE;

CREATE TABLE IF NOT EXISTS study_reminders (
    reminder_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    days_of_week         SMALLINT[] NOT NULL,
    reminder_time        TIME NOT NULL,
    timezone             VARCHAR(100) NOT NULL,
    enabled              BOOLEAN NOT NULL DEFAULT TRUE,
    last_sent_at         TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_reminder_days CHECK (days_of_week <@ ARRAY[1,2,3,4,5,6,7]::SMALLINT[] AND cardinality(days_of_week) > 0)
);

-- ============================================================
-- 9. OPERATIONS, CONFIGURATION AND AUDIT
-- ============================================================

CREATE TABLE IF NOT EXISTS system_configurations (
    config_key           VARCHAR(100) PRIMARY KEY,
    config_value         TEXT NOT NULL,
    value_type           VARCHAR(20) NOT NULL,
    description          TEXT,
    is_secret            BOOLEAN NOT NULL DEFAULT FALSE,
    is_admin_editable    BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by           BIGINT REFERENCES users(user_id),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_config_type CHECK (value_type IN ('STRING','INTEGER','DECIMAL','BOOLEAN','JSON')),
    CONSTRAINT ck_config_secret_edit CHECK (is_secret = FALSE OR is_admin_editable = FALSE)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    audit_log_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id        BIGINT REFERENCES users(user_id),
    action               VARCHAR(100) NOT NULL,
    entity_type          VARCHAR(100) NOT NULL,
    entity_id            VARCHAR(100),
    old_value            JSONB,
    new_value            JSONB,
    ip_address           INET,
    correlation_id       UUID NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_audit_logs_actor_date ON audit_logs(actor_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_audit_logs_entity ON audit_logs(entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_audit_logs_correlation ON audit_logs(correlation_id);

CREATE TABLE IF NOT EXISTS system_logs (
    system_log_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_level            VARCHAR(10) NOT NULL,
    source               VARCHAR(150) NOT NULL,
    sanitized_message    TEXT NOT NULL,
    correlation_id       UUID,
    exception_type       VARCHAR(255),
    metadata             JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_system_log_level CHECK (log_level IN ('TRACE','DEBUG','INFO','WARN','ERROR'))
);

CREATE INDEX IF NOT EXISTS ix_system_logs_date_level ON system_logs(created_at DESC, log_level);
CREATE INDEX IF NOT EXISTS ix_system_logs_correlation ON system_logs(correlation_id);

-- ============================================================
-- 10. COMMON TRIGGERS AND PROTECTIVE RULES
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DO $$
DECLARE
    table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'users','levels','lessons','vocabulary','kanji','grammar_points',
        'examples','quizzes','reading_contents','listening_contents','questions',
        'learning_progress','user_streaks','flashcard_progress','import_jobs',
        'knowledge_documents','chat_sessions','study_reminders'
    ]
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I', table_name, table_name);
        EXECUTE format(
            'CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
            table_name, table_name
        );
    END LOOP;
END;
$$;

-- Submitted attempts and their answer snapshots are immutable.
CREATE OR REPLACE FUNCTION protect_submitted_attempt()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.status = 'SUBMITTED' THEN
        RAISE EXCEPTION 'Submitted quiz attempts are immutable';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_protect_submitted_attempt ON quiz_attempts;
CREATE TRIGGER trg_protect_submitted_attempt
BEFORE UPDATE OR DELETE ON quiz_attempts
FOR EACH ROW EXECUTE FUNCTION protect_submitted_attempt();

CREATE OR REPLACE FUNCTION protect_submitted_answer()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_status VARCHAR(20);
BEGIN
    SELECT status INTO v_status
    FROM quiz_attempts
    WHERE attempt_id = OLD.attempt_id;

    IF v_status = 'SUBMITTED' THEN
        RAISE EXCEPTION 'Answers of a submitted attempt are immutable';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_protect_submitted_answer ON quiz_attempt_answers;
CREATE TRIGGER trg_protect_submitted_answer
BEFORE UPDATE OR DELETE ON quiz_attempt_answers
FOR EACH ROW EXECUTE FUNCTION protect_submitted_answer();

-- ============================================================
-- 11. INITIAL REFERENCE DATA
-- ============================================================

INSERT INTO roles(role_name, description)
VALUES
    ('LEARNER', 'Người học sử dụng nội dung và theo dõi tiến độ'),
    ('ADMIN', 'Quản trị người dùng, nội dung và vận hành')
ON CONFLICT (role_name) DO NOTHING;

INSERT INTO levels(code, name, description, sort_order, status)
VALUES
    ('N5', 'JLPT N5', 'Trình độ nhập môn', 1, 'PUBLISHED'),
    ('N4', 'JLPT N4', 'Trình độ sơ cấp', 2, 'PUBLISHED'),
    ('N3', 'JLPT N3', 'Trình độ trung cấp', 3, 'PUBLISHED'),
    ('N2', 'JLPT N2', 'Mở rộng trong tương lai', 4, 'DRAFT'),
    ('N1', 'JLPT N1', 'Mở rộng trong tương lai', 5, 'DRAFT')
ON CONFLICT (code) DO NOTHING;

INSERT INTO system_configurations
    (config_key, config_value, value_type, description, is_secret, is_admin_editable)
VALUES
    ('flashcard.dailyNewCardLimit', '20', 'INTEGER', 'Số flashcard mới tối đa mỗi ngày', FALSE, TRUE),
    ('flashcard.algorithmVersion', 'SM2_V1', 'STRING', 'Phiên bản thuật toán spaced repetition', FALSE, TRUE),
    ('ai.requestsPerMinute', '5', 'INTEGER', 'Giới hạn AI request mỗi phút cho một người học', FALSE, TRUE),
    ('ai.requestsPerDay', '20', 'INTEGER', 'Giới hạn AI request mỗi ngày địa phương', FALSE, TRUE),
    ('ai.concurrentRequestsPerUser', '1', 'INTEGER', 'Số AI request đồng thời cho một người học', FALSE, TRUE),
    ('ai.timeoutSeconds', '15', 'INTEGER', 'Timeout cứng của AI Provider', FALSE, FALSE),
    ('auth.accessTokenMinutes', '15', 'INTEGER', 'Thời hạn access token', FALSE, FALSE),
    ('auth.refreshTokenDays', '7', 'INTEGER', 'Thời hạn refresh token', FALSE, FALSE),
    ('import.maxRows', '1000', 'INTEGER', 'Số dòng dữ liệu tối đa trong file import', FALSE, FALSE),
    ('import.maxFileSizeBytes', '10485760', 'INTEGER', 'Kích thước file import tối đa 10 MB', FALSE, FALSE)
ON CONFLICT (config_key) DO NOTHING;

COMMIT;

-- Verification queries (run automatically and return summary rows).
SELECT 'tables_created' AS check_name, COUNT(*)::TEXT AS result
FROM information_schema.tables
WHERE table_schema = 'public' AND table_type = 'BASE TABLE';

SELECT 'roles' AS check_name, STRING_AGG(role_name, ', ' ORDER BY role_name) AS result
FROM roles;

SELECT 'levels' AS check_name, STRING_AGG(code, ', ' ORDER BY sort_order) AS result
FROM levels;
