// Comprehensive Sino-Vietnamese (Âm Hán Việt) & Kanji Meaning Dictionary for JLPT N5 - N3

export interface KanjiCharDetail {
  char: string;
  hanViet: string;
  meaningVi?: string;
}

export interface VocabularyKanjiAnalysis {
  fullHanViet: string;
  details: KanjiCharDetail[];
}

const SINO_VIETNAMESE_MAP: Record<string, { hanViet: string; meaningVi?: string }> = {
  // Lesson 26 + N4 Kanji
  棚: { hanViet: "BẰNG", meaningVi: "Giá, kệ, giàn" },
  箱: { hanViet: "TƯƠNG", meaningVi: "Cái hộp, thùng" },
  窓: { hanViet: "SONG", meaningVi: "Cửa sổ" },
  戸: { hanViet: "HỘ", meaningVi: "Cánh cửa" },
  壁: { hanViet: "BÍCH", meaningVi: "Bức tường" },
  床: { hanViet: "SÀNG", meaningVi: "Sàn nhà" },
  庭: { hanViet: "ĐÌNH", meaningVi: "Sân vườn" },
  池: { hanViet: "TRÌ", meaningVi: "Ao nước" },
  橋: { hanViet: "KIỀU", meaningVi: "Cây cầu" },
  坂: { hanViet: "PHẢN", meaningVi: "Con dốc" },
  袋: { hanViet: "ĐẠI", meaningVi: "Túi, bao" },
  鍵: { hanViet: "KIỆN", meaningVi: "Chìa khóa" },
  帽: { hanViet: "MẠO", meaningVi: "Mũ, nón" },
  靴: { hanViet: "NGOẠC", meaningVi: "Giày" },
  服: { hanViet: "PHỤC", meaningVi: "Quần áo" },
  傘: { hanViet: "TẢN", meaningVi: "Cái ô, dù" },
  鏡: { hanViet: "KÍNH", meaningVi: "Tấm gương" },
  具: { hanViet: "CỤ", meaningVi: "Dụng cụ, đồ dùng" },
  器: { hanViet: "KHÍ", meaningVi: "Dụng cụ, khí cụ" },
  連: { hanViet: "LIÊN", meaningVi: "Liên kết, nối liền" },
  絡: { hanViet: "LẠC", meaningVi: "Liên lạc, dây dợ" },
  診: { hanViet: "CHẨN", meaningVi: "Chẩn đoán, khám bệnh" },
  探: { hanViet: "THÁM", meaningVi: "Tìm kiếm, dò hỏi" },
  遅: { hanViet: "TRÌ", meaningVi: "Chậm trễ, muộn" },
  合: { hanViet: "HỢP", meaningVi: "Thích hợp, vừa vặn" },
  拾: { hanViet: "THẬP", meaningVi: "Nhặt, lượm" },
  場: { hanViet: "TRƯỜNG", meaningVi: "Nơi chốn, địa điểm" },
  所: { hanViet: "SỞ", meaningVi: "Địa điểm, vị trí" },
  財: { hanViet: "TÀI", meaningVi: "Tiền tài, của cải" },
  布: { hanViet: "BỐ", meaningVi: "Vải vóc, tuyên bố" },
  議: { hanViet: "NGHỊ", meaningVi: "Nghị luận, bàn bạc" },
  堂: { hanViet: "ĐƯỜNG", meaningVi: "Nhà lớn, hội trường" },
  平: { hanViet: "BÌNH", meaningVi: "Bằng phẳng, hòa bình" },
  片: { hanViet: "PHIẾN", meaningVi: "Tấm, mảng, một bên" },
  付: { hanViet: "PHÓ", meaningVi: "Gắn vào, giao cho" },
  燃: { hanViet: "NHIÊN", meaningVi: "Cháy, đốt cháy" },
  瓶: { hanViet: "BÌNH", meaningVi: "Chai lọ thủy tinh" },
  缶: { hanViet: "PHẪU", meaningVi: "Vỏ lon" },
  宇: { hanViet: "VŨ", meaningVi: "Vũ trụ, không gian" },
  宙: { hanViet: "TRỤ", meaningVi: "Thời gian, vũ trụ" },
  運: { hanViet: "VẬN", meaningVi: "Vận động, may mắn" },
  動: { hanViet: "ĐỘNG", meaningVi: "Cử động, hoạt động" },
  盆: { hanViet: "BỒN", meaningVi: "Lễ Bon, cái khay" },
  踊: { hanViet: "DŨNG", meaningVi: "Múa, nhảy múa" },
  横: { hanViet: "HOÀNH", meaningVi: "Ngang, bên cạnh" },
  置: { hanViet: "TRÍ", meaningVi: "Đặt, để" },
  弁: { hanViet: "BIỆN", meaningVi: "Biện luận, tiếng địa phương" },
  度: { hanViet: "ĐỘ", meaningVi: "Lần, mức độ" },
  接: { hanViet: "TIẾP", meaningVi: "Gặp gỡ, tiếp xúc" },
  勝: { hanViet: "THẮNG", meaningVi: "Thắng lợi" },
  負: { hanViet: "PHỤ", meaningVi: "Thua, gánh vác" },
  受: { hanViet: "THỤ", meaningVi: "Nhận, tiếp nhận" },
  開: { hanViet: "KHAI", meaningVi: "Mở, khai mạc" },
  閉: { hanViet: "BẾ", meaningVi: "Đóng, bế mạc" },
  集: { hanViet: "TẬP", meaningVi: "Tập hợp, gom lại" },
  換: { hanViet: "HOÁN", meaningVi: "Đổi, trao đổi" },
  変: { hanViet: "BIẾN", meaningVi: "Thay đổi, biến đổi" },
  止: { hanViet: "CHỈ", meaningVi: "Dừng lại, đình chỉ" },
  整: { hanViet: "CHỈNH", meaningVi: "Sắp xếp, chỉnh sửa" },
  理: { hanViet: "LÝ", meaningVi: "Quản lý, nguyên lý" },
  落: { hanViet: "LẠC", meaningVi: "Rơi, rụng" },
  壊: { hanViet: "HOẠI", meaningVi: "Hỏng, phá hủy" },
  直: { hanViet: "TRỰC", meaningVi: "Trực tiếp, sửa chữa" },
  割: { hanViet: "CÁT", meaningVi: "Vỡ, chia ra" },

  // N5 Core Kanji
  私: { hanViet: "TƯ", meaningVi: "Cá nhân, riêng tư" },
  人: { hanViet: "NHÂN", meaningVi: "Con người" },
  方: { hanViet: "PHƯƠNG", meaningVi: "Hướng, ngài, vị" },
  名: { hanViet: "DANH", meaningVi: "Tên, danh tiếng" },
  前: { hanViet: "TIỀN", meaningVi: "Phía trước, trước đây" },
  本: { hanViet: "BẢN", meaningVi: "Gốc, sách, nguồn" },
  語: { hanViet: "NGỮ", meaningVi: "Ngôn ngữ, từ ngữ" },
  学: { hanViet: "HỌC", meaningVi: "Học tập, trường học" },
  校: { hanViet: "GIÁO", meaningVi: "Trường học" },
  生: { hanViet: "SINH", meaningVi: "Sinh sống, học sinh" },
  先: { hanViet: "TIÊN", meaningVi: "Trước, tiên sinh" },
  会: { hanViet: "HỘI", meaningVi: "Gặp gỡ, hội họp" },
  社: { hanViet: "XÃ", meaningVi: "Xã hội, công ty" },
  員: { hanViet: "VIÊN", meaningVi: "Thành viên, nhân viên" },
  銀: { hanViet: "NGÂN", meaningVi: "Bạc, ngân hàng" },
  行: { hanViet: "HÀNH", meaningVi: "Đi, thực hành" },
  医: { hanViet: "Y", meaningVi: "Y học, bác sĩ" },
  者: { hanViet: "GIẢ", meaningVi: "Người" },
  研: { hanViet: "NGHIÊN", meaningVi: "Nghiên cứu" },
  究: { hanViet: "CỨU", meaningVi: "Nghiên cứu, tìm hiểu" },
  病: { hanViet: "BỆNH", meaningVi: "Bệnh tật" },
  院: { hanViet: "VIỆN", meaningVi: "Bệnh viện, học viện" },
  電: { hanViet: "ĐIỆN", meaningVi: "Điện năng" },
  車: { hanViet: "XA", meaningVi: "Xe cộ" },
  気: { hanViet: "KHÍ", meaningVi: "Khí chất, tinh thần" },
  年: { hanViet: "NIÊN", meaningVi: "Năm, tuổi" },
  歳: { hanViet: "TUẾ", meaningVi: "Tuổi" },
  日: { hanViet: "NHẬT", meaningVi: "Ngày, mặt trời" },
  月: { hanViet: "NGUYỆT", meaningVi: "Tháng, mặt trăng" },
  火: { hanViet: "HỎA", meaningVi: "Lửa" },
  水: { hanViet: "THỦY", meaningVi: "Nước" },
  木: { hanViet: "MỘC", meaningVi: "Cây, gỗ" },
  金: { hanViet: "KIM", meaningVi: "Vàng, tiền" },
  土: { hanViet: "THỔ", meaningVi: "Đất" },
  何: { hanViet: "HÀ", meaningVi: "Cái gì" },
  時: { hanViet: "THỜI", meaningVi: "Thời gian, giờ" },
  分: { hanViet: "PHÂN", meaningVi: "Phút, phân chia" },
  半: { hanViet: "BÁN", meaningVi: "Một nửa" },
  今: { hanViet: "KIM", meaningVi: "Bây giờ, hiện tại" },
  朝: { hanViet: "TRIÊU", meaningVi: "Buổi sáng" },
  昼: { hanViet: "TRÚ", meaningVi: "Buổi trưa" },
  晩: { hanViet: "VÃN", meaningVi: "Buổi tối" },
  夜: { hanViet: "DẠ", meaningVi: "Ban đêm" },
  休: { hanViet: "HƯU", meaningVi: "Nghỉ ngơi" },
  切: { hanViet: "THIẾT", meaningVi: "Cắt, thân thiết" },
  貸: { hanViet: "THẢI", meaningVi: "Cho mượn" },
  借: { hanViet: "TÁ", meaningVi: "Vay, mượn" },
  送: { hanViet: "TỐNG", meaningVi: "Gửi, đưa tiễn" },
  買: { hanViet: "MÃI", meaningVi: "Mua" },
  売: { hanViet: "MẠI", meaningVi: "Bán" },
  食: { hanViet: "THỰC", meaningVi: "Ăn, thực phẩm" },
  飲: { hanViet: "ẨM", meaningVi: "Uống" },
  見: { hanViet: "KIẾN", meaningVi: "Nhìn, xem" },
  聞: { hanViet: "VĂN", meaningVi: "Nghe, lắng nghe" },
  読: { hanViet: "ĐỌC", meaningVi: "Đọc sách" },
  書: { hanViet: "THƯ", meaningVi: "Viết, sách" },
  話: { hanViet: "THOẠI", meaningVi: "Nói chuyện, thoại" },
  教: { hanViet: "GIÁO", meaningVi: "Dạy dỗ, tôn giáo" },
  習: { hanViet: "TẬP", meaningVi: "Luyện tập, học tập" },
  勉: { hanViet: "MIỄN", meaningVi: "Cố gắng, gượng ép" },
  強: { hanViet: "CƯỜNG", meaningVi: "Mạnh mẽ" },
  働: { hanViet: "ĐỘNG", meaningVi: "Làm việc" },
  終: { hanViet: "CHUNG", meaningVi: "Kết thúc, cuối cùng" },
  始: { hanViet: "THỦY", meaningVi: "Bắt đầu" },
  帰: { hanViet: "QUY", meaningVi: "Trở về" },
  出: { hanViet: "XUẤT", meaningVi: "Ra ngoài, xuất hiện" },
  入: { hanViet: "NHẬP", meaningVi: "Vào, nhập vào" },
  立: { hanViet: "LẬP", meaningVi: "Đứng, thành lập" },
  座: { hanViet: "TỌA", meaningVi: "Chỗ ngồi, ngồi" },
  持: { hanViet: "TRÌ", meaningVi: "Cầm, giữ" },
  待: { hanViet: "ĐÃI", meaningVi: "Chờ đợi" },
  手: { hanViet: "THỦ", meaningVi: "Bàn tay" },
  足: { hanViet: "TÚC", meaningVi: "Chân, đầy đủ" },
  目: { hanViet: "MỤC", meaningVi: "Mắt, hạng mục" },
  口: { hanViet: "KHẨU", meaningVi: "Miệng, cổng" },
  耳: { hanViet: "NHĨ", meaningVi: "Lỗ tai" },
  頭: { hanViet: "ĐẦU", meaningVi: "Cái đầu" },
  心: { hanViet: "TÂM", meaningVi: "Trái tim, tâm trí" },
  友: { hanViet: "HỮU", meaningVi: "Bạn bè" },
  達: { hanViet: "ĐẠT", meaningVi: "Đạt tới, các bạn" },
  家: { hanViet: "GIA", meaningVi: "Ngôi nhà, gia đình" },
  国: { hanViet: "QUỐC", meaningVi: "Đất nước, quốc gia" },
  町: { hanViet: "ĐINH", meaningVi: "Khu phố, thị trấn" },
  山: { hanViet: "SƠN", meaningVi: "Núi" },
  川: { hanViet: "XUYÊN", meaningVi: "Sông" },
  花: { hanViet: "HOA", meaningVi: "Bông hoa" },
  雨: { hanViet: "VŨ", meaningVi: "Cơn mưa" },
  天: { hanViet: "THIÊN", meaningVi: "Trời, thiên nhiên" },
  空: { hanViet: "KHÔNG", meaningVi: "Bầu trời, trống rỗng" },
  赤: { hanViet: "XÍCH", meaningVi: "Màu đỏ" },
  青: { hanViet: "THANH", meaningVi: "Màu xanh" },
  白: { hanViet: "BẠCH", meaningVi: "Màu trắng" },
  黒: { hanViet: "HẮC", meaningVi: "Màu đen" },
  高: { hanViet: "CAO", meaningVi: "Cao, đắt tiền" },
  安: { hanViet: "AN", meaningVi: "An toàn, rẻ" },
  大: { hanViet: "ĐẠI", meaningVi: "To lớn" },
  小: { hanViet: "TIỂU", meaningVi: "Nhỏ bé" },
  新: { hanViet: "TÂN", meaningVi: "Mới" },
  古: { hanViet: "CỔ", meaningVi: "Cũ, cổ xưa" },
  多: { hanViet: "ĐA", meaningVi: "Nhiều" },
  少: { hanViet: "THIỂU", meaningVi: "Ít" },
  長: { hanViet: "TRƯỜNG", meaningVi: "Dài, trưởng" },
  短: { hanViet: "ĐOẢN", meaningVi: "Ngắn" },
  重: { hanViet: "TRỌNG", meaningVi: "Nặng, coi trọng" },
  軽: { hanViet: "KHINH", meaningVi: "Nhẹ" },
  好: { hanViet: "HẢO", meaningVi: "Thích, tốt" },
  上: { hanViet: "THƯỢNG", meaningVi: "Phía trên" },
  下: { hanViet: "HẠ", meaningVi: "Phía dưới" },
  中: { hanViet: "TRUNG", meaningVi: "Bên trong, trung tâm" },
  外: { hanViet: "NGOẠI", meaningVi: "Bên ngoài, ngoại quốc" },
  右: { hanViet: "HỮU", meaningVi: "Bên phải" },
  左: { hanViet: "TẢ", meaningVi: "Bên trái" },
  北: { hanViet: "BẮC", meaningVi: "Phía Bắc" },
  南: { hanViet: "NAM", meaningVi: "Phía Nam" },
  東: { hanViet: "ĐÔNG", meaningVi: "Phía Đông" },
  西: { hanViet: "TÂY", meaningVi: "Phía Tây" },

  // Numbers & Family & N5 Supplemental
  一: { hanViet: "NHẤT", meaningVi: "Số một" },
  二: { hanViet: "NHỊ", meaningVi: "Số hai" },
  三: { hanViet: "TAM", meaningVi: "Số ba" },
  四: { hanViet: "TỨ", meaningVi: "Số bốn" },
  五: { hanViet: "NGŨ", meaningVi: "Số năm" },
  六: { hanViet: "LỤC", meaningVi: "Số sáu" },
  七: { hanViet: "THẤT", meaningVi: "Số bảy" },
  八: { hanViet: "BÁT", meaningVi: "Số tám" },
  九: { hanViet: "CỬU", meaningVi: "Số chín" },
  十: { hanViet: "THẬP", meaningVi: "Số mười" },
  百: { hanViet: "BÁCH", meaningVi: "Trăm" },
  千: { hanViet: "THIÊN", meaningVi: "Nghìn" },
  万: { hanViet: "VẠN", meaningVi: "Mười nghìn" },
  円: { hanViet: "YÊN", meaningVi: "Đồng Yên Nhật, tròn" },
  父: { hanViet: "PHỤ", meaningVi: "Cha, bố" },
  母: { hanViet: "MẪU", meaningVi: "Mẹ" },
  兄: { hanViet: "HUYNH", meaningVi: "Anh trai" },
  姉: { hanViet: "TỶ", meaningVi: "Chị gái" },
  弟: { hanViet: "ĐỆ", meaningVi: "Em trai" },
  妹: { hanViet: "MUỘI", meaningVi: "Em gái" },
  夫: { hanViet: "PHU", meaningVi: "Chồng" },
  妻: { hanViet: "THÊ", meaningVi: "Vợ" },
  子: { hanViet: "TỬ", meaningVi: "Con cái, trẻ em" },
  男: { hanViet: "NAM", meaningVi: "Nam giới, đàn ông" },
  女: { hanViet: "NỮ", meaningVi: "Nữ giới, phụ nữ" },
  親: { hanViet: "THÂN", meaningVi: "Cha mẹ, thân thiết" },

  // N4 Additional Kanji
  洗: { hanViet: "TẨY", meaningVi: "Rửa, giặt" },
  走: { hanViet: "TẨU", meaningVi: "Chạy" },
  泳: { hanViet: "VỊNH", meaningVi: "Bơi" },
  飛: { hanViet: "PHI", meaningVi: "Bay" },
  乗: { hanViet: "THỪA", meaningVi: "Cưỡi, lên xe" },
  降: { hanViet: "HÀNG", meaningVi: "Xuống xe, rơi" },
  着: { hanViet: "TRƯỚC", meaningVi: "Mặc áo, đến nơi" },
  脱: { hanViet: "THOÁT", meaningVi: "Cởi ra, thoát khỏi" },
  押: { hanViet: "ÁP", meaningVi: "Ấn, ấn nút" },
  引: { hanViet: "DẪN", meaningVi: "Kéo, dẫn dắt" },
  広: { hanViet: "QUẢNG", meaningVi: "Rộng rãi" },
  狭: { hanViet: "HIỆP", meaningVi: "Hẹp" },
  暗: { hanViet: "ÁM", meaningVi: "Tối, u ám" },
  明: { hanViet: "MINH", meaningVi: "Sáng, rõ ràng" },
  速: { hanViet: "TỐC", meaningVi: "Nhanh chóng, tốc độ" },
  遠: { hanViet: "VIỄN", meaningVi: "Xa" },
  近: { hanViet: "CẬN", meaningVi: "Gần" },
  弱: { hanViet: "NHƯỢC", meaningVi: "Yếu" },
  暑: { hanViet: "THỬ", meaningVi: "Nóng (thời tiết)" },
  寒: { hanViet: "HÀN", meaningVi: "Lạnh (thời tiết)" },
  熱: { hanViet: "NHIỆT", meaningVi: "Nóng, sốt" },
  冷: { hanViet: "LÃNH", meaningVi: "Lạnh (vật thể)" },
  甘: { hanViet: "CAM", meaningVi: "Ngọt" },
  辛: { hanViet: "TÂN", meaningVi: "Cay" },
  苦: { hanViet: "KHỔ", meaningVi: "Đắng, đau khổ" },
  塩: { hanViet: "DIÊM", meaningVi: "Muối" },
  味: { hanViet: "VỊ", meaningVi: "Hương vị" },
  田: { hanViet: "ĐIỀN", meaningVi: "Ruộng" },
  畑: { hanViet: "HẠCH", meaningVi: "Nương rẫy" },
  森: { hanViet: "SÂM", meaningVi: "Rừng rậm" },
  林: { hanViet: "LÂM", meaningVi: "Rừng cây" },
  風: { hanViet: "PHONG", meaningVi: "Gió" },
  雪: { hanViet: "TUYẾT", meaningVi: "Tuyết" },
  雲: { hanViet: "VÂN", meaningVi: "Mây" },
  晴: { hanViet: "TÌNH", meaningVi: "Nắng, trời quang" },
  陰: { hanViet: "ÂM", meaningVi: "Bóng râm, u ám" },
  春: { hanViet: "XUÂN", meaningVi: "Mùa xuân" },
  夏: { hanViet: "HẠ", meaningVi: "Mùa hè" },
  秋: { hanViet: "THU", meaningVi: "Mùa thu" },
  冬: { hanViet: "ĐÔNG", meaningVi: "Mùa đông" },
  週: { hanViet: "CHU", meaningVi: "Tuần" },
  昔: { hanViet: "TÍCH", meaningVi: "Ngày xưa" },
  去: { hanViet: "KHỨ", meaningVi: "Quá quá, đã qua" },
  来: { hanViet: "LAI", meaningVi: "Đến, tương lai" },
  毎: { hanViet: "MỖI", meaningVi: "Mỗi, hàng" },
  回: { hanViet: "HỒI", meaningVi: "Lần, quay lại" },
  番: { hanViet: "PHIÊN", meaningVi: "Số thứ tự, lượt" },
  号: { hanViet: "HỆU", meaningVi: "Số hiệu, tên gọi" },
  館: { hanViet: "QUÁN", meaningVi: "Tòa nhà, hội quán" },
  室: { hanViet: "THẤT", meaningVi: "Phòng" },
  屋: { hanViet: "ỐC", meaningVi: "Mái nhà, cửa hàng" },
  店: { hanViet: "ĐIẾM", meaningVi: "Cửa hàng" },
  駅: { hanViet: "DỊCH", meaningVi: "Nhà ga" },
  港: { hanViet: "CẢNG", meaningVi: "Bến cảng" },
  薬: { hanViet: "DƯỢC", meaningVi: "Thuốc" },
  法: { hanViet: "PHÁP", meaningVi: "Pháp luật" },
  律: { hanViet: "LUẬT", meaningVi: "Luật lệ" },
  政: { hanViet: "CHÍNH", meaningVi: "Chính trị" },
  治: { hanViet: "TRỊ", meaningVi: "Chữa trị, quản lý" },
  経: { hanViet: "KINH", meaningVi: "Kinh tế, trải qua" },
  済: { hanViet: "TẾ", meaningVi: "Kinh tế, hoàn thành" },
  商: { hanViet: "THƯƠNG", meaningVi: "Thương mại, buôn bán" },
  工: { hanViet: "CÔNG", meaningVi: "Công nghiệp, thợ" },
  農: { hanViet: "NÔNG", meaningVi: "Nông nghiệp" },
  建: { hanViet: "KIẾN", meaningVi: "Xây dựng" },
  設: { hanViet: "THIẾT", meaningVi: "Thiết lập, thiết kế" },
  計: { hanViet: "KẾ", meaningVi: "Kế hoạch, đo đạc" },
  画: { hanViet: "HỌA", meaningVi: "Bức tranh, kế hoạch" },
  意: { hanViet: "Ý", meaningVi: "Ý kiến, ý nghĩ" },
  思: { hanViet: "TƯ", meaningVi: "Suy nghĩ" },
  考: { hanViet: "KHẢO", meaningVi: "Suy nghĩ, khảo sát" },
  知: { hanViet: "TRI", meaningVi: "Biết, tri thức" },
  問: { hanViet: "VẤN", meaningVi: "Hỏi, câu hỏi" },
  題: { hanViet: "ĐỀ", meaningVi: "Chủ đề, đề bài" },
  答: { hanViet: "ĐÁP", meaningVi: "Trả lời, đáp án" },
  案: { hanViet: "ÁN", meaningVi: "Đề án, phương án" },
  試: { hanViet: "THÍ", meaningVi: "Thử nghiệm, thi" },
  験: { hanViet: "NGHIỆM", meaningVi: "Thí nghiệm, kiểm nghiệm" },
  育: { hanViet: "DỤC", meaningVi: "Nuôi dưỡng, giáo dục" },
  復: { hanViet: "PHỤC", meaningVi: "Phục hồi, ôn tập" },
  練: { hanViet: "LUYỆN", meaningVi: "Luyện tập" },
  質: { hanViet: "CHẤT", meaningVi: "Chất lượng, câu hỏi" },
  疑: { hanViet: "NGHI", meaningVi: "Nghi ngờ, nghi vấn" },
  論: { hanViet: "LUẬN", meaningVi: "Lý luận, thảo luận" },
  説: { hanViet: "THUYẾT", meaningVi: "Giải thích, tiểu thuyết" },
  章: { hanViet: "CHƯƠNG", meaningVi: "Chương sách, bài văn" },
  言: { hanViet: "NGÔN", meaningVi: "Lời nói, ngôn ngữ" },
  告: { hanViet: "CÁO", meaningVi: "Thông báo, báo cáo" },
  伝: { hanViet: "TRUYỀN", meaningVi: "Truyền đạt, truyền tin" },
  報: { hanViet: "BÁO", meaningVi: "Báo cáo, thông báo" },
  呼: { hanViet: "HÔ", meaningVi: "Gọi, hô hoán" },
  取: { hanViet: "THỦ", meaningVi: "Lấy, đón lấy" },
  渡: { hanViet: "ĐỘ", meaningVi: "Băng qua, trao cho" },
  払: { hanViet: "PHẤT", meaningVi: "Thanh toán, trả tiền" },
  費: { hanViet: "PHÍ", meaningVi: "Chi phí" },
  銅: { hanViet: "ĐỒNG", meaningVi: "Kim loại đồng" },
  鉄: { hanViet: "THIẾT", meaningVi: "Sắt" },
  油: { hanViet: "DU", meaningVi: "Dầu" },
  光: { hanViet: "QUANG", meaningVi: "Ánh sáng" },
  色: { hanViet: "SẮC", meaningVi: "Màu sắc" },
  音: { hanViet: "ÂM", meaningVi: "Âm thanh" },
  声: { hanViet: "THANH", meaningVi: "Giọng nói, tiếng" },
  歌: { hanViet: "CA", meaningVi: "Bài hát, hát" },
  真: { hanViet: "CHÂN", meaningVi: "Chân thật, hình ảnh" },
  図: { hanViet: "ĐỒ", meaningVi: "Bản đồ, biểu đồ" },
  写: { hanViet: "TẢ", meaningVi: "Sao chép, chụp ảnh" },
  像: { hanViet: "TƯỢNG", meaningVi: "Hình tượng, bức tượng" },
  表: { hanViet: "BIỂU", meaningVi: "Bảng biểu, mặt ngoài" },
  後: { hanViet: "HẬU", meaningVi: "Phía sau, sau này" },
  内: { hanViet: "NỘI", meaningVi: "Bên trong, nội bộ" },
  間: { hanViet: "GIAN", meaningVi: "Khoảng cách, thời gian" },
  向: { hanViet: "HƯỚNG", meaningVi: "Hướng về" },
  角: { hanViet: "GIÁC", meaningVi: "Góc, sừng" },
  端: { hanViet: "ĐOAN", meaningVi: "Đầu mút, mép" },
  位: { hanViet: "VỊ", meaningVi: "Vị trí" },
  点: { hanViet: "ĐIỂM", meaningVi: "Điểm số, chấm" },
  線: { hanViet: "TUYẾN", meaningVi: "Đường dây, tuyến" },
  面: { hanViet: "DIỆN", meaningVi: "Mặt, bề mặt" },
  体: { hanViet: "THỂ", meaningVi: "Cơ thể, thể chất" },
  顔: { hanViet: "NHAN", meaningVi: "Khuôn mặt" },
  歯: { hanViet: "XỈ", meaningVi: "Răng" },
  指: { hanViet: "CHỈ", meaningVi: "Ngón tay, chỉ trỏ" },
  背: { hanViet: "BỐI", meaningVi: "Lưng, chiều cao" },
  腹: { hanViet: "PHÚC", meaningVi: "Bụng" },
  骨: { hanViet: "CỐT", meaningVi: "Xương" },
  血: { hanViet: "HUYẾT", meaningVi: "Máu" },
  皮: { hanViet: "BÌ", meaningVi: "Da, vỏ" },
  肉: { hanViet: "NHỤC", meaningVi: "Thịt" },
  身: { hanViet: "THÂN", meaningVi: "Thân thể, bản thân" },
  力: { hanViet: "LỰC", meaningVi: "Sức lực, sức mạnh" },
  命: { hanViet: "MỆNH", meaningVi: "Tính mạng, số mệnh" },
  痛: { hanViet: "THỐNG", meaningVi: "Đau đớn" },
  感: { hanViet: "CẢM", meaningVi: "Cảm giác, cảm xúc" },
  情: { hanViet: "TÌNH", meaningVi: "Tình cảm, tình hình" },
  愛: { hanViet: "ÁI", meaningVi: "Tình yêu, yêu thương" },
  喜: { hanViet: "HỶ", meaningVi: "Vui mừng" },
  怒: { hanViet: "NỘ", meaningVi: "Tức giận" },
  哀: { hanViet: "AI", meaningVi: "Thương ai, buồn bã" },
  楽: { hanViet: "LẠC", meaningVi: "Vui vẻ, âm nhạc" },
  望: { hanViet: "VỌNG", meaningVi: "Hi vọng, ước vọng" },
  願: { hanViet: "NGUYỆN", meaningVi: "Nguyện vọng, cầu mong" },
  欲: { hanViet: "DỤC", meaningVi: "Muốn, ham muốn" },
  要: { hanViet: "YẾU", meaningVi: "Cần thiết, quan trọng" },
  必: { hanViet: "TẤT", meaningVi: "Tất nhiên, nhất định" },
  利: { hanViet: "LỢI", meaningVi: "Lợi ích, thuận lợi" },
  害: { hanViet: "HẠI", meaningVi: "Tổn hại, tác hại" },
  成: { hanViet: "THÀNH", meaningVi: "Thành công, trở thành" },
  功: { hanViet: "CÔNG", meaningVi: "Thành công, công lao" },
  敗: { hanViet: "BẠI", meaningVi: "Thất bại" },
  失: { hanViet: "THẤT", meaningVi: "Mất mát, thất bại" },
  確: { hanViet: "XÁC", meaningVi: "Xác thực, chính xác" },
  定: { hanViet: "ĐỊNH", meaningVi: "Quyết định, cố định" },
  約: { hanViet: "ƯỚC", meaningVi: "Hẹn ước, khoảng" },
  束: { hanViet: "THÚC", meaningVi: "Bó, ràng buộc" },
  守: { hanViet: "THỦ", meaningVi: "Bảo vệ, giữ gìn" },
  破: { hanViet: "PHÁ", meaningVi: "Rách, phá vỡ" },
  化: { hanViet: "HÓA", meaningVi: "Thay đổi, biến hóa" },
  進: { hanViet: "TIẾN", meaningVi: "Tiến lên, tiến bộ" },
  退: { hanViet: "THOÁI", meaningVi: "Rút lui, thoái lùi" },
  発: { hanViet: "PHÁT", meaningVi: "Phát triển, xuất phát" },
  起: { hanViet: "KHỞI", meaningVi: "Thức dậy, khởi đầu" },
  寝: { hanViet: "TẨM", meaningVi: "Ngủ" },
  歩: { hanViet: "BỘ", meaningVi: "Đi bộ, bước đi" },
  跳: { hanViet: "KHIÊU", meaningVi: "Nhảy" },
  浴: { hanViet: "DỤC", meaningVi: "Tắm" },
  吸: { hanViet: "HẤP", meaningVi: "Hít vào, hút" },
  吐: { hanViet: "THỔ", meaningVi: "Nôn ra, nhổ" },
  吹: { hanViet: "XUY", meaningVi: "Thổi (gió, còi)" },
  鳴: { hanViet: "MINH", meaningVi: "Hót, reo (chuông)" },
  視: { hanViet: "THỊ", meaningVi: "Thị giác, quan sát" },
  描: { hanViet: "MIÊU", meaningVi: "Vẽ, miêu tả" },
  塗: { hanViet: "ĐỒ", meaningVi: "Sơn, quét" },
  折: { hanViet: "CHIẾT", meaningVi: "Bẻ gãy, gấp lại" },
  修: { hanViet: "TU", meaningVi: "Sửa chữa, tu dưỡng" },
  備: { hanViet: "BỊ", meaningVi: "Chuẩn bị, trang bị" },
  選: { hanViet: "TUỂN", meaningVi: "Tuyển chọn, lựa chọn" },
  択: { hanViet: "TRẠCH", meaningVi: "Lựa chọn" },
  過: { hanViet: "QUÁ", meaningVi: "Đi qua, quá mức" },
  通: { hanViet: "THÔNG", meaningVi: "Đi qua, giao thông" },
  迎: { hanViet: "NGHÊNH", meaningVi: "Đón tiếp" },
  追: { hanViet: "TRUY", meaningVi: "Đuổi theo" },
  逃: { hanViet: "ĐÀO", meaningVi: "Chạy trốn" },
  捕: { hanViet: "BỘ", meaningVi: "Bắt giữ" },
  伴: { hanViet: "BẠN", meaningVi: "Đi cùng, bạn đồng hành" },
  散: { hanViet: "TẢN", meaningVi: "Tản bộ, phân tán" },
  離: { hanViet: "LY", meaningVi: "Rời xa, ly khai" },
  残: { hanViet: "TÀN", meaningVi: "Còn lại, tàn dư" },
  続: { hanViet: "TỤC", meaningVi: "Tiếp tục" },
  停: { hanViet: "ĐÌNH", meaningVi: "Dừng lại, đình chỉ" },
  防: { hanViet: "PHÒNG", meaningVi: "Phòng ngừa, bảo vệ" },
  救: { hanViet: "CỨU", meaningVi: "Cứu giúp, giải cứu" },
  助: { hanViet: "TRỢ", meaningVi: "Giúp đỡ, hỗ trợ" },
  争: { hanViet: "TRANH", meaningVi: "Tranh chấp, cạnh tranh" },
  戦: { hanViet: "CHIẾN", meaningVi: "Chiến đấu, chiến tranh" },
  和: { hanViet: "HÒA", meaningVi: "Hòa bình, hài hòa" },
};

/**
 * Checks if a character is Japanese Kanji (CJK Unified Ideographs)
 */
export function isKanjiChar(ch: string): boolean {
  return /[\u4e00-\u9faf\u3400-\u4dbf]/.test(ch);
}

/**
 * Single character lookup for Sino-Vietnamese reading
 */
export function getSinoVietnamese(kanjiChar?: string): string {
  if (!kanjiChar) return "";
  return SINO_VIETNAMESE_MAP[kanjiChar]?.hanViet || "";
}

/**
 * Returns joined string of Sino-Vietnamese readings (e.g. "LIÊN LẠC")
 */
export function getSinoVietnameseReading(kanjiStr?: string): string {
  if (!kanjiStr) return "";

  const chars = kanjiStr.split("");
  const sinoList: string[] = [];

  for (const ch of chars) {
    if (SINO_VIETNAMESE_MAP[ch]) {
      sinoList.push(SINO_VIETNAMESE_MAP[ch].hanViet);
    }
  }

  return sinoList.join(" ");
}

/**
 * Detailed breakdown analysis for each Kanji character in a word
 */
export function getVocabularyKanjiAnalysis(kanjiStr?: string): VocabularyKanjiAnalysis | null {
  if (!kanjiStr) return null;

  const chars = kanjiStr.split("");
  const details: KanjiCharDetail[] = [];
  const fullHanList: string[] = [];

  for (const ch of chars) {
    if (isKanjiChar(ch)) {
      const info = SINO_VIETNAMESE_MAP[ch];
      const hanViet = info ? info.hanViet : ch;
      const meaningVi = info?.meaningVi;

      fullHanList.push(hanViet);
      details.push({
        char: ch,
        hanViet,
        meaningVi,
      });
    }
  }

  if (details.length === 0) return null;

  return {
    fullHanViet: fullHanList.join(" "),
    details,
  };
}
