// Sino-Vietnamese (Âm Hán Việt) Dictionary Mapping for Japanese Kanji
const SINO_VIETNAMESE_MAP: Record<string, string> = {
  私: "TƯ",
  人: "NHÂN",
  方: "PHƯƠNG",
  名: "DANH",
  前: "TIỀN",
  本: "BẢN",
  語: "NGỮ",
  学: "HỌC",
  校: "GIÁO",
  生: "SINH",
  先: "TIÊN",
  会: "HỘI",
  社: "XÃ",
  員: "VIÊN",
  銀: "NGÂN",
  行: "HÀNH",
  医: "Y",
  者: "GIẢ",
  研: "NGHIÊN",
  究: "CỨU",
  病: "BỆNH",
  院: "VIỆN",
  電: "ĐIỆN",
  車: "XA",
  気: "KHÍ",
  年: "NIÊN",
  歳: "TUẾ",
  日: "NHẬT",
  月: "NGUYỆT",
  火: "HỎA",
  水: "THỦY",
  木: "MỘC",
  金: "KIM",
  土: "THỔ",
  何: "HÀ",
  時: "THỜI",
  分: "PHÂN",
  半: "BÁN",
  今: "KIM",
  朝: "TRIÊU",
  昼: "TRÚ",
  晩: "VÃN",
  夜: "DẠ",
  休: "HƯU",
  切: "THIẾT",
  貸: "THẢI",
  借: "TÁ",
  送: "TỐNG",
  買: "MÃI",
  売: "MẠI",
  食: "THỰC",
  飲: "ẨM",
  見: "KIẾN",
  聞: "VĂN",
  読: "ĐỌC",
  書: "THƯ",
  話: "THOẠI",
  教: "GIÁO",
  習: "TẬP",
  勉: "MIỄN",
  強: "CƯỜNG",
  動: "ĐỘNG",
  働: "ĐỘNG",
  終: "CHUNG",
  始: "THỦY",
  帰: "QUY",
  出: "XUẤT",
  入: "NHẬP",
  立: "LẬP",
  座: "TỌA",
  持: "TRÌ",
  待: "ĐÃI",
  手: "THỦ",
  足: "TÚC",
  目: "MỤC",
  口: "KHẨU",
  耳: "NHĨ",
  頭: "ĐẦU",
  心: "TÂM",
  友: "HỮU",
  達: "ĐẠT",
  家: "GIA",
  国: "QUỐC",
  町: "ĐINH",
  山: "SƠN",
  川: "XUYÊN",
  花: "HOA",
  雨: "VŨ",
  天: "THIÊN",
  空: "KHÔNG",
  赤: "XÍCH",
  青: "THANH",
  白: "BẠCH",
  黒: "HẮC",
  高: "CAO",
  安: "AN",
  大: "ĐẠI",
  小: "TIỂU",
  新: "TÂN",
  古: "CỔ",
  多: "ĐA",
  少: "THIỂU",
  長: "TRƯỜNG",
  短: "ĐOẢN",
  重: "TRỌNG",
  軽: "KHINH",
  好: "HẢO",
  上: "THƯỢNG",
  下: "HẠ",
  中: "TRUNG",
  外: "NGOẠI",
  右: "HỮU",
  左: "TẢ",
  北: "BẮC",
  南: "NAM",
  東: "ĐÔNG",
  西: "TÂY",
};

/**
 * Extracts Sino-Vietnamese (Âm Hán Việt) reading for any Japanese Kanji string
 */
export function getSinoVietnamese(kanjiChar?: string): string {
  if (!kanjiChar) return "";
  return SINO_VIETNAMESE_MAP[kanjiChar] || "";
}

export function getSinoVietnameseReading(kanjiStr?: string): string {
  if (!kanjiStr) return "";

  const chars = kanjiStr.split("");
  const sinoList: string[] = [];

  for (const ch of chars) {
    if (SINO_VIETNAMESE_MAP[ch]) {
      sinoList.push(SINO_VIETNAMESE_MAP[ch]);
    }
  }

  return sinoList.join(" ");
}
