import { LessonData } from "./LessonCard";
import { LevelItem } from "./LevelSidebar";

export const MOCK_LEVELS: LevelItem[] = [
  { id: "N5", name: "Sơ cấp" },
  { id: "N4", name: "Sơ trung cấp" },
  { id: "N3", name: "Trung cấp" },
  { id: "N2", name: "Trung cao cấp" },
  { id: "N1", name: "Cao cấp" },
];

export const MOCK_LESSONS_DATA: Record<string, LessonData[]> = {
  N5: [
    { 
      id: 1, 
      level: "N5", 
      lessonNumber: 1, 
      title: "Bài 1: Giới thiệu bản thân & Chào hỏi (わたしは～です)", 
      description: "Giới thiệu tên, quốc tịch, nghề nghiệp, câu chào hỏi ban đầu", 
      topicCount: 7, 
      exerciseCount: 14,
      grammarChips: ["N1 は N2 です", "N1 は N2 ではありません", "N1 は N2 ですか", "N も", "N の N"],
      status: "IN_PROGRESS",
      progressPercent: 65
    },
    { 
      id: 2, 
      level: "N5", 
      lessonNumber: 2, 
      title: "Bài 2: Đồ vật & Chỉ định từ (これ・それ・あれ)", 
      description: "Hỏi và trả lời về đồ vật xung quanh, quyền sở hữu đồ đạc", 
      topicCount: 6, 
      exerciseCount: 12,
      grammarChips: ["これ/それ/あれ", "この/その/あの N", "N1 か N2 か", "どれ/どの N", "違います"],
      status: "NOT_STARTED"
    },
    { 
      id: 3, 
      level: "N5", 
      lessonNumber: 3, 
      title: "Bài 3: Nơi chốn & Phương hướng (ここ・そこ・あそこ)", 
      description: "Hỏi vị trí địa điểm, tầng lầu, xuất xứ sản phẩm và giá tiền", 
      topicCount: 6, 
      exerciseCount: 12,
      grammarChips: ["ここ/そこ/あそこ", "どこ/どちら", "こちら/そちら/あちら", "いくらですか"],
      status: "NOT_STARTED"
    },
    { 
      id: 4, 
      level: "N5", 
      lessonNumber: 4, 
      title: "Bài 4: Thời gian & Giờ giấc (今～時です / ～から～まで)", 
      description: "Hỏi giờ, phút, thứ, ngày tháng và khung thời gian làm việc", 
      topicCount: 6, 
      exerciseCount: 12,
      grammarChips: ["今〜時〜分です", "Vます/ません/ました", "〜から〜まで", "〜ごろ", "に (Thời gian)"],
      status: "NOT_STARTED"
    },
    { 
      id: 5, 
      level: "N5", 
      lessonNumber: 5, 
      title: "Bài 5: Đi lại & Phương tiện (～へ行きます / ～で)", 
      description: "Di chuyển đi đâu, bằng phương tiện gì, đi cùng với ai", 
      topicCount: 6, 
      exerciseCount: 12,
      grammarChips: ["Địa điểm へ 行きます", "Phương tiện で", "Người と 行きます", "どこへも〜ません"],
      status: "NOT_STARTED"
    },
    { 
      id: 6, 
      level: "N5", 
      lessonNumber: 6, 
      title: "Bài 6: Hành động & Ngoại động từ (～をします / ～を買います)", 
      description: "Diễn tả hành động ăn, uống, mua sắm và rủ rê cùng làm", 
      topicCount: 5, 
      exerciseCount: 10,
      grammarChips: ["N を V", "Địa điểm で V", "V-ませんか", "V-ましょう"],
      status: "NOT_STARTED"
    },
    { 
      id: 7, 
      level: "N5", 
      lessonNumber: 7, 
      title: "Bài 7: Công cụ & Cho nhận quà (～で / あげます・もらいます)", 
      description: "Sử dụng công cụ/ngôn ngữ làm gì, hành động tặng/nhận quà", 
      topicCount: 6, 
      exerciseCount: 12,
      grammarChips: ["Công cụ で", "あげます/もらいます", "かします/かります", "もう〜ました"],
      status: "NOT_STARTED"
    },
    { 
      id: 8, 
      level: "N5", 
      lessonNumber: 8, 
      title: "Bài 8: Tính từ & Miêu tả (い形容詞・な形容詞)", 
      description: "Miêu tả đặc điểm, tính chất của sự vật, người và nơi chốn", 
      topicCount: 7, 
      exerciseCount: 14,
      grammarChips: ["Adj-い / Adj-な", "とても", "あまり〜ません", "どんな N"],
      status: "NOT_STARTED"
    },
    { 
      id: 9, 
      level: "N5", 
      lessonNumber: 9, 
      title: "Sở thích, Năng lực & Lý do (〜から)", 
      description: "Diễn tả sở thích, năng lực và nguyên nhân", 
      topicCount: 5, 
      exerciseCount: 10,
      grammarChips: ["N が 好き/わかります", "上手です/下手です", "Mệnh đề から", "どうして"],
      status: "NOT_STARTED"
    },
    { 
      id: 10, 
      level: "N5", 
      lessonNumber: 10, 
      title: "Tồn tại người & vật (あります / います)", 
      description: "Vị trí tồn tại đồ vật và động vật", 
      topicCount: 5, 
      exerciseCount: 10,
      grammarChips: ["Địa điểm に N が あります/います", "上/下/前/後ろ", "N1 や N2 [など]"],
      status: "NOT_STARTED"
    },
    { id: 11, level: "N5", lessonNumber: 11, title: "Lượng từ & Khoảng thời gian (〜日間)", description: "Cách dùng lượng từ và biểu thị thời gian nghỉ", topicCount: 4, exerciseCount: 8, grammarChips: ["〜ぐらい", "どのくらい", "〜回", "Lượng từ + だけ"] },
    { id: 12, level: "N5", lessonNumber: 12, title: "So sánh tính từ (〜より / 〜のほうが)", description: "So sánh hơn, so sánh lựa chọn và so sánh nhất", topicCount: 6, exerciseCount: 12, grammarChips: ["N1 は N2 より", "N1 の ほうが Adj", "で N が 一番 Adj"] },
    { id: 13, level: "N5", lessonNumber: 13, title: "Mong muốn (〜たいです / 〜がほしいです)", description: "Bày tỏ nguyện vọng và mục đích di chuyển", topicCount: 5, exerciseCount: 10, grammarChips: ["V-たいです", "N が ほしいです", "Địa điểm へ Vに行きます"] },
    { id: 14, level: "N5", lessonNumber: 14, title: "Thể て & Nhờ vả lịch sự (〜てください)", description: "Chia thể て, câu nhờ vả và đề nghị giúp đỡ", topicCount: 7, exerciseCount: 14, grammarChips: ["V-てください", "Chia 3 nhóm thể て", "V-ましょうか"] },
    { id: 15, level: "N5", lessonNumber: 15, title: "Cho phép, Cấm đoán & Trạng thái (〜ています)", description: "Cấu trúc cho phép, cấm đoán và hôn nhân/sống", topicCount: 6, exerciseCount: 12, grammarChips: ["V-てもいいです", "V-てはいけません", "V-ています (Trạng thái)"] },
    { id: 16, level: "N5", lessonNumber: 16, title: "Nối chuỗi hành động (〜て、〜て) & Nối tính từ", description: "Liên kết chuỗi hành động và kết hợp tính từ", topicCount: 6, exerciseCount: 12, grammarChips: ["V1-て、V2-て", "V1-てから V2", "Nối Adj (〜くて / 〜で)"] },
    { id: 17, level: "N5", lessonNumber: 17, title: "Thể ない & Xin đừng / Bắt buộc", description: "Cấu trúc 〜ないでください và 〜なければなりません", topicCount: 6, exerciseCount: 12, grammarChips: ["V-ないでください", "V-なければなりません", "V-なくてもいいです"] },
    { id: 18, level: "N5", lessonNumber: 18, title: "Thể Nguyên Mẫu (辞書形) & Khả năng / Sở thích", description: "Biểu thị khả năng và cấu trúc 趣味は〜ことです", topicCount: 6, exerciseCount: 12, grammarChips: ["V-辞書形 ことができます", "趣味は Vる ことです", "Vる 前に"] },
    { id: 19, level: "N5", lessonNumber: 19, title: "Thể Quá Khứ (V-た) & Trải nghiệm (〜たことがあります)", description: "Nói về kinh nghiệm đã từng làm và liệt kê 〜たり", topicCount: 6, exerciseCount: 12, grammarChips: ["V-た ことがあります", "V1-たり V2-たり", "〜くなります / 〜になります"] },
    { id: 20, level: "N5", lessonNumber: 20, title: "Thể Thông Thường / Thể Ngắn (普通形)", description: "Trọn bộ 4 dạng thể ngắn trong văn thoại thân mật", topicCount: 8, exerciseCount: 16, grammarChips: ["だ / じゃない", "だった / じゃなかった", "Hội thoại thân mật"] },
    { id: 21, level: "N5", lessonNumber: 21, title: "Ý kiến cá nhân (〜と思います) & Trích dẫn", description: "Bày tỏ suy nghĩ và trích dẫn câu nói", topicCount: 5, exerciseCount: 10, grammarChips: ["〜と 思います", "〜と 言いました", "たぶん", "〜でしょう？"] },
    { id: 22, level: "N5", lessonNumber: 22, title: "Mệnh đề bổ nghĩa danh từ (名詞修飾)", description: "Động từ đứng trước danh từ bổ nghĩa chi tiết", topicCount: 6, exerciseCount: 12, grammarChips: ["V-普通形 + N", "S が V-普通形 N", "Động từ trang phục"] },
    { id: 23, level: "N5", lessonNumber: 23, title: "Thời điểm (〜とき) & Hễ... thì... (〜と)", description: "Phân biệt Vるとき và Vとき, điều kiện tự nhiên", topicCount: 6, exerciseCount: 12, grammarChips: ["とき (Nの/Adj/V)", "Vる と、〜 (Kết quả tự nhiên)"] },
    { id: 24, level: "N5", lessonNumber: 24, title: "Cho & Nhận hành động (〜てあげます / もらいます / くれます)", description: "Diễn tả sự giúp đỡ và nhận ơn trong giao tiếp", topicCount: 6, exerciseCount: 12, grammarChips: ["V-て くれます", "V-て あげます", "V-て もらいます"] },
    { id: 25, level: "N5", lessonNumber: 25, title: "Điều kiện giả định (〜たら) & Cho dù (〜ても)", description: "Câu giả định nếu... thì... và cho dù... nhưng...", topicCount: 6, exerciseCount: 12, grammarChips: ["V-たら", "もし 〜たら", "いくら 〜ても"] },
  ],
  N4: [
    {
      id: 26,
      level: "N4",
      lessonNumber: 26,
      title: "Bài 26: Giải thích lý do & Nhấn mạnh (～んです)",
      description: "Dùng Ndesu để giải thích hoàn cảnh, lý do và yêu cầu lời khuyên",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["〜んです", "〜んですか", "〜んですが、〜", "〜ていただけませんか", "〜たらいいですか"],
      status: "NOT_STARTED"
    },
    {
      id: 27,
      level: "N4",
      lessonNumber: 27,
      title: "Bài 27: Động từ Khả năng (可能形)",
      description: "Cách chia động từ thể khả năng (có thể làm gì) và phân biệt 見えます/聞こえます",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["V-可能形 (られる/れる)", "〜しか〜ない", "が見えます / が聞こえます", "ができます"],
      status: "NOT_STARTED"
    },
    {
      id: 28,
      level: "N4",
      lessonNumber: 28,
      title: "Bài 28: Vừa làm vừa & Thói quen (～ながら / ～し)",
      description: "Thực hiện 2 hành động song song và liệt kê lý do tương đồng",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["V1-ながら V2", "V-ています (Thói quen)", "〜し、〜し (Liệt kê lý do)"],
      status: "NOT_STARTED"
    },
    {
      id: 29,
      level: "N4",
      lessonNumber: 29,
      title: "Bài 29: Trạng thái kết quả & Hoàn thành (～ています / ～てしまいました)",
      description: "Diễn tả trạng thái tự động từ và sự nuối tiếc lỡ làm gì",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["V(tự động từ)-ています", "V-てしまいました (Nuối tiếc)", "V-てしまいました (Hoàn thành)"],
      status: "NOT_STARTED"
    },
    {
      id: 30,
      level: "N4",
      lessonNumber: 30,
      title: "Bài 30: Chuẩn bị & Sắp đặt sẵn (～てあります / ～ておきます)",
      description: "Trạng thái tha động từ có mục đích và hành động chuẩn bị sẵn",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["V(tha động từ)-てあります", "V-ておきます (Chuẩn bị)", "V-ておきます (Giữ nguyên)"],
      status: "NOT_STARTED"
    },
    {
      id: 31,
      level: "N4",
      lessonNumber: 31,
      title: "Bài 31: Ý định Volitional (意向形 / ～つもりです)",
      description: "Cách chia thể Ý định và diễn tả dự định trong tương lai",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["V-意向形 (おう/よう)", "V-意向形 と思っています", "Vる/Vない つもりです", "Nの 予定です"],
      status: "NOT_STARTED"
    },
    {
      id: 32,
      level: "N4",
      lessonNumber: 32,
      title: "Bài 32: Khuyên bảo & Suy đoán (～ほうがいいです / ～でしょう)",
      description: "Đưa ra lời khuyên nên/không nên và phỏng đoán có lẽ",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["Vた/Vない ほうがいいです", "〜でしょう", "〜かもしれません"],
      status: "NOT_STARTED"
    },
    {
      id: 33,
      level: "N4",
      lessonNumber: 33,
      title: "Bài 33: Mệnh lệnh & Cấm đoán (命令形 / 禁止形)",
      description: "Chia thể Mệnh lệnh và thể Cấm đoán (dùng trong khẩn cấp/biển báo)",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["V-命令形", "V-禁止形 (な)", "〜と書いてあります", "〜という意味です"],
      status: "NOT_STARTED"
    },
    {
      id: 34,
      level: "N4",
      lessonNumber: 34,
      title: "Bài 34: Theo như & Sau khi (～とおりに / ～あとで)",
      description: "Làm theo chỉ dẫn và trình tự hành động sau khi làm việc gì",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["V1とおりに V2 / Nのとおりに", "V1あとで V2 / Nのあとで", "V1ないで V2"],
      status: "NOT_STARTED"
    },
    {
      id: 35,
      level: "N4",
      lessonNumber: 35,
      title: "Bài 35: Thể Điều kiện Ba (条件形 - ば)",
      description: "Cách chia thể điều kiện Ba và mẫu câu càng... càng...",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["V-ば / Adj-ければ / N-なら", "V-ば Vるほど", "Nなら"],
      status: "NOT_STARTED"
    },
    {
      id: 36,
      level: "N4",
      lessonNumber: 36,
      title: "Bài 36: Cố gắng & Thay đổi trạng thái (～ようにします / ～ようになります)",
      description: "Cố gắng tạo thói quen và sự thay đổi khả năng từ không thành có",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["Vる/Vない ようにします", "Vる/Vない ようになります", "Vる ように"],
      status: "NOT_STARTED"
    },
    {
      id: 37,
      level: "N4",
      lessonNumber: 37,
      title: "Bài 37: Thể Bị động Passive (受身形)",
      description: "Cách chia thể bị động, bị ai đó làm phiền hoặc sự kiện công cộng",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["V-受身形 (られる/れる)", "N1 は N2 に V-られます", "N1 は N2 に N3 を V-られます"],
      status: "NOT_STARTED"
    },
    {
      id: 38,
      level: "N4",
      lessonNumber: 38,
      title: "Bài 38: Danh từ hóa mệnh đề (～のは / ～のが)",
      description: "Biến mệnh đề động từ thành danh từ để miêu tả, thích/giỏi",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["Vる のは Adj です", "Vる のが 好き/上手です", "Vる のを 忘れました"],
      status: "NOT_STARTED"
    },
    {
      id: 39,
      level: "N4",
      lessonNumber: 39,
      title: "Bài 39: Nguyên nhân & Lý do khách quan (～て/で / ～ので)",
      description: "Chỉ nguyên nhân kết quả tự nhiên, tai nạn, lý do khách quan",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["Vて / Adjくて / Adjで", "N (tai nạn/thiên tai) で", "〜ので"],
      status: "NOT_STARTED"
    },
    {
      id: 40,
      level: "N4",
      lessonNumber: 40,
      title: "Bài 40: Dạng nghi vấn phụ & Thử làm (～かどうか / ～てみます)",
      description: "Lồng câu hỏi vào trong câu lớn và thử làm hành động gì",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["〜かどうか", "Nghi vấn từ + 〜か", "V-てみます (Thử làm)"],
      status: "NOT_STARTED"
    },
    {
      id: 41,
      level: "N4",
      lessonNumber: 41,
      title: "Bài 41: Cho nhận kính ngữ (～ていただきます / ～てくださいます)",
      description: "Hành động cho/nhận mang tính lịch sự với người trên",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["V-て いただきます", "V-て くださいます", "V-て やります"],
      status: "NOT_STARTED"
    },
    {
      id: 42,
      level: "N4",
      lessonNumber: 42,
      title: "Bài 42: Mục đích để làm gì (～ために / ～のに)",
      description: "Dùng cho mục đích cá nhân và công dụng của đồ vật",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["Vる/Nの ために", "Vる/Nの に (dùng vào việc/tốn thời gian)"],
      status: "NOT_STARTED"
    },
    {
      id: 43,
      level: "N4",
      lessonNumber: 43,
      title: "Bài 43: Sắp sửa & Trông có vẻ (～そうです / ～てきます)",
      description: "Phỏng đoán trực quan có vẻ sắp xảy ra và đi rồi về",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["Vます/Adj そうです (Trông có vẻ)", "V-て きます (Đi làm rồi về)"],
      status: "NOT_STARTED"
    },
    {
      id: 44,
      level: "N4",
      lessonNumber: 44,
      title: "Bài 44: Quá mức & Dễ/Khó làm (～すぎます / ～やすい・にくい)",
      description: "Hành động quá đà và mức độ dễ/khó thực hiện",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["Vます/Adj すぎます", "Vます やすいです", "Vます にくいです"],
      status: "NOT_STARTED"
    },
    {
      id: 45,
      level: "N4",
      lessonNumber: 45,
      title: "Bài 45: Trong trường hợp & Mặc dù (～ばあいは / ～のに)",
      description: "Giả định tình huống trường hợp và sự bất ngờ trái kỳ vọng",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["〜場合は", "〜のに (Mặc dù... nhưng...)"],
      status: "NOT_STARTED"
    },
    {
      id: 46,
      level: "N4",
      lessonNumber: 46,
      title: "Bài 46: Vừa mới làm xong (～ところです / ～ばかりです)",
      description: "Các giai đoạn thời điểm của hành động và vừa mới làm",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["Vる/Vている/Vた ところです", "Vた ばかりです"],
      status: "NOT_STARTED"
    },
    {
      id: 47,
      level: "N4",
      lessonNumber: 47,
      title: "Bài 47: Nghe nói & Hình như (～そうです / ～ようです)",
      description: "Truyền đạt thông tin nghe đồn và suy đoán từ căn cứ",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["V-普通形 そうです (Nghe nói)", "V-普通形 ようです (Hình như)"],
      status: "NOT_STARTED"
    },
    {
      id: 48,
      level: "N4",
      lessonNumber: 48,
      title: "Bài 48: Thể Sai khiến Causative (使役形 - させる)",
      description: "Chia thể sai khiến, cho phép hoặc bắt người khác làm",
      topicCount: 5,
      exerciseCount: 10,
      grammarChips: ["V-使役形 (させる/せます)", "V-使役形 ていただきます"],
      status: "NOT_STARTED"
    },
    {
      id: 49,
      level: "N4",
      lessonNumber: 49,
      title: "Bài 49: Tôn kính ngữ (尊敬語 - Keigo)",
      description: "Kính ngữ dùng khi nói về hành động của cấp trên, khách hàng",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["お Vます になります", "いらっしゃいます / おっしゃいます", "V-受身形 (Kính ngữ)"],
      status: "NOT_STARTED"
    },
    {
      id: 50,
      level: "N4",
      lessonNumber: 50,
      title: "Bài 50: Khiêm nhường ngữ (謙譲語 - Kenjougo)",
      description: "Khiêm nhường ngữ dùng khi nói về hành động của bản thân",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["お Vます します", "参ります / 申します / いたします", "ございます"],
      status: "NOT_STARTED"
    }
  ],
  N3: [
    {
      id: 51,
      level: "N3",
      lessonNumber: 51,
      title: "Bài 51: Trạng thái & Xu hướng (～に違いない / ～がち)",
      description: "Phỏng đoán chắc chắn và diễn tả khuynh hướng dễ xảy ra",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜に違いない", "〜がち", "〜っぽい", "〜とする"],
      status: "NOT_STARTED"
    },
    {
      id: 52,
      level: "N3",
      lessonNumber: 52,
      title: "Bài 52: Giới hạn & Phạm vi (～について / ～に関して)",
      description: "Liên quan đến chủ đề và phạm vi kéo dài không gian thời gian",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜について", "〜に関して", "〜にわたって", "〜を通じて"],
      status: "NOT_STARTED"
    },
    {
      id: 53,
      level: "N3",
      lessonNumber: 53,
      title: "Bài 53: Nhấn mạnh & Đối lập (～にもかかわらず / ～わりに)",
      description: "Nhượng bộ mặc dù... nhưng và đối lập trái với suy đoán",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜にもかかわらず", "〜わりに", "〜くせに", "〜はんめん"],
      status: "NOT_STARTED"
    },
    {
      id: 54,
      level: "N3",
      lessonNumber: 54,
      title: "Bài 54: So sánh & Tỷ lệ (～にくらべて / ～にしたがって)",
      description: "So sánh 2 đối tượng và biến đổi đồng thời kéo theo tỷ lệ",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜にくらべて", "〜にたいして", "〜にしたがって", "〜につれて"],
      status: "NOT_STARTED"
    },
    {
      id: 55,
      level: "N3",
      lessonNumber: 55,
      title: "Bài 55: Nguyên nhân N3 (～おかげで / ～せいで / ～によって)",
      description: "Nhờ có (tích cực), tại vì (tiêu cực) và phương thức nguyên nhân",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜おかげで", "〜せいで", "〜によって", "〜だけに"],
      status: "NOT_STARTED"
    },
    {
      id: 56,
      level: "N3",
      lessonNumber: 56,
      title: "Bài 56: Mục đích & Kỳ vọng (～ように / ～ために)",
      description: "Phân biệt mục đích ように và ために, bày tỏ nguyện vọng",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜ように (Mục đích)", "〜ために (Mục đích)", "〜ように願う"],
      status: "NOT_STARTED"
    },
    {
      id: 57,
      level: "N3",
      lessonNumber: 57,
      title: "Bài 57: Giả định & Điều kiện N3 (～さえ～ば / ～ない限り)",
      description: "Chỉ cần... thì... và chừng nào còn chưa... thì...",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜さえ〜ば", "〜たとえ〜ても", "〜ない限り", "〜としたら"],
      status: "NOT_STARTED"
    },
    {
      id: 58,
      level: "N3",
      lessonNumber: 58,
      title: "Bài 58: Bắt buộc & Cấm đoán N3 (～ざるを得ない / ～わけにはいかない)",
      description: "Đành phải làm (dù không muốn) và không thể làm vì lý do đạo đức",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜ざるを得ない", "〜わけにはいかない", "〜てはならない"],
      status: "NOT_STARTED"
    },
    {
      id: 59,
      level: "N3",
      lessonNumber: 59,
      title: "Bài 59: Cảm xúc & Tâm trạng (～てたまらない / ～てしようがない)",
      description: "Bày tỏ cảm xúc vô cùng, không thể chịu nổi",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜てたまらない", "〜てしようがない", "〜てかなわない"],
      status: "NOT_STARTED"
    },
    {
      id: 60,
      level: "N3",
      lessonNumber: 60,
      title: "Bài 60: Ý kiến & Đánh giá (～にすぎない / ～というものだ)",
      description: "Chỉ là... & Bản chất chính là...",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜にすぎない", "〜にほかならない", "〜とされている"],
      status: "NOT_STARTED"
    },
    {
      id: 61,
      level: "N3",
      lessonNumber: 61,
      title: "Bài 61: Phương thức & Căn cứ (～をもとに / ～に基づいて)",
      description: "Dựa trên cơ sở, căn cứ và tuân theo nguyên tắc",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜をもとに", "〜に基づいて", "〜に沿って", "〜に応じた"],
      status: "NOT_STARTED"
    },
    {
      id: 62,
      level: "N3",
      lessonNumber: 62,
      title: "Bài 62: Thời điểm & Tiến trình (～際 / ～にあたって / ～最中に)",
      description: "Khi nhân dịp, nhân cơ hội và đúng lúc đang giữa chừng",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜際", "〜にあたって", "〜ついでに", "〜最中に"],
      status: "NOT_STARTED"
    },
    {
      id: 63,
      level: "N3",
      lessonNumber: 63,
      title: "Bài 63: Rút gọn & Văn thoại N3 (～っけ / ～っこない)",
      description: "Xác nhận ký ức và tuyệt đối không thể nào xảy ra",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜っけ", "〜っこない", "〜ちゃう/じゃう", "〜とく"],
      status: "NOT_STARTED"
    },
    {
      id: 64,
      level: "N3",
      lessonNumber: 64,
      title: "Bài 64: Kính ngữ N3 nâng cao (～ていただく / ～においでになる)",
      description: "Kính ngữ trang trọng trong công sở và giao tiếp đối tác",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜においでになる", "〜と申される", "〜ていただく"],
      status: "NOT_STARTED"
    },
    {
      id: 65,
      level: "N3",
      lessonNumber: 65,
      title: "Bài 65: Phủ định kép & Tổng hợp N3 (～わけがない / ～かねる)",
      description: "Tuyệt đối không có chuyện... & Khó mà / Không thể làm được",
      topicCount: 6,
      exerciseCount: 12,
      grammarChips: ["〜わけがない", "〜わけではない", "〜かねる", "〜ざるを得ない"],
      status: "NOT_STARTED"
    }
  ],
  N2: [],
  N1: [],
};
